### ISSUE TITLE
Connections to a Redis pod timing out after upgrade to Linkerd 2.9.0

### ISSUE THREAD

**Issue by dkulchinsky** [linkerd/linkerd2#5344] opened 2020-12-07 20:44 UTC
### What is the issue?

After upgrading to Linekrd v2.9.0 from v2.8.1 we noticed that our application pods are failing to communicate with the Redis pod.

The application in question is Harbor Container Registry `jobservice` (https://github.com/goharbor/harbor/tree/master/src/jobservice) which is based https://github.com/gocraft/work background jobs management framework, it uses Redis to manage the worker pools.

### How can it be reproduced?

1. Deploy a Redis server
2. Deploy an application that accesses above Redis (considering the specific application above, it seems like the client creates a connection and may be idle for prolonged period of time).
3. ensure they are meshed
4. Observe i/o timeout on the application trying to access Redis

### Logs, error output, etc

application error log:
```
[harbor-jobservice-7f5fdc497f-4rjdd jobservice] 2020-12-07T19:48:47Z [ERROR] [/jobservice/hook/hook_agent.go:204]: Resend hook event error: read tcp 172.16.8.138:56726->172.16.6.101:6379: i/o timeout
```

linkerd-proxy sidecar for above application:
```
[harbor-jobservice-7f5fdc497f-4rjdd linkerd-proxy] [ 13290.081770s]  INFO ThreadId(01) outbound:accept{peer.addr=172.16.8.138:56726 target.addr=172.16.6.101:6379}: linkerd2_app_core::serve: Connection closed error=Broken pipe (os error 32)
```

#### `linkerd check` output

```text
❯ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-ha-checks
-----------------
√ multiple replicas of control plane pods

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
```

### Environment

- Kubernetes Version: v1.17.12-gke.2502
- Cluster Environment: GKE
- Host OS: GKE COS
- Linkerd version: 2.9.0

### Possible solution (well, more like workarounds at this point)

- Bypassing port 6379 seems like a possible workaround? (EDIT: confirmed, this workaround works too)
- Reverting to 2.8.1 also works

### Additional context

A past Conduit ticket suggested that Redis might be a server-speaks-first protocol, but it looks like this is not the case. https://github.com/linkerd/linkerd2/issues/432

**Comment by dkulchinsky** [comment] 2020-12-08 15:12
just a quick update, both workarounds mentioned above "fix" the issue:
1. skip outbound port 6379
2. revert to 2.8.1

**Comment by Pothulapati** [comment] 2020-12-10 18:32
Hey @dkulchinsky, It would be awesome if you could provide further information that can help us deubg the issue. Some of the following could be helpful.
- [Debug logs from the proxy](https://linkerd.io/2/tasks/modifying-proxy-log-level/)
- Also, Does this happen with a specific pattern or random? Does this occur right away once the application starts? 🤔

**Comment by dkulchinsky** [comment] 2020-12-11 15:06
Hey @Pothulapati, sure - I'll work on gathering all that.

Would logs be needed from the client or server (redis) proxy as well?

as for the pattern, it's a bit difficult to pin point, but it looks like this happens after some time of inactivity on the client side, since it's an async worker scheduling service it's a bit of challenge to follow.

**Comment by Pothulapati** [comment] 2020-12-11 16:43
@dkulchinsky Client logs is the important part, as thats where the error seems to be. the redis proxy logs would be helpful too, if included.

Yep, I will also try running the stuff that you mentioned in the issue, and see if I'm able to reproduce.

**Comment by borchero** [comment] 2020-12-15 00:22
I encountered a similar issue when deploying Redis Cluster on a cluster running Linkerd 2.9.0. The issue was resolved by adding the following annotations on the Redis Pods:

```yaml
config.linkerd.io/skip-outbound-ports: "16379"
config.linkerd.io/skip-inbound-ports: "16379"
```

**Comment by adleong** [comment] 2020-12-17 23:42
I think this issue started in 2.9.0 because of the addition of protocol detection timeouts.  If a meshed pod establishes a connection, Linkerd will listen to that connection to determine if it is HTTP or not.  If it doesn't receive any bytes on that connection within 5 seconds, it will fail the connection.  

I suspect that what is happening is that the Redis client is probably eagerly creating connections but not necessarily sending requests on them right away.  This causes Linkerd to time out protocol detection and fail the connection.  

In Linkerd 2.10 we'll have a more robust way to handle this where you can mark certain ports as "opaque" which will cause the proxy to treat them as pure TCP and not attempt detection.  In the meantime, the best thing to do is to simply have the proxy skip the Redis ports altogether as @borchero suggested.

**Comment by olix0r** [comment] 2020-12-18 01:48
I've put up a change to [drastically increase our protocol detection timeouts](https://github.com/linkerd/linkerd2-proxy/pull/782). I can't be sure that this will resolve issue for redis, but I'd be curious to get feedback from those who can test it. In order to test it, set the workload annotations:

```
spec:
  template:
    metadata:
      annotations:
        config.linkerd.io/proxy-image: ghcr.io/olix0r/l2-proxy
        config.linkerd.io/proxy-version: detect-timeout.642efd13 
```

**Comment by sjahl** [comment] 2020-12-23 15:24
I'm running linkerd 2.9.1 and experienced redis timeouts as well. Skipping the redis ports in my config made things work again.

@olix0r I tried disabling the skip ports and redeployed my redis and application pods with the detect-timeout image and version, but it looks like no traffic was getting through to anywhere with that image in place (both from my app -> redis, and also from my app to postgres pod that was not running the detect-timeout version).

I'm still fairly new to linkerd -- let me know if there's some debugging I can turn on and where I can easily find logs that might help understand what's going on.

**Comment by olix0r** [comment] 2020-12-23 19:03
I think the most reliable way for us to figure out what's going on would be to try to reproduce these issues in an isolated configuration; and, ideally, we'd add this configuration to our integration test suite. Even if we can get our hands on a k8s manifest that exhibits this behavior, that would be a huge help.

In lieu of a repro, there are a few things to try:

* You could try running with very verbose logging like: `config.linkerd.io/proxy-log-level: linkerd=trace,warn`. Setting this on the application pod would likely give us a deeper look at where the proxy is hitting this timeout:
* [`ksniff`](https://github.com/eldadru/ksniff) can help capture PCAP data that illustrates the exact sequence of packets that trigger this issue, giving us insight into the behavior at the network-level.
* The next edge release will introduce a new "opaque transport" feature that should enable the proxy to transport these streams without attempting protocol detection at all. I'm hoping that this will be available to test next week, but this is contingent on holiday schedules.

**Comment by bohrasd** [comment] 2021-01-23 14:23
I ran into the same problem, it cannot access to redis once in a while. Sometimes it worked perfectly fine so it's kinda tricky to track down.
The linkerd-proxy outputs:
```
[  2831.586931s]  INFO ThreadId(02) outbound:accept{peer.addr=172.16.3.183:53432 target.addr=172.19.12.177:6379}: linkerd2_app_core::serve: Connection closed err
 or=closed
 [  2831.657482s]  INFO ThreadId(02) outbound:accept{peer.addr=172.16.3.183:53440 target.addr=172.19.12.177:6379}: linkerd2_app_core::serve: Connection closed err
 or=closed
 [  2836.587321s]  INFO ThreadId(03) outbound:accept{peer.addr=172.16.3.183:53784 target.addr=172.19.12.177:6379}: linkerd2_app_core::serve: Connection closed err
 or=closed
 [  2836.650528s]  INFO ThreadId(03) outbound:accept{peer.addr=172.16.3.183:53794 target.addr=172.19.12.177:6379}: linkerd2_app_core::serve: Connection closed err
 or=closed
```
Here's the log output of linkerd-debug, in case it could help:
```
2021-01-23T13:39:59.244815897Z 127152 2779.605533986 172.16.3.183 → 172.16.7.57  TCP 120 36356 → 6379 [PSH, ACK] Seq=5032197 Ack=65534 Win=58 Len=52 TSval=3494092233 TSecr=1910793054
2021-01-23T13:39:59.244821343Z 127153 2779.605724111  172.16.7.57 → 172.16.3.183 TCP 73 6379 → 36356 [PSH, ACK] Seq=65534 Ack=5032249 Win=4097 Len=5 TSval=1910796058 TSecr=3494092233
2021-01-23T13:39:59.244826649Z 127154 2779.605737223 172.16.3.183 → 172.16.7.57  TCP 68 36356 → 6379 [ACK] Seq=5032249 Ack=65539 Win=58 Len=0 TSval=3494092234 TSecr=1910796058
2021-01-23T13:39:59.24483226Z 127155 2779.612379236 172.19.12.177 → 172.16.3.183 TCP 73 6379 → 41226 [PSH, ACK] Seq=65534 Ack=5032197 Win=8194 Len=5 TSval=3494092240 TSecr=3494092233
2021-01-23T13:39:59.244848907Z 127158 2779.613653052 172.16.3.183 → 172.16.7.57  TCP 714 36356 → 6379 [PSH, ACK] Seq=5032249 Ack=65539 Win=58 Len=646 TSval=3494092242 TSecr=1910796058
2021-01-23T13:39:59.244853724Z 127159 2779.613887084  172.16.7.57 → 172.16.3.183 TCP 72 6379 → 36356 [PSH, ACK] Seq=65539 Ack=5032895 Win=4097 Len=4 TSval=1910796066 TSecr=3494092242
2021-01-23T13:39:59.24485854Z 127160 2779.614627671 172.19.12.177 → 172.16.3.183 TCP 72 6379 → 41226 [PSH, ACK] Seq=65539 Ack=5032843 Win=8194 Len=4 TSval=3494092243 TSecr=3494092241
2021-01-23T13:39:59.244868964Z 127162 2779.617684708 172.16.3.183 → 172.16.7.57  TCP 715 36356 → 6379 [PSH, ACK] Seq=5032895 Ack=65543 Win=58 Len=647 TSval=3494092246 TSecr=1910796066
2021-01-23T13:39:59.24487574Z 127163 2779.617910912  172.16.7.57 → 172.16.3.183 TCP 72 6379 → 36356 [PSH, ACK] Seq=65543 Ack=5033542 Win=4097 Len=4 TSval=1910796070 TSecr=3494092246
2021-01-23T13:39:59.244881948Z 127164 2779.618628474 172.19.12.177 → 172.16.3.183 TCP 72 6379 → 41226 [PSH, ACK] Seq=65543 Ack=5033490 Win=8194 Len=4 TSval=3494092247 TSecr=3494092246
2021-01-23T13:39:59.244893484Z 127166 2779.621787366 172.16.3.183 → 172.16.7.57  TCP 571 36356 → 6379 [PSH, ACK] Seq=5033542 Ack=65547 Win=58 Len=503 TSval=3494092250 TSecr=1910796070
2021-01-23T13:39:59.244912788Z 127167 2779.622049876  172.16.7.57 → 172.16.3.183 TCP 82 6379 → 36356 [PSH, ACK] Seq=65547 Ack=5034045 Win=4097 Len=14 TSval=1910796075 TSecr=3494092250
2021-01-23T13:39:59.244919471Z 127168 2779.625621044 172.19.12.177 → 172.16.3.183 TCP 82 6379 → 41226 [PSH, ACK] Seq=65547 Ack=5033993 Win=8194 Len=14 TSval=3494092254 TSecr=3494092249
2021-01-23T13:39:59.24493017Z 127170 2779.625814788 172.16.3.183 → 172.16.7.57  TCP 720 36356 → 6379 [PSH, ACK] Seq=5034045 Ack=65561 Win=58 Len=652 TSval=3494092254 TSecr=1910796075
2021-01-23T13:39:59.244934921Z 127171 2779.626021761  172.16.7.57 → 172.16.3.183 TCP 72 6379 → 36356 [PSH, ACK] Seq=65561 Ack=5034697 Win=4097 Len=4 TSval=1910796079 TSecr=3494092254
2021-01-23T13:39:59.244939636Z 127172 2779.626630515 172.19.12.177 → 172.16.3.183 TCP 72 6379 → 41226 [PSH, ACK] Seq=65561 Ack=5034645 Win=8194 Len=4 TSval=3494092255 TSecr=3494092254
2021-01-23T13:39:59.24494885Z 127174 2779.628726977 172.16.3.183 → 172.16.7.57  TCP 721 36356 → 6379 [PSH, ACK] Seq=5034697 Ack=65565 Win=58 Len=653 TSval=3494092257 TSecr=1910796079
2021-01-23T13:39:59.244953921Z 127175 2779.628937541  172.16.7.57 → 172.16.3.183 TCP 72 6379 → 36356 [PSH, ACK] Seq=65565 Ack=5035350 Win=4097 Len=4 TSval=1910796081 TSecr=3494092257
2021-01-23T13:39:59.741883387Z 127176 2779.630671084 172.19.12.177 → 172.16.3.183 TCP 72 6379 → 41226 [PSH, ACK] Seq=65565 Ack=5035298 Win=8194 Len=4 TSval=3494092259 TSecr=3494092257
2021-01-23T13:39:59.741931781Z 127178 2779.630941758 172.16.3.183 → 172.16.7.57  TCP 577 36356 → 6379 [PSH, ACK] Seq=5035350 Ack=65569 Win=58 Len=509 TSval=3494092259 TSecr=1910796081
2021-01-23T13:39:59.741937214Z 127179 2779.631147794  172.16.7.57 → 172.16.3.183 TCP 82 6379 → 36356 [PSH, ACK] Seq=65569 Ack=5035859 Win=4097 Len=14 TSval=1910796084 TSecr=3494092259
2021-01-23T13:39:59.741942797Z 127180 2779.632723367 172.19.12.177 → 172.16.3.183 TCP 82 6379 → 41226 [PSH, ACK] Seq=65569 Ack=5035807 Win=8194 Len=14 TSval=3494092261 TSecr=3494092259
2021-01-23T13:39:59.741953766Z 127182 2779.632928969 172.16.3.183 → 172.16.7.57  TCP 712 36356 → 6379 [PSH, ACK] Seq=5035859 Ack=65583 Win=58 Len=644 TSval=3494092261 TSecr=1910796084
2021-01-23T13:39:59.741959077Z 127183 2779.633134580  172.16.7.57 → 172.16.3.183 TCP 72 6379 → 36356 [PSH, ACK] Seq=65583 Ack=5036503 Win=4097 Len=4 TSval=1910796086 TSecr=3494092261
2021-01-23T13:39:59.741964382Z 127184 2779.633669999 172.19.12.177 → 172.16.3.183 TCP 72 6379 → 41226 [PSH, ACK] Seq=65583 Ack=5036451 Win=8194 Len=4 TSval=3494092262 TSecr=3494092261
2021-01-23T13:39:59.74198813Z 127186 2779.634753814 172.16.3.183 → 172.16.7.57  TCP 713 36356 → 6379 [PSH, ACK] Seq=5036503 Ack=65587 Win=58 Len=645 TSval=3494092263 TSecr=1910796086
2021-01-23T13:39:59.741999988Z 127187 2779.635003912  172.16.7.57 → 172.16.3.183 TCP 72 6379 → 36356 [PSH, ACK] Seq=65587 Ack=5037148 Win=4097 Len=4 TSval=1910796088 TSecr=3494092263
2021-01-23T13:39:59.742004711Z 127188 2779.635603144 172.19.12.177 → 172.16.3.183 TCP 72 6379 → 41226 [PSH, ACK] Seq=65587 Ack=5037096 Win=8194 Len=4 TSval=3494092264 TSecr=3494092263
2021-01-23T13:39:59.742017044Z 127190 2779.635942592 172.16.3.183 → 172.16.7.57  TCP 569 36356 → 6379 [PSH, ACK] Seq=5037148 Ack=65591 Win=58 Len=501 TSval=3494092264 TSecr=1910796088
2021-01-23T13:39:59.742021755Z 127191 2779.636134860  172.16.7.57 → 172.16.3.183 TCP 82 6379 → 36356 [PSH, ACK] Seq=65591 Ack=5037649 Win=4097 Len=14 TSval=1910796089 TSecr=3494092264
2021-01-23T13:39:59.742026458Z 127192 2779.636190335 172.19.12.177 → 172.16.3.183 TCP 82 6379 → 41226 [PSH, ACK] Seq=65591 Ack=5037597 Win=8194 Len=14 TSval=3494092264 TSecr=3494092264
2021-01-23T13:39:59.742032214Z 127193 2779.675588839 172.16.3.183 → 172.16.7.57  TCP 68 36356 → 6379 [ACK] Seq=5037649 Ack=65605 Win=58 Len=0 TSval=3494092304 TSecr=1910796089
```

**Comment by adleong** [comment] 2021-01-26 19:37
If I'm following this correctly, the fact that Redis clients which establish an idle connection get timed out by Linkerd-proxy is expected behavior in 2.9.0.  The solution is to either skip the proxy or to mark the port as opaque (requires a recent edge release of Linkerd).

@olix0r is there any other information that we need here or any other action we should take?

**Comment by fpetkovski** [comment] 2021-02-02 16:09
We ran into this problem today and went ahead with marking the Redis port as opaque. However, I noticed the annotation is not documented here: https://linkerd.io/2/reference/proxy-configuration. Might make sense to add it for future reference.

**Comment by adleong** [comment] 2021-02-10 21:05
@fpetkovski thanks!  We will definitely be adding documentation about the opaque ports as part of the stable-2.10 release.

Besides this, I think everything here is working as expected.  Please feel free to re-open this if that is not the case.

**Closed by adleong** 2021-02-10 21:05 UTC
Labels: priority/P0
