### ISSUE TITLE
Helm chart ignores global.proxyInit.ignoreOutboundPorts

### ISSUE THREAD

**Issue by mozts2005** [linkerd/linkerd2#5139] opened 2020-10-26 22:21 UTC
### What is the issue?
when using the helm chart to install. I am setting "global.proxyInit.ignoreOutboundPorts" to add a custom port to all proxy sidecars. 
the custom port is not configured to be ignored. 

When setting I add the annotation "config.linkerd.io/skip-outbound-ports" to the application pod it is ignored.
### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: 1.\18.6
- Cluster Environment: AKS
- Host OS: 
- Linkerd version: Current

**Comment by grampelberg** [comment] 2020-10-26 22:43
Would you mind sharing your values.yaml and pod specs so that we can take a look?

**Comment by adleong** [comment] 2020-10-27 16:29
This sounds like a duplicate of https://github.com/linkerd/linkerd2/issues/4991

**Comment by adleong** [comment] 2020-10-27 16:36
I just tested this with edge-20.10.5.  I created a values.yml containing: 

```
global:
  proxyInit:
    ignoreOutboundPorts: 12345
```

and then ran 

```
linkerd install --config=values.yml
```

The resulting proxy init containers have:

```
        - --outbound-ports-to-ignore
        - 443,12345
```

**Closed** 2021-05-28 17:15 UTC
Labels: wontfix
