### ISSUE TITLE
Cloud Integration flakiness?

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4285] opened 2020-04-23 17:55 UTC
When the proxy merged master, its Cloud Integration run [failed with the following](https://pipelines.actions.githubusercontent.com/p7a3cQoVOfFGt1NRY3JcIVixtulpQevYmOxJelqxEKZRqxlSR3/_apis/pipelines/1/runs/4569/signedlogcontent/22?urlExpires=2020-04-22T22%3A14%3A27.1326673Z&urlSigningMethod=HMACV1&urlSignature=JWIu%2B%2BT9mNCkAJyXBxjDxHleqRlZ%2BKUTgAM9rq6K9zU%3D):

```
2020-04-22T21:33:16.5063904Z --- FAIL: TestServiceProfileMetrics (504.14s)
2020-04-22T21:33:16.5065729Z     serviceprofiles_test.go:233: expected Effective Success to be at least 95% with retries enabled. But got 0.00
2020-04-22T21:33:16.5067242Z FAIL
2020-04-22T21:33:16.5068552Z FAIL	github.com/linkerd/linkerd2/test/serviceprofiles	535.534s
2020-04-22T21:33:16.5070053Z ok  	github.com/linkerd/linkerd2/test/stat	0.056s [no tests to run]
2020-04-22T21:33:16.5071484Z ok  	github.com/linkerd/linkerd2/test/tap	47.994s
2020-04-22T21:33:16.5073176Z --- FAIL: TestTracing (426.40s)
2020-04-22T21:33:16.5075022Z     tracing_test.go:118: Pod [nginx-ingress-765d64c6f6-pg8kg] in namespace [l5d-integration-emojivoto] is not running
2020-04-22T21:33:16.5076912Z     tracing_test.go:122: Error validating deployment [nginx-ingress]:
2020-04-22T21:33:16.5078990Z         Expected deployment [nginx-ingress] in namespace [l5d-integration-emojivoto] to have [1] replicas, but found [0]
2020-04-22T21:33:16.5081145Z     tracing_test.go:118: Pod [jaeger-9df7c4cdc-wt7sh] in namespace [l5d-integration-tracing] is not running
2020-04-22T21:33:16.5082730Z     tracing_test.go:122: Error validating deployment [jaeger]:
2020-04-22T21:33:16.5084712Z         Expected deployment [jaeger] in namespace [l5d-integration-tracing] to have [1] replicas, but found [0]
2020-04-22T21:33:16.5086575Z     --- FAIL: TestTracing/expect_full_trace (0.04s)
2020-04-22T21:33:16.5087987Z         tracing_test.go:130: no running pods found for jaeger
2020-04-22T21:33:16.5089403Z FAIL
2020-04-22T21:33:16.5090641Z FAIL	github.com/linkerd/linkerd2/test/tracing	426.467s
2020-04-22T21:33:16.5096271Z --- FAIL: TestTrafficSplitCli (0.42s)
2020-04-22T21:33:16.5097727Z     trafficsplit_test.go:152: linkerd inject command failed
2020-04-22T21:33:16.5099015Z         
2020-04-22T21:33:16.5100803Z         Cannot find Linkerd: linkerd-controller-75f66f75b9-hm8wn status is PodInitializing
2020-04-22T21:33:16.5102761Z         Validate the install with: linkerd check --linkerd-namespace l5d-integration
2020-04-22T21:33:16.5104202Z FAIL
2020-04-22T21:33:16.5105451Z FAIL	github.com/linkerd/linkerd2/test/trafficsplit	0.484s
2020-04-22T21:33:16.5106849Z ok  	github.com/linkerd/linkerd2/test/uninstall	0.050s
2020-04-22T21:33:16.5108112Z FAIL
2020-04-22T21:33:16.5912913Z 
2020-04-22T21:33:16.5917472Z === FAIL: error during deep tests
```

On a subsequent run, it passed. Is this worth paying attention to?

**Comment by alpeb** [comment] 2020-06-08 14:13
#4522 has merged, which will get us logs/events that might help us knowing the cause of these failed tests.

**Closed by alpeb** 2020-06-08 14:13 UTC
Labels: area/test
