### ISSUE TITLE
Limit services export to specified clusters

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4479] opened 2020-05-25 05:40 UTC
### What problem are you trying to solve?

Now, whenever a service is marked as mirror, It is automatically mirrored into all the remote clusters that have service mirror configured to read from this cluster.
In the default case, making all remote clusters mirror, seems fine. but users would want to connect only some services in some clusters?

### How should the problem be solved?

Add a new label, through which remote clusters can be specified. If the label is absent default to null. We can also have a relevant flag for the same.

### Any alternatives you've considered?

As Services are plain objects, I don't think its a problem to have mirror services which are not used, WDYT?

This is definitely not a P0, but this issue could act like a global issue, where users could comment if they are interested in this.

### How would users interact with this feature?

`linkerd cluster export-service - --clusters east-1,east-2`

**Comment by adleong** [comment] 2020-06-17 00:14
Closing as duplicate of https://github.com/linkerd/linkerd2/issues/4481

**Closed by adleong** 2020-06-17 00:14 UTC
Labels: area/controller, help wanted
