### ISSUE TITLE
Grafana Dashboard JSON - allow datasource specification when importing

### ISSUE THREAD

**Issue by RajKuni** [linkerd/linkerd2#6221] opened 2021-06-03 22:42 UTC
## Feature Request
When importing grafana linkerd dashboard json files, we should have an option to specify the data source that the dashboards will use.
 
### What problem are you trying to solve?
Currently, dashboards assume datasource has name of "prometheus". But it could be the case that the linkerd prometheus instance that is used as a datasource has a different name.

### How should the problem be solved?
Modify dashboard JSON to take datasource name as a parameter.

**Comment by importhuman** [comment] 2021-07-10 12:16
I'd like to work on this :smile:

**Comment by mateiidavid** [comment] 2021-07-12 16:48
Hey @importhuman, apologies for the slight mix-up but this seems to be a duplicate of #6044. I hadn't noticed before; with #6044 we decided not to go ahead with the implementation. When it comes to the grafana charts, we'd like to favour simplicity so it's not ideal for us to have the dashboard take the datasource as a parameter. We'd like at some point to spin these charts (and maintain them) separately. I've quoted @alpeb's explanation from #6044 below:

> (...) we've decided to not to follow this direction. The Grafana charts we provide are more for people to get started, and we expect folks to draw on them to build charts more specific to their needs. As such, we'd like to keep them as simple as possible, without trying to cater for very specific needs like the current PR attempts to. As a matter of fact, we're thinking at some point to push these charts in some sort of Grafana charts repo people can retrieve them from, and also contribute with different approaches, uncoupling them from the linkerd repo itself. Anyways, thanks again, these discussions are always appreciated! [[1]]

Sorry if you have already started on this! Completely on me for not realising sooner. I'll be closing this issue now. 

[1]: https://github.com/linkerd/linkerd2/pull/6044#issuecomment-829354652

**Closed by mateiidavid** 2021-07-12 16:48 UTC
Labels: help wanted
