### ISSUE TITLE
Expose headers to allow clients to require private communications.

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2185] opened 2019-01-31 19:13 UTC
When an application is sending a request, it cannot know whether linkerd will establish a private communication with its peer or not.

Support a new header in outbound proxies, `l5d-require-server-id`, that causes linkerd to fail requests when the specified server-id cannot be validated.

Values of this header may include the following:
- `*` indicates that a validated secure connection must be established, but the peers name is not checked.
- `name.example.com` indicates that a validated secure connection must be established and the peer must have an identity that is exactly `name.example.com`
- `*.example.com` indicates that a validated secure connection must be established and the peer must have an identity with the suffix `.example.com`.

This value should not be checked against the SNI name (i.e. that is returned from the proxy-api), but instead validated against the certificate that the server replies with (i.e. so that SANs can be checked).

**Comment by kleimkuhler** [comment] 2019-07-30 21:11
Duplicate of #2677. Additional behavior around providing a regex of identities to match is proposed here, but ultimately that was not in scope for why this header was required in tap hardening. This could be explored more when there is a use case for it.

**Closed by kleimkuhler** 2019-07-30 21:11 UTC
Labels: area/identity, area/proxy, priority/P2
