### ISSUE TITLE
Get 502 Bad Gateway when setting http_proxy inside container

### ISSUE THREAD

**Issue by renpengzhang** [linkerd/linkerd2#3888] opened 2020-01-06 21:06 UTC
## Bug Report
I have a k8s cluster which gets linkerd enabled. And I found that if I set http_proxy in the container, the following http requests from the container would return 502 Bad Gateway. While if I disabled the linkerd, http_proxy works fine.
### What is the issue?
As above.
### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: v1.14.8
- Cluster Environment: (GKE, AKS, kops, ...) AKS
- Host OS: Ubuntu
- Linkerd version: stable-2.6.1

**Comment by renpengzhang** [comment] 2020-01-07 01:55
My assumption is linkerd will reset the "http_proxy" env, which make the previous "http_proxy" env doesn't work. Feel free to correct me if I am wrong.

**Comment by cpretzer** [comment] 2020-01-07 02:24
Hi @renpengzhang I'm going to put together a test case to reproduce this and I'll update the ticket.

I _think_ the http_proxy setting is handled at the container level and Linkerd will honor the value. I'm looking in to that now

**Comment by cpretzer** [comment] 2020-01-15 00:29
@renpengzhang I think I have a reproducible test case for this. I'm going to keep working on it and will update this issue when I have more info.

Can you tell me the value that you have configured for `http_proxy`?

It will also be helpful to get some of the log files with the 502 error so that I can compare them to my own log files.

**Comment by cpretzer** [comment] 2020-01-27 22:58
@renpengzhang it turns out that the errors that I saw when I reproduced this are related to the proxy not being able to connect to the upstream service.

I set up the test using the [emojivoto](https://github.com/buoyantIO/emojivoto) sample application injected with Linkerd.

Once the application was running and handling requests. I added an nginx deployment to use as the proxy. The deployment yaml files are in this [gist](https://gist.github.com/cpretzer/4abc0e947f7d7c307aeb10ff4bdfc58e).

Next, I edited the web deployment `kubectl edit deploy web` and added the `http_proxy` environment variable:

```
...
   env:
   - name: http_proxy
      value: nginx-proxy.emojivoto:8080
...
```

The logs from the `web` and `nginx-proxy` pods show that the requests are being proxied through nginx.

So, I'm going to close this issue for now. Please reopen the issue if you're still seeing the 502 errors and provide more detail about the configuration of the proxy.

**Closed by cpretzer** 2020-01-27 22:58 UTC
Labels: area/proxy
