### ISSUE TITLE
HTTP throughput big downgradation with linkerd-proxy

### ISSUE THREAD

**Issue by ukcuf** [linkerd/linkerd2#3755] opened 2019-11-22 12:51 UTC
## Bug Report

This comes from the discussion at: 
https://linkerd.slack.com/archives/C89RTCWJF/p1574340470004700

### What is the issue?
We observed http throughput from pod that runs a simple web service downgrades a lot after linkerd-proxy is injected to it and takes over its incoming/outgoing traffic. 

The background is we have 2 micro-service deployments running on Kubernetes. The *service-client* can create hundreds of connections to the *service-server* and do request with no pause. And initially, we found the single *server* pod's throughput without linkerd can keep at `10k` RPS, but with linkerd injected to both sides (which enables mTLS per `linkerd tap` tells), the throughput downgrades to around `3k` RPS. 

### How can it be reproduced?
I worked out a simple way to reproduce the problem. 

1. find a Kube cluster and create a new namespace, e.g. `bug`
```
kubectl create ns bug
```

2. apply below specs to the namespace `bug`, which:
  - deploys 2 nginx deployments with replica at `1`, and one of them is injected with linkerd-proxy, and configured the linkerd-proxy's resource request&limit to `2` CPU and `4Gi` memory.
  - create 2 services for above deployments.
  - deploys 1 client pod

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lkd
spec:
  selector:
    matchLabels:
      app: nginx-lkd
  replicas: 1
  template:
    metadata:
      annotations:
        config.linkerd.io/proxy-cpu-limit: "2"
        config.linkerd.io/proxy-cpu-request: "2"
        config.linkerd.io/proxy-memory-limit: 4Gi
        config.linkerd.io/proxy-memory-request: 4Gi
        linkerd.io/inject: enabled
      labels:
        app: nginx-lkd
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-lkd
  name: nginx-lkd
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-lkd
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: debian:stretch-slim
        args: ["sleep", "3600"]
```

3. kube exec to the client pod and then:

```sh
apt update && apt install -y wrk
wrk -d 10s -c 100 http://nginx.bug.svc.cluster.local:80
wrk -d 10s -c 100 http://nginx-lkd.bug.svc.cluster.local:80
```

4. compare the output. In my dev environment, it shows:

```
root@client-84fbf7449-sdml2:/# wrk -d 10s -c 100 http://nginx-lkd.bug.svc.cluster.local:80
Running 10s test @ http://nginx-lkd.bug.svc.cluster.local:80
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    21.28ms    2.36ms  63.92ms   94.97%
    Req/Sec     2.36k   211.43     2.76k    83.50%
  47067 requests in 10.04s, 37.03MB read
Requests/sec:   4689.84
Transfer/sec:      3.69MB

root@client-84fbf7449-sdml2:/# wrk -d 10s -c 100 http://nginx.bug.svc.cluster.local:80
Running 10s test @ http://nginx.bug.svc.cluster.local:80
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   116.96ms  176.66ms 944.92ms   81.23%
    Req/Sec     6.31k     1.60k   10.57k    69.00%
  125542 requests in 10.01s, 101.64MB read
Requests/sec:  12546.34
Transfer/sec:     10.16MB
```

So it is `4.7k` V.S. `12.5k`, which shows similar throughput downgrade we observed from our own application deployment environment. 

### Logs, error output, etc

I observed the CPU usage of linkerd-proxy container in the pod, and it always shows like a single core is fully used even in case I have already configured the spec to allocate it 2 CPUs. In below chart, the orange line is the CPU usage of `linkerd-proxy` when the server pod was stressed.

![image](https://user-images.githubusercontent.com/13572784/69426940-5bbc0f80-0d69-11ea-8a3d-c8ee63c36535.png)

I also build a linkerd-proxy image with `procps` based on stable-2.6.0 tag, and with `top` in linkerd-proxy container, I see the CPU usage was keeping at 100%. 

![image](https://user-images.githubusercontent.com/13572784/69427075-b3f31180-0d69-11ea-92a4-b18fc9f6b848.png)

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.14.8
- Cluster Environment: IBM Kubernetes Service
- Host OS: Ubuntu 18.04
- Linkerd version: stable-2.6.0

### Possible solution
Not found yet.

### Additional context

What I am seeing with `linkerd-proxy` are:
  (1). it does not use additional cpu core I allocated for it.
  (2). my server serves at 10k rps only uses 80% cpu cycles, but a 3k rps is already draining linkerd-proxy. So does this mean I will have to allocate more CPU cores just for the meshing sidecars rather than my own application?

**Comment by grampelberg** [comment] 2019-11-22 16:13
At the moment, the proxy is limited to a single core. There's some great work happening in tokio to allow for multiple cores but we're spending a lot of time validating correctness there. In my personal experience, the proxy maxes out around 10k rps total. Any outgoing requests will count in that budget alongside incoming requests, so it seems to check out with your use case.

> (2). my server serves at 10k rps only uses 80% cpu cycles, but a 3k rps is already draining linkerd-proxy. So does this mean I will have to allocate more CPU cores just for the meshing sidecars rather than my own application?

Yup, unfortunately. Service meshes have real overhead and aren't right for every solution. With something this high performance you might want to consider not actually adding this specific workload to the mesh. We'd love to chat about providing the tools inside your application to make it cooperate with the mesh though!

**Comment by CamelCaseNotation** [comment] 2019-11-22 20:09
> the proxy is limited to a single core
@grampelberg is this because of rust, or because of how the proxy was written, or something else (3rd-party library)?

Even if the proxy is able to use more cores, you're saying @ukcuf should still consider not adding the application with high performance requirements to the mesh _only_ because it would require more compute for the whole cluster?

> We'd love to chat about providing the tools inside your application to make it cooperate with the mesh though!

What sorts of things could be done from within the application in order to facilitate better performance while operating within the Linkerd mesh, both with and without the limitation of the proxy only being able to use one core (dunno if that's relevant)

**Comment by hawkw** [comment] 2019-11-22 20:15
> @grampelberg is this because of rust, or because of how the proxy was written, or something else (3rd-party library)?

It's by design — the intention behind this was to avoid starving injected applications under lower loads by tying up all the cores on the host. In the future, we are planning to revisit this to support workloads with higher load.

**Comment by CamelCaseNotation** [comment] 2019-11-22 20:36
@hawkw solid, sound reasoning. Once multi-core proxy is possible, it could be manually enabled via the annotation, while leaving single-core proxy the default.

This issue has me thinking though, at what point does linkerd start impacting the performance of the injected application? I guess that's very application specific though

**Comment by hawkw** [comment] 2019-11-22 22:35
> This issue has me thinking though, at what point does linkerd start impacting the performance of the injected application? I guess that's very application specific though

Unfortunately, as is often the case, I think you're right that the only true answer to this is "it depends".

**Comment by wmorgan** [comment] 2019-11-26 18:44
AIUI in this case 3k RPS is saturating a full core in the proxy, which is pretty different from @grampelberg's 10k number. Do we have any theories as to why that is?

**Comment by olix0r** [comment] 2019-11-26 18:59
@wmorgan I think we have enough information here to try reproduce this ourselves, so there's need to theorize. We should also take care to ensure that the nginx & client containers all configured suitable resource requests to ensure these processes are not starved. I'm also curious if the same behavior is observed when resource _limits_ are not set.

**Comment by ukcuf** [comment] 2019-12-02 13:44
> AIUI in this case 3k RPS is saturating a full core in the proxy, which is pretty different from @grampelberg's 10k number. Do we have any theories as to why that is?

@wmorgan I am not sure if @grampelberg and I were using the same hardware on our testing, given what I care most is the overhead and additional CPU cores I have to pay when the overall throughput of my application has to meet a designated goal. 

Given the assumption of linear throughput increment can happen in the system, I can surely workaround the problem I am seeing by deploying more replicas with smaller (on CPU core resource limit) pods. I haven't got a chance to test how big the total throughput my deployment with linkerd2 can provide, unfortunately. I am wondering if we can be advised on some best practice on using linkerd2 with a system that can serve throughput RPS at, say, 30K RPS per Kube cluster?

**Comment by grampelberg** [comment] 2019-12-02 17:59
@ukcuf that sounds right to me. The overhead will still be there, but that'll definitely fit into less than one core (back of the envelope numbers suggest 0.33 or so core).

**Comment by grampelberg** [comment] 2019-12-02 22:27
I'm going to close this out for now @ukcuf, if there's a specific bug here let's reopen and see where to go from there!

**Closed by grampelberg** 2019-12-02 22:27 UTC

**Comment by ashishxooa** [comment] 2020-01-16 10:25
Went over the thread, very insightful. I am facing a similar kind of scenario and even tried what @ukcuf mentioned scaling horizontally but it didn't help (@grampelberg ). Without the Linkerd mesh, I could get 250k tips from a simple http/2 hello world application using 8-10 pods on 4 c4.2xlarge instances on AWS. With Linkerd on default configuration ( Could't even find any configuration to fine tune the performance, is there any? ) I am getting about 5-6k with 1 replica of my server. With 5 replicas around 10k rps. With 30 replicas about 13-14k rps. Then I tried with 50 and even 100 replicas on some 10 c4.xlarge instances still couldn't beat 14k tps. Is there a bottleneck which is not allowing me to horizontally scale the performance.

**Comment by grampelberg** [comment] 2020-01-16 16:26
There's no mesh-wide bottleneck that I'm aware of. I've definitely pushed more than 14k rps on fewer than 10 instances before. I suspect you're running into some contention issues and setting aggressive resource requests/limits would improve the situation.

**Comment by ashish235** [comment] 2020-01-16 17:33
@grampelberg resource limits on the control/data plane pods or my http2 server pods? Also all my pods are running with no limitations and my instances were under 40% cpu and memory usage.

**Comment by grampelberg** [comment] 2020-01-16 17:40
Both, though at this scale setting the request/limit to 1cpu for the data plane will be the most important.

**Comment by thecooltechguy** [comment] 2020-10-12 23:31
We're also facing similar throughput degradation for gRPC traffic, with the linked injection causing the throughput to reduce by half in our case. We tried increasing the cpu requests/limits for the linkerd2 proxy but we still got the same requests per seconds without any improvement

**Comment by pranaypratyush** [comment] 2021-02-10 17:00
This seems to be a recurring issue. Request the issue to be re-opened.

**Comment by wmorgan** [comment] 2021-02-15 16:20
@pranaypratyush and/or @thecooltechguy can you make a new issue please, with as many details as you can? We will need a lot of info in order to be helpful, especially version, traffic type and volume, and when this behavior is triggered.
