### ISSUE TITLE
Unexpected behavior change on ingress injected pods in v2.13.x

### ISSUE THREAD

**Issue by relu** [linkerd/linkerd2#10908] opened 2023-05-16 11:40 UTC
### What is the issue?

After upgrading from v2.12.x to v2.13.x I've noticed the Contour HTTPProxies configured without explicitly setting the `l5d-dst-override`  header started to fail with 503s generated by linkerd-proxy. These failures are reported by Contour's envoy pods injected with the new version of linkerd-proxy in ingress mode.

### How can it be reproduced?

Create a local kind cluster and apply the following configuration:
```
kind create cluster --name linkerd-contour
# First we install the 2.12.5 version of Linkerd
linkerd-stable-2.12.5 install --crds | kubectl apply -f -
linkerd-stable-2.12.5 install | kubectl apply -f -

# Install Contour
kubectl apply -f https://projectcontour.io/quickstart/contour.yaml
kubectl patch daemonset -n projectcontour envoy -p '{"spec":{"template":{"metadata":{"annotations":{"linkerd.io/inject": "ingress"}}}}}'
kubectl patch service -n projectcontour envoy -p '{"spec":{"type": "ClusterIP"}}'

# Install example workload
kubectl patch ns default -p '{"metadata":{"annotations":{"linkerd.io/inject": "enabled"}}}'
kubectl apply -k https://github.com/stefanprodan/podinfo//kustomize
```
Create HTTPProxy
```
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: podinfo
  namespace: default
spec:
  routes:
  - services:
    - name: podinfo
      port: 9898
  virtualhost:
    fqdn: podinfo.localtest.me
```

If we port-fortward to envoy:
```
kubectl port-forward -n projectcontour svc/envoy 8080:80
```

This should work just fine: http://podinfo.localtest.me:8080/

Now upgrading Linkerd to v2.13.3:
```
linkerd-stable-2.13.3 upgrade --crds | kubectl apply -f -
linkerd-stable-2.13.3 upgrade | kubectl apply -f -

# Restart Contour envoy to re-mesh with new version of Linkerd
kubectl rollout restart daemonset -n projectcontour envoy
kubectl port-forward -n projectcontour svc/envoy 8080:80
kubectl logs -f -n projectcontour -l app=envoy
```

Now, if you visit the endpoint it will fail: http://podinfo.localtest.me:8080/
> upstream connect error or disconnect/reset before headers. reset reason: connection termination

Example output from envoy linkerd-proxy logs:
```
[   151.573999s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=error from user's Service: buffered service failed: status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 16 May 2023 11:31:08 GMT", "content-length": "0"} } error.sources=[buffered service failed: status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 16 May 2023 11:31:08 GMT", "content-length": "0"} }, status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 16 May 2023 11:31:08 GMT", "content-length": "0"} }] client.addr=10.244.0.24:60326
[   151.688059s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=error from user's Service: buffered service failed: status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 16 May 2023 11:31:08 GMT", "content-length": "0"} } error.sources=[buffered service failed: status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 16 May 2023 11:31:08 GMT", "content-length": "0"} }, status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 16 May 2023 11:31:08 GMT", "content-length": "0"} }] client.addr=10.244.0.24:33550
```

Example output from envoy logs:
```
[2023-05-16T11:31:08.177Z] "GET / HTTP/1.1" 503 UC 0 88 2 - "10.244.0.24" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.42" "9e61d3ff-9442-4eb9-a45b-389e30dd0b32" "podinfo.localtest.me" "10.244.0.15:9898"
[2023-05-16T11:31:08.290Z] "GET /favicon.ico HTTP/1.1" 503 UC 0 88 3 - "10.244.0.24" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.42" "f10ec7f6-523d-47e5-ab06-01d881ba7667" "podinfo.localtest.me" "10.244.0.16:9898"
```

The fix is to add the `l5d-dst-override` header either in the HTTPProxy or globally in the contour configuration:
```
kubectl patch httpproxies.projectcontour.io -n default podinfo --type merge -p '{"spec":{"routes":[{"services": [{"name":"podinfo", "port": 9898, "requestHeadersPolicy": {"set": [{"name":"l5d-dst-override", "value": "podinfo.default.svc.cluster.local:9898"}]}}]}]}}'
````

Visiting again the endpoint should yield success: http://podinfo.localtest.me:8080/

### Logs, error output, etc

Example messages from Contour's envoy:
```
"GET /x HTTP/2" 503 UC ...
```

### output of `linkerd check -o short`

```
Status check results are √
```

### Environment

- Kubernetes v1.26.2-eks-a59e1f0
- EKS
- Bottlerocket OS 1.13.4
- Linkerd v2.13.3

### Possible solution

I think this might just be a configuration detail that is not correctly documented or is lacking. However, the main problem seems to be with the different behavior between the two minor versions which should probably be mentioned in the upgrade guide.

### Would you like to work on fixing this bug?

maybe

**Comment by wc-s** [comment] 2023-05-18 10:50
Just want to add that, this happened to our `nginx` ingress too.

We are using the `linkerd.io/inject: ingress` mode.

In the proxy's debug logs, you'd see repeated entries of:

```
[ 41714.198748s] DEBUG ThreadId(02) outbound:accept{client.addr=10.42.115.3:52440}:ingress{addr=10.42.117.163:5000}: linkerd_detect: Detected protocol protocol=None elapsed=8.286µs
[ 41714.198919s]  INFO ThreadId(02) outbound:accept{client.addr=10.42.115.3:52440}: linkerd_app_core::serve: Connection closed error=buffered service failed: status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Thu, 18 May 2023 10:47:10 GMT", "content-length": "0"} } error.sources=[status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Thu, 18 May 2023 10:47:10 GMT", "content-length": "0"} }] client.addr=10.42.115.3:52440
[ 41714.603301s] DEBUG ThreadId(02) outbound:accept{client.addr=10.42.115.3:52450}:ingress{addr=10.42.117.163:5000}: linkerd_detect: Detected protocol protocol=None elapsed=150.793µs
[ 41714.606142s]  INFO ThreadId(02) outbound:accept{client.addr=10.42.115.3:52450}: linkerd_app_core::serve: Connection closed error=buffered service failed: status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Thu, 18 May 2023 10:47:10 GMT", "content-length": "0"} } error.sources=[status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Thu, 18 May 2023 10:47:10 GMT", "content-length": "0"} }] client.addr=10.42.115.3:52450
```

This happened after we upgraded from `2.12.4` to `2.13.3`

**Comment by alpeb** [comment] 2023-05-19 16:50
@wc-s it also gets fixed by adding the `l5d-dst-override` header?

So this is currently working as documented in `2.13.3`. In `2.12` you were probably hitting a fallback behavior that resulted in not requiring that header, but I wouldn't rely on that for all cases. I'll add an item to the upgrade notes emphasizing this requirement.

**Comment by relu** [comment] 2023-05-19 19:18
Thank you for your answer @alpeb. As I anticipated, it is not a bug but rather an enforced behavior change that we were not prepared for. It would be great to have this documented in the upgrade guide so that this issue won't bite others having a misconfigured ingress configuration.

**Comment by erkerb4** [comment] 2023-06-02 16:08
I have also encountered this behavior after upgrading to 2.13 release. I am using `traefik:v2.10` as my ingress controller with `linkerd.io/inject: ingress` pod annotation. We primarily use `Ingress` object instead of `IngressRoute` and I do have `ingress.kubernetes.io/custom-request-headers:` annotation configured on all meshed services. However, I am still seeing the behavior mentioned in this issue. 

For example, I have an ArgoCD deployed in argocd namespace. The WebUI is internally reachable from `http://argocd-server.argocd.svc.cluster.local`. I have the following annotation set on the ArgoCD `Ingress` object: `ingress.kubernetes.io/custom-request-headers: l5d-dst-override:argocd-server.argocd.svc.cluster.local:80`

When I hit the Ingress object, my browser is displaying `Bad Gateway`. The linkerd-proxy running by `traefik` has the following log entries:

```
linkerd-proxy [   477.835339s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=error from user's Service: buffered service failed: status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 02 Jun 2023 15:50:32 GMT", "content-length": "0"} } error.sources=[buffered service failed: status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 02 Jun 2023 15:50:32 GMT", "content-length": "0"} }, status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 02 Jun 2023 15:50:32 GMT", "content-length": "0"} }] client.addr=172.31.3.197:35006
linkerd-proxy [   478.080220s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=error from user's Service: buffered service failed: status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 02 Jun 2023 15:50:32 GMT", "content-length": "0"} } error.sources=[buffered service failed: status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 02 Jun 2023 15:50:32 GMT", "content-length": "0"} }, status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 02 Jun 2023 15:50:32 GMT", "content-length": "0"} }] client.addr=172.31.3.197:46616
linkerd-proxy [   480.397582s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=error from user's Service: buffered service failed: status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 02 Jun 2023 15:50:35 GMT", "content-length": "0"} } error.sources=[buffered service failed: status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 02 Jun 2023 15:50:35 GMT", "content-length": "0"} }, status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 02 Jun 2023 15:50:35 GMT", "content-length": "0"} }] client.addr=172.31.3.197:36626
```
The `client.addr=172.31.3.197` IP address of the traefik pod. 

With 2.13.3, I cannot get to meshed and non-meshed resources.

**Comment by chicocvenancio** [comment] 2023-06-02 17:58
@erkerb4 I think `ingress.kubernetes.io/custom-request-headers` is not supported in traefik 2, so the `l5d-dst-override` header is not being added. You could use `traefik.ingress.kubernetes.io/router.middlewares` and add middlewares for each service to keep ingress use.

**Comment by erkerb4** [comment] 2023-06-02 18:12
> @erkerb4 I think `ingress.kubernetes.io/custom-request-headers` is not supported in traefik 2, so the `l5d-dst-override` header is not being added. You could use `traefik.ingress.kubernetes.io/router.middlewares` and add middlewares for each service to keep ingress use.

Oh, right. You are right about that. Thank you for pointing that out. I'll go back and reconfigure the middlewares.

Is it normal for non-meshed services to be inaccessible?

**Comment by chicocvenancio** [comment] 2023-06-02 18:19
I think it is the new behavior in ingress mode as of 2.13. Any request without `l5d-dst-override` will fail. I don't quite yet have an opinion on if its good or not.

**Comment by chicocvenancio** [comment] 2023-06-02 20:33
I'm now a bit surprised by the change after finding https://github.com/linkerd/linkerd2/issues/6157 and noticing the valid use-cases that become impossible with this (static, non meshed, external services in particular). In that implementation the error message was also much nicer than `status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "content-length": "0"} } error.sources=[status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"`.

**Comment by hawkw** [comment] 2023-06-13 18:12
Hi folks,

Taking a look at the proxy code, this is definitely a bug that was introduced in 2.13.x. The issue is that the `NotFound` status is returned by the policy controller when the proxy looks up a traffic target that is not a ClusterIP Service (such as a pod IP): https://github.com/linkerd/linkerd2/blob/40dc561759b71ad50ee9db6a6458d16ea26b365a/policy-controller/grpc/src/outbound.rs#L69

In the normal outbound proxy (not ingress mode), we handle this error by falling back to a ServiceProfile looked up from the policy controller: https://github.com/linkerd/linkerd2-proxy/blob/864a5dbc97538262f49f73e432b3a7ab071104c7/linkerd/app/outbound/src/sidecar.rs#L70 (note that we push the `self.resolver(..)` resolver function which performs ServiceProfile fallback on `NotFound` gRPC responses from the policy controller: https://github.com/linkerd/linkerd2-proxy/blob/864a5dbc97538262f49f73e432b3a7ab071104c7/linkerd/app/outbound/src/discover.rs#L63).

In the ingress mode proxy, on the other hand, we don't use this logic: https://github.com/linkerd/linkerd2-proxy/blob/864a5dbc97538262f49f73e432b3a7ab071104c7/linkerd/app/outbound/src/ingress.rs#L82-L95
Instead, we fail the discovery if either the policy controller *or* the destination controller return a gRPC error from their discovery APIs. This is an oversight which we should address, as we should instead be doing the same synthesis behavior here.

**Comment by hawkw** [comment] 2023-06-14 15:39
> Thanks for the explanation. Am I right to say that, after the fix, it will return to the behaviour of 2.12.x, where _neither_ `l5d-dst-override` or `ServiceProfile` are necessary? (ie., it'll behave as mentioned in #6157, where the outbound proxy will do this
> 
> > support routing requests that do not have a l5d-dst-override header set by honoring the request's original destination address.
 
Yes, that's correct; the change in behavior in 2.13.x is a bug. A fix for this issue should result in ingress-mode proxies behaving the way they did in 2.12, regardless of whether or not the `l5d-dst-override` header is present.
 
> May I also suggest explaining the behavior of "ingress mode without l5d-dst-header" in the documentation here? (https://linkerd.io/2.13/tasks/using-ingress/), since there seems to be some confusion around what exactly is linkerd's promised behavior in such a case.

I'm definitely interested in improving the documentation around ingress mode! Do you have any specific suggestions for things we can make clearer? [This section](https://linkerd.io/2.13/tasks/using-ingress/#ingress-details) discusses the purpose of ingress mode and the `l5d-dst-override` header; is there anything in particular we could add to that section to make this behavior less confusing?

**Comment by wc-s** [comment] 2023-06-14 15:50
Hey, thanks for the confirmation! It's good news for us because otherwise we're looking at some complicated migration ha.

Regarding the documentation, I'd hope for an explicit explanation on "what is the behaviour of the proxy in `ingress` mode, if the request does not have `l5d-dst-override`". It's pretty much what everyone in this thread has been confused about. There was talk of `l5d-dst-override` being necessary, and now it turns out that, no, that's a bug, and `l5d-dst-override` is not necessary. I'd also explicitly mention that, if `l5d-dst-override` does not exist, then most of the proxy functionalities (mTLS etc.) will _not_ work.

There's also a more minor point - the documentation's nginx example applies to the "more popular" nginx ingress controller implementation (https://github.com/kubernetes/ingress-nginx); but actually there also exists another sigfinicant nginx ingress implementation (https://github.com/nginxinc/kubernetes-ingress).

**Comment by hawkw** [comment] 2023-06-19 18:30
PR linkerd/linkerd2-proxy#2431 should fix this. I've verified the change using the Contour and podinfo repro steps described in the first post, and the ingress mode proxy once again appears to route correctly after applying that change.

**Closed** 2023-06-20 19:14 UTC
Labels: bug

**Comment by chicocvenancio** [comment] 2023-06-26 21:13
I'm still getting a similar error message with proxy stable-2.13.5 with externalName services.
```
[    43.621164s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=error from user's Service: buffered service failed: status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Mon, 26 Jun 2023 20:39:30 GMT", "content-length": "0"} } error.sources=[buffered service failed: status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Mon, 26 Jun 2023 20:39:30 GMT", "content-length": "0"} }, status: NotFound, message: "No such service", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Mon, 26 Jun 2023 20:39:30 GMT", "content-length": "0"} }] client.addr=192.168.13.60:37888
```

Services internal to the cluster do work for me with proxy stable-2.13.5 with or without l5d headers, as well as being meshed or unmeshed.

**Comment by hawkw** [comment] 2023-06-29 18:26
Thanks for reporting back, @chicocvenancio. The reproduction I used for testing linkerd/linkerd2-proxy/#2431 used ClusterIP Services, so I'm going to do some additional investigation into why that change wouldn't have fixed this for ExternalName Services.

**Comment by hawkw** [comment] 2023-06-29 19:11
Also, just to make sure, @chicocvenancio, can you confirm that the same ExternalName services did work correctly in Linkerd 2.12.x? Thanks!

**Comment by chicocvenancio** [comment] 2023-06-29 19:38
@hawkw yes, it is working correctly in 2.12.x.

**Comment by hawkw** [comment] 2023-06-30 19:44
Okay, I think I see what's going on with ExternalName services. 

I believe the error is still being returned because in this case, the policy controller returns `NotFound`, and the Destination controller *also* doesn't return a ServiceProfile for the target address, which results in the fallback logic added in linkerd/linkerd2-proxy#2431 propagating the policy controller's error.

Prior to 2.13, the ingress mode proxy would only attempt profile resolution if a `l5d-dst-override` header is present and route directly to the `SO_ORIGINAL_DST` address (bypassing profile resolution) if no `l5d-dst-override` is found (see https://github.com/linkerd/linkerd2-proxy/blob/4e1720430fd5b4fae9b29f78be8244befbb269f2/linkerd/app/outbound/src/ingress.rs#L208-L227 and https://github.com/linkerd/linkerd2-proxy/blob/4e1720430fd5b4fae9b29f78be8244befbb269f2/linkerd/app/outbound/src/ingress.rs#L164-L200). I believe this is the path that traffic to the `ExternalName` service would have taken in 2.12.

In 2.13, however, the profile and policy resolution is always performed, with the fallback logic from linkerd/linkerd2-proxy#2431 handling the case where a ServiceProfile is discovered but no client policy is discovered. However, we are now always performing this discovery, even when there is no `l5d-dst-override` header present. For `ExternalName`  services, I believe this means we can now hit a case where both the policy controller and the destination controller don't provide the proxy with discovery, resulting in the error.

I'd like to do some more testing to confirm this hypothesis. I think it's possible that the best solution here is to go back to performing discovery only when the `l5d-dst-override` header is present, as we did in 2.13.
