### ISSUE TITLE
Add CNI Chart To Helm Hub

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3802] opened 2019-12-09 19:29 UTC
Add the Linkerd CNI chart to Helm Hub. See the Helm Hub [docs](https://github.com/helm/hub/blob/master/Repositories.md) for more information.

Depends on #3801.
See #3367 for previous work.

**Comment by zaharidichev** [comment] 2020-01-13 11:51
@alpeb As far as I take it this is blocked on releasing 2.7 as there is no CNI chart in the stable channel now because it has not yet been built by the CI, correct?

**Comment by alpeb** [comment] 2020-01-13 14:18
@zaharidichev It appears there's nothing to do here. Only a config at the repo level `(https://helm.linkerd.io/(edge|stable)` is needed, which we already did when the linkerd2 chart was added to the Helm Hub. And after last week's edge the linkerd2-cni chart was automatically picked up:
https://hub.helm.sh/charts/linkerd2-edge/linkerd2-cni
So when stable-2.7.0 gets released I expect it well get picked automatically as well.

**Comment by zaharidichev** [comment] 2020-01-13 14:42
Ah, this is pretty nice!!! I guess we can keep the issue upen until we verify that 2.7.0 will get picked as well.

**Comment by alpeb** [comment] 2020-03-02 19:44
Closing this, as I confirmed the linkerd2-cni 2.7.0 chart was automatically picked in the helm hub:
https://hub.helm.sh/charts/linkerd2/linkerd2-cni

**Closed by alpeb** 2020-03-02 19:44 UTC
Labels: area/build, priority/P1
