### ISSUE TITLE
Intermittent 0-byte responses in simpleRPC calls.

### ISSUE THREAD

**Issue by prasus** [linkerd/linkerd2#6058] opened 2021-04-26 10:08 UTC
### What is the issue?

We have recently introduced Linkerd (`stable-2.10.0`, deployed on self hosted k8s) in some of our apps and it works fine in general, but I have observed that every now and then the HTTP requests from our apps receives a response with an empty body (0 bytes), such events (simpleRPC calls from a few non-meshed apps to a meshed app) happens intermittently and I believe this has got something to do with Linkerd as this issue doesn't exist when we run the app without using Linkerd. 

The JSON content of the application error shows `closed early with 0 bytes received within 89 milliseconds` messages and a workaround solution is to add automatic retries in our simpleRPC library (the retry attempt succeeds without any issues). I already tried enabling proxy debug, trace logs for the app, but unfortunately the logs doesn't  provide much details during the 0-byte events. 🙁 

It would be extremely helpful if we could somehow fix this as we plan to inject Linkerd into many of our services and we might have an increased latency/response time due to this issue. Are there any tunable parameters (timeout, retry etc..) which can be set at Linkerd level for fixing this?

### How can it be reproduced?

This issues happens intermittently and there is not much info on the proxy (debug, trace) logs.

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 2.10.0 but the latest stable version is 2.10.1
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.10.0 but the latest stable version is 2.10.1
    see https://linkerd.io/checks/#l5d-version-control for hints
√ control plane and cli versions match

linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system

Status check results are √

Linkerd extensions checks
=========================

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ can initialize the client
√ viz extension self-check

Status check results are √
```

### Environment

 - Kubernetes Version: v1.18.8
 - Cluster Environment: Self hosted, Deployed via kubeadm
  - Host OS: Ubuntu 18.04.2 LTS
  - Linkerd version: stable-2.10.0 (deployed using helm chart)

### Possible solution

A workaround fix is to add automatic retries to the simpleRPC library.

**Comment by mateiidavid** [comment] 2021-04-26 14:06
Hey @prasus thanks for raising this! Think we briefly discussed in on Slack. Since there isn't much information available, it would probably be worth it for me to reproduce and see exactly what's going on to try and pinpoint the issue. 

To that end, any reproduction steps you can provide are much appreciated. And just to confirm, this only happens when you have an unmeshed workload sending an outbound request to a meshed workload? 

> I already tried enabling proxy debug, trace logs for the app, but unfortunately the logs doesn't provide much details during the 0-byte events. 🙁

Mm I see. It would still be pretty helpful for me to have a look if you can please paste them in, might be some good tidbits that we can use to investigate this. The recommended log-level in this case for the proxy would probably be `linkerd=debug,linkerd_proxy_http=trace,hyper=trace,warn`

In terms of timeouts and retries, you can generally use [ServiceProfiles](https://linkerd.io/2.10/features/retries-and-timeouts/) but I'm not very confident this would help much in the current scenario; timeouts/retries are usually "enforced" by the outbound proxy client which would be inexistent in an unmeshed workload.

Last but not least, have you considered upgrading to `stable-2.10.1`? There have been a number of issues fixed which might make your current configuration work as expected, such as 

>  fixed inbound TLS detection from non-meshed workloads

**Comment by prasus** [comment] 2021-04-27 11:04
Thanks much for the response, @mateiidavid. Yes, we discussed this last week on Slack, I thought of raising an issue here for tracking this in detail. 🙂 

> And just to confirm, this only happens when you have an meshed workload sending an outbound request to a meshed workload?

Yes, this is what we have noticed so far, but I am not 100% sure as most of our apps are currently non-meshed. 

Below is the trace logs snippet taken during incident time. I have only included the relevant log lines here, please let me know if you wish to see the full logs. `10.244.78.84` is the non-meshed app pod.

```text
Apr 27, 2021 @ 10:25:52.507[ 16767.292578s]  INFO ThreadId(01) inbound:accept{client.addr=10.244.78.84:46080 target.addr=10.244.42.122:80}: linkerd_app_core::serve: Connection closed error=TLS detection timeout
Apr 27, 2021 @ 10:25:52.158[ 16735.596479s]  INFO ThreadId(01) inbound:accept{client.addr=10.244.78.84:46082 target.addr=10.244.5.41:80}: linkerd_app_core::serve: Connection closed error=TLS detection timeout
Apr 27, 2021 @ 10:25:50.438[ 16764.243314s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
Apr 27, 2021 @ 10:25:50.437[ 16764.243303s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::io: flushed 5 bytes
Apr 27, 2021 @ 10:25:50.435[ 16764.243219s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::conn: flushed({role=server}): State { reading: KeepAlive, writing: Body(Encoder { kind: Chunked, is_last: false }), keep_alive: Busy }
Apr 27, 2021 @ 10:25:50.427[ 16764.243089s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::io: flushed 100 bytes
Apr 27, 2021 @ 10:25:50.427[ 16764.243103s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::conn: flushed({role=server}): State { reading: KeepAlive, writing: Body(Encoder { kind: Chunked, is_last: false }), keep_alive: Busy }
Apr 27, 2021 @ 10:25:50.426[ 16764.243000s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}:encode_headers: hyper::proto::h1::role: Server::encode status=200, body=Some(Unknown), req_method=Some(POST)
Apr 27, 2021 @ 10:25:50.426[ 16764.243033s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::encode: encoding chunked 11B
Apr 27, 2021 @ 10:25:50.418[ 16764.240474s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::conn: flushed({role=server}): State { reading: KeepAlive, writing: Init, keep_alive: Busy }
Apr 27, 2021 @ 10:25:50.415[ 16764.240297s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::conn: incoming body completed
Apr 27, 2021 @ 10:25:50.415[ 16764.240342s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::conn: flushed({role=server}): State { reading: KeepAlive, writing: Init, keep_alive: Busy }
Apr 27, 2021 @ 10:25:50.414[ 16764.240253s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::decode: decode; state=Length(5)
Apr 27, 2021 @ 10:25:50.412[ 16764.199475s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::conn: flushed({role=server}): State { reading: Body(Length(5)), writing: Init, keep_alive: Busy }
Apr 27, 2021 @ 10:25:50.411[ 16764.199435s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}:http{v=1.x}:http1{name=image-metadata.appns.svc.cluster.local:80}:profile:http1: hyper::client::pool: take? ("http", image-metadata.appns.svc.cluster.local): expiration = Some(20s)
Apr 27, 2021 @ 10:25:50.411[ 16764.199450s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}:http{v=1.x}:http1{name=image-metadata.appns.svc.cluster.local:80}:profile:http1: hyper::client::pool: reuse idle connection for ("http", image-metadata.appns.svc.cluster.local)
Apr 27, 2021 @ 10:25:50.410[ 16764.199411s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::decode: decode; state=Length(5)
Apr 27, 2021 @ 10:25:50.409[ 16764.199351s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}:http{v=1.x}:http1{name=image-metadata.appns.svc.cluster.local:80}:profile:http1: linkerd_proxy_http::client: headers={"user-agent": "Jaumo HTTP Client, PHP 7.4.16", "content-type": "avro/binary", "accept": "avro/binary", "accept-encoding": "gzip, deflate, identity", "host": "image-metadata.appns.svc.cluster.local", "content-length": "5"}
Apr 27, 2021 @ 10:25:50.409[ 16764.199371s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}:http{v=1.x}:http1{name=image-metadata.appns.svc.cluster.local:80}:profile:http1: linkerd_proxy_http::h1: Using origin-form client
Apr 27, 2021 @ 10:25:50.408[ 16764.199274s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::conn: flushed({role=server}): State { reading: Body(Length(5)), writing: Init, keep_alive: Busy }
Apr 27, 2021 @ 10:25:50.408[ 16764.199330s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}:http{v=1.x}:http1{name=image-metadata.appns.svc.cluster.local:80}:profile:http1: linkerd_proxy_http::client: method=POST uri=http://image-metadata.appns.svc.cluster.local/rpc/getPhotoDuplicates version=HTTP/1.1
Apr 27, 2021 @ 10:25:50.407[ 16764.199139s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}:http{v=1.x}: linkerd_proxy_http::normalize_uri: Normalizing URI authority=image-metadata.appns.svc.cluster.local
Apr 27, 2021 @ 10:25:50.407[ 16764.199196s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::decode: decode; state=Length(5)
Apr 27, 2021 @ 10:25:50.406[ 16764.199092s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::conn: incoming body is content-length (5 bytes)
Apr 27, 2021 @ 10:25:50.406[ 16764.199119s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}:http{v=1.x}: linkerd_proxy_http::normalize_uri: Origin form uri=/rpc/getPhotoDuplicates
Apr 27, 2021 @ 10:25:50.405[ 16764.199017s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}:parse_headers: hyper::proto::h1::role: Request.parse Complete(248)
Apr 27, 2021 @ 10:25:50.405[ 16764.199027s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}:parse_headers: hyper::proto::h1::role: headers: [Header { name: "User-Agent", value: [74, 97, 117, 109, 111, 32, 72, 84, 84, 80, 32, 67, 108, 105, 101, 110, 116, 44, 32, 80, 72, 80, 32, 55, 46, 52, 46, 49, 54] }, Header { name: "Content-Type", value: [97, 118, 114, 111, 47, 98, 105, 110, 97, 114, 121] }, Header { name: "Accept", value: [97, 118, 114, 111, 47, 98, 105, 110, 97, 114, 121] }, Header { name: "Accept-Encoding", value: [103, 122, 105, 112, 44, 32, 100, 101, 102, 108, 97, 116, 101, 44, 32, 105, 100, 101, 110, 116, 105, 116, 121] }, Header { name: "host", value: [105, 109, 97, 103, 101, 45, 109, 101, 116, 97, 100, 97, 116, 97, 46, 105, 109, 97, 103, 101, 45, 102, 101, 97, 116, 117, 114, 101, 115, 46, 115, 118, 99, 46, 99, 108, 117, 115, 116, 101, 114, 46, 108, 111, 99, 97, 108] }, Header { name: "content-length", value: [53] }]
Apr 27, 2021 @ 10:25:50.405[ 16764.199078s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::io: parsed 6 headers
Apr 27, 2021 @ 10:25:50.404[ 16764.198964s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}: hyper::proto::h1::conn: Conn::read_head
Apr 27, 2021 @ 10:25:50.404[ 16764.199002s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.78.84:46076 target.addr=10.244.42.122:80}:parse_headers: hyper::proto::h1::role: Request.parse([Header; 100], [u8; 248])
```
Let me know if you need an further details, Thanks! 🙏🏿

**Comment by prasus** [comment] 2021-04-28 09:13
Hey @mateiidavid, We have upgraded to `stable-2.10.1` earlier today but unfortunately it didn't help and the issue persists after the upgrade, Thanks!

**Comment by mateiidavid** [comment] 2021-04-28 09:44
> Hey @mateiidavid, We have upgraded to `stable-2.10.1` earlier today but unfortunately it didn't help and the issue persists after the upgrade, Thanks!

Thanks for letting me know! I haven't started reproducing this yet but I was hoping an upgrade would solve this (especially since I saw those two `Connection closed error=TLS detection timeout` lines at the top of the logs). 

I'll look into it this week and update this comment with my findings 🔍.

**Comment by mateiidavid** [comment] 2021-04-28 17:46
Hey @prasus,

I looked into this a bit today. The first thing that stood out to me were the two lines at the top:
```
Apr 27, 2021 @ 10:25:52.507[ 16767.292578s]  INFO ThreadId(01) inbound:accept{client.addr=10.244.78.84:46080 target.addr=10.244.42.122:80}: linkerd_app_core::serve: Connection closed error=TLS detection timeout
Apr 27, 2021 @ 10:25:52.158[ 16735.596479s]  INFO ThreadId(01) inbound:accept{client.addr=10.244.78.84:46082 target.addr=10.244.5.41:80}: linkerd_app_core::serve: Connection closed error=TLS detection timeout
```

Other than those TLS detection timeout errors there isn't much information that can pinpoint the issue. As a starting point in getting this demystified, it would be great to see the logs before the incident. If you saved the logs somewhere, it would be helpful to run a grep on the two ports (`46076` and `46080`) and paste the results here.

Linkerd does protocol detection on connections; TLS detection timeout is a symptom of a failed protocol detection here, since the debug statements are turned on it will be very helpful to see what happened before the timeout occurred.

I have a few more things we can try but this should be a good starting point!

**Comment by prasus** [comment] 2021-04-29 07:03
Thanks again for looking into this, @mateiidavid. 

I did a grep as suggested today after re-enabling the trace logs, but there is only a single `DEBUG` entry before the timeout as seen below.

```
Apr 29, 2021 @ 06:27:07.223[ 78621.042481s]  INFO ThreadId(01) inbound:accept{client.addr=10.244.47.173:35752}: linkerd_app_core::serve: Connection closed error=TLS detection timeout
Apr 29, 2021 @ 06:26:57.185[ 78611.041151s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.47.173:35752}:server{port=80}: linkerd_app_inbound::prevent_loop: addr=10.244.75.123:80 self.port=4143                                                                                                                                                                                                     
```

I am not sure if this helps, Please let me know if you wish to see the full logs. Thank you!

**Comment by prasus** [comment] 2021-04-29 07:34
The trace logs between the below timestamps are available [here](https://gist.github.com/prasus/b50734ccb79e6c38cd845c736da050ec), I have only included the log enrties from pod ip `10.244.47.173` (`grep 10.244.47.173`). 

```
Apr 29, 2021 @ 06:27:07.223[ 78621.042481s]  INFO ThreadId(01) inbound:accept{client.addr=10.244.47.173:35752}: linkerd_app_core::serve: Connection closed error=TLS detection timeout
Apr 29, 2021 @ 06:26:57.185[ 78611.041151s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.47.173:35752}:server{port=80}: linkerd_app_inbound::prevent_loop: addr=10.244.75.123:80 self.port=4143 
```

**Comment by mateiidavid** [comment] 2021-04-29 15:37
Hey @prasus,

Thanks for the logs and prompt reply! I've looked at the logs a few times and there are some additional questions I have; as it stands, there is still not much to go on in terms of pinpointing the issue.

To get this out of the way, the `prevent_loop` statements shouldn't be an issue, this just gets logged out since we [prevent looping on the inbound side](https://github.com/linkerd/linkerd2-proxy/blob/3a3f25fa2ebcb4473eb6f21790e7c0e4f648cf3e/linkerd/app/inbound/src/prevent_loop.rs)
```
Apr 29, 2021 @ 06:26:57.185[ 78611.041151s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.47.173:35752}:server{port=80}: linkerd_app_inbound::prevent_loop: addr=10.244.75.123:80 self.port=4143 
```


What stood out to me is that we seem to have different clients sending stuff through to the server. For example, in the first set of logs you posted, we can see TLS detection timeouts on 2 different client addrs:
```
# client addr 1: 10.244.78.84:46080
Apr 27, 2021 @ 10:25:52.507[ 16767.292578s]  INFO ThreadId(01) inbound:accept{client.addr=10.244.78.84:46080 target.addr=10.244.42.122:80}: linkerd_app_core::serve: Connection closed error=TLS detection timeout

# client addr 2: 10.244.78.84:46082
Apr 27, 2021 @ 10:25:52.158[ 16735.596479s]  INFO ThreadId(01) inbound:accept{client.addr=10.244.78.84:46082 target.addr=10.244.5.41:80}: linkerd_app_core::serve: Connection closed error=TLS detection timeout
```

This seems to also surface in the more extensive logs you provided, instead of different IPs we have different ports on the client side:
```
# :35752
Apr 29, 2021 @ 06:27:07.223[ 78621.042481s]  INFO ThreadId(01) inbound:accept{client.addr=10.244.47.173:35752}: linkerd_app_core::serve: Connection closed error=TLS detection timeout

# :35666 
Apr 29, 2021 @ 06:27:04.494[ 78592.040793s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.47.173:35666}:server{port=80}:proxy: hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }

# :35668
Apr 29, 2021 @ 06:27:04.641[ 78592.042266s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.47.173:35668}:server{port=80}:proxy: hyper::proto::h1::conn: flushed({role=server}): State { reading: Init, writing: Init, keep_alive: Idle }
```

The TLS detection timeout we see is a bit peculiar. I thought at first it would mean there is no data read from the socket on the proxy inbound side, which would mean there is no way to detect the protocol in use (or the proxy times out when detecting it, timeout is around 10s). However, in the logs you posted _we do seem to peek in the TCP stream_ so we do in fact read data from the socket:

```
Apr 29, 2021 @ 06:27:05.924[ 78550.557488s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.47.173:35744}:server{port=80}:proxy: linkerd_proxy_http::server: Handling as HTTP version=Http1
Apr 29, 2021 @ 06:27:05.924[ 78550.557576s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.47.173:35744}:server{port=80}:proxy: hyper::proto::h1::conn: Conn::read_head
Apr 29, 2021 @ 06:27:05.923[ 78550.557390s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.47.173:35744}:server{port=80}:proxy: linkerd_detect: DetectResult protocol=Some(Http1) elapsed=50.951µs
Apr 29, 2021 @ 06:27:05.923[ 78550.557382s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.47.173:35744}:server{port=80}:proxy: linkerd_proxy_http::detect: Matched HTTP/1
Apr 29, 2021 @ 06:27:05.923[ 78550.557441s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.47.173:35744}:server{port=80}:proxy: linkerd_proxy_http::server: Creating HTTP service version=Http1
Apr 29, 2021 @ 06:27:05.922[ 78550.557374s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.47.173:35744}:server{port=80}:proxy: linkerd_proxy_http::detect: Parsing HTTP/1 message
Apr 29, 2021 @ 06:27:05.922[ 78550.557366s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.47.173:35744}:server{port=80}:proxy: linkerd_proxy_http::detect: Checking H2 preface
Apr 29, 2021 @ 06:27:05.921[ 78550.557342s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.47.173:35744}:server{port=80}:proxy: linkerd_proxy_http::detect: Reading capacity=1024
Apr 29, 2021 @ 06:27:05.921[ 78550.557358s] TRACE ThreadId(01) inbound:accept{client.addr=10.244.47.173:35744}:server{port=80}:proxy: linkerd_proxy_http::detect: Read sz=243
Apr 29, 2021 @ 06:27:05.920[ 78550.557259s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.47.173:35744}:server{port=80}:proxy: linkerd_tls::server: Peeked bytes from TCP stream sz=238
```

*To put it all together*:  I think the issue here is less about the server sending 0 byte responses, and more about the connection(s) being terminated. Since we see different client addresses (/ports) _and_ a TLS detection timeout, here are the questions that I have:

1. Does the client do its own TLS? Could lead us to some more interesting discoveries if yes.

2. Does the client (or the library) have a connection pool? Since we are seeing different ports, I'd assume there is a connection pool on the client side, if that's the case then certain connections might be idling and dropped by the proxy -- this would explain why you see this intermittently and why retries help you go around the problem, if the connection is dropped the client simply retries.

Let me know what you think, there is one additional thing we can try if the answer is No to both (1) and (2).

**Comment by prasus** [comment] 2021-04-30 07:04
Thanks much for the quick and detailed response, @mateiidavid 🙏🏿 

> What stood out to me is that we seem to have different clients sending stuff through to the server.

You are right, there are multiple/different clients/apps sending connections to the meshed app

> Does the client do its own TLS? 

No
> Does the client (or the library) have a connection pool? 

Yes

Please let me know if you need any further details, Thanks! 🙂

**Comment by mateiidavid** [comment] 2021-05-04 17:41
Hey @prasus sorry for the wait!

I have been looking into this for a while, I went through my previous assumptions and tried to figure out why those TLS detection errors are thrown. My assumption is that the connection pool is likely a cause, but I'd still like to verify it.

I wanted to give you an overview of what exactly is happening to the request to see whether we can get any more information from your logs. Failing that, there are a couple of suggestions that could probably help you work around this.

To understand why you're encountering these errors, it's helpful to look at the proxy code. [This is where we construct](https://github.com/linkerd/linkerd2-proxy/blob/3a3f25fa2ebcb4473eb6f21790e7c0e4f648cf3e/linkerd/app/inbound/src/lib.rs#L208) the inbound side of the proxy; what's of interest to us starts from [this line (273)](https://github.com/linkerd/linkerd2-proxy/blob/3a3f25fa2ebcb4473eb6f21790e7c0e4f648cf3e/linkerd/app/inbound/src/lib.rs#L273). Overly simplified, we construct a couple of network layers and push them ontop of a stack, so we need to read this bottoms-up. You'll notice on line 273 we construct a `prevent_loop` -- that's the line that starts your logs off.

Some of your connections seem to be torn down in the [TLS detection layer](https://github.com/linkerd/linkerd2-proxy/blob/3a3f25fa2ebcb4473eb6f21790e7c0e4f648cf3e/linkerd/app/inbound/src/lib.rs#L255) on line 255, others seem to go past this point (we know this because in the logs we can see protocols are being detected, also this happens intermittently like you have pointed out). I have been stuck trying to figure out _why it would fail here_. The answer is in a different file [where we try to detect whether TLS is in use](https://github.com/linkerd/linkerd2-proxy/blob/00c3394ab36eeff14192e6ae52c41238376daabd/linkerd/tls/src/server/mod.rs#L171) -- you'll notice that we try to resolve the SNI from the client or timeout (as the comment suggests), this doesn't mean that without an SNI we timeout, it means that we will timeout if we can't handle the SNI detection properly. [Detection may fail for a number of reasons](https://github.com/linkerd/linkerd2-proxy/blob/00c3394ab36eeff14192e6ae52c41238376daabd/linkerd/tls/src/server/mod.rs#L215-L227) but if you look through the lines highlighted we would at least get some data off the socket, or encounter some debug statements  -- I haven't seen any of those present there though which baffled me to be completely honest, but led me to believe that the connection would be simply idling (so the client wouldn't send anything through the TCP Stream).

I'll have to ask again for logs but this time only for the port of a client that fails with detect TLS timeout (so we can remove some of the noise). For example, if a client socket with port `:35752` fails it then it would be more helpful to get only logs pertaining to it with plenty of lines before and after the failure. I also think we can take `hyper` out of the log level since it doesn't necessarily give us anything new. I'd  also add a `trace` level, something like `linkerd2=debug,linkerd2_proxy=trace` (which I think might work). Feel free to redact any info that you don't want us to see (if there is anything sensitive).

Now, there are a couple of obvious things you can do to bypass the error:
* Mesh the client too (and this will limit the proxy to only talk with one client which will probably get rid of the idle timeouts),
* Configure your connection pool and see if the issue disappears.

If you can give us a demo client to run and reproduce this I'd be happy to dig deeper. You can also let us know what library and configuration you use and we can have a look at the connection pool and perhaps suggest a different configuration.

Let me know what works best for you, happy to keep digging into this :)

**Comment by prasus** [comment] 2021-05-05 08:48
Hey @mateiidavid Thank you very much for your continued support, much appreciated! 🙏🏿 

Please find the new logs attached [here](https://gist.github.com/prasus/27c6f4a5e08380a098a36896f42bae43) (I have omitted sensitive data and have also grepped for the client pod IP `10.244.44.64`) Below are the `Connection closed error=TLS detection timeout` errors in the logs.

```
May 5, 2021 @ 06:54:35.675[176916.878033s]  INFO ThreadId(01) inbound:accept{client.addr=10.244.44.64:51490}: linkerd_app_core::serve: Connection closed error=TLS detection timeout
May 5, 2021 @ 06:54:35.675[176916.898323s]  INFO ThreadId(01) inbound:accept{client.addr=10.244.44.64:51584}: linkerd_app_core::serve: Connection closed error=TLS detection timeout
May 5, 2021 @ 06:54:35.674[176916.817268s]  INFO ThreadId(01) inbound:accept{client.addr=10.244.44.64:51376}: linkerd_app_core::serve: Connection closed error=TLS detection timeout
```

As you noticed it looks like the client doesn't sent any data after opening the connection as we don't have any log entries between the connection initialization and the timeout as seen below.

```
May 5, 2021 @ 06:54:35.675[176916.878033s]  INFO ThreadId(01) inbound:accept{client.addr=10.244.44.64:51490}: linkerd_app_core::serve: Connection closed error=TLS detection timeout
May 5, 2021 @ 06:54:25.969[176906.875707s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.44.64:51490}:server{port=80}: linkerd_app_inbound::prevent_loop: addr=10.244.65.122:80 self.port=4143
May 5, 2021 @ 06:54:35.675[176916.898323s]  INFO ThreadId(01) inbound:accept{client.addr=10.244.44.64:51584}: linkerd_app_core::serve: Connection closed error=TLS detection timeout
May 5, 2021 @ 06:54:25.972[176906.896870s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.44.64:51584}:server{port=80}: linkerd_app_inbound::prevent_loop: addr=10.244.65.122:80 self.port=4143
May 5, 2021 @ 06:54:35.674[176916.817268s]  INFO ThreadId(01) inbound:accept{client.addr=10.244.44.64:51376}: linkerd_app_core::serve: Connection closed error=TLS detection timeout
May 5, 2021 @ 06:54:25.961[176906.816080s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.44.64:51376}:server{port=80}: linkerd_app_inbound::prevent_loop: addr=10.244.65.122:80 self.port=4143
```
We also performed a detailed investigation from the application side in the last couple of days and based on that we also believe that these connections would be simply idling like you have pointed out, and then linkerd drops them out of its pool. I am wondering whether Linkerd has any default client side idle timeout, if so we can adjust the idle time in the application side to match with Linkerd's values to mitigate this.

We intend to mesh all our apps, but unfortunately this will take some time. 🙁  Our applications are based on spring web server, I will work with our team and let you know the connection pool implementation details, Thank you! 🙂

**Comment by mateiidavid** [comment] 2021-05-06 15:31
> As you noticed it looks like the client doesn't sent any data after opening the connection as we don't have any log entries between the connection initialization and the timeout as seen below.

Yup. Unfortunately nothing new there :( 

> am wondering whether Linkerd has any default client side idle timeout

Not really. There is the TLS detection timeout which is 10s (same as protocol timeout). The proxy doesn't really know what to with the connection so it just drops it. Normally, we need to know whether it is TLS'd first and then establish a connection to the target addr. This is seen [in the inbound stack](https://github.com/linkerd/linkerd2-proxy/blob/3a3f25fa2ebcb4473eb6f21790e7c0e4f648cf3e/linkerd/app/inbound/src/lib.rs#L254) with TcpAccept being implemented [here](https://github.com/linkerd/linkerd2-proxy/blob/3a3f25fa2ebcb4473eb6f21790e7c0e4f648cf3e/linkerd/app/inbound/src/target.rs#L62). You could perhaps trying to lower the idle timeout to be 10 or below 10s?



10 second timeout in action (notice the difference in timestamps, ~ 10s):
```
May 5, 2021 @ 06:54:25.972[176906.896870s] DEBUG ThreadId(01) inbound:accept{client.addr=10.244.44.64:51584}:server{port=80}: linkerd_app_inbound::prevent_loop: addr=10.244.65.122:80 self.port=4143

May 5, 2021 @ 06:54:35.675[176916.898323s]  INFO ThreadId(01) inbound:accept{client.addr=10.244.44.64:51584}: linkerd_app_core::serve: Connection closed error=TLS detection timeout
```

There isn't really anything else on my side that I can look into. Will leave this issue open for a bit longer to see whether there is any config we could look through or if you have any updates. If you notice anything please reach out :)

**Comment by mateiidavid** [comment] 2021-05-14 13:00
Hey @prasus any new findings on this?

**Comment by mateiidavid** [comment] 2021-05-18 14:05
@prasus I'll be closing this for now. If you have some new findings and would like this re-opened just post a comment and mention me.

Alternatively, feel free to raise a new issue :)

**Closed by mateiidavid** 2021-05-18 14:05 UTC
