### ISSUE TITLE
HTTP Metrics is blank for some of the PODS

### ISSUE THREAD

**Issue by praveenpattisapu** [linkerd/linkerd2#5853] opened 2021-03-02 10:40 UTC
We are using stable 2.9.2 linkerd2 version on AKS(1.16.15).
on the linkerd2 dashboard, http metric results are very inconsistent and that means, for the same API, if we have 2 pods running, it shows the data for one pod and for the other one it is blank. And for some of the API's it shows blank.And for some of the API's it shows the full data.please see the attached screen shots for more details
We have implemented network policy and added the below snippet code to allow linkerd name space but still that did'nt do the trick.

Code Added in NetworkPolicy.yaml:
- from:
    - namespaceSelector:
        matchLabels:
          linkerd.io/control-plane-ns: "linkerd"

These are the logs from linkerd-proxy container from premethues pod,

AlertMessagePayload {
level: Fatal,
description: AccessDenied,
},
),
}
[ 1927.689445s] WARN ThreadId(01) outbound:accept{peer.addr=10.186.78.137:41626 target.addr=10.186.79.195:4191}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
[ 1927.807922s] WARN ThreadId(01) outbound:accept{peer.addr=10.186.78.137:55900 target.addr=10.186.78.141:4191}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
[ 1927.847426s] ERROR ThreadId(01) outbound: rustls::session: TLS alert received: Message {
typ: Alert,
version: TLSv1_2,
payload: Alert(
AlertMessagePayload {
level: Fatal,
description: AccessDenied,
},
),
}
[ 1927.912865s] ERROR ThreadId(01) outbound: rustls::session: TLS alert received: Message {
typ: Alert,
version: TLSv1_2,
payload: Alert(
AlertMessagePayload {
level: Fatal,
description: AccessDenied,

please let me know if you require more info,

Any help here is very much appreciated.

Below is the output from linkerd2 check:

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 20.12.1 but the latest edge version is 21.2.4
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.9.2 but the latest stable version is 2.9.4
    see https://linkerd.io/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running stable-2.9.2 but cli running edge-20.12.1
    see https://linkerd.io/checks/#l5d-version-control for hints

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √

**Comment by praveenpattisapu** [comment] 2021-03-02 15:42
[API Showing No Traffic.docx](https://github.com/linkerd/linkerd2/files/6069798/API.Showing.No.Traffic.docx)
Attached is the file

**Comment by adleong** [comment] 2021-03-12 00:40
Hi @praveenpattisapu.  Based on the error message in the proxy logs, it looks like connections from Prometheus's to other pods are getting rejected by the network policy.  You will need to make sure your network policy is configured to allow these connection or disable the network policy entirely in order for Prometheus to be able to scrape metrics from pods.

**Comment by praveenpattisapu** [comment] 2021-03-12 09:32
Hi @adleong thanks for your reply, I even tested with out network policy but i am getting the same results, so network policy is not making any difference. Also, in our K8 cluster, we got 2 Envs which are differentiated by the name space like DEV and TST, So any API will be deployed on both the envs.But for most of the API's(Not all), it will only show HTTP metrics only on one name space either in dev or test which is very strange as the code is same.

**Comment by adleong** [comment] 2021-03-13 01:45
Yep, that does sound strange.  Unfortunately, without concrete reproduction steps, there's not a lot we can do to help.

All I can tell you is that the Linkerd error message indicates that the TLS connection is getting AccessDenied.  I know that you said you disabled network policy, but perhaps some remnant of it is still in place?  I'd recommend focusing on figuring out why that TLS connection is getting AccessDenied.

In the meantime, I'm going to close this issue since we can't help much beyond that.  But please feel free to re-open if you are able to provide concrete reproduction steps or if you need help interpreting Linkerd logs or behaviors.

**Closed by adleong** 2021-03-13 01:45 UTC

**Comment by praveenpattisapu** [comment] 2021-03-16 10:39
> Yep, that does sound strange. Unfortunately, without concrete reproduction steps, there's not a lot we can do to help.
> 
> All I can tell you is that the Linkerd error message indicates that the TLS connection is getting AccessDenied. I know that you said you disabled network policy, but perhaps some remnant of it is still in place? I'd recommend focusing on figuring out why that TLS connection is getting AccessDenied.
> 
> In the meantime, I'm going to close this issue since we can't help much beyond that. But please feel free to re-open if you are able to provide concrete reproduction steps or if you need help interpreting Linkerd logs or behaviors.

This issue still persists and please reopen the issue, I can reproduce the issue.
