### ISSUE TITLE
Timeouts to the linkerd-policy-validator service with latest edge

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#7941] opened 2022-02-22 20:35 UTC
### What is the issue?

On a fresh linkerd install of the latest edge, when I `kubectl apply` a srv object, the request that's made to the policy validator to validate the new object times out after 10 seconds.

### How can it be reproduced?

Install linkerd:

```
linkerd install | kubectl apply -f -
```

Then apply the following config:

```yaml
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: default
  name: admin
spec:
  podSelector:
    matchLabels:
      app: foo
  port: admin
  proxyProtocol: HTTP/1
```

Note that the apply request completes, but only after 10 seconds:

```
$ time kubectl apply -f policy.yaml
server.policy.linkerd.io/admin created
kubectl apply -f policy.yaml  0.33s user 0.39s system 7% cpu 10.190 total
```

Then update the `failurePolicy` for the validating webhook config to be `Fail` instead of `Ignore`:

```
kubectl -n linkerd edit validatingwebhookconfiguration/linkerd-policy-validator-webhook-config
```

The delete the previously applied server config:

```
kubectl delete -f policy.yaml 
```

And re-apply it:

```
$ kubectl apply -f policy.yaml                                                           
Error from server (InternalError): error when creating "policy.yaml": Internal error occurred: failed calling webhook "linkerd-policy-validator.linkerd.io": Post "https://linkerd-policy-validator.linkerd.svc:443/?timeout=10s": context deadline exceeded
```

The apply fails.

### Logs, error output, etc

`policy` container logs:

```
$ kubectl -n linkerd logs deploy/linkerd-destination policy
2022-02-22T20:23:34.582875Z  INFO serve{addr=0.0.0.0:9990}: linkerd_policy_controller::admin: HTTP admin server listening addr=0.0.0.0:9990
2022-02-22T20:23:34.583288Z  INFO linkerd_policy_controller: Admission controller server listening addr=0.0.0.0:9443
2022-02-22T20:23:34.583341Z  INFO grpc{addr=0.0.0.0:8090 cluster_networks=[10.0.0.0/8, 100.64.0.0/10, 172.16.0.0/12, 192.168.0.0/16]}: linkerd_policy_controller: gRPC server listening addr=0.0.0.0:8090
2022-02-22T20:24:34.385347Z ERROR admission:connection{client.addr=127.0.0.1:44284}: linkerd_policy_controller: error=TLS error
2022-02-22T20:24:36.446045Z ERROR admission:connection{client.addr=127.0.0.1:44298}: linkerd_policy_controller: error=TLS error
2022-02-22T20:24:37.084101Z ERROR admission:connection{client.addr=127.0.0.1:44310}: linkerd_policy_controller: error=TLS error
2022-02-22T20:25:04.213935Z ERROR admission:connection{client.addr=127.0.0.1:44620}: linkerd_policy_controller: error=TLS error
2022-02-22T20:25:25.602525Z  INFO admission:connection{client.addr=10.244.0.23:47336}: linkerd_policy_controller: Connection closed error=Connection closed
2022-02-22T20:26:57.943647Z  INFO admission:connection{client.addr=10.244.0.23:48352}: linkerd_policy_controller: Connection closed error=Connection closed
2022-02-22T20:27:28.762075Z  INFO admission:connection{client.addr=10.244.0.23:48698}: linkerd_policy_controller: Connection closed error=Connection closed
2022-02-22T20:33:54.665310Z  INFO admission:connection{client.addr=10.244.0.23:52910}: linkerd_policy_controller: Connection closed error=Connection closed
```

### output of `linkerd check -o short`

```
$ linkerd check -o short
Status check results are √
```

### Environment

```
$ kubectl version --short
Client Version: v1.22.5
Server Version: v1.21.1
```

```
$ linkerd version --short
edge-22.2.3
edge-22.2.3
```

**Comment by adleong** [comment] 2022-02-23 00:25
This can be observed by manually curling the admission server.  The following curl command yields this output and then hangs:

<details>
<summary>
req.json
</summary>


```json
{ 
"apiVersion": "admission.k8s.io/v1",
"kind": "AdmissionRequest",
"request": {
  "uid": "03365d18-34f8-47fe-b1de-4af9d9ee8f65",
  "kind": {
    "group": "policy.linkerd.io",
    "version": "v1beta1",
    "kind": "Server"
  },
  "resource": {
    "group": "policy.linkerd.io",
    "version":"v1beta1",
    "resource":"servers"
  },
  "name": "emoji-grpc",
  "namespace": "emojivoto",
  "operation": "UPDATE",
  "userInfo": {},
  "object": {
    "apiVersion": "policy.linkerd.io/v1beta1",
    "kind": "Server",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"policy.linkerd.io/v1alpha1\",\"kind\":\"Server\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/name\":\"emoji\",\"app.kubernetes.io/part-of\":\"emojivoto\",\"app.kubernetes.io/version\":\"v11\"},\"name\":\"emoji-grpc\",\"namespace\":\"emojivoto\"},\"spec\":{\"podSelector\":{\"matchLabels\":{\"app\":\"emoji-svc\"}},\"port\":\"grpc\",\"proxyProtocol\":\"gRPC\"}}\n"
        },
        "creationTimestamp": "2022-02-22T20:01:09Z",
        "generation": 7,
        "labels": {
            "app.kubernetes.io/name": "emoji",
            "app.kubernetes.io/part-of": "emojivoto",
            "app.kubernetes.io/version": "v11"
        },
        "name": "emoji-grpc",
        "namespace": "emojivoto",
        "resourceVersion": "6014359",
        "uid": "c3afff54-52c1-4218-ab4d-798e7b3d028e"
    },
    "spec": {
        "podSelector": {
            "matchLabels": {
                "app": "emoji-svc"
            }
        },
        "port": "grpcxyz",
        "proxyProtocol": "gRPC"
    }
}
}
}
```
</details>

```console
> k port-forward -n linkerd svc/linkerd-policy-validator 8888:443 &
> curl -kv -X POST https://localhost:8888 -d @req.json
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:8888...
* Connected to localhost (127.0.0.1) port 8888 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=linkerd-policy-validator.linkerd.svc
*  start date: Feb 22 23:05:24 2022 GMT
*  expire date: Feb 22 23:05:24 2023 GMT
*  issuer: CN=linkerd-policy-validator.linkerd.svc
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55f4e900a250)
> POST / HTTP/2
> Host: localhost:8888
> user-agent: curl/7.74.0
> accept: */*
> content-length: 1602
> content-type: application/x-www-form-urlencoded
> 
* We are completely uploaded and fine
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
```

The policy admission controller logs that it successfully parses the request, but does not log that it builds a response:

```
2022-02-23T00:10:34.731951Z DEBUG linkerd_policy_controller::admission: req=AdmissionRequest { types: TypeMeta { api_version: "admission.k8s.io/v1", kind: "AdmissionRequest" }, uid: "03365d18-34f8-47fe-b1de-4af9d9ee8f65", kind: GroupVersionKind { group: "policy.linkerd.io", version: "v1beta1", kind: "Server" }, resource: GroupVersionResource { group: "policy.linkerd.io", version: "v1beta1", resource: "servers", api_version: "" }, sub_resource: None, request_kind: None, request_resource: None, request_sub_resource: None, name: "emoji-grpc", namespace: Some("emojivoto"), operation: Update, user_info: UserInfo { extra: None, groups: None, uid: None, username: None }, object: Some(DynamicObject { types: Some(TypeMeta { api_version: "policy.linkerd.io/v1beta1", kind: "Server" }), metadata: ObjectMeta { annotations: Some({"kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"policy.linkerd.io/v1alpha1\",\"kind\":\"Server\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/name\":\"emoji\",\"app.kubernetes.io/part-of\":\"emojivoto\",\"app.kubernetes.io/version\":\"v11\"},\"name\":\"emoji-grpc\",\"namespace\":\"emojivoto\"},\"spec\":{\"podSelector\":{\"matchLabels\":{\"app\":\"emoji-svc\"}},\"port\":\"grpc\",\"proxyProtocol\":\"gRPC\"}}\n"}), cluster_name: None, creation_timestamp: Some(Time(2022-02-22T20:01:09Z)), deletion_grace_period_seconds: None, deletion_timestamp: None, finalizers: None, generate_name: None, generation: Some(7), labels: Some({"app.kubernetes.io/name": "emoji", "app.kubernetes.io/part-of": "emojivoto", "app.kubernetes.io/version": "v11"}), managed_fields: None, name: Some("emoji-grpc"), namespace: Some("emojivoto"), owner_references: None, resource_version: Some("6014359"), self_link: None, uid: Some("c3afff54-52c1-4218-ab4d-798e7b3d028e") }, data: Object({"spec": Object({"podSelector": Object({"matchLabels": Object({"app": String("emoji-svc")})}), "port": String("grpcxyz"), "proxyProtocol": String("gRPC")})}) }), old_object: None, dry_run: false, options: None }
2022-02-23T00:10:34.732197Z DEBUG tower::buffer::worker: service.ready=true processing request
```

The only async which happens in between where the request is logged and where the response is logged is this call to api.list: https://github.com/linkerd/linkerd2/blob/main/policy-controller/src/admission.rs#L71.  Does this suggest that this async call is never completing?

Interestingly, this problem doesn't seem to happen when I run the policy controller locally.  In that case, the same curl request gets a response immediately.

**Comment by NeonSludge** [comment] 2022-02-23 13:11
We're seeing the same behavior with the latest edge.
Here are two interesting details:
1. The policy admission controller works fine for about 30-50 seconds after a restart. After that time has passed, any admission requests hang indefinitely. It doesn't matter how many admission requests it has processed during this period.
2. The policy admission controller retrieves a list of `Server`'s while processing an admission request. We can see this request when the controller is working fine but no such requests are made after the controller has entered the "failure state". It doesn't even try to connect to the k8s API server (we've confirmed this by tracing system calls made by the controller). This might be an indication of some problem with the API server connection pool (if there is, in fact, a connection pool).

Hope this helps.

**Comment by olix0r** [comment] 2022-02-23 15:06
ThisI expect that this was caused by https://github.com/kube-rs/kube-rs/issues/829, which has been fixed in Linkerd via https://github.com/linkerd/linkerd2/pull/7913.

**Comment by adleong** [comment] 2022-02-23 23:59
I've verified that this seems to be fixed on main and the fix should be present in the next edge release.

**Comment by olix0r** [comment] 2022-02-24 16:46
Closing this, as it is fixed in today's edge release.

**Closed by olix0r** 2022-02-24 16:46 UTC
Labels: bug
