### ISSUE TITLE
Proxy-injector skipping some pods when scaling nodes

### ISSUE THREAD

**Issue by jonasdkhansen** [linkerd/linkerd2#3290] opened 2019-08-20 07:17 UTC
### What is the issue?
I have a cluster with four nodes, that i scaling down to zero at night, and up again in the morning. There is about 300 pods with linkerd proxy injection annotation, and when the cluster starts in the morning, only about half of them is getting the proxy injected. I can see on the proxy-injector that it skipped some, but not why.

Sometimes it's the same deployment where some pods get the sidecar and some dosen't. If i delete the pods that does not have the sidecar, then they will get injected correct.

I have tried with running a fifth node, which is not getting scaling down at night, and this has only the linkerd deployments running, so the proxy-injector would be ready when the other nodes is coming up, but this is not helping, i'm getting the same results.

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.13.7-gke.8
- Cluster Environment: GKE
- Host OS: Ubuntu
- Linkerd version: 2.4.0

**Comment by grampelberg** [comment] 2019-08-20 15:16
By default, the proxy injector is not required as part of startup (`failurePolicy: Fail`). Unfortunately, in this example, if you turn that on .... you'll end up wedging your cluster as k8s will wait indefinitely for something that doesn't get scheduled.

Maybe something around pod priorities would help? Something like [guaranteed scheduling](https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/)? I suspect that this might be a use case that just doesn't work for auto-injection because of the scheduling issues and you might end up just having to use `inject --manual` everywhere as a guarantee.

**Comment by ihcsim** [comment] 2019-08-20 16:54
> I have tried with running a fifth node, which is not getting scaling down at night, and this has only the linkerd deployments running,

@jonasdkhansen This should work. Are you running the Linkerd control plane in HA mode with at least 3 replicas of the proxy injector? (It's not necessary, but it will be interesting to try.) I am also interested in knowing if the k8s api server logs any errors when this happens? On GKE, you can view the api server logs with:
```
kubectl proxy
curl http://localhost:8001/logs/kube-apiserver.log
```

Two more things to confirm:

1. I assume this isn't a private GKE cluster
1. I notice that you are using Ubuntu host - are you using the Linkerd CNI?

**Comment by wmorgan** [comment] 2019-08-20 16:54
@jonasdkhansen To be clear, this behavior is happening because the proxy injector is coming up after pods are coming up. Not a bug in Linkerd but something that needs to be handled at the K8s level.

**Comment by jonasdkhansen** [comment] 2019-08-22 07:44
@grampelberg I have tried setting podPriority on linkerd without luck. But i could also just run a cron job after the cluster is up and running, and do the manual injection.

@ihcsim I've also tried with HA mode, but this is just getting way worse. No pods except linkerd is getting up and running, and everything is blocked. Even Linkerd pods are not running correctly, they are missing the sidecar execept identity. The error message i see on proxy injector and controller is `admin={bg=identity} linkerd2_proxy::app::identity Failed to certify identity: grpc-status: Unknown, grpc-message: "the request could not be dispatched in a timely fashion"`
The Kubernetes logs is not showing anything useful.
I'm not using the CNI plugin.

@wmorgan I have tried having the proxy injector running at night, so it's ready when the other pods is coming up, but without luck. There is still about 50% of the pods, not getting the sidecar.

**Comment by ihcsim** [comment] 2019-08-31 04:13
@jonasdkhansen We have reasons to believe that what you saw is related to a timeout imposed on the webhook call, by the k8s API server. I have created #3358 to investigate into the proxy injector code, to see if there are any bottlenecks on our end, or if there is anything about the k8s API server that we don't understand when it's under load.

Per the k8s [docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#mutatingwebhook-v1beta1-admissionregistration-k8s-io), it doesn't look like the timeout can be configured to exceed the default 30 seconds. As a workaround, are you able to perform gradual scaling (i.e. instead of from 0 to 300 pods, try 0 to 50, 50 to 100 etc.)?

**Comment by ihcsim** [comment] 2019-09-19 20:47
@jonasdkhansen The latest [edge-19.9.3](https://github.com/linkerd/linkerd2/releases/tag/edge-19.9.3) release has a fix for this issue. I'm closing this issue. Feel free to ping me on slack if you have any questions.

**Closed by ihcsim** 2019-09-19 20:47 UTC
Labels: needs/repro
