### ISSUE TITLE
Grafana and Prometheus latencies skyrocket when dashboard is open

### ISSUE THREAD

**Issue by bourquep** [linkerd/linkerd2#807] opened 2018-04-19 12:22 UTC
This morning, I spent 10-15 minutes looking at Grafana dashboards. While doing that I noticed the CPU load of one node in my cluster was much higher than usual. Turns out it was the node on which both the `conduit/grafana` and `conduit/prometheus` pods were running.

I went to look at the _Conduit Health_ dashboard and noticed latencies in the 10-20 seconds for grafana and prometheus as well as dips in grafana success rate, and RPS stats that seem pretty high:

<img width="1599" alt="image" src="https://user-images.githubusercontent.com/65096/38990867-da2895f4-43a9-11e8-8f18-df1c4550856d.png">

The node's CPU load came back to normal after closing my Grafana browser tab.

**Comment by siggy** [comment] 2018-04-19 16:48
Thanks for the report @bourquep. A couple questions:
- How much cpu/mem does each node have?
- How many namespaces and deployments are you running?
- If you change the refresh rate on Grafana, to something like every 30s or 1m, does that change the CPU usage?
- Would you mind sharing the output of `kubectl describe nodes`, most notably:
```bash
$ kubectl describe nodes | grep -A 2 -e "^\\s*CPU Requests"
  CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ------------  ----------  ---------------  -------------
  810m (27%)    0 (0%)      110Mi (0%)       170Mi (1%)
```

**Comment by bourquep** [comment] 2018-04-19 20:46
I'll get back to you soon with the requested info. For now I'll add this observation:

In the _Conduit Deployment_ dashboard for one of my services, I selected "Past 12 hours, auto-refresh off". In that case, most of the latency charts fail with a red exclamation mark in the dashboard.

Browser console shows:

```
Summary
URL: http://127.0.0.1:50711/api/v1/namespaces/conduit/services/grafana:http/proxy/api/datasources/proxy/1/api/v1/query_range?query=histogram_quantile(0.95%2C%20sum(irate(response_latency_ms_bucket%7Bnamespace%3D%22studyo%22%2C%20deployment%3D%22rest-api%22%2C%20direction%3D%22inbound%22%7D%5B20s%5D))%20by%20(le%2C%20deployment))&start=1524127457&end=1524170657&step=60
Status: 500 Internal Server Error
Source: Network
Address: 127.0.0.1:50711

Request
GET /api/v1/namespaces/conduit/services/grafana:http/proxy/api/datasources/proxy/1/api/v1/query_range HTTP/1.1
Host: 127.0.0.1:50711
DNT: 1
Connection: keep-alive
Accept-Language: en-ca
Accept-Encoding: gzip, deflate
Cookie: grafana_sess=a5f30ccd0869bee3
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
Accept: application/json, text/plain, */*
Referer: http://127.0.0.1:50711/api/v1/namespaces/conduit/services/grafana:http/proxy/d/6svnwykmk/conduit-deployment?var-namespace=studyo&var-deployment=rest-api&orgId=1&from=now-12h&to=now
X-Grafana-Org-Id: 1

Response
HTTP/1.1 500 Internal Server Error
Expires: -1
Pragma: no-cache
Date: Thu, 19 Apr 2018 20:44:27 GMT
Content-Type: text/plain; charset=utf-8
Cache-Control: no-cache
Content-Length: 0
Audit-Id: d33870df-e482-4cef-95ff-2c1cc8908a95

Query String Parameters
query: histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace="studyo", deployment="rest-api", direction="inbound"}[20s])) by (le, deployment))
start: 1524127457
end: 1524170657
step: 60
```

**Comment by bourquep** [comment] 2018-04-27 19:14
Running the query described in #800 directly on Prometheus, to get a chart for the past hour, took 10 seconds. Looks like the queries used by the dashboard are too heavy to be used at a timescale larger than a few minutes, which might explain the CPU spike initially reported in this issue.

<img src="https://dropshare.studyo.co/Screen-Shot-2018-04-27-15-07-41.png">

**Comment by klingerf** [comment] 2018-07-30 18:13
I'm not able to reproduce the latency spikes described in this issue, using:

* minikube v0.28.2
* kubernetes v1.10.0
* linkerd v18.7.2

I pulled up the Linkerd Deployment dashboard for one of my deployments and expanded the time window to 12 hours. Then in a separate window I pulled up the the Linkerd Health dashboard, to look at the latencies for Grafana and Prometheus. p99 latency for both is consistently <500ms:

![image](https://user-images.githubusercontent.com/9226/43414882-e8604a7e-93e8-11e8-8a30-9ee9cb87af6c.png)

I'm going to close this issue, but please reopen or open a separate issue if you're seeing high latencies in your environment.

**Closed by klingerf** 2018-07-30 18:13 UTC
Labels: priority/P1
