### ISSUE TITLE
Support Kafka Protocol and Request/Response protobuf over Kafka

### ISSUE THREAD

**Issue by hanoisteve** [linkerd/linkerd2#4266] opened 2020-03-22 17:29 UTC
# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [ ] Bug report
- [ X] Feature request

**What happened**:
Service mesh is still evolving. I believe that the most reliable way to do inter service communication is over Kakfa delivering protobuf or similar payloads. This can be done Request/Response as well and would overcome may of the challenges in GRPC found on both Istio and Linkerd2.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The simple fact is that Kafka is the best possible inter-service communication mechanism possible.  Supporting this with Linkerd2 would and allowing simple integration Kafka would provide the most robust solution.
**Environment**:
- linkerd/namerd version, config files:
- Platform, version, and config files (Kubernetes, DC/OS, etc):
- Cloud provider or hardware configuration:

**Comment by grampelberg** [comment] 2020-04-16 17:05
Closing this out as a duplicate of #2214.

**Closed by grampelberg** 2020-04-16 17:05 UTC
