### ISSUE TITLE
Thanos Query cannot connect to Prometheus with Linkerd

### ISSUE THREAD

**Issue by irizzant** [linkerd/linkerd2#6804] opened 2021-09-03 12:10 UTC
### What is the issue?

I have deployed Prometheus (https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)  and Thanos in my cluster, without linkerd everything is working fine.

As soon as I enable linkerd for both Prometheus and Thanos the Query pod stops communicating with Prometheus.
`linkerd-proxy` reports connection errors and stops collecting metrics.

### How can it be reproduced?

* install linkerd 
* install [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) with Thanos sidecar and linkerd injection enabled at namespace level
* install [Thanos](https://github.com/bitnami/charts/tree/master/bitnami/thanos/#installing-the-chart). I've used the configuration reported [here](https://github.com/bitnami/charts/tree/master/bitnami/thanos/#integrate-thanos-with-prometheus-and-alertmanager)

### Logs, error output, etc
Thanos Query's linkerd-proxy output:
https://gist.github.com/irizzant/bfe93d82b293915fc4ffa7b5edb77773

Screenshot taken from linkerd-viz to show the path Thanos Query is trying to reach:
![screenshot-localhost_50750-2021 09 03-13_27_58](https://user-images.githubusercontent.com/15982257/132002906-1d5d785c-e337-4aac-97b3-2dc285ae7e81.png)

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
W0903 14:08:03.083583   23673 warnings.go:67] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √

Linkerd extensions checks
=========================

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ prometheus is installed and configured correctly
√ can initialize the client
√ viz extension self-check

Status check results are √

```

### Environment

- Kubernetes Version: k3d v1.21.1+k3s1
- Cluster Environment: (GKE, AKS, kops, ...) k3d
- Host OS: 
- Linkerd version: 
```
Client version: stable-2.10.2
Server version: stable-2.10.2
```

**Comment by olix0r** [comment] 2021-09-03 18:10
Based on your logs, it appears that it's trying to communicate with services that have no endpoints:

```
[     4.568871s]  INFO ThreadId(01) server{orig_dst=10.43.179.37:10901}: linkerd_proxy_api_resolve::resolve: No endpoints
[     4.568890s]  INFO ThreadId(01) server{orig_dst=10.43.112.5:10901}: linkerd_proxy_api_resolve::resolve: No endpoints
```

I assume 10.43.179.37 and 10.43.112.5 are the ClusterIP addresses of Kubernetes services? Can you share any details about these services?

**Comment by irizzant** [comment] 2021-09-04 09:31
I have the following statefulsets:
```
alertmanager-prometheus-kube-prometheus-alertmanager   1/1     3d4h
prometheus-grafana                                     1/1     3d4h
prometheus-prometheus-kube-prometheus-prometheus       1/1     3d4h
thanos-ruler                                           1/1     20h
thanos-storegateway                                    1/1     20h
```

and those are Service IP's:
```
thanos-storegateway                           ClusterIP   10.43.179.37    <none>        9090/TCP,10901/TCP           4d18h
thanos-ruler                                  ClusterIP   10.43.112.5     <none>        9090/TCP,10901/TCP           4d17h
```

**Comment by irizzant** [comment] 2021-09-18 22:17
@adleong @olix0r 
I also added a simple reproducer. Please check this repo:
https://github.com/irizzant/linkerd-issue-6804/tree/main

**Comment by olix0r** [comment] 2021-09-21 16:16
@irizzant thanks so much! this should make it much easier to track it down. we'll take a look

**Comment by Pothulapati** [comment] 2021-12-24 12:51
Hey @irizzant 

Sorry for the late getback, but I'm trying to replicate the environment. I'm able to see errors on the `thanos-query` proxy trying to communicate with the storegateway but getting no endpoints. In my case, This is right, as the pod is not getting ready due to a initialisation error in the storegateway as per

```
level=warn ts=2021-12-24T12:49:32.622188136Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="bucket store initial sync: sync block: BaseFetcher: iter bucket: The Access Key Id you provided does not exist in our records."
level=info ts=2021-12-24T12:49:32.622201491Z caller=grpc.go:138 service=gRPC/server component=store msg="internal server is shutting down" err="bucket store initial sync: sync block: BaseFetcher: iter bucket: The Access Key Id you provided does not exist in our records."
level=info ts=2021-12-24T12:49:32.622220497Z caller=grpc.go:151 service=gRPC/server component=store msg="gracefully stopping internal server"
level=info ts=2021-12-24T12:49:32.622263743Z caller=grpc.go:164 service=gRPC/server component=store msg="internal server is shutdown gracefully" err="bucket store initial sync: sync block: BaseFetcher: iter bucket: The Access Key Id you provided does not exist in our records."
level=error ts=2021-12-24T12:49:32.622368891Z caller=main.go:158 err="The Access Key Id you provided does not exist in our records.\nBaseFetcher: iter bucket\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetchMetadata\n\t/app/pkg/block/fetcher.go:379\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch.func2\n\t/app/pkg/block/fetcher.go:443\ngithub.com/golang/groupcache/singleflight.(*Group).Do\n\t/go/pkg/mod/github.com/golang/groupcache@v0.0.0-20210331224755-41bb18bfe9da/singleflight/singleflight.go:56\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch\n\t/app/pkg/block/fetcher.go:441\ngithub.com/thanos-io/thanos/pkg/block.(*MetaFetcher).Fetch\n\t/app/pkg/block/fetcher.go:509\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).SyncBlocks\n\t/app/pkg/store/bucket.go:456\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/app/pkg/store/bucket.go:525\nmain.runStore.func4\n\t/app/cmd/thanos/store.go:369\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nsync block\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/app/pkg/store/bucket.go:526\nmain.runStore.func4\n\t/app/cmd/thanos/store.go:369\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nbucket store initial sync\nmain.runStore.func4\n\t/app/cmd/thanos/store.go:371\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nstore command failed\nmain.main\n\t/app/cmd/thanos/main.go:158\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"
```

In your case, I see that all the pods are running correctly. I'm trying to see what the issue is here. Once I can get everything running, I'll be able to debug whats wrong on the linkerd side here.

**Comment by irizzant** [comment] 2021-12-29 17:07
Hey @Pothulapati 
you're right, the error is because I foresaw Thanos chart version in the [reproducer repo](https://github.com/irizzant/linkerd-issue-6804).

I updated the reproducer repo with the fix, now storegateway should start fine.

**Comment by Pothulapati** [comment] 2022-01-03 11:05
Hey @irizzant,

Thanks for the repro. I was able to run the components.

I did see some initial errors around the `thanos-query` rying to connect and failing with no endpoints but once all the components went ready, they vanished and things seem to work correctly, and I see no warning logs.

I'm also able to see Thanos being able to talk to Prometheus!

![image](https://user-images.githubusercontent.com/7892868/147923612-9340500b-2f07-416c-b59c-fbb02d9030cc.png)

This is on the latest edge, trying on stable now!

**Comment by Pothulapati** [comment] 2022-01-03 11:56
@irizzant I was able to verify the same on the latest stable i.e `2.11.1`. I'm sure there are a lot of changes that changed from `2.10.2` that could've fixed it. Any specific reason why you are using `2.10.2`?

I'm happy to try it too!

**Comment by dabo-ZON** [comment] 2022-01-03 15:29
Hi @irizzant,

I had the same problem and I fixed it with adding the annotation `"config.linkerd.io/opaque-ports" = "10901"` to the prometheus pods in order to disable Linkerd's protocol detection for gRPC.

**Comment by irizzant** [comment] 2022-01-03 16:45
Hi @dabo-ZON , please check this [comment](https://github.com/linkerd/linkerd2/issues/6804#issuecomment-1004042433) above, what version are you using?

**Comment by irizzant** [comment] 2022-01-03 16:47
Hi @Pothulapati 
version `2.11.1` seems to work, I don't have any particular reason to keep `2.10.2`, I'm going to upgrade it.

Thanks

**Comment by Pothulapati** [comment] 2022-01-04 05:41
@dabo-ZON For `grpc`, you would never want to set the port as opaque as the proxy should understand grpc and also provide additional metrics which is the case on the latest stable and edge.

I'm testing it out on `2.10.2`, and trying to see whats wrong. The logs are as follows on `debug` level on `thanos-query` which is trying to talk to the prometheus instance

```
[    74.867544s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2: rustls::client::hs: No cached session for DNSNameRef("prometheus-kube-prometheus-prometheus.monitoring.serviceaccount.identity.linkerd.cluster.local")    
[    74.867557s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2: rustls::client::hs: Not resuming any session    
[    74.867794s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:35764}:server{orig_dst=10.96.193.164:10901}:http{v=h2}:Connection{peer=Server}: h2::codec::framed_write: send frame=Headers { stream_id: StreamId(29), flags: (0x4: END_HEADERS) }
[    74.867819s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:35764}:server{orig_dst=10.96.193.164:10901}:http{v=h2}:Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(29) }
[    74.867830s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:35764}:server{orig_dst=10.96.193.164:10901}:http{v=h2}:Connection{peer=Server}: h2::codec::framed_write: send frame=Headers { stream_id: StreamId(29), flags: (0x5: END_HEADERS | END_STREAM) }
[    74.867892s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:53594}:server{orig_dst=10.96.40.205:10901}:http{v=h2}:Connection{peer=Server}: h2::codec::framed_write: send frame=Headers { stream_id: StreamId(31), flags: (0x4: END_HEADERS) }
[    74.867910s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:53594}:server{orig_dst=10.96.40.205:10901}:http{v=h2}:Connection{peer=Server}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(31) }
[    74.867918s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:53594}:server{orig_dst=10.96.40.205:10901}:http{v=h2}:Connection{peer=Server}: h2::codec::framed_write: send frame=Headers { stream_id: StreamId(31), flags: (0x5: END_HEADERS | END_STREAM) }
[    74.868087s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2: rustls::client::hs: Using ciphersuite TLS13_CHACHA20_POLY1305_SHA256    
[    74.868205s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2: rustls::client::tls13: Not resuming    
[    74.868247s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2: rustls::client::tls13: TLS1.3 encrypted extensions: [ServerNameAck]    
[    74.868260s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2: rustls::client::hs: ALPN protocol is None    
[    74.868278s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2: rustls::client::tls13: Got CertificateRequest CertificateRequestPayloadTLS13 { context: PayloadU8([]), extensions: [SignatureAlgorithms([ECDSA_NISTP384_SHA384, ECDSA_NISTP256_SHA256, ED25519, RSA_PSS_SHA512, RSA_PSS_SHA384, RSA_PSS_SHA256, RSA_PKCS1_SHA512, RSA_PKCS1_SHA384, RSA_PKCS1_SHA256]), AuthorityNames([PayloadU16([48, 28, 49, 26, 48, 24, 6, 3, 85, 4, 3, 19, 17, 105, 100, 101, 110, 116, 105, 116, 121, 46, 108, 105, 110, 107, 101, 114, 100, 46])])] }    
[    74.868292s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2: rustls::client::tls13: Attempting client auth    
[    74.868706s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2: linkerd_proxy_transport::metrics: client connection open
[    74.868726s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2: h2::client: binding client connection
[    74.868759s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2: h2::client: client connection bound
[    74.869202s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2: h2::codec::framed_write: send frame=Settings { flags: (0x0), enable_push: 0, initial_window_size: 65535, max_frame_size: 16384 }
[    74.869249s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:35764}:server{orig_dst=10.96.193.164:10901}:http{v=h2}:Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 35 }
[    74.869262s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:35764}:server{orig_dst=10.96.193.164:10901}:http{v=h2}:Connection{peer=Server}: h2::codec::framed_read: received frame=Ping { ack: false, payload: [2, 4, 16, 16, 9, 14, 7, 7] }
[    74.869269s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:35764}:server{orig_dst=10.96.193.164:10901}:http{v=h2}:Connection{peer=Server}: h2::codec::framed_write: send frame=Ping { ack: true, payload: [2, 4, 16, 16, 9, 14, 7, 7] }
[    74.869310s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=WindowUpdate { stream_id: StreamId(0), size_increment: 983041 }
[    74.869356s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}: tower::buffer::worker: service.ready=true processing request
[    74.869372s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2: linkerd_proxy_http::client: method=POST uri=http://10.244.0.25:10901/thanos.info.Info/Info version=HTTP/2.0
[    74.869378s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2: linkerd_proxy_http::client: headers={"content-type": "application/grpc", "user-agent": "grpc-go/1.40.0", "te": "trailers", "grpc-timeout": "4998916u"}
[    74.869420s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
[    74.869441s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(1), flags: (0x1: END_STREAM) }
[    74.869497s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:53594}:server{orig_dst=10.96.40.205:10901}:http{v=h2}:Connection{peer=Server}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 78 }
[    74.869510s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:53594}:server{orig_dst=10.96.40.205:10901}:http{v=h2}:Connection{peer=Server}: h2::codec::framed_read: received frame=Ping { ack: false, payload: [2, 4, 16, 16, 9, 14, 7, 7] }
[    74.869516s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:53594}:server{orig_dst=10.96.40.205:10901}:http{v=h2}:Connection{peer=Server}: h2::codec::framed_write: send frame=Ping { ack: true, payload: [2, 4, 16, 16, 9, 14, 7, 7] }
[    74.869564s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2:Connection{peer=Client}: h2::codec::framed_read: received frame=Settings { flags: (0x0), initial_window_size: 65535, max_frame_size: 16384 }
[    74.869582s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=Settings { flags: (0x1: ACK) }
[    74.869591s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2:Connection{peer=Client}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 983041 }
[    74.869598s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2:Connection{peer=Client}: h2::codec::framed_read: received frame=Settings { flags: (0x1: ACK) }
[    74.869603s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2:Connection{peer=Client}: h2::proto::settings: received settings ACK; applying Settings { flags: (0x0), enable_push: 0, initial_window_size: 65535, max_frame_size: 16384 }
[    74.869712s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2:Connection{peer=Client}: h2::codec::framed_read: received frame=GoAway { error_code: NO_ERROR, last_stream_id: StreamId(2147483647) }
[    74.869725s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2:Connection{peer=Client}: h2::codec::framed_read: received frame=Ping { ack: false, payload: [11, 123, 162, 240, 139, 155, 254, 84] }
[    74.869732s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=Ping { ack: true, payload: [11, 123, 162, 240, 139, 155, 254, 84] }
[    74.869748s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2:Connection{peer=Client}: h2::codec::framed_read: received frame=Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }
[    74.869779s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=GoAway { error_code: NO_ERROR, last_stream_id: StreamId(0) }
[    74.869787s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2:Connection{peer=Client}: h2::proto::connection: Connection::poll; connection error error=NO_ERROR
[    74.869804s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}:h2:Connection{peer=Client}: rustls::session: Sending warning alert CloseNotify    
[    74.869912s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:Connection{peer=Server}: h2::codec::framed_write: send frame=Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }
[    74.870176s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:Connection{peer=Server}: h2::codec::framed_read: received frame=Headers { stream_id: StreamId(3), flags: (0x4: END_HEADERS) }
[    74.870205s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:Connection{peer=Server}: h2::codec::framed_read: received frame=Data { stream_id: StreamId(3), flags: (0x1: END_STREAM) }
[    74.870256s]  WARN ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}: linkerd_reconnect::service: Service failed error=channel closed
[    74.870273s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}:endpoint{server.addr=10.244.0.25:10901}: linkerd_reconnect::service: Recovering
[    74.870291s] DEBUG ThreadId(01) outbound:accept{client.addr=10.244.0.38:50648}:server{orig_dst=10.244.0.25:10901}:http{v=h2}: linkerd_timeout::failfast: HTTP Server service has become unavailable
```

On the prometheus side, I see the following logs

```
[   539.548435s]  WARN ThreadId(01) server{port=10901}: linkerd_app_core::errors: Failed to proxy request: HTTP Logical service in fail-fast client.addr=10.244.0.38:49176
[   539.657537s]  WARN ThreadId(01) server{port=10901}: linkerd_app_core::errors: Failed to proxy request: HTTP Logical service in fail-fast client.addr=10.244.0.38:49182
[   542.730567s]  WARN ThreadId(01) server{port=10901}: linkerd_app_core::errors: Failed to proxy request: HTTP Logical service in fail-fast client.addr=10.244.0.39:48012
[   542.846966s]  WARN ThreadId(01) server{port=10901}: linkerd_app_core::errors: Failed to proxy request: HTTP Logical service in fail-fast client.addr=10.244.0.39:48030
[   544.553681s]  WARN ThreadId(01) server{port=10901}: linkerd_app_core::errors: Failed to proxy request: HTTP Logical service in fail-fast client.addr=10.244.0.38:49466
[   544.668607s]  WARN ThreadId(01) server{port=10901}: linkerd_app_core::errors: Failed to proxy request: HTTP Logical service in fail-fast client.addr=10.244.0.38:49472
[   547.733929s]  WARN ThreadId(01) server{port=10901}: linkerd_app_core::errors: Failed to proxy request: HTTP Logical service in fail-fast client.addr=10.244.0.39:48296
[   547.845790s]  WARN ThreadId(01) server{port=10901}: linkerd_app_core::errors: Failed to proxy request: HTTP Logical service in fail-fast client.addr=10.244.0.39:48300
[   549.553585s]  WARN ThreadId(01) server{port=10901}: linkerd_app_core::errors: Failed to proxy request: HTTP Logical service in fail-fast client.addr=10.244.0.38:49674
[   549.660771s]  WARN ThreadId(01) server{port=10901}: linkerd_app_core::errors: Failed to proxy request: HTTP Logical service in fail-fast client.addr=10.244.0.38:49680
```

**Comment by dabo-ZON** [comment] 2022-01-04 07:27
You're right! The newer version is working without the annotation. It seems that in my case one cluster had an older version of Linkerd proxy running with prometheus. I just upgraded them. Thank you both.

**Comment by adleong** [comment] 2022-01-04 17:11
Since this seems to be fixed on the latest version, I'm going to close this out.

**Closed by adleong** 2022-01-04 17:11 UTC
