### ISSUE TITLE
"linkerd inject --manual" changes types of label values (string becomes float64)

### ISSUE THREAD

**Issue by KIVagant** [linkerd/linkerd2#3983] opened 2020-01-28 14:12 UTC
### What is the issue?

After `linkerd inject --manual` is applied, all Deployment labels lose double quotes around label values which causes problems with unobvious types.

### How can it be reproduced?

1. Create the deployment:

```yaml
# tmp-2.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "1493e89"
    commit: "1493e89"
  name: "1493e89"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "1493e89"
  template:
    metadata:
      labels:
        app: "1493e89"
        commit: "1493e89"
      name: "1493e89"
    spec:
      containers:
        - image: nginx
          name: "1493e89"
```

2. Apply it using `kubectl apply -f tmp-2.yaml` and make sure it works. New pods will start, for example:

```
NAME                                       READY   STATUS    RESTARTS   AGE
1493e89-7946985fdc-7zx2w                   1/1     Running   0          2m31s
```

3. Inject Linkerd Proxy `linkerd inject --manual tmp-2.yaml`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: 1493e89
    commit: 1493e89
  name: 1493e89
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 1493e89
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/created-by: linkerd/cli edge-19.9.3 # actually, there's edge-20.1.2 on server side which behaves the same
        linkerd.io/identity-mode: default
        linkerd.io/proxy-version: edge-20.1.2
      creationTimestamp: null
      labels:
        app: 1493e89
        commit: 1493e89
        linkerd.io/control-plane-ns: linkerd
        linkerd.io/proxy-deployment: 1493e89
      name: 1493e89
    spec:
      containers:
      - image: nginx
        name: 1493e89
        resources: {}
...
```

As you can see here, all labels (and not only labels) lost double quotes around values. Now try to apply it:

```
linkerd inject --manual tmp-2.yaml | kubectl apply -f -
```

### Logs, error output, etc

```
deployment "1493e89" injected

error: error when retrieving current configuration of:
...
Object: &{map["apiVersion":"apps/v1" "kind":"Deployment" ...
:map["app":%!q(float64=+1.493e+92) "commit":%!q(float64=+1.493e+92)] "name":%!q(float64=+1.493e+92)
...
from server for: "STDIN": resource name may not be empty

// or even more unclear error:

for: "./tmp-2.yaml": unrecognized type: string

```

### Environment

- Kubernetes Version: v1.14.9-eks-c0eccc
- Cluster Environment: EKS
- Host OS: Amazon Linux
- Linkerd version: **edge-20.1.2**

### Possible solution

Add quotes in yaml templates everywhere by default when possible.

### Workaround:

Update the commit id in any way, if it is a commit id causing the problem.

**Comment by ihcsim** [comment] 2020-01-28 18:03
This might also be problematic for labels that has `"true"` / `"false"` values, which when stripped turns into boolean, causing deployment to fail completely (labels only takes string values.)

**Comment by adrijshikhar** [comment] 2020-01-29 16:13
@grampelberg , i would like to work on this.
i have already setup the repo

**Comment by grampelberg** [comment] 2020-01-29 16:17
@adrijshikhar awesome! Go for it!

**Comment by adrijshikhar** [comment] 2020-01-29 16:30
What does inject do basically?

**Comment by grampelberg** [comment] 2020-01-29 16:46
@adrijshikhar I would recommend going through the getting started tutorials and spending some time in the docs to answer that question =)

**Comment by Vineet-Sharma29** [comment] 2020-02-13 20:47
@adrijshikhar Are you still working on this issue? If not, I would like to work on it.

**Comment by adrijshikhar** [comment] 2020-02-15 18:38
no i am not

**Comment by saurav-malani** [comment] 2020-02-24 21:39
@grampelberg is this assigned to anyone? If not, then please assign this to me, I would like to give this issue a try.

**Comment by grampelberg** [comment] 2020-02-24 21:46
@Vineet-Sharma29 are you still working on this?

**Comment by Vineet-Sharma29** [comment] 2020-02-25 05:25
@grampelberg No

**Comment by saurav-malani** [comment] 2020-03-06 15:12
@grampelberg  @ihcsim According to me there is somethings is wrong with the "transform" function in cli/cmd/inject.go, specifically here: https://github.com/linkerd/linkerd2/blob/master/cli/cmd/inject.go#L193-L208. i.e. when interconversion occurs from yaml to json and then back to yaml.
ie. maybe when yamltojson conversion is done then every string is under double quote (" "), so conversion method fails to keep track of it. So, doule quotes disappears when when jsonToYaml conversion is done. And, hence the values in final injected yaml files do not have double quotes.

**Comment by Pothulapati** [comment] 2020-03-06 18:36
As @saurav-malani mentioned, It's not straight forward from what we discussed. 
but I do think its an important use-case, I can take this up and see what I can do there. 

@ihcsim Do you have some ideas on how to fix this?

**Comment by ihcsim** [comment] 2020-03-09 20:32
@Pothulapati @saurav-malani Can you help me to extract out that block of code into an unexported function and add some unit test to help identify which library is acting weird? Maybe something like:

```go
func applyPatch(original, patchJSON []byte) ([]byte, error) {
	patch, err := jsonpatch.DecodePatch(patchJSON)
	if err != nil {
		return nil, err
	}

	origJSON, err := yaml.YAMLToJSON(original)
	if err != nil {
		return nil, err
	}

	injectedJSON, err := patch.Apply(original)
	if err != nil {
		return nil, err
	}

	return conf.JSONToYAML(injectedJSON)
}

```
There is a good example on how to set up your unit test with simple inputs in the `json-patch` library [README](https://github.com/evanphx/json-patch#create-and-apply-a-json-patch). Thanks!

**Comment by saurav-malani** [comment] 2020-03-09 21:33
@ihcsim I commented out [this](https://github.com/linkerd/linkerd2/blob/master/cli/cmd/inject.go#L205-L208) portion and returned injectedJSON instead of injectedYAML. And, the output corresponding to is exactly same as expected i.e. integer not under double quote and rest under double quote. So, I believe there is nothing wrong till L208 and probably something goes wrong afterwards, specifically here: `injectedYAML, err := conf.JSONToYAML(injectedJSON)`

**Comment by ihcsim** [comment] 2020-03-11 16:41
Are you able to trace down what's going on in `conf.JSONToYAML(injectedJSON)`? Adding some unit tests might help to flush out the bugs.

**Comment by adnxn** [comment] 2020-04-06 20:07
@ihcsim: cant seem to repro this using example above with build from latest commit on master. i wonder if it was fixed with a dependency upgrade or something. haven't actually sifted through the PRs.

```
$ linkerd version
Client version: stable-2.7.0
Server version: stable-2.7.0

$ linkerd inject --manual tmp.yml | k apply -f -

deployment "1493e89" injected

error: unable to decode "STDIN": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but found 1, error found in #10 byte of ...|":{"app":1.493e+92,"|..., bigger context ...|,"kind":"Deployment","metadata":{"labels":{"app":1.493e+92,"commit":1.493e+92},"name":1.493e+92},"sp|...

$ linkerd inject --manual tmp.yml | grep commit

deployment "1493e89" injected

    commit: 1493e89
        commit: 1493e89
```

```
$ ./target/cli/darwin/linkerd version
Client version: git-d6460cf0
Server version: stable-2.7.0

$ ./target/cli/darwin/linkerd inject --manual tmp.yml | k apply -f -

deployment "1493e89" injected

deployment.apps/1493e89 configured

$ ./target/cli/darwin/linkerd inject --manual tmp.yml | grep commit

deployment "1493e89" injected

    commit: "1493e89"
        commit: "1493e89"

```

**Comment by KIVagant** [comment] 2020-06-01 21:12
Can confirm the issue in `stable-2.7.1`

**Comment by Ashish-Bansal** [comment] 2020-06-05 17:45
@adnxn You are right. I confirm that issue has been fixed due to dependency upgrade in https://github.com/linkerd/linkerd2/pull/4221

Upstream PR - https://github.com/go-yaml/yaml/pull/171

@KIVagant Latest stable release doesn't include that patch.

**Comment by kflynn** [comment] 2023-10-05 15:57
Three years on (🤦‍♂) I've confirmed that our current Linkerd doesn't do this any more. Many thanks to everyone who helped out here!!

**Closed by kflynn** 2023-10-05 15:57 UTC
Labels: help wanted, good first issue, area/cli, bug
