### ISSUE TITLE
Surface authz errors in tap

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3518] opened 2019-10-02 21:49 UTC
## What problem are you trying to solve?

When there are errors between the tap controller and destination proxy, running `linkerd tap` produces no output.

### How should the problem be solved?

Inform the user that there are authz errors and that there is something broken in their cluster.

**Comment by zaharidichev** [comment] 2019-10-03 13:06
So @grampelberg I started working on that one. my idea is to wrap the TapEvent into an ADT. Something like TapData(TapEvent|TapError). This way any error stemming from the tap events acquisition logic can be propagated into the tap events stream without tearing down the stream and we can render one error for one pod, while successfully tapping the rest. 

Problem is however that quite a lot of code relies on the assumption that the tap api server returns a stream of tap events rather than events + errors. Tap, top, profiles all of that. So I wonder what do you think about this approach. Do not feel  like I have enough context to say it for sure, but it looks reasonable to me even with the amount of changes required. WDYT?

**Comment by grampelberg** [comment] 2019-10-03 17:44
@adleong and @siggy probably have a better idea on the API side of things.

**Comment by olix0r** [comment] 2019-10-03 17:49
So, I am pretty sure that this is going to require proxy changes (that I am currently [blocking](https://github.com/linkerd/linkerd2-proxy/pull/368) to return an Unauthorized grpc-status (rather than closing the whole connection).

I think I am -1 on exposing any of this in the Tap API. It's not clear to me, though, where or how this error should be surfaced.

**Comment by olix0r** [comment] 2019-10-03 17:54
@olix0r Nope, I'm totally wrong. It looks like the tap server properly returns unauthenticated grpc-status messages. No proxy changes should be necessary.

**Comment by zaharidichev** [comment] 2019-10-03 18:01
@olix0r It does indeed https://github.com/linkerd/linkerd2-proxy/blob/master/src/app/tap.rs#L84. I can even see it in the logging. 
I am a bit hesitant of exposing this on the tap api as well. But indeed if you tap on two separate pods , one of them might succeed and emit a stream of tap events while the other one can just fail due to some error (authorization for example), but there is nothing that one can do to propagate that to the caller of tap because the stream is containing just tap events or... nothing.

So it looks to me like there is not a good way to do it without touching a bunch of code and protobuf schemas. Might be missing something...

**Comment by olix0r** [comment] 2019-10-03 18:07
@zaharidichev you're right. there are two Tap APIs, and I initially misunderstood this to be in the context of the [proxy's API](https://github.com/linkerd/linkerd2-proxy-api).

However, I'm still not sure what the desired behavior is with regard to reporting/retrying/etc.  This seems like something that should definitely be emitted as errors in the tap controller's logs, and incremented as counters in the tap controller so that UI's can report those errors...

But it's not clear to me that these errors should be surfaced as tap events, in the tap event API...

**Comment by zaharidichev** [comment] 2019-10-03 18:09
Yeah, I aggree certainly. I guess the immediate problem is that one can ultimatelly run a tap through the CLI on a pod that has auth problems and pretty much see nothing as no events are coming at all. Dont really see much of a way to change that without changing whats coming through the tap api. Will think about it.

**Comment by olix0r** [comment] 2019-10-03 18:15
@zaharidichev I'm not sure I'm against the API change, for what it's worth... but it's probably helpful  to get clearer about the expected behavior when, for instance, you run `linkerd tap deploy/foo` on a deploy in which only some pods through unauthorized errors.  Or when they all emit unauthorized errors? What if other errors are encountered (like connection refused)?

Note, for instance, that if you tap a non-existent deploy or one that is not injected, I believe _nothing_ is emitted. This all seems somewhat inconsistent... Authz errors are just one case of a larger class of problem that could use some UX thought...

**Comment by grampelberg** [comment] 2019-10-03 20:03
What about a summary when you first run `tap`?

```bash
$ linkerd tap deploy/foobar
total pods: 4 active: 4 error: 0
```

**Comment by olix0r** [comment] 2019-10-03 21:44
@grampelberg that feels a bit odd to me... how would that work with -o json? What happens if the deploy changes while it runs? (Consider that tap can work on namespaces, etc, and can run indefinitely long).

**Comment by grampelberg** [comment] 2019-10-03 21:47
What happens to the tap when the deploy changes?

**Closed** 2020-03-08 17:42 UTC
Labels: priority/P0, wontfix
