### ISSUE TITLE
Tap / Top not working on EKS 1.18

### ISSUE THREAD

**Issue by kenichi-shibata** [linkerd/linkerd2#5860] opened 2021-03-03 12:15 UTC
### What is the issue?

Tap and Top not working in either Dashboard or CLI 

### How can it be reproduced?

Create an EKS Cluter using eksctl

```
git clone https://github.com/k8s-gitops/fleet-baseline
eksctl create cluster -f ./fleet-baseline/.eksctl/init-cluster.yaml
```

Follow the linkerd2 getting started guide

```
linkerd install | kubectl apply -f -

curl -sL https://run.linkerd.io/emojivoto.yml \
  | kubectl apply -f -

kubectl get -n emojivoto deploy -o yaml \
  | linkerd inject - \
  | kubectl apply -f -

```

Check tap and top doesnt work

```
linkerd -n emojivoto top deploy

linkerd -n emojivoto tap deploy/web
```

### Logs, error output, etc

Empty responses on `top` or `tap` requests 

linkerd-tap
```
[linkerd-tap-6d9575f5c-ckqd5 tap] time="2021-03-03T11:50:32Z" level=info msg="Tapping 1 pods for target: namespace:\"emojivoto\" type:\"deployment\" name:\"web\""
[linkerd-tap-6d9575f5c-ckqd5 linkerd-proxy] [  3836.031821s]  WARN ThreadId(01) outbound:accept{peer.addr=11.1.0.19:35360 target.addr=11.1.29.199:4190}: linkerd2_app_core::errors: Failed to proxy request: request required the identity 'web.emojivoto.serviceaccount.identity.linkerd.cluster.local' but no identity found
[linkerd-tap-6d9575f5c-ckqd5 tap] time="2021-03-03T11:50:32Z" level=info msg="Establishing tap on 11.1.29.199:4190"
[linkerd-tap-6d9575f5c-ckqd5 tap] time="2021-03-03T11:50:32Z" level=error msg="[11.1.29.199] encountered an error: rpc error: code = FailedPrecondition desc = request required the identity 'web.emojivoto.serviceaccount.identity.linkerd.cluster.local' but no identity found"
[linkerd-tap-6d9575f5c-ckqd5 tap] time="2021-03-03T11:50:53Z" level=info msg="Tapping 4 pods for target: namespace:\"emojivoto\" type:\"deployment\""
[linkerd-tap-6d9575f5c-ckqd5 tap] time="2021-03-03T11:50:53Z" level=info msg="Establishing tap on 11.1.29.199:4190"
[linkerd-tap-6d9575f5c-ckqd5 tap] time="2021-03-03T11:50:53Z" level=info msg="Establishing tap on 11.1.85.220:4190"
[linkerd-tap-6d9575f5c-ckqd5 tap] time="2021-03-03T11:50:53Z" level=info msg="Establishing tap on 11.1.81.57:4190"
[linkerd-tap-6d9575f5c-ckqd5 linkerd-proxy] [  3856.734201s]  WARN ThreadId(01) outbound:accept{peer.addr=11.1.0.19:35640 target.addr=11.1.29.199:4190}: linkerd2_app_core::errors: Failed to proxy request: request required the identity 'web.emojivoto.serviceaccount.identity.linkerd.cluster.local' but no identity found
[linkerd-tap-6d9575f5c-ckqd5 tap] time="2021-03-03T11:50:53Z" level=info msg="Establishing tap on 11.1.25.171:4190"
[linkerd-tap-6d9575f5c-ckqd5 linkerd-proxy] [  3856.734703s]  WARN ThreadId(01) outbound:accept{peer.addr=11.1.0.19:56762 target.addr=11.1.85.220:4190}: linkerd2_app_core::errors: Failed to proxy request: request required the identity 'default.emojivoto.serviceaccount.identity.linkerd.cluster.local' but no identity found
[linkerd-tap-6d9575f5c-ckqd5 tap] time="2021-03-03T11:50:53Z" level=error msg="[11.1.29.199] encountered an error: rpc error: code = FailedPrecondition desc = request required the identity 'web.emojivoto.serviceaccount.identity.linkerd.cluster.local' but no identity found"
[linkerd-tap-6d9575f5c-ckqd5 linkerd-proxy] [  3856.735735s]  WARN ThreadId(01) outbound:accept{peer.addr=11.1.0.19:48012 target.addr=11.1.81.57:4190}: linkerd2_app_core::errors: Failed to proxy request: request required the identity 'voting.emojivoto.serviceaccount.identity.linkerd.cluster.local' but no identity found
[linkerd-tap-6d9575f5c-ckqd5 linkerd-proxy] [  3856.736088s]  INFO ThreadId(01) outbound:accept{peer.addr=11.1.0.19:56778 target.addr=11.1.85.220:4190}: linkerd2_app_core::serve: Connection closed error=connection error: Broken pipe (os error 32)
[linkerd-tap-6d9575f5c-ckqd5 tap] time="2021-03-03T11:50:53Z" level=error msg="[11.1.85.220] encountered an error: rpc error: code = FailedPrecondition desc = request required the identity 'default.emojivoto.serviceaccount.identity.linkerd.cluster.local' but no identity found"
[linkerd-tap-6d9575f5c-ckqd5 tap] time="2021-03-03T11:50:53Z" level=error msg="[11.1.81.57] encountered an error: rpc error: code = FailedPrecondition desc = request required the identity 'voting.emojivoto.serviceaccount.identity.linkerd.cluster.local' but no identity found"
[linkerd-tap-6d9575f5c-ckqd5 tap] time="2021-03-03T11:50:53Z" level=error msg="[11.1.25.171] encountered an error: rpc error: code = FailedPrecondition desc = request required the identity 'emoji.emojivoto.serviceaccount.identity.linkerd.cluster.local' but no identity found"
```

linkerd-identity
```
time="2021-03-03T10:46:21Z" level=info msg="running version stable-2.9.4"
time="2021-03-03T10:46:21Z" level=info msg="starting admin server on :9990"
time="2021-03-03T10:46:21Z" level=info msg="starting gRPC server on :8080"
time="2021-03-03T10:46:32Z" level=info msg="certifying linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local until 2021-03-04 10:46:52 +0000 UTC"
time="2021-03-03T10:46:39Z" level=info msg="certifying linkerd-controller.linkerd.serviceaccount.identity.linkerd.cluster.local until 2021-03-04 10:46:59 +0000 UTC"
time="2021-03-03T10:46:39Z" level=info msg="certifying linkerd-grafana.linkerd.serviceaccount.identity.linkerd.cluster.local until 2021-03-04 10:46:59 +0000 UTC"
time="2021-03-03T10:46:40Z" level=info msg="certifying linkerd-web.linkerd.serviceaccount.identity.linkerd.cluster.local until 2021-03-04 10:47:00 +0000 UTC"
time="2021-03-03T10:46:40Z" level=info msg="certifying linkerd-proxy-injector.linkerd.serviceaccount.identity.linkerd.cluster.local until 2021-03-04 10:47:00 +0000 UTC"
time="2021-03-03T10:46:40Z" level=info msg="certifying linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local until 2021-03-04 10:47:00 +0000 UTC"
time="2021-03-03T10:46:42Z" level=info msg="certifying linkerd-tap.linkerd.serviceaccount.identity.linkerd.cluster.local until 2021-03-04 10:47:02 +0000 UTC"
time="2021-03-03T10:46:42Z" level=info msg="certifying linkerd-prometheus.linkerd.serviceaccount.identity.linkerd.cluster.local until 2021-03-04 10:47:02 +0000 UTC"
time="2021-03-03T10:46:43Z" level=info msg="certifying linkerd-sp-validator.linkerd.serviceaccount.identity.linkerd.cluster.local until 2021-03-04 10:47:03 +0000 UTC"
time="2021-03-03T10:57:38Z" level=info msg="certifying voting.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2021-03-04 10:57:58 +0000 UTC"
time="2021-03-03T10:57:38Z" level=info msg="certifying emoji.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2021-03-04 10:57:58 +0000 UTC"
time="2021-03-03T10:57:38Z" level=info msg="certifying default.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2021-03-04 10:57:58 +0000 UTC"
time="2021-03-03T10:57:38Z" level=info msg="certifying web.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2021-03-04 10:57:58 +0000 UTC"
```

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
```

### Environment

- Kubernetes Version: :"v1.18.9-eks-d1db3c"
- Cluster Environment: EKS
- Host OS: Default Amazon Linux
- Linkerd version: stable-2.9.4
   - Client version: stable-2.9.4
   - Server version: stable-2.9.4

### Possible solution

Fix mTLS? im new to linkerd. 

I tried to check mTLS using https://linkerd.io/2/tasks/securing-your-service/ but it looks good

```
❯ linkerd -n linkerd edges deployment

SRC                  DST                  SRC_NS    DST_NS    SECURED
linkerd-controller   linkerd-prometheus   linkerd   linkerd   √
linkerd-web          linkerd-controller   linkerd   linkerd   √
```

but this command is still empty response
```
linkerd -n linkerd tap deploy
```

Maybe I missed somethinig very simple? This is my first time trying Linkerd. 🔢  please be nice 😄 

### Additional context

I cant find any other issue other than 

```
request required the identity 'emoji.emojivoto.serviceaccount.identity.linkerd.cluster.local' but no identity found"
```

**Comment by kleimkuhler** [comment] 2021-03-03 17:52
Hey @kenichi-shibata I've been unable to reproduce this on an EKS cluster. My thought is that maybe you don't have the right permissions setup on the cluster.

I'd be curious to see the tap container logs if you can install linkerd on debug log level: `linkerd install --controller-log-level debug |kubectl apply -f -`. The log line I am interested in seeing is [this](https://github.com/linkerd/linkerd2/blob/57d851b4347bfeb57584790f1c340a95190ce68b/viz/tap/api/grpc_server.go#L153).

If linkerd is somehow unable to construct the identity name, it could lead to there not being an identity on the tap request and result in the errors you are seeing.

**Comment by kleimkuhler** [comment] 2021-03-03 21:23
@kenichi-shibata So I have been able to reproduce this with the `init-cluster.yaml` you provided. When I create a fresh EKS myself, it works fine.

Therefore, I think it's probably some configuration you have set in the yaml that is preventing identity from being read properly. I'd look through each configuration—specifically those dealing with IAM—and see if adjusting those fixes it.

I can get back into looking at this at some point, but since it seems to permissions related with the way the cluster is created I don't think this is actually a bug with linkerd itself.

**Comment by kleimkuhler** [comment] 2021-03-03 21:31
You may also want to refer to the GKE specific debugging steps for tap errors [here](https://linkerd.io/2/tasks/securing-your-cluster/#gke).

It may be helpful to make sure your IAM user can actually tap resources.

**Comment by kenichi-shibata** [comment] 2021-03-04 12:03
@kleimkuhler you are right i created a basic cluster to test it does work.

https://github.com/k8s-gitops/fleet-baseline/blob/main/.eksctl/staging-cluster.yaml

Now I'm lost :D I'll try to find the IAM policies being attached by eksctl when adding these 

https://github.com/k8s-gitops/fleet-baseline/blob/main/.eksctl/init-cluster.yaml

```
    iam:
      withAddonPolicies:
        albIngress: true
        appMesh: true
        xRay: true
        cloudWatch: true
```

I had a look at GKE's specific debugging and made sure to create my own IAM user, attached with aws-auth. So i was able rule that out as the issue.

**Comment by kenichi-shibata** [comment] 2021-03-04 14:37
I finally found the issue :) Have to delete and recreate the clusters a few times.

This is the offending line

https://github.com/k8s-gitops/fleet-baseline/blob/main/.eksctl/init-cluster.yaml#L35

linkerd2 doesn't support the custom cidr I guess?

**Comment by kleimkuhler** [comment] 2021-03-08 15:06
@kenichi-shibata Thanks for the update! That's interesting I'm not sure why that would cause an issue. I'm going to close this for now, but if that is something you need to configure and it's still an issue, feel free to open a new issue specifically about setting that in clusters. We can look into it a little more and see what the issue may be.

**Closed by kleimkuhler** 2021-03-08 15:06 UTC
