### ISSUE TITLE
Discrepancy between linkerd logs command and kubectl logs command

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#2674] opened 2019-04-09 17:43 UTC
I noticed that the output of `linkerd logs` appears to be "stuck" and does not include recent log lines that are visible when using `kubectl logs`.  For example, when running `linkerd logs -c public-api`, the final line of output is from `time="2019-04-09T17:27:45Z"`.

```
linkerd linkerd-controller-75b4647f78-6kbmd public-api time="2019-04-09T17:27:45Z" level=debug msg="Serving POST /api/v1/Version" req.Form="map[]" req.Headers="map[User-Agent:[Go-http-client/2.0] Content-Length:[0] Accept-Encoding:[gzip] X-Forwarded-For:[199.116.73.216] X-Forwarded-Uri:[/api/v1/namespaces/linkerd/services/linkerd-controller-api:http/proxy/api/v1/Version]]" req.Method=POST req.URL=/api/v1/Version
```

However, running `kubectl -n linkerd logs linkerd-controller-75b4647f78-6kbmd -c public-api` reveals more recent log lines:

```
time="2019-04-09T17:30:03Z" level=debug msg="Serving POST /api/v1/Version" req.Form="map[]" req.Headers="map[X-Forwarded-For:[199.116.73.216] X-Forwarded-Uri:[/api/v1/namespaces/linkerd/services/linkerd-controller-api:http/proxy/api/v1/Version] User-Agent:[Go-http-client/2.0] Content-Length:[0] Accept-Encoding:[gzip]]" req.Method=POST req.URL=/api/v1/Version
```

**Comment by klingerf** [comment] 2019-04-09 18:08
This relates to #2359. I wonder if we need to explicitly flush stdout when printing log lines. Also, what behavior do you see from kubectl when running the same log command with `-f` specified?

**Comment by adleong** [comment] 2019-04-09 18:11
No output when running `kubectl -n linkerd logs linkerd-controller-75b4647f78-6kbmd -c public-api -f`.

Do you think I should close this as a duplicate of #2359?

**Comment by klingerf** [comment] 2019-04-09 18:31
Yep, I think this is a dupe of #2359. And I'm not sure what the right fix is exactly, since `kubectl logs -f` suffers from the same issue. But we can use #2359 to try to figure that out.

**Closed** 2019-04-09 18:36 UTC
Labels: area/cli
