### ISSUE TITLE
Memory leak in the controller

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1761] opened 2018-10-12 20:22 UTC
### What is the issue?

Over the course of 24 hours, the controller pod went from approx 100mb worth of memory usage to around 1.4gb before it restarted.

### How can it be reproduced?

- Install the control plane with TLS enabled.
- Install emojivoto, inject with TLS enabled.
- Scale vote-bot to 100 pods

### Environment

- Kubernetes Version: 1.10.7
- Cluster Environment: AKS
- Host OS: Ubuntu 16.04
- Linkerd version: stable-2.0.0

**Comment by klingerf** [comment] 2018-10-12 20:27
@grampelberg Thanks for reporting this. Is it possible to identify which container in the controller pod is consuming all of the memory?

**Comment by grampelberg** [comment] 2018-10-12 20:30
I'm in the progress of replicating this again. When I went to figure out *which* container it was, the controller restarted all the pods and I missed out. I'll update with any more info as I get it.

**Comment by hawkw** [comment] 2018-11-28 23:44
per @klingerf, it seems quite possible that this issue is caused by #1361

**Comment by hawkw** [comment] 2018-12-05 19:14
I deployed emojivoto with 100 vote-bots as described in @grampelberg's repro steps given above, and it appears that the growing memory usage in the controller's proxy _is_ caused by a growing number of TCP connections with `{direction="inbound", peer="dst", tls="internal traffic"}` (as in #1361).

So, that confirms that
1. issue #1361 does still exist on `edge-18.11.3` 
2. memory leak is likely caused by #1361 

I'll keep trying to nail down the root cause.

**Comment by grampelberg** [comment] 2018-12-05 19:17
Thank goodness, I'm not insane!

**Comment by hawkw** [comment] 2018-12-05 19:22
In both graphs, the yellow line with the distinct upward trend is the controller proxy:
![screen shot 2018-12-05 at 11 20 23 am](https://user-images.githubusercontent.com/2796466/49538326-0220b380-f880-11e8-9e6f-ec1e1fd5a143.png)
![screen shot 2018-12-05 at 11 20 13 am](https://user-images.githubusercontent.com/2796466/49538327-0220b380-f880-11e8-93a4-ba1324501608.png)

**Comment by hawkw** [comment] 2018-12-05 19:53
Now _this_ is interesting: it looks like that proxy's report of the number of open TCP conns stays pretty stable, but the number of open _fds_ is increasing (and execing into the pod and grepping `/proc/pid/fd` confirms that 820 out of 832 of them are sockets). So, it seems like the proxy may think it's closing the connection but it's actually failing to close the underlying socket.

Proxy's self-reported number of open conns:
![screen shot 2018-12-05 at 11 51 04 am](https://user-images.githubusercontent.com/2796466/49540132-22eb0800-f884-11e8-9fce-e87ad214c90d.png)
Number of open fds (again, the controller proxy is the yellow line):
![screen shot 2018-12-05 at 11 51 14 am](https://user-images.githubusercontent.com/2796466/49540145-2aaaac80-f884-11e8-8615-8cf25d090627.png)
Memory impact:
![screen shot 2018-12-05 at 11 51 23 am](https://user-images.githubusercontent.com/2796466/49540142-28485280-f884-11e8-84c7-373f4734b73f.png)

**Comment by hawkw** [comment] 2018-12-05 23:04
according to a `grep` of `/proc` on the controller pod, a majority of these are _UDP_ sockets. what is going on here? perhaps they're from DNS queries?

**Comment by hawkw** [comment] 2018-12-06 22:08
I strongly suspect that the memory leak described here was caused by #1950, which appears to have been fixed by linkerd/linkerd2-proxy#146. 

The memory consumption appears stable in edge-18.12.1:
![screen shot 2018-12-06 at 1 59 51 pm](https://user-images.githubusercontent.com/2796466/49614848-6f0b7a80-f960-11e8-8ff4-289e3141f18b.png)

**Comment by hawkw** [comment] 2018-12-06 23:41
Controller proxy's memory usage has been holding steady at 48.9 MB for about four hours now. I think it's safe to say this issue is fixed in 2.1.

**Closed by hawkw** 2018-12-06 23:41 UTC
Labels: area/controller, area/proxy, area/tls, bug, priority/P2
