### ISSUE TITLE
Controller must work in clusters with >100 pods

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#1322] opened 2018-07-13 18:21 UTC
Currently, the control plane does not work well in clusters with more than 100 pods due to #1234.

Can we avoid having the outbound prometheus route be handled as HTTP in the proxy to avoid this constraint temporarily?

Are there any other scale constraints in the controller like this?

**Comment by seanmonstar** [comment] 2018-07-17 20:53
Seems there's a couple ways this could be fixed:

- Set `LINKERD2_PROXY_OUTBOUND_ROUTER_CAPACITY=10000` or some other high number on the Prometheus pod's proxy. This allows the proxy to still report metrics about if prometheus scraping is working or not.
- Set `LINKERD2_PROXY_OUTBOUND_PORTS_DISABLE_PROTOCOL_DETECTION=4143` on the Prometheus pod's proxy. This would make all scraping requests just be TCP proxies, which would make it harder to see if/when it's failing.
- There's a comment in the proxy about the default router capacities, stating its expected that a pod would only need ~100 local routes, and ~10,000 outbound routes, but the defaults for both are set to 100. Should the outbound default be set to 10,000?

**Comment by briansmith** [comment] 2018-07-17 21:20
> Set LINKERD2_PROXY_OUTBOUND_PORTS_DISABLE_PROTOCOL_DETECTION=4143 on the Prometheus pod's proxy. This would make all scraping requests just be TCP proxies, which would make it harder to see if/when it's failing.

Note that this would prohibit us from doing the scraping over TLS until undone, so it is a very short-term solution. (It's not done over TLS yet so it wouldn't be a regression.)

**Comment by hawkw** [comment] 2018-07-20 21:48
I can confirm @siggy's finding that (as far as I can tell) there's no way to limit the concurrency of scrapes in Prometheus.

**Comment by olix0r** [comment] 2018-07-20 21:55
it would probably be good to open a prom issue to see if this is by design or if they'd be open to a throttling config of some sort.

in the meantime, we could try simply increasing the router cache size on the prom instace's proxy --- these authorities shouldn't cause discovery lookups.  it's a dirty hack but it should be good enough until we have a proper solution.

**Comment by hawkw** [comment] 2018-07-20 22:37
If increasing the Prometheus pod's proxy is the right way to work around this issue for now, should we just bring back @siggy's branch #1228, which makes that change?

**Comment by hawkw** [comment] 2018-07-23 18:18
I've opened prometheus/prometheus#4408 to request the addition of a configurable limit to Prometheus' scrape concurrency.

**Comment by hawkw** [comment] 2018-07-23 18:30
Opened #1358 as a workaround.

**Comment by briansmith** [comment] 2018-07-23 18:47
> these authorities shouldn't cause discovery lookups

Given this, and given that the problem is really in the destination service (IIUC), it seems like we should remove or increase the the router-level cap and move the cap to the discovery submodule. And/or, we could increase the router-level limit a lot and add a new, smaller, discovery-level limit.

There are kinds of scraper/robot pods like Prometheus, including our own tap server, so it seems like a good idea to find a (simple) solution that works more generally. (This isn't meant to imply that the currently-proposed workaround should be dropped.)

**Comment by hawkw** [comment] 2018-07-23 18:49
> it seems like we should remove or increase the the router-level cap and move the cap to the discovery submodule. And/or, we could increase the router-level limit a lot and add a new, smaller, discovery-level limit.

I think that should be possible, and it sounds like a good potential longer-term solution. I'll look into it.

**Comment by hawkw** [comment] 2018-07-23 22:11
I took a pass at separating the upper bound on Destination service resolutions from the router capacity (in another branch), and it ended up being fairly easy. I still need to do a bit of testing to ensure it behaves at scale, though.

**Comment by hawkw** [comment] 2018-08-02 23:47
Okay, PRs linkerd/linkerd2-proxy#36 and linkerd/linkerd2#1358 have both merged. 

PR linkerd/linkerd2#1358 increases the router capacity of the Prometheus proxy at inject time, while the proxy PR linkerd/linkerd2-proxy#36 adds a limit on concurrent Destination service queries in the proxy, so that it can't overload the Destination service regardless of what its' router capacity is set to.

Together, these branches should constitute a fix to the issue of Prometheus scrapes hitting the router capacity. We should do additional validation to ensure no other issues crop up at scale.

**Comment by hawkw** [comment] 2018-08-07 18:48
Since linkerd/linkerd2-proxy#36 and linkerd/linkerd2#1358 have fixed the specific issue around the router capacity for the Prometheus pod, this issue should be closable. #1406 has been opened to track the other scale issue that's come up while testing this.

**Closed by hawkw** 2018-08-07 18:48 UTC
Labels: area/scale, area/telemetry, priority/P0
