### ISSUE TITLE
conduit_proxy doesn't resolve IPv6 name

### ISSUE THREAD

**Issue by valentin2105** [linkerd/linkerd2#91] opened 2017-12-25 22:33 UTC
Hi,

I try Conduit in my IPv6-only cluster, 

I correctly Got the dashboard, but when deploying my first deployment (with conduit sidecar enabled), It seem that ConduitProxy can't resolve IPv6 Name : 

```
 conduit_proxy::control "controller-client", poll rpc services
 conduit_proxy::control::discovery "controller-client", poll_rpc
 conduit_proxy::dns "controller-client", resolve proxy-api.conduit.svc.k8s.domain.tld
 conduit_proxy::control::telemetry "controller-client", poll_rpc
 conduit_proxy::control::telemetry "controller-client", controller unavailable
 conduit_proxy::telemetry::control "controller-client", poll
 conduit_proxy::telemetry::control "controller-client", recv.poll(Receiver { capacity: AtomicUsize(10000) })
 conduit_proxy::control "controller-client", poll rpc services
 conduit_proxy::control::discovery "controller-client", poll_rpc
WARN conduit_proxy::control "controller-client", controller error: Connect(Connect(Connect(Error { repr: Custom(Custom { kind: NotFound, error: StringError("DNS resolution failed") }) })))
 conduit_proxy::control::telemetry "controller-client", poll_rpc
 conduit_proxy::control::telemetry "controller-client", controller unavailable
 conduit_proxy::telemetry::control "controller-client", poll
 conduit_proxy::telemetry::control "controller-client", recv.poll(Receiver { capacity: AtomicUsize(10000) })
```

But in a Alpine pod : 

```
bash-4.3# dig AAAA proxy-api.conduit.svc.k8s.domain.ltd +short
ff1234:d400:ff:88::e:88:2b38
```

It seem the bug happen in `conduit/proxy/src/dns.rs` but I'm not such good on Rust to find the problem. 

Thanks !!

**Comment by olix0r** [comment] 2017-12-26 16:40
Thanks for this report!  It's important to us that conduit support things like IPv6 out-of-the-box.

Can you share any pointers/references/docs on how you've set up your kubernetes cluster to use IPv6? I'd like to replicate this environment for integration tests.

**Comment by valentin2105** [comment] 2017-12-26 21:04
Hi @olix0r,
I don't have follow any docs about that but I wrote a detailed blog post about that,

https://opsnotice.xyz/kubernetes-ipv6-only/

I will continu to try too in my cluster to report any problem ;)

Thanks !

**Comment by briansmith** [comment] 2018-02-02 07:56
Like @olix0r said, we definitely want to support IPv6-only configurations. I believe there's only one place where we use DNS in Conduit: resolving the hostname of the control plane. Until we find out what the issue is with that, you may be able to work around this by allocating an IPv4 address only to the control plane pods.

#257 was filed as a duplicate of this, which may mean there's more interest in IPv6-only configurations than we expected, so we should consider increasing the priority.

**Comment by valentin2105** [comment] 2018-02-03 02:21
Hi, 

Sorry for opened two issue, I forgot about the first one lol, 

Yeah, conduit seem really a great product and I really looking forward about trying this with my production services in IPv6 cluster and more since you support HTTP1.1 and TCP stuffs.

I can support you on the testing side if you release some test image, I can try them quickly if needed ;)

**Comment by wmorgan** [comment] 2018-02-13 22:45
IPv6 support is currently unprioritized, but contributions are welcome! Specific error reports around breakages due to IPv6 also welcome.

**Comment by valentin2105** [comment] 2018-04-18 00:42
I gived a new try on v0.4.0 release,

I don't get any error on the Conduit deployment, 

But when I deploy my Nginx deployment with conduit-proxy, here is the logs : 

```
INFO conduit_proxy using controller at HostAndPort { host: DnsName(Name(Name("proxy-api.conduit.svc.k8s.my-cluster.tld"))), port: 8086 }
INFO conduit_proxy routing on V4(127.0.0.1:4140)
INFO conduit_proxy proxying on V4(0.0.0.0:4143) to None
INFO conduit_proxy serving Prometheus metrics on V4(0.0.0.0:4191)
INFO conduit_proxy protocol detection disabled for inbound ports {25, 3306}
INFO conduit_proxy protocol detection disabled for outbound ports {25, 3306}
ERR! conduit_proxy::control "controller-client", controller error: Error attempting to establish underlying session layer: DNS resolution failed

```
If it can help ! :smile:

**Comment by olix0r** [comment] 2018-04-18 17:59
@valentin2105 thanks for the updated information! i think we're getting closer to being able to fix this. as we improve some of the discovery logic for 0.5, we can take a look trying to determine what has to change in the proxy to accommodate this.

**Comment by valentin2105** [comment] 2018-04-18 21:13
@olix0r Thanks for investigating this, 
Looking forward seen conduit running at glance on IPv6 ;)

**Comment by briansmith** [comment] 2018-04-19 00:37
This is most likely due to limitations of the abstract_ns/ns_dns_tokio crates. In particular, note things like https://github.com/tailhook/abstract-ns/blob/af4fa2abe1aed67c505364cc78aaf2e7dd5fcb10/ns-dns-tokio/src/lib.rs#L72-L81 where AAAA support just wasn't considered yet.

I think we'll have to switch to another crate--probably Trust-DNS--to fix this.

**Comment by valentin2105** [comment] 2018-04-19 04:44
@briansmith TrustDNS seem really better and support IPv6.
Pretty strange for a DNS library to support only IPv4..

**Comment by grampelberg** [comment] 2019-12-18 23:30
Tracking IPv6 support in #3849.

**Closed by grampelberg** 2019-12-18 23:30 UTC
Labels: help wanted
