### ISSUE TITLE
Prometheus is unreachable after clean install

### ISSUE THREAD

**Issue by mt-inside** [linkerd/linkerd2#7638] opened 2022-01-19 17:11 UTC
### What is the issue?

The prometheus container claims to be happy

```
...
level=info ts=2022-01-19T16:47:17.927Z caller=main.go:695 msg="TSDB started"
level=info ts=2022-01-19T16:47:17.927Z caller=main.go:799 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2022-01-19T16:47:17.928Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2022-01-19T16:47:17.928Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2022-01-19T16:47:17.928Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2022-01-19T16:47:17.929Z caller=kubernetes.go:253 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2022-01-19T16:47:17.929Z caller=main.go:827 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2022-01-19T16:47:17.929Z caller=main.go:646 msg="Server is ready to receive web requests."
```

However its sidecar says it can't talk to it
```
[     0.000689s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
[     0.000968s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191
[     0.000976s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143
[     0.000978s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140
[     0.000979s]  INFO ThreadId(01) linkerd2_proxy: Tap DISABLED
[     0.000980s]  INFO ThreadId(01) linkerd2_proxy: Local identity is prometheus.linkerd-viz.serviceaccount.identity.linkerd.cluster.local
[     0.000982s]  INFO ThreadId(01) linkerd2_proxy: Identity verified via linkerd-identity-headless.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.000983s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via linkerd-dst-headless.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.004658s]  INFO ThreadId(02) daemon:identity: linkerd_app: Certified identity: prometheus.linkerd-viz.serviceaccount.identity.linkerd.cluster.local
[    18.159396s]  INFO ThreadId(01) outbound:server{orig_dst=172.17.0.12:9998}: linkerd_app_outbound::http::proxy_connection_close: Closing application connection for remote proxy error=Connection refused (os error 111)
[    26.002266s]  INFO ThreadId(01) outbound:server{orig_dst=172.17.0.14:9995}: linkerd_app_outbound::http::proxy_connection_close: Closing application connection for remote proxy error=Connection refused (os error 111)
```

This results in multiple symptoms, including failures in:

`kubectl -n linkerd-viz logs deploy/metrics-api metrics-api`
```
...
time="2022-01-19T16:55:42Z" level=error msg="Query(max(process_start_time_seconds{}) by (pod, namespace)) failed with: server_error: server error: 504"
time="2022-01-19T16:55:48Z" level=error msg="Query(max(process_start_time_seconds{}) by (pod, namespace)) failed with: server_error: server error: 504"
```

`linkerd2 check`
```
...
linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ viz extension proxies are healthy
√ viz extension proxies are up-to-date
√ viz extension proxies and cli versions match
√ prometheus is installed and configured correctly
√ can initialize the client
× viz extension self-check
    Error calling Prometheus from the control plane: server_error: server error: 504
    see https://linkerd.io/2.11/checks/#l5d-viz-metrics-api for hints

Status check results are ×
```

### How can it be reproduced?

Clean minikube cluster `minikube start --kubernetes-version=v1.23.1 --cpus=6 --memory=8g --driver=docker --cni=auto --embed-certs=false --feature-gates=EphemeralContainers=true --addons=dashboard --addons=metrics-server`

Followed by clean linkerd 2.11.1 install: `linkerd2-cli-stable-2.11.1-linux-amd64 install`

### Logs, error output, etc

See above

### output of `linkerd check -o short`

much time passes... then

```text
$ linkerd check -o short
Linkerd core checks
===================


Status check results are √

Linkerd extensions checks
=========================


Status check results are √


Status check results are √

linkerd-viz
-----------
× viz extension self-check
    Error calling Prometheus from the control plane: server_error: server error: 504
    see https://linkerd.io/2.11/checks/#l5d-viz-metrics-api for hints

Status check results are ×
```

### Environment

* Kubernetes 1.23.1
* Cluster: `minikube v1.24.0 on Arch 21.2.1`
* Host OS: Linux 5.10.89
* Linkerd version: 2.11.1

### Would you like to work on fixing this bug?

maybe

**Comment by mt-inside** [comment] 2022-01-19 17:43
This happens with linkerd 2.10.2 as well, which points at the cluster?

**Comment by mt-inside** [comment] 2022-01-19 19:13
Seems like it - works fine on k8s 1.20.2, broken on 1.20.14, so some backport broke it

**Comment by Pothulapati** [comment] 2022-01-20 11:35
Hey @mt-inside,

I just tried this on a `1.23.0` and I don't see any problem with `kind`. Prometheus and the proxies seem work fine. Are you sure its not a minikube thing? 🤔 Maybe try out on a `kind` or another host and report back?

I'll try to get minikube up, and give this a try meanwhile.

**Comment by mt-inside** [comment] 2022-01-20 12:37
Hey @Pothulapati , thanks! It does seem weird I agree. I'll try with KinD

**Comment by Pothulapati** [comment] 2022-01-21 09:07
@mt-inside I tried out the same on kind `v0.11.1`, and k8s `1.23.1` for both the edge and stable.

Both of those seem to work fine
```
on ⛵ kind-kind  linkerd2 on 🌱 main [📦🤷‍] via 🐼 v1.16.12 via  via ⚙️ v1.56.1took 2m17s
➜ k version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2022-01-06T22:13:50Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

on ⛵ kind-kind  linkerd2 on 🌱 main [📦🤷‍] via 🐼 v1.16.12 via  via ⚙️ v1.56.1
➜ kind version
kind v0.11.1 go1.16.12 linux/amd64

on ⛵ kind-kind  linkerd2 on 🌱 main [📦🤷‍] via 🐼 v1.16.12 via  via ⚙️ v1.56.1
➜ linkerd viz check
linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ viz extension proxies are healthy
√ viz extension proxies are up-to-date
√ viz extension proxies and cli versions match
√ prometheus is installed and configured correctly
√ can initialize the client
√ viz extension self-check

Status check results are √
on ⛵ kind-kind  linkerd2 on 🌱 main [📦🤷‍] via 🐼 v1.16.12 via  via ⚙️ v1.56.1
➜ linkerd version
Client version: stable-2.11.1
Server version: stable-2.11.1

```

Are you sure you aren't being limited by your laptop limits i.e memory, etc. prometheus does take up a lot! 🤔

**Comment by adleong** [comment] 2022-02-01 19:22
@mt-inside I'm going to close this since we can't reproduce it.  Please feel free to reopen if you have concrete reproduction steps.

**Closed by adleong** 2022-02-01 19:22 UTC
Labels: needs/repro
