### ISSUE TITLE
TLS secrets for pods / services etc not removed after removal of pods or service

### ISSUE THREAD

**Issue by stephenpope** [linkerd/linkerd2#1882] opened 2018-11-28 16:00 UTC
## Bug Report

I have linkerd2 configured for Auto Proxy Injection (`linkerd install --tls=optional --proxy-auto-inject | kubectl apply -f -`)

When I deploy a pod / service / replicaset the side-car proxys are injected correctly and it creates secrets for all of them for secure communication.

If I remove the pod / service / replicaset then the secrets are not removed and I (currently) need to make sure I remove them.

As far as I can see there is no reason to keep them around as, i assume, they cant be reused (as some are mapped to unique/random pod suffixes etc)

### What is the issue?

Secrets are not cleaned up after removal of pods / service / replicaset etc

### How can it be reproduced?

Install Emojivoto
`curl -sL https://run.linkerd.io/emojivoto.yml | kubectl apply -f -`

Remove Emojivoto
`kubectl delete replicasets,services,deployments,pods,rc --all -n emojivoto`

While the application is removed the secrets for each pod / replicaset are still around.

### Environment

- Kubernetes Version: 1.10.3
- Cluster Environment: (GKE, AKS, kops, ...) `Docker for Windows + Kubernetes`
- Host OS: `Windows`
- Linkerd version: `edge-18.11.2`

**Comment by klingerf** [comment] 2018-11-28 19:02
Thanks for reporting this, @stephenpope! I just wanted to the note that this behavior exists whenever TLS is enabled, regardless of whether you're using auto inject or manually injecting via the CLI. I've updated the issue title accordingly.

**Comment by hawkw** [comment] 2018-12-11 23:23
I believe this and #1249 describe the same issue?

**Comment by klingerf** [comment] 2019-01-10 00:04
Am going to close this as a dupe of #1249, which is tracking the TLS work.

**Closed by klingerf** 2019-01-10 00:04 UTC
Labels: area/tls, polish, priority/P2
