### ISSUE TITLE
Tap - tls: bad certificate

### ISSUE THREAD

**Issue by voki** [linkerd/linkerd2#3754] opened 2019-11-22 10:39 UTC
## Bug Report
Linkerd 2.6.0 Tap is failing due to TLS handshake error. 
Linkerd 2.4.0 works with no issues.

### What is the issue?
There seems to be issue with certificates.

### How can it be reproduced?
Linkerd 2.6.0 manual installation:
```linkerd  install | kubectl apply -f -```

### Logs, error output, etc
Tap pod logs:
```2019/11/22 10:27:39 http: TLS handshake error from 127.0.0.1:43990: tls: failed to verify client's certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "front-proxy-ca")```

API Server logs:
```E1122 13:49:21.978188       1 available_controller.go:409] v1alpha1.tap.linkerd.io failed with: Operation cannot be fulfilled on apiservices.apiregistration.k8s.io "v1alpha1.tap.linkerd.io": the object has been modified; please apply your changes to the latest version and try again
I1122 13:49:21.980256       1 controller.go:107] OpenAPI AggregationController: Processing item v1alpha1.tap.linkerd.io
W1122 13:49:21.980315       1 handler_proxy.go:91] no RequestInfo found in the context
E1122 13:49:21.980358       1 controller.go:114] loading OpenAPI spec for "v1alpha1.tap.linkerd.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
, Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
I1122 13:49:21.980371       1 controller.go:127] OpenAPI AggregationController: action for item v1alpha1.tap.linkerd.io: Rate Limited Requeue.
E1122 13:49:21.996993       1 available_controller.go:409] v1alpha1.tap.linkerd.io failed with: failing or missing response from https://10.102.227.180:443/apis/tap.linkerd.io/v1alpha1: Get https://10.102.227.180:443/apis/tap.linkerd.io/v1alpha1: remote error: tls: bad certificate
E1122 13:49:22.016176       1 available_controller.go:409] v1alpha1.tap.linkerd.io failed with: Operation cannot be fulfilled on apiservices.apiregistration.k8s.io "v1alpha1.tap.linkerd.io": the object has been modified; please apply your changes to the latest version and try again
E1122 13:49:22.031894       1 available_controller.go:409] v1alpha1.tap.linkerd.io failed with: failing or missing response from https://10.102.227.180:443/apis/tap.linkerd.io/v1alpha1: Get https://10.102.227.180:443/apis/tap.linkerd.io/v1alpha1: remote error: tls: bad certificate
```

#### `linkerd check` output

```kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.15.2 
- Cluster Environment: Kubeadm
- Host OS: Centos 7.6.1810
- Linkerd version: 2.6.0

### Additional context
Tested also on K8s 1.16.3, same error.
Because of this issue, cluster is unusable, e.g. helm is not working when installing other charts with:

```Error: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: tap.linkerd.io/v1alpha1: the server is currently unable to handle the request```

**Comment by voki** [comment] 2019-11-22 10:46
I have also tried do provide my custom certificates with:
```linkerd install --identity-issuer-certificate-file linkerd.pem --identity-issuer-key-file linkerd-key.pem --identity-trust-anchors-file CA.pem```

I am getting error:
```Error: unsupported block type: 'PRIVATE KEY'```

Certifiacates were generated with openssl, signed by my own CA.
Private key was verified with openssl and is ok.

**Comment by zaharidichev** [comment] 2019-11-22 11:26
Hi @voki How did you generate these certificates. How do they defer from certs generated using the recommended way: https://linkerd.io/2/tasks/generate-certificates/

**Comment by voki** [comment] 2019-11-22 13:17
In the provided link it says it can be generated with openssl. I didn't try generating certs with step tool as looks like it is only available for Debian like systems. We are running on CentOS.

I have my own CA setup with openssl. We are running dozens of systems using this certificates and never had an issue with it. 

CNF file:
```
[ req ]
prompt                  = no
distinguished_name      = server_distinguished_name
req_extensions          = v3_req

[ server_distinguished_name ]
commonName              = linkerd-prd
stateOrProvinceName     = EU
countryName             = EU
emailAddress            = email
organizationName        = company
organizationalUnitName  = team

[ v3_req ]
basicConstraints        = CA:FALSE
keyUsage                = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = linkerd-prd
```
Generate CSR and key:
```openssl req -out csr.pem -newkey rsa:2048 -keyout pk.pem -nodes```

Sign certificate:
```openssl ca -in csr.pem -out certificate.pem```

**Comment by zaharidichev** [comment] 2019-11-22 15:06
@voki so the problem is that your key needs to be either `EC PRIVATE KEY` or `RSA PRIVATE KEY` (EC or PKCS1 respectively).

**Comment by voki** [comment] 2019-11-22 15:34
@zaharidichev Strange, it is RSA key generted with rsa:2048 as you can see above, but when I am checking it with:
``` openssl rsa -in pk.pem -check
RSA key ok
writing RSA key
-----BEGIN RSA PRIVATE KEY-----
.
.
.
-----END RSA PRIVATE KEY-----```

It says ok, but prints key with different header, in file it is "-----BEGIN PRIVATE KEY-----".
Anyway that one works indeed, moving forward, thanks.

Now with custom certificates looks like tap issue is gone, but now there is another one, identity pod is failing.

```linkerd-identity-5677885cbc-2tcqj         0/2     Error     4          107s```

```time="2019-11-22T15:25:53Z" level=info msg="running version stable-2.6.0"
time="2019-11-22T15:25:53Z" level=fatal msg="Failed to read CA from /var/run/linkerd/identity/issuer: x509: failed to parse EC private key: asn1: structure error: tags don't match (4 vs {class:0 tag:2 length:257 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @7"
```
Looks like it is expecting EC key but RSA is provided ?
Other thing is why 2.4.0 works with default certificates and 2.6.0 not?

**Comment by grampelberg** [comment] 2019-11-22 15:58
The original problem here has nothing to do with the linkerd certificates. Tap is an APIService that uses the aggregation layer to forward connections from the api-server to the tap server itself. We fetch a certificate from the api-server (the `extension-apiserver-authentication` configmap, `client-ca-file` field). If that is not present in the configmap and not provided by the api-server when making incoming requests, we fail the connection. You can fix this by following the [k8s documentation](https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/#enable-kubernetes-apiserver-flags) on this.

**Comment by voki** [comment] 2019-11-25 13:46
@grampelberg I have checked my current API server configuration and it is as follows:
```
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
```
I have also checked the extension-apiserver-authentication configmap and it contains proper CA read from client-ca-file argument.
How can I make 2.6.0 work out of box with default linkerd certificates?
Linkerd 2.4.0 is working for me with no issues on this cluster.

**Comment by grampelberg** [comment] 2019-11-25 16:39
2.4 didn't have tap as an APIService, so it makes sense that it works there =) Only thing I can think of is validating the certificates you've got there, the tap server is saying that `proxy-client-cert-file` was not created with `requestheader-client-ca-file`.

**Comment by voki** [comment] 2019-11-26 10:09
But it looks like proxy-client-cert-file is signed by requestheader-client-ca-file.
Config:
```
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
```
Verify:
```
openssl verify -CAfile /etc/kubernetes/pki/front-proxy-ca.crt /etc/kubernetes/pki/front-proxy-client.crt
/etc/kubernetes/pki/front-proxy-client.crt: OK
```

**Comment by grampelberg** [comment] 2019-11-26 16:34
@cpretzer do you have any ideas?

**Comment by ihcsim** [comment] 2019-11-26 17:59
@voki Since you are using both `--client-ca-file` and `--requestheader-client-ca-file`, can you confirm they use different CAs, per the K8s [docs](https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/#enable-kubernetes-apiserver-flags): 

> For this reason, use different CA certs for the --client-ca-file option - to authorize control plane components and end-users - and the --requestheader-client-ca-file option - to authorize aggregation apiserver requests.

(AFAICT, `--client-ca-file` might be optional.)

Also, make sure the `--requestheader-allowed-names` matches the CN of `--request-client-ca-file`:

> The Kubernetes apiserver then checks if the common name CN= is one of the names in the list provided by --requestheader-allowed-names. If the name is allowed, the request is approved; if it is not, the request is not.

**Comment by cpretzer** [comment] 2019-11-26 18:42
> @cpretzer do you have any ideas?

If we're still talking about these X509 errors from the identity service:

```
time="2019-11-22T15:25:53Z" level=info msg="running version stable-2.6.0"
time="2019-11-22T15:25:53Z" level=fatal msg="Failed to read CA from /var/run/linkerd/identity/issuer: x509: failed to parse EC private key: asn1: structure error: tags don't match (4 vs {class:0 tag:2 length:257 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @7"
```

Then I'm curious to know whether the identity service was restarted or Linkerd 2.6.0 was reinstalled after the custom certificates were applied.

**Comment by cpretzer** [comment] 2019-11-27 04:06
@voki what is the output from `kubectl get secret -n secret | grep linkerd-identity-issuer`?

That is the secret that provides the volumeMount for `/var/run/linkerd/identity/issuer`

**Comment by voki** [comment] 2019-11-27 09:42
@ihcsim Yes, they are different, client-ca-file is provided by me, front proxy is generated by kubeadm.
```openssl x509 -in /etc/kubernetes/pki/front-proxy-ca.crt -fingerprint -noout
SHA1 Fingerprint=5B:55:83:81:2D:60:F2:6A:13:E0:95:BE:47:64:6A:C6:2F:B6:6A:AE```
```openssl x509 -in /etc/kubernetes/pki/ca.crt -fingerprint -noout
SHA1 Fingerprint=F0:7F:CA:92:5E:AE:DC:4B:65:DB:73:DB:FB:58:E5:12:5D:F5:9D:67```
I have also rebuild cluster with empty requestheader-allowed-names, which according to docs should now allow all CNs. Still no luck.

@cpretzer There are two issues, one with default installation, when tap is not working with the errors from the first post. Second issue is when I provide my custom certificates during linkerd installation, tap works, but identity service is not working. But as error states, probably I just need to provide EC key instead of RSA and it should work, didn't try yet. I am focusing on getting it running with default certificates. Service was not restarted, it was installed with custom parameters, I assume restart is not needed in that case.

kubectl get secret -n linkerd | grep linkerd-identity-issuer:
```Name:         linkerd-identity-issuer```

kubectl describe secret linkerd-identity-issuer -n linkerd
```Name:         linkerd-identity-issuer
Namespace:    linkerd
Labels:       linkerd.io/control-plane-component=identity
              linkerd.io/control-plane-ns=linkerd
Annotations:  linkerd.io/created-by: linkerd/cli stable-2.6.0
              linkerd.io/identity-issuer-expiry: 2020-11-26T09:27:13Z

Type:  Opaque

Data
====
key.pem:  226 bytes
crt.pem:  586 bytes
```

**Comment by voki** [comment] 2019-12-10 14:27
I have tried 2.6 with Kubernetes 1.17.0 and it seems to work out of box with default installation. 
It seems something was broken in 1.16.3.
Tap service seems to work when I have played with it from ui, but I found some errors in api server logs, don't know if it is relevant.

```
I1210 14:20:11.095671       1 controller.go:107] OpenAPI AggregationController: Processing item v1alpha1.tap.linkerd.io
E1210 14:20:12.046973       1 controller.go:114] loading OpenAPI spec for "v1alpha1.tap.linkerd.io" failed with: ERROR $root.paths./apis/tap.linkerd.io/v1alpha1.get is missing required property: responses
ERROR $root.paths./apis/tap.linkerd.io.get is missing required property: responses
I1210 14:20:12.047031       1 controller.go:127] OpenAPI AggregationController: action for item v1alpha1.tap.linkerd.io: Rate Limited Requeue.
```

**Comment by ihcsim** [comment] 2019-12-10 17:35
> E1210 14:20:12.046973       1 controller.go:114] loading OpenAPI spec for "v1alpha1.tap.linkerd.io" failed with: ERROR $root.paths./apis/tap.linkerd.io/v1alpha1.get is missing required property: responses
ERROR $root.paths./apis/tap.linkerd.io.get is missing required property: responses

That error is benign. It was recently fixed in https://github.com/linkerd/linkerd2/pull/3700.

**Comment by grampelberg** [comment] 2019-12-10 17:47
Awesome! Closing this out then.

**Closed by grampelberg** 2019-12-10 17:47 UTC
Labels: needs/more

**Comment by cpretzer** [comment] 2019-12-10 18:53
Thanks for the update @voki !
