### ISSUE TITLE
Error creating admission webhook. Request Denied

### ISSUE THREAD

**Issue by callumeveratt** [linkerd/linkerd2#6005] opened 2021-04-09 12:14 UTC
### What is the issue?
We have just swapped to using cert-manager to manage rotation of certificates (only recent change) after redeploying the entire cluster admission webhooks now fail with:
`Error creating: admission webhook "linkerd-proxy-injector.linkerd.io" denied
  the request: failed to unmarshal JSON from: /var/run/linkerd/config/values:
  error unmarshaling JSON: while decoding JSON: parsing time """" as
  ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "2006"`

### Logs, error output, etc
`involvedObject:
  kind: ReplicaSet
  namespace: expensesdeployment
  name: notification-service-selenity-service-notifications-587d55f4cd
  uid: 681b0eab-7d84-4f15-b8a0-7d88515b5c38
  apiVersion: apps/v1
  resourceVersion: '23335'
reason: FailedCreate
message: >-
  Error creating: admission webhook "linkerd-proxy-injector.linkerd.io" denied
  the request: failed to unmarshal JSON from: /var/run/linkerd/config/values:
  error unmarshaling JSON: while decoding JSON: parsing time """" as
  ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "2006"
source:
  component: replicaset-controller
firstTimestamp: '2021-04-09T12:06:28Z'
lastTimestamp: '2021-04-09T12:09:12Z'
count: 16
type: Warning
eventTime: null
reportingComponent: ''
reportingInstance: ''`
(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
× control plane ClusterRoles exist
    missing ClusterRoles: linkerd-linkerd-prometheus
    see https://linkerd.io/checks/#l5d-existence-cr for hints
```

### Environment

- Kubernetes Version: 1.19.6
- Cluster Environment: (GKE, AKS, kops, ...) AKS
- Host OS: Linux
- Linkerd version: 2.9.4

**Comment by kleimkuhler** [comment] 2021-04-09 13:17
@callumeveratt It looks like the timestamp `""2006-01-02T15:04:05Z07:00""` is double wrapped in double quotes. I would expect it to be `"2006-01-02T15:04:05Z07:00"`. Is this something that cert-manager is incorrectly generating?

**Comment by callumeveratt** [comment] 2021-04-09 13:22
@kleimkuhler Where about are you thinking it could be generated? Looking at the certificate request the following is returned: 
`kubectl describe certificaterequests -n linkerd
Name:         linkerd-identity-issuer-nqfdf
Namespace:    linkerd
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  cert-manager.io/certificate-name: linkerd-identity-issuer
              cert-manager.io/certificate-revision: 1
              cert-manager.io/private-key-secret-name: linkerd-identity-issuer-ghpbq
              meta.helm.sh/release-name: certmanager-requests
              meta.helm.sh/release-namespace: certmanager
API Version:  cert-manager.io/v1
Kind:         CertificateRequest
Metadata:
  Creation Timestamp:  2021-04-09T10:29:10Z
  Generate Name:       linkerd-identity-issuer-
  Generation:          1
  Managed Fields:
    API Version:  cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:cert-manager.io/certificate-name:
          f:cert-manager.io/certificate-revision:
          f:cert-manager.io/private-key-secret-name:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:generateName:
        f:labels:
          .:
          f:app.kubernetes.io/managed-by:
        f:ownerReferences:
          .:
          k:{"uid":"006b4b6b-da5b-4704-a062-ffd2917e401b"}:
            .:
            f:apiVersion:
            f:blockOwnerDeletion:
            f:controller:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        .:
        f:duration:
        f:isCA:
        f:issuerRef:
          .:
          f:kind:
          f:name:
        f:request:
        f:usages:
      f:status:
        .:
        f:ca:
        f:certificate:
        f:conditions:
    Manager:    controller
    Operation:  Update
    Time:       2021-04-09T10:29:10Z
  Owner References:
    API Version:           cert-manager.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Certificate
    Name:                  linkerd-identity-issuer
    UID:                   006b4b6b-da5b-4704-a062-ffd2917e401b
  Resource Version:        3437
  Self Link:               /apis/cert-manager.io/v1/namespaces/linkerd/certificaterequests/linkerd-identity-issuer-nqfdf
  UID:                     24ccde5f-40a0-4ecb-b2d1-8a0e0d4dfec9
Spec:
  Duration:  48h0m0s
  Is CA:     true
  Issuer Ref:
    Kind:   ClusterIssuer
    Name:   linkerd-trust-anchor
  Request:  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQlREQ0I4d0lCQURBcE1TY3dKUVlEVlFRREV4NXBaR1Z1ZEdsMGVTNXNhVzVyWlhKa0xtTnNkWE4wWlhJdQpiRzlqWVd3d1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRTTBFZ1ExakI4bi9TcXVUdC9rYU1xCkpQQUFEMzQ0a2hrQU5qbUxrWk5FR0V0dUdOeTcwSmZhQ1VELzU5Y0lTc1FXVHNXRFZLVTJqRnVPRlA3cFFZa08Kb0dnd1pnWUpLb1pJaHZjTkFRa09NVmt3VnpBcEJnTlZIUkVFSWpBZ2doNXBaR1Z1ZEdsMGVTNXNhVzVyWlhKawpMbU5zZFhOMFpYSXViRzlqWVd3d0N3WURWUjBQQkFRREFnRUdNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CCkJnZ3JCZ0VGQlFjREFqQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQS9zdU5ha0F4YXRmZmJ0dE9vK2tRMmZtQVYKekw1OTlDOUdFR3c5TXg4emJnSWhBSVp3eUtxbmNTMEN2QU4wYVl6SVRBKzczZzhKYXJubHByMXhzWE5pQXJnVwotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  Usages:
    cert sign
    crl sign
    server auth
    client auth
Status:
  Ca:           LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJxRENDQVUrZ0F3SUJBZ0lRZUZPNDlYUGx4Z0FVL3hrUlNtTW43akFLQmdncWhrak9QUVFEQWpBbE1TTXcKSVFZRFZRUURFeHB5YjI5MExteHBibXRsY21RdVkyeDFjM1JsY2k1c2IyTmhiREFlRncweU1UQTBNRGt4TURFNQpNelZhRncwek1UQTBNRGN4TURFNU16VmFNQ1V4SXpBaEJnTlZCQU1UR25KdmIzUXViR2x1YTJWeVpDNWpiSFZ6CmRHVnlMbXh2WTJGc01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXU1dWJmNzRrNXdoKzRvMFQKL05hMnlXNHhUUEpRL2dVRjRBajVtVGE0UDJFeTJoM2pmNTRXOEJlekdFdGsvbG1QT3IrQWxJM2k1c2NOeEJsSAowK05FUmFOaE1GOHdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyCkJnRUZCUWNEQWpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTZ2xqZjdPOUlBS0EwMVhuN1kKekxsVlBacUdmREFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFrM2RvTXFmNTdhSDhJNXRkZE9uVzJpVk5NNXVZSQpidGlzY0c1N3c5a29iUUlnVkZOdGdoa2NLU3hRaEZQNXBMRDhDd3Iwa1JuVEVFVFF2c29iUGh2RXNpOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  Certificate:  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrekNDQWFHZ0F3SUJBZ0lRY0xrRkZSOXhpNW1WcjNXSkFhd0UrekFLQmdncWhrak9QUVFEQWpBbE1TTXcKSVFZRFZRUURFeHB5YjI5MExteHBibXRsY21RdVkyeDFjM1JsY2k1c2IyTmhiREFlRncweU1UQTBNRGt4TURJNQpNVEJhRncweU1UQTBNVEV4TURJNU1UQmFNQ2t4SnpBbEJnTlZCQU1USG1sa1pXNTBhWFI1TG14cGJtdGxjbVF1ClkyeDFjM1JsY2k1c2IyTmhiREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCQXpRU0JEV01IeWYKOUtxNU8zK1JveW9rOEFBUGZqaVNHUUEyT1l1UmswUVlTMjRZM0x2UWw5b0pRUC9uMXdoS3hCWk94WU5VcFRhTQpXNDRVL3VsQmlRNmpnYTR3Z2Fzd0RnWURWUjBQQVFIL0JBUURBZ0VHTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGCkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlRkSWFvMnZFc1cKaUpVWFdRM1FISGV1VE1FWktEQWZCZ05WSFNNRUdEQVdnQlNnbGpmN085SUFLQTAxWG43WXpMbFZQWnFHZkRBcApCZ05WSFJFRUlqQWdnaDVwWkdWdWRHbDBlUzVzYVc1clpYSmtMbU5zZFhOMFpYSXViRzlqWVd3d0NnWUlLb1pJCnpqMEVBd0lEU0FBd1JRSWhBUHRqNjllWlF5NWk0Ym5laExIdWdnYklSSUJEWmpDZnlRSjZNODVoTGtLM0FpQjEKdmhUL2ZQMGhQYkRWbnREQnY5SUZ6RkM1ZFlBMDcrMGpKbHF6VUR0SW1nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  Conditions:
    Last Transition Time:  2021-04-09T10:29:10Z
    Message:               Certificate fetched from issuer successfully
    Reason:                Issued
    Status:                True
    Type:                  Ready
Events:                    <none>`

**Comment by callumeveratt** [comment] 2021-04-09 13:23
@kleimkuhler Where abouts are you thinking it could be generated by cert-manager? certificate request shows the following

> kubectl describe certificaterequests -n linkerd
> Name:         linkerd-identity-issuer-nqfdf
> Namespace:    linkerd
> Labels:       app.kubernetes.io/managed-by=Helm
> Annotations:  cert-manager.io/certificate-name: linkerd-identity-issuer
>               cert-manager.io/certificate-revision: 1
>               cert-manager.io/private-key-secret-name: linkerd-identity-issuer-ghpbq
>               meta.helm.sh/release-name: certmanager-requests
>               meta.helm.sh/release-namespace: certmanager
> API Version:  cert-manager.io/v1
> Kind:         CertificateRequest
> Metadata:
>   Creation Timestamp:  2021-04-09T10:29:10Z
>   Generate Name:       linkerd-identity-issuer-
>   Generation:          1
>   Managed Fields:
>     API Version:  cert-manager.io/v1
>     Fields Type:  FieldsV1
>     fieldsV1:
>       f:metadata:
>         f:annotations:
>           .:
>           f:cert-manager.io/certificate-name:
>           f:cert-manager.io/certificate-revision:
>           f:cert-manager.io/private-key-secret-name:
>           f:meta.helm.sh/release-name:
>           f:meta.helm.sh/release-namespace:
>         f:generateName:
>         f:labels:
>           .:
>           f:app.kubernetes.io/managed-by:
>         f:ownerReferences:
>           .:
>           k:{"uid":"006b4b6b-da5b-4704-a062-ffd2917e401b"}:
>             .:
>             f:apiVersion:
>             f:blockOwnerDeletion:
>             f:controller:
>             f:kind:
>             f:name:
>             f:uid:
>       f:spec:
>         .:
>         f:duration:
>         f:isCA:
>         f:issuerRef:
>           .:
>           f:kind:
>           f:name:
>         f:request:
>         f:usages:
>       f:status:
>         .:
>         f:ca:
>         f:certificate:
>         f:conditions:
>     Manager:    controller
>     Operation:  Update
>     Time:       2021-04-09T10:29:10Z
>   Owner References:
>     API Version:           cert-manager.io/v1
>     Block Owner Deletion:  true
>     Controller:            true
>     Kind:                  Certificate
>     Name:                  linkerd-identity-issuer
>     UID:                   006b4b6b-da5b-4704-a062-ffd2917e401b
>   Resource Version:        3437
>   Self Link:               /apis/cert-manager.io/v1/namespaces/linkerd/certificaterequests/linkerd-identity-issuer-nqfdf
>   UID:                     24ccde5f-40a0-4ecb-b2d1-8a0e0d4dfec9
> Spec:
>   Duration:  48h0m0s
>   Is CA:     true
>   Issuer Ref:
>     Kind:   ClusterIssuer
>     Name:   linkerd-trust-anchor
>   Request:  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQlREQ0I4d0lCQURBcE1TY3dKUVlEVlFRREV4NXBaR1Z1ZEdsMGVTNXNhVzVyWlhKa0xtTnNkWE4wWlhJdQpiRzlqWVd3d1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRTTBFZ1ExakI4bi9TcXVUdC9rYU1xCkpQQUFEMzQ0a2hrQU5qbUxrWk5FR0V0dUdOeTcwSmZhQ1VELzU5Y0lTc1FXVHNXRFZLVTJqRnVPRlA3cFFZa08Kb0dnd1pnWUpLb1pJaHZjTkFRa09NVmt3VnpBcEJnTlZIUkVFSWpBZ2doNXBaR1Z1ZEdsMGVTNXNhVzVyWlhKawpMbU5zZFhOMFpYSXViRzlqWVd3d0N3WURWUjBQQkFRREFnRUdNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CCkJnZ3JCZ0VGQlFjREFqQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQS9zdU5ha0F4YXRmZmJ0dE9vK2tRMmZtQVYKekw1OTlDOUdFR3c5TXg4emJnSWhBSVp3eUtxbmNTMEN2QU4wYVl6SVRBKzczZzhKYXJubHByMXhzWE5pQXJnVwotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
>   Usages:
>     cert sign
>     crl sign
>     server auth
>     client auth
> Status:
>   Ca:           LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJxRENDQVUrZ0F3SUJBZ0lRZUZPNDlYUGx4Z0FVL3hrUlNtTW43akFLQmdncWhrak9QUVFEQWpBbE1TTXcKSVFZRFZRUURFeHB5YjI5MExteHBibXRsY21RdVkyeDFjM1JsY2k1c2IyTmhiREFlRncweU1UQTBNRGt4TURFNQpNelZhRncwek1UQTBNRGN4TURFNU16VmFNQ1V4SXpBaEJnTlZCQU1UR25KdmIzUXViR2x1YTJWeVpDNWpiSFZ6CmRHVnlMbXh2WTJGc01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXU1dWJmNzRrNXdoKzRvMFQKL05hMnlXNHhUUEpRL2dVRjRBajVtVGE0UDJFeTJoM2pmNTRXOEJlekdFdGsvbG1QT3IrQWxJM2k1c2NOeEJsSAowK05FUmFOaE1GOHdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyCkJnRUZCUWNEQWpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTZ2xqZjdPOUlBS0EwMVhuN1kKekxsVlBacUdmREFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUFrM2RvTXFmNTdhSDhJNXRkZE9uVzJpVk5NNXVZSQpidGlzY0c1N3c5a29iUUlnVkZOdGdoa2NLU3hRaEZQNXBMRDhDd3Iwa1JuVEVFVFF2c29iUGh2RXNpOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
>   Certificate:  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrekNDQWFHZ0F3SUJBZ0lRY0xrRkZSOXhpNW1WcjNXSkFhd0UrekFLQmdncWhrak9QUVFEQWpBbE1TTXcKSVFZRFZRUURFeHB5YjI5MExteHBibXRsY21RdVkyeDFjM1JsY2k1c2IyTmhiREFlRncweU1UQTBNRGt4TURJNQpNVEJhRncweU1UQTBNVEV4TURJNU1UQmFNQ2t4SnpBbEJnTlZCQU1USG1sa1pXNTBhWFI1TG14cGJtdGxjbVF1ClkyeDFjM1JsY2k1c2IyTmhiREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCQXpRU0JEV01IeWYKOUtxNU8zK1JveW9rOEFBUGZqaVNHUUEyT1l1UmswUVlTMjRZM0x2UWw5b0pRUC9uMXdoS3hCWk94WU5VcFRhTQpXNDRVL3VsQmlRNmpnYTR3Z2Fzd0RnWURWUjBQQVFIL0JBUURBZ0VHTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGCkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlRkSWFvMnZFc1cKaUpVWFdRM1FISGV1VE1FWktEQWZCZ05WSFNNRUdEQVdnQlNnbGpmN085SUFLQTAxWG43WXpMbFZQWnFHZkRBcApCZ05WSFJFRUlqQWdnaDVwWkdWdWRHbDBlUzVzYVc1clpYSmtMbU5zZFhOMFpYSXViRzlqWVd3d0NnWUlLb1pJCnpqMEVBd0lEU0FBd1JRSWhBUHRqNjllWlF5NWk0Ym5laExIdWdnYklSSUJEWmpDZnlRSjZNODVoTGtLM0FpQjEKdmhUL2ZQMGhQYkRWbnREQnY5SUZ6RkM1ZFlBMDcrMGpKbHF6VUR0SW1nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
>   Conditions:
>     Last Transition Time:  2021-04-09T10:29:10Z
>     Message:               Certificate fetched from issuer successfully
>     Reason:                Issued
>     Status:                True
>     Type:                  Ready
> Events:                    <none>

**Comment by olix0r** [comment] 2021-04-09 14:45
This error is likely being thrown by https://github.com/linkerd/linkerd2/blob/a393c42536d569e5a9becc3b1dd8227063fba478/pkg/config/config.go#L37-L64 and invoked by https://github.com/linkerd/linkerd2/blob/a11012819c366574e07fadbbdf4e4a341d0cae54/controller/proxy-injector/webhook.go#L39-L39 -- when trying to parse the ConfigMap from  `/var/run/linkerd/config/values` in the injector pod.

Can you share the output of `kubectl describe -n linkerd cm/linkerd-config` -- I would assume something is incorrect in this ConfigMap.

**Comment by callumeveratt** [comment] 2021-04-09 14:57
@olix0r Here you go:

> kubectl describe -n linkerd cm/linkerd-config
> Name:         linkerd-config
> Namespace:    linkerd
> Labels:       app.kubernetes.io/managed-by=Helm
>               linkerd.io/control-plane-component=controller
>               linkerd.io/control-plane-ns=linkerd
> Annotations:  linkerd.io/created-by: linkerd/helm stable-2.9.4
>               meta.helm.sh/release-name: linkerd
>               meta.helm.sh/release-namespace: linkerd
> 
> Data
> ====
> values:
> ----
> controllerImage: cr.l5d.io/linkerd/controller
> controllerReplicas: 1
> controllerUID: 2103
> dashboard:
>   replicas: 1
> debugContainer:
>   image:
>     name: cr.l5d.io/linkerd/debug
>     pullPolicy: IfNotPresent
>     version: stable-2.9.4
> disableHeartBeat: false
> enableH2Upgrade: true
> enforcedHostRegexp: ""
> global:
>   clusterDomain: cluster.local
>   clusterNetworks: 10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16
>   cniEnabled: false
>   controlPlaneTracing: false
>   controllerComponentLabel: linkerd.io/control-plane-component
>   controllerLogLevel: info
>   controllerNamespaceLabel: linkerd.io/control-plane-ns
>   createdByAnnotation: linkerd.io/created-by
>   enableEndpointSlices: false
>   grafanaUrl: grafana-testing.expenses360.com
>   identityTrustAnchorsPEM: |
>     -----BEGIN CERTIFICATE-----
>     MIIBqDCCAU+gAwIBAgIQeFO49XPlxgAU/xkRSmMn7jAKBggqhkjOPQQDAjAlMSMw
>     IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMTA0MDkxMDE5
>     MzVaFw0zMTA0MDcxMDE5MzVaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
>     dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEu5ubf74k5wh+4o0T
>     /Na2yW4xTPJQ/gUF4Aj5mTa4P2Ey2h3jf54W8BezGEtk/lmPOr+AlI3i5scNxBlH
>     0+NERaNhMF8wDgYDVR0PAQH/BAQDAgEGMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
>     BgEFBQcDAjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSgljf7O9IAKA01Xn7Y
>     zLlVPZqGfDAKBggqhkjOPQQDAgNHADBEAiAk3doMqf57aH8I5tddOnW2iVNM5uYI
>     btiscG57w9kobQIgVFNtghkcKSxQhFP5pLD8Cwr0kRnTEETQvsobPhvEsi8=
>     -----END CERTIFICATE-----
>   identityTrustDomain: cluster.local
>   imagePullPolicy: IfNotPresent
>   imagePullSecrets: []
>   linkerdNamespaceLabel: linkerd.io/is-control-plane
>   linkerdVersion: stable-2.9.4
>   namespace: linkerd
>   podAnnotations: {}
>   podLabels: {}
>   prometheusUrl: prometheus-testing.expenses360.com
>   proxy:
>     cores: 0
>     enableExternalProfiles: false
>     image:
>       name: cr.l5d.io/linkerd/proxy
>       pullPolicy: IfNotPresent
>       version: stable-2.9.4
>     inboundConnectTimeout: 100ms
>     logFormat: plain
>     logLevel: warn,linkerd=info
>     outboundConnectTimeout: 1000ms
>     ports:
>       admin: 4191
>       control: 4190
>       inbound: 4143
>       outbound: 4140
>     requireIdentityOnInboundPorts: ""
>     resources:
>       cpu:
>         limit: ""
>         request: ""
>       memory:
>         limit: ""
>         request: ""
>     trace:
>       collectorSvcAccount: default
>       collectorSvcAddr: ""
>     uid: 2102
>     waitBeforeExitSeconds: 0
>   proxyInit:
>     closeWaitTimeoutSecs: 0
>     ignoreInboundPorts: 25,443,587,3306,11211,5432
>     ignoreOutboundPorts: 25,443,587,3306,11211,5432
>     image:
>       name: cr.l5d.io/linkerd/proxy-init
>       pullPolicy: IfNotPresent
>       version: v1.3.9
>     resources:
>       cpu:
>         limit: 100m
>         request: 10m
>       memory:
>         limit: 50Mi
>         request: 10Mi
>     xtMountPath:
>       mountPath: /run
>       name: linkerd-proxy-init-xtables-lock
>   proxyInjectAnnotation: linkerd.io/inject
>   proxyInjectDisabled: disabled
>   workloadNamespaceLabel: linkerd.io/workload-ns
> grafana:
>   enabled: false
> heartbeatSchedule: 0 0 * * *
> identity:
>   issuer:
>     clockSkewAllowance: 20s
>     crtExpiry: ""
>     crtExpiryAnnotation: linkerd.io/identity-issuer-expiry
>     issuanceLifetime: 24h0m0s
>     scheme: kubernetes.io/tls
>     tls:
>       crtPEM: ""
> installNamespace: false
> nodeSelector:
>   beta.kubernetes.io/os: linux
>   os: linux
> omitWebhookSideEffects: false
> profileValidator:
>   caBundle: ""
>   crtPEM: ""
>   externalSecret: false
>   namespaceSelector:
>     matchExpressions:
>     - key: config.linkerd.io/admission-webhooks
>       operator: NotIn
>       values:
>       - disabled
> prometheus:
>   enabled: false
> proxyInjector:
>   caBundle: ""
>   crtPEM: ""
>   externalSecret: false
>   namespaceSelector:
>     matchExpressions:
>     - key: config.linkerd.io/admission-webhooks
>       operator: NotIn
>       values:
>       - disabled
> tap:
>   caBundle: ""
>   crtPEM: ""
>   externalSecret: false
> tracing:
>   enabled: false
> webImage: cr.l5d.io/linkerd/web
> webhookFailurePolicy: Ignore
> 
> Events:  <none>

**Comment by callumeveratt** [comment] 2021-04-09 14:57
@olix0r Here you go:
```
kubectl describe -n linkerd cm/linkerd-config
Name:         linkerd-config
Namespace:    linkerd
Labels:       app.kubernetes.io/managed-by=Helm
              linkerd.io/control-plane-component=controller
              linkerd.io/control-plane-ns=linkerd
Annotations:  linkerd.io/created-by: linkerd/helm stable-2.9.4
              meta.helm.sh/release-name: linkerd
              meta.helm.sh/release-namespace: linkerd

Data
====
values:
----
controllerImage: cr.l5d.io/linkerd/controller
controllerReplicas: 1
controllerUID: 2103
dashboard:
  replicas: 1
debugContainer:
  image:
    name: cr.l5d.io/linkerd/debug
    pullPolicy: IfNotPresent
    version: stable-2.9.4
disableHeartBeat: false
enableH2Upgrade: true
enforcedHostRegexp: ""
global:
  clusterDomain: cluster.local
  clusterNetworks: 10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16
  cniEnabled: false
  controlPlaneTracing: false
  controllerComponentLabel: linkerd.io/control-plane-component
  controllerLogLevel: info
  controllerNamespaceLabel: linkerd.io/control-plane-ns
  createdByAnnotation: linkerd.io/created-by
  enableEndpointSlices: false
  grafanaUrl: grafana-testing.expenses360.com
  identityTrustAnchorsPEM: |
    -----BEGIN CERTIFICATE-----
    MIIBqDCCAU+gAwIBAgIQeFO49XPlxgAU/xkRSmMn7jAKBggqhkjOPQQDAjAlMSMw
    IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMTA0MDkxMDE5
    MzVaFw0zMTA0MDcxMDE5MzVaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
    dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEu5ubf74k5wh+4o0T
    /Na2yW4xTPJQ/gUF4Aj5mTa4P2Ey2h3jf54W8BezGEtk/lmPOr+AlI3i5scNxBlH
    0+NERaNhMF8wDgYDVR0PAQH/BAQDAgEGMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
    BgEFBQcDAjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSgljf7O9IAKA01Xn7Y
    zLlVPZqGfDAKBggqhkjOPQQDAgNHADBEAiAk3doMqf57aH8I5tddOnW2iVNM5uYI
    btiscG57w9kobQIgVFNtghkcKSxQhFP5pLD8Cwr0kRnTEETQvsobPhvEsi8=
    -----END CERTIFICATE-----
  identityTrustDomain: cluster.local
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  linkerdNamespaceLabel: linkerd.io/is-control-plane
  linkerdVersion: stable-2.9.4
  namespace: linkerd
  podAnnotations: {}
  podLabels: {}
  prometheusUrl: prometheus-testing.expenses360.com
  proxy:
    cores: 0
    enableExternalProfiles: false
    image:
      name: cr.l5d.io/linkerd/proxy
      pullPolicy: IfNotPresent
      version: stable-2.9.4
    inboundConnectTimeout: 100ms
    logFormat: plain
    logLevel: warn,linkerd=info
    outboundConnectTimeout: 1000ms
    ports:
      admin: 4191
      control: 4190
      inbound: 4143
      outbound: 4140
    requireIdentityOnInboundPorts: ""
    resources:
      cpu:
        limit: ""
        request: ""
      memory:
        limit: ""
        request: ""
    trace:
      collectorSvcAccount: default
      collectorSvcAddr: ""
    uid: 2102
    waitBeforeExitSeconds: 0
  proxyInit:
    closeWaitTimeoutSecs: 0
    ignoreInboundPorts: 25,443,587,3306,11211,5432
    ignoreOutboundPorts: 25,443,587,3306,11211,5432
    image:
      name: cr.l5d.io/linkerd/proxy-init
      pullPolicy: IfNotPresent
      version: v1.3.9
    resources:
      cpu:
        limit: 100m
        request: 10m
      memory:
        limit: 50Mi
        request: 10Mi
    xtMountPath:
      mountPath: /run
      name: linkerd-proxy-init-xtables-lock
  proxyInjectAnnotation: linkerd.io/inject
  proxyInjectDisabled: disabled
  workloadNamespaceLabel: linkerd.io/workload-ns
grafana:
  enabled: false
heartbeatSchedule: 0 0 * * *
identity:
  issuer:
    clockSkewAllowance: 20s
    crtExpiry: ""
    crtExpiryAnnotation: linkerd.io/identity-issuer-expiry
    issuanceLifetime: 24h0m0s
    scheme: kubernetes.io/tls
    tls:
      crtPEM: ""
installNamespace: false
nodeSelector:
  beta.kubernetes.io/os: linux
  os: linux
omitWebhookSideEffects: false
profileValidator:
  caBundle: ""
  crtPEM: ""
  externalSecret: false
  namespaceSelector:
    matchExpressions:
    - key: config.linkerd.io/admission-webhooks
      operator: NotIn
      values:
      - disabled
prometheus:
  enabled: false
proxyInjector:
  caBundle: ""
  crtPEM: ""
  externalSecret: false
  namespaceSelector:
    matchExpressions:
    - key: config.linkerd.io/admission-webhooks
      operator: NotIn
      values:
      - disabled
tap:
  caBundle: ""
  crtPEM: ""
  externalSecret: false
tracing:
  enabled: false
webImage: cr.l5d.io/linkerd/web
webhookFailurePolicy: Ignore

Events:  <none>
```

**Comment by olix0r** [comment] 2021-04-09 15:29
At a guess, I think the problem is that the `identity.crtExpiry` field is empty:
```yaml
identity:
  issuer:
    clockSkewAllowance: 20s
    crtExpiry: ""
```

In a healthy cluster I see this set as, for instance:
```
identity:
  issuer:
    clockSkewAllowance: 20s
    crtExpiry: "2022-03-25T15:08:36Z"
```

So, it would be great if we could handle this error more gracefully in our parsing code; but I think you'll also need to ensure that your config is generated properly.

How did you go about creating this cluster?

**Comment by callumeveratt** [comment] 2021-04-09 20:08
@olix0r  Currently in my helm chart I have it set as blank, I assumed this would come from the certificate certmanager issues. Is there another value I need to provide in here when using Kubernetes.io/tls as the scheme?

**Comment by callumeveratt** [comment] 2021-04-12 10:31
Update - so removing the following from the Helm Chart made it happy again:
` # must match the expiry date in crtPEM
    crtExpiry: |`

I'll leave this open if required because, as suggested, the error around it could be clearer but my issue is solved.

**Comment by adleong** [comment] 2021-04-12 22:55
That's great to hear, @callumeveratt!  I agree that giving a more descriptive error would be ideal but given that this error comes from an underlying json parsing library, it's not trivial.  Given that setting `crtExpiry` is described in https://linkerd.io/2.10/tasks/install-helm/ I'm inclined to close this issue.  But if you have any specific ideas on how to make this clearer, we'd welcome a PR!

**Closed by adleong** 2021-04-12 22:55 UTC
