### ISSUE TITLE
linkerd-proxy uses node's public ip instead of cluster network

### ISSUE THREAD

**Issue by cortopy** [linkerd/linkerd2#7507] opened 2021-12-20 10:17 UTC
### What is the issue?

I've just upgraded to 2.11 from 2.8 and I'm having issues with authorization policies.

When I try to install linkerd-viz, none of the pods are authorised.

In the logs I'm getting:

```
[ 1.137943s] INFO ThreadId(01) inbound:server{port=9998}:rescue{client.addr=<node-public-ip>:49086}: linkerd_app_core::errors::respond: Request failed error=unauthorized connection on server admin
Mon, Dec 20 2021 10:05:07 am
```

However, if I add the `node-public-ip` address to the `clusterNetworks` value in the helm chart, it all works fine.

I'm not sure why 

### How can it be reproduced?

- Install linkerd-cni with helm
- Install linkerd 2.11 with helm
- Install linkerd-viz 2.11 with helm

### Logs, error output, etc

This is the node description of the node:

```
Name:               worker-1
Roles:              worker
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=worker-1
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/worker=true
                    pool=robot
Annotations:        csi.volume.kubernetes.io/nodeid: {"driver.longhorn.io":"worker-1"}
                    flannel.alpha.coreos.com/backend-data: {"VtepMAC":"************"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 192.168.4.1
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: 192.168.4.1/12
                    projectcalico.org/IPv4IPIPTunnelAddr: 10.42.1.1
                    rke.cattle.io/external-ip: <public-ip>
                    rke.cattle.io/internal-ip: 192.168.4.1
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sun, 14 Feb 2021 18:22:18 +0000
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  worker-1
  AcquireTime:     <unset>
  RenewTime:       Mon, 20 Dec 2021 10:12:28 +0000
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Tue, 14 Sep 2021 22:21:00 +0100   Tue, 14 Sep 2021 22:21:00 +0100   FlannelIsUp                  Flannel is running on this node
  MemoryPressure       False   Mon, 20 Dec 2021 10:10:56 +0000   Wed, 24 Nov 2021 09:41:24 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Mon, 20 Dec 2021 10:10:56 +0000   Wed, 24 Nov 2021 09:41:24 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Mon, 20 Dec 2021 10:10:56 +0000   Wed, 24 Nov 2021 09:41:24 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Mon, 20 Dec 2021 10:10:56 +0000   Wed, 24 Nov 2021 09:41:24 +0000   KubeletReady                 kubelet is posting ready status. AppArmor enabled
Addresses:
  InternalIP:  192.168.4.1
  Hostname:    worker-1
```

### output of `linkerd check -o short`

```
Linkerd extensions checks
=========================
| Running viz extension check
```

### Environment

- Kubernetes: 1.20
- Cluster: rancher
- CNI: calico

### Possible solution

As I said above, if I add the public IP of worker nodes to the cluster network, it all works fine.

But I would expect the linkerd-proxy to use a cluster network ip (i.e.: the public ip of the pod)

**Comment by olix0r** [comment] 2021-12-21 16:56
@cortopy This isn't anything that Linkerd is doing, really. Instead, it's a detail of your CNI configuration: Kubelet probes originate from the node network and not the pod network. Linkerd isn't factoring into this choice of IP address. We're working out how to improve this experience for authorizing probes, tracked by #7050

**Comment by adleong** [comment] 2022-01-04 17:35
Duplicate of #7050

**Closed by adleong** 2022-01-04 17:35 UTC
