### ISSUE TITLE
Update the SMI TrafficSplit  API version to v1alpha2

### ISSUE THREAD

**Issue by stefanprodan** [linkerd/linkerd2#3950] opened 2020-01-18 16:10 UTC
In the TrafficSplit v1alpha2 the weight type was changed from `resource.Quantity` to `int` see https://github.com/deislabs/smi-sdk-go/pull/24. 

Linkerd should use the v1alpha2 API internally and the Helm chart and install YAMLs should deploy the v1alpha2 CRD.

**Comment by adleong** [comment] 2020-02-12 18:07
This is complicated because of two important goals that we should maintain for Linkerd upgrades:

* Upgrading Linkerd should incur no Linkerd downtime
* Upgrading Linkerd should not unexpectedly change any traffic shifts

Additionally, Linkerd reads traffic split resources and takes action based on them, but it does not write or modify them in any way.

I think to do this properly, we need a two phase deprecation cycle.

In the first phase, Linkerd will need to include both a v1alpha1 client and a v1alpha2 client.  All traffic split read operations will be first attempted with the v1alpha2 client.  If that read fails because of a schema error (because the object is stored in the v1alpha1 format), the read is then attempted using the v1alpha1 client.  If this succeeds, Linkerd internally converts the v1alpha1 resource into a v1alpha2 resource for internal usage.  Note that it does **not** write the object back to Kubernetes at all and therefore does not convert the stored resource in any way.

Linkerd check will warn if any v1alpha1 traffic splits are present and advise that users should manually upgrade them to the v1alpha2 format.

In the second phase, Linkerd upgrade should ensure that no v1alpha1 traffic splits exist before proceeding.  After the upgrade, Linkerd should only use the v1alpha2 client.

**Comment by adleong** [comment] 2020-04-07 00:03
Duplicate of https://github.com/linkerd/linkerd2/issues/3962

**Closed by adleong** 2020-04-07 00:03 UTC
Labels: area/controller
