### ISSUE TITLE
Linkerd + gRPC returns 200 instead of error status when the gRPC status description is too long

### ISSUE THREAD

**Issue by alexklibisz** [linkerd/linkerd2#4227] opened 2020-04-02 18:21 UTC
### What is the issue?

I have a gRPC service implemented in scala using akka-grpc version 0.7.1.
The client I'm using is also implemented in scala using akka-grpc.
There's a specific rpc that should return an INVALID_ARGUMENT status with a description that's about 300 chars.
When I hit that rpc without any linkerd proxying, the status and description are fine.
But, when I introduce linkerd2 proxies in the service and client, the client throws an exception like: `io.grpc.StatusRuntimeException: UNKNOWN: HTTP status code 200`.
I found the only way to return the correct status is to truncate the description at 150 chars.. 180 chars works sometimes, but not consistently.

### How can it be reproduced?

I don't have an isolated repro.. you would have to implementa  scala/akka-grpc service and return a `Status.INVALID_ARGUMENT` with a description longer than 150 chars.

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
$ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
× control plane ClusterRoles exist
< error redacted >
```

^^ I don't think my user has permissions to list these resources in the last part.. I can come back to it if absolutely necessary.

### Environment

- Kubernetes Version: 1.15.7
- Cluster Environment: Kops on AWS
- Host OS: client and service pods are based on ubuntu 18.04
- Linkerd version: 2.6.0 installed on the cluster, but I've also injected proxy version stable-2.7.0 and see the same issue.

### Possible solution

What works for now is truncating the grpc status description to 150 chars. 

### Additional context

Original slack thread: https://linkerd.slack.com/archives/C89RTCWJF/p1585849987432200

**Comment by grampelberg** [comment] 2020-04-13 21:09
@alexklibisz would you happen to have a small replication setup we could run ourselves? That'll help out a ton for figuring out where the problem is occurring!

**Comment by olix0r** [comment] 2020-04-13 22:23
Are there any errors in the linkerd proxy pod's logs?

**Comment by olix0r** [comment] 2020-04-13 22:30
It looks like the error message comes from:

https://github.com/grpc/grpc-java/blob/c91e127f93f1a60e5625c8bb71c4e09f7858966b/core/src/main/java/io/grpc/internal/GrpcUtil.java#L269-L272

The odd thing about this is that gRPC response statuses are _always_ 200, so it seems as if the process is getting a response without gRPC metadata?

Before stable-2.7.0, Linkerd would not add grpc status when the proxy threw errors, but that was addressed in https://github.com/linkerd/linkerd2-proxy/commit/3567471f175e20698b8df65d504dc4a2445111c7 which was released as a part of `stable-2.7.0`.  But there should be errors in the proxy's logs if this is what you're seeing.

We've just released `stable-2.7.1` with additional fixes for some classes of spurious request timeout. I'd be curious what you see on this latest version.

**Comment by alexklibisz** [comment] 2020-04-17 01:21
@grampelberg I can try to set something up on minikube over the weekend.

@olix0r I'll try 2.7.0 or greater when I setup a repro.. we are also planning to upgrade cluster-wide in the next week or so.

**Comment by alexklibisz** [comment] 2020-04-25 15:06
Hey, sorry, still haven't had the time to look into this. It isn't a big
issue for us internally but I would like to get into it as it's an
interesting problem.

**Comment by olix0r** [comment] 2020-04-25 15:33
@alexklibisz Thanks for the update.

We recently received another issue related to gRPC error codes (https://github.com/linkerd/linkerd2/issues/4262#issuecomment-618738482) -- I'm not sure that this is the same issue being described here, but I'd be curious to have you test that fix when it is ready (hopefully for next week's Edge release).

**Comment by alexklibisz** [comment] 2020-05-19 03:01
It's been a while but this is still sitting in my inbox/todo list so I haven't forgotten. 
Feel free to close if you need to tidy up.
The temporary fix is just working too well... :)

**Comment by steve-gray** [comment] 2020-09-09 03:51
We're still seeing this on the latest edge (our own service name is edge, but edge-7 here is our app). Note the GRPC error it got back talking to other services. In terms of diagnostics is very painful, as we lose information passed between services when linkerd is in the mix.

```
edge-7fbdfb68c8-7gwld edge edge-7fbdfb68c8-7gwld{"error":"rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field","level":"error","msg":"service_call_failed","operation":"get_event","process":{"host":"edge-7fbdfb68c8-7gwld","name":"edge","runtime":4985.396622537,"version":"1"},"time":"2020-09-08T08:21:07Z"}
 linkerd-proxy [  4985.29219347s]  WARN ThreadId(06) outbound:accept{peer.addr=10.202.167.190:49128}:source{target.addr=172.20.23.57:50051}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
edge-7fbdfb68c8-7gwld edge {"error":"rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field","level":"error","msg":"service_call_failed","operation":"ingest_delta","process":{"host":"edge-7fbdfb68c8-7gwld","name":"edge","runtime":4985.528984901,"version":"1"},"time":"2020-09-08T08:21:07Z"}
edge-7fbdfb68c8-7gwld linkerd-proxy [  4985.161562870s]  WARN ThreadId(06) outbound:accept{peer.addr=10.202.167.190:34128}:source{target.addr=172.20.82.1:50051}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
edge-7fbdfb68c8-7gwld edge {"error":"rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field","level":"error","msg":"service_call_failed","operation":"get_event","process":{"host":"edge-7fbdfb68c8-7gwld","name":"edge","runtime":4985.775839788,"version":"1"},"time":"2020-09-08T08:21:08Z"}
```

linkerd version:
```
Client version: edge-20.9.1
Server version: edge-20.9.1
```

linkerd check
```
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-identity-data-plane
---------------------------
√ data plane proxies certificate match CA

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
```

**Comment by steve-gray** [comment] 2020-09-09 23:10
If it helps, it *seems* like during service startup we get a storm of these messages - but they die off gradually. It's as if during startup/discovery phase for A > B routing potentially the proxy is trying to signal back something, as I'm not entirely sure these are manifesting in response to a server side error - We've checked a bunch of stuff and we can't narrow down what did that on the server side.

**Comment by alexklibisz** [comment] 2020-09-09 23:52
In our case it was definitely just server side errors. We aren't doing any
service discovery. Also I still haven't had time to produce a repro.
Truncating the error message is still working. In our case we do this in an
akka exception handler directive.

**Comment by olix0r** [comment] 2020-09-14 21:40
Thanks @alexklibisz -- I think we have enough to repro your issue.

@steve-gray I'm curious if you can share more details about how your request is formed. Specifically, we detect the GRPC-ness of requests by matching the `content-type` header. When the value begins with `application/grpc`, we treat the stream as gRPC; and otherwise it is handled as plain-old HTTP. You can get these details by adding the annotation `config.linkerd.io/proxy-log-level: linkerd2_proxy_http=debug,linkerd=info,warn`

**Comment by AdallomRoy** [comment] 2020-10-09 06:41
We are also experiencing this with 2.8.1-stable.
I am not sure if the root cause is a too long description, but this definitely started happening since we've added linkerd to our cluster.

**Comment by AdallomRoy** [comment] 2020-10-09 11:37
Some more info -> This happens when the server pod being proxied crashes with panic, for some reason, the client receives an illegal grpc response from the server proxy.
In the server pod with the crash, the proxy prints errors like this for a few moments, until the server container resurrects (ip addresses removed):
`│ [  9485.187890323s]  WARN inbound:accept{peer.addr=XXX:51086}:source{target.addr=XXX:3000}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast                                                                                                                                        ││ [  9485.187925730s]  WARN inbound:accept{peer.addr=XXX:36826}:source{target.addr=XXX:3000}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast                                                                                                                                        ││ [  9485.188294279s]  WARN inbound:accept{peer.addr=XXX:36826}:source{target.addr=XXX:3000}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast                                                                                                                                        ││ [  9485.188348083s]  WARN inbound:accept{peer.addr=XXX:43224}:source{target.addr=XXX:3000}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast                                                                                                                                        │`

**Comment by cpretzer** [comment] 2021-01-11 22:18
@AdallomRoy have you been able to determine what the illegal gRPC response is from the proxy? It sounds like the server container is restarting when the `fail fast` messages are displayed in the log, is that right?

I'm also curious to know if this error occurs with Linkerd 2.9.1, which is the latest stable version. Have you had a chance to test with 2.9.1?

**Closed** 2021-06-04 18:59 UTC
Labels: area/proxy, needs/repro, wontfix
