### ISSUE TITLE
destination controller panics during shutdown

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2553] opened 2019-03-24 21:01 UTC
Running an AKS cluster, I noticed one of my controller instances in crashloopbackoff; and it appears that during shutdown the controller just panics:
```
:; kubectl logs linkerd-controller-695dcbdcf7-9bsvp  -c destination -n linkerd
time="2019-03-24T20:54:37Z" level=info msg="running version edge-19.3.3"
time="2019-03-24T20:54:37Z" level=info msg="Built k8s name resolver"
time="2019-03-24T20:54:37Z" level=info msg="waiting for caches to sync"
time="2019-03-24T20:54:37Z" level=info msg="caches synced"
time="2019-03-24T20:54:37Z" level=info msg="starting admin server on :9996"
time="2019-03-24T20:54:37Z" level=info msg="starting gRPC server on :8086"
time="2019-03-24T20:54:37Z" level=info msg="Establishing watch on endpoint linkerd-prometheus.linkerd:9090" component=endpoints-watcher
time="2019-03-24T20:54:37Z" level=info msg="Establishing watch on endpoint linkerd-grafana.linkerd:3000" component=endpoints-watcher
time="2019-03-24T20:54:37Z" level=info msg="Establishing watch on endpoint emoji-svc.emojivoto:8080" component=endpoints-watcher
time="2019-03-24T20:54:37Z" level=info msg="Establishing watch on endpoint linkerd-controller-api.linkerd:8085" component=endpoints-watcher
time="2019-03-24T20:54:37Z" level=info msg="Establishing watch on endpoint voting-svc.emojivoto:8080" component=endpoints-watcher
time="2019-03-24T20:55:16Z" level=info msg="shutting down gRPC server on :8086"
panic: close of closed channel

goroutine 147 [running]:
github.com/linkerd/linkerd2/controller/api/destination.(*profileListener).Stop(0xc0009f94c0)
	/go/src/github.com/linkerd/linkerd2/controller/api/destination/profile_listener.go:39 +0x2f
github.com/linkerd/linkerd2/controller/api/destination.(*fallbackChildListener).Stop(0xc000572790)
	/go/src/github.com/linkerd/linkerd2/controller/api/destination/fallback_profile_listener.go:65 +0x37
github.com/linkerd/linkerd2/controller/api/destination.(*profileEntry).unsubscribeAll(0xc000b9c090)
	/go/src/github.com/linkerd/linkerd2/controller/api/destination/profile_watcher.go:192 +0xa6
github.com/linkerd/linkerd2/controller/api/destination.(*profileWatcher).stop(0xc0007a69c0)
	/go/src/github.com/linkerd/linkerd2/controller/api/destination/profile_watcher.go:57 +0xd2
github.com/linkerd/linkerd2/controller/api/destination.(*k8sResolver).stop(0xc0007a69f0)
	/go/src/github.com/linkerd/linkerd2/controller/api/destination/k8s_resolver.go:125 +0x41
github.com/linkerd/linkerd2/controller/api/destination.NewServer.func1(0xc00068d4a0, 0x1636a20, 0xc0007a69f0)
	/go/src/github.com/linkerd/linkerd2/controller/api/destination/server.go:74 +0x48
created by github.com/linkerd/linkerd2/controller/api/destination.NewServer
	/go/src/github.com/linkerd/linkerd2/controller/api/destination/server.go:72 +0x39
```

**Comment by tammert** [comment] 2019-05-28 19:26
I'd like to give this a go! Would you assign it to me?

**Comment by tammert** [comment] 2019-05-30 09:25
Thanks @olix0r! It was a little harder than I thought, but fun nonetheless :). PR is ready for review, with some notes that you guys might want to follow up on.

**Comment by mayankshah1607** [comment] 2020-02-28 12:53
@ihcsim @adleong  looks like this is very similar to https://github.com/linkerd/linkerd2/pull/4007
If this is not being worked on, I'd love to take up this one! :)

**Comment by ihcsim** [comment] 2020-02-28 17:18
@mayankshah1607 Go for it!

**Comment by tammert** [comment] 2020-02-28 20:06
Just a heads up: I'm pretty sure this bug should have been closed after the refactorings that are mentioned in my non-merged PR #2867.

Unless the bug was reintroduced of course, but if you can't reproduce it quickly I wouldn't spend too much time on it :-)

**Comment by mayankshah1607** [comment] 2020-03-03 13:22
@tammert you're right. The portion of the code that causes this routine to crash has been refactored/moved. Unless this issue can be reproduced again, it doesn't seem like it should be pursued. 
@ihcsim Should this be marked as closed?

**Comment by ihcsim** [comment] 2020-03-03 17:44
@mayankshah1607 Yup, looks like this is fixed. This is the log I see after sending a `kill -15` to the `destination` container.

```
...
time="2020-03-03T17:39:10Z" level=info msg="Stopping watch on profile linkerd/linkerd-dst" addr=":8086" component=traffic-split-watcher
time="2020-03-03T17:40:44Z" level=info msg="shutting down gRPC server on :8086"

☁  kubectl -n linkerd logs -f linkerd-destination-74bdc4d9fc-qrhrf destination                            
time="2020-03-03T17:41:14Z" level=info msg="running version edge-20.2.3"
time="2020-03-03T17:41:14Z" level=info msg="waiting for caches to sync"
time="2020-03-03T17:41:14Z" level=info msg="caches synced"
time="2020-03-03T17:41:14Z" level=info msg="starting admin server on :9996"
time="2020-03-03T17:41:14Z" level=info msg="starting gRPC server on :8086"
```

**Closed by ihcsim** 2020-03-03 17:44 UTC
Labels: area/controller, good first issue
