### ISSUE TITLE
Upgrade command seems to have incorrect Grafana image

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#5014] opened 2020-09-27 19:44 UTC
Upgrade command has incorrect repo for grafana image. 

```
(main) | bin/linkerd install --ignore-cluster | grep  "linkerd/grafana"
        image: ghcr.io/linkerd/grafana:git-e8f0724a
```

```
 bin/linkerd upgrade  | grep  "linkerd-io/grafana"
        image: gcr.io/linkerd-io/grafana:git-e8f0724a
```

**Comment by Pothulapati** [comment] 2020-09-28 10:36
@zaharidichev This should only happen when you perform an upgrade to the latest edges from the stable `2.9.1`. I can confirm that this is not the case in the latest edges.

 This is because,  `grafana.image.name` was included in the `linkerd-config-addons` which is the overrides, and hence the new `ghcr.io/*` gets overridden by the `gcr.io/*` stored in the CM.

This is fixed in the edges, by moving `grafana.image.name` into the default fields, and thus making the overrides not contain any fields other than `enabled` (unless overridden)

To facilitate upgrades from `2.9.1` to `2.10`. we should either have the CLI do it for them before the release or documentation showing steps on removing that field from the CM before the release.

cc: @alpeb

**Comment by alpeb** [comment] 2020-09-28 17:28
Everybody upgrading is gonna fall into this trap, so IMO we should address it in the code. Similar to what we did once with `repairConfigs()` in `upgrade.go`.

**Closed** 2020-10-13 20:12 UTC
Labels: priority/P0
