### ISSUE TITLE
Evaluate actions/checkout@v2

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#3881] opened 2020-01-02 23:32 UTC
Per https://github.com/actions/checkout/issues/27#issuecomment-570397019, our incorrect SHA issue may be resolved in `actions/checkout@v2`. We should test this, and if it works, we can roll back our workaround in #3602.

**Comment by alpeb** [comment] 2020-01-07 16:41
@siggy It appears github is merging the PR branch into master using the same master SHA across all jobs, that is the master HEAD at the moment the build was triggered regardless of it changing across jobs, thus fixing the issue :+1: 
This happens before, and is independent of the `actions/checkout` update. I couldn't reproduce the issue using `actions/checkout@v1`.

I used [this test](https://github.com/alpeb/linkerd2/blob/15db70a59272d55481cb1d89241627cc0c96ac7a/.github/workflows/workflow.yml), based off of [your test](https://github.com/siggy/linkerd2/blob/a2583cac37a6c958dfc9bf5ae2075e6af7c1cf0b/.github/workflows/workflow.yml) with some simplifications, pushing something to master during the 1 minute sleep, and still seeing the same merged ref being used before and after the sleep:
https://github.com/alpeb/linkerd2/commit/15db70a59272d55481cb1d89241627cc0c96ac7a/checks?check_suite_id=388305569

**Comment by siggy** [comment] 2020-01-07 17:50
@alpeb Thanks for digging in. FWIW, I also was not able to reliably reproduce the issue with the contrived example above:
https://github.com/actions/checkout/issues/27#issuecomment-531000315
...and those observations occurred when we were definitely experiencing the issue in ci. It may be that our more complex ci workflow with lots of jobs and tasks, somehow causes the issue to manifest more reliably.

I think it's still worth rolling out `actions/checkout@v2` on our full ci workflow. If the issue returns we can also roll back to our bespoke checkout code.

**Closed** 2020-01-08 22:57 UTC
Labels: area/build, area/test
