### ISSUE TITLE
Seeing "profile stream failed" warnings in proxy logs

### ISSUE THREAD

**Issue by bourquep** [linkerd/linkerd2#2320] opened 2019-02-18 21:15 UTC
### What is the issue?

I was seeing quite a few `WARN linkerd2_proxy::app::profiles profile stream failed: Grpc(Status { code: Internal })` proxy log entries across my pods. It does not seem to have a negative impact on my services

### How can it be reproduced?

Don't know

### Logs, error output, etc

`WARN linkerd2_proxy::app::profiles profile stream failed: Grpc(Status { code: Internal })`

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ can query the control plane API
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus

linkerd-service-profile
-----------------------
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.11.5
- Cluster Environment: AKS
- Host OS: 🤷‍♂️
- Linkerd version: stable-2.2.0

### Additional context

This morning, I saw quite a few of these warnings in the previous 12-hour logs, across most of my injected deployments. However, nothing else seemed to indicate that my system was not behaving as expected.

Now, 8 hours later as I file this issue, I checked to see how much of those warnings had been logged during the day, but there are none. I did not do anything special to make them go away (i.e. I did not restart the control plane, I did not restart my deployments, etc).

I am not too worried about it, but would like to understand what this warning means, in case it is a symptom of something that is failing deep down.

**Comment by klingerf** [comment] 2019-02-18 22:37
@bourquep Thanks for reporting this. Can you also paste the logs from the `proxy-api` container, next time you see those warning in any of your `linkerd-proxy` containers? `linkerd logs -c proxy-api` should do the trick.

**Comment by bourquep** [comment] 2019-02-18 23:35
@klingerf The only logs I see from this container for the past 24 hours are a few `Establishing watch on endpoint xyz` entries, not many.

**Comment by klingerf** [comment] 2019-02-18 23:36
Hmm, ok, that's good to know too, thanks.

**Comment by bourquep** [comment] 2019-02-19 20:19
So now, I have a public-facing service (api-v3) that is unable to communicate with other in-cluster services via gRpc. The proxy logs from that pod are:

```
2019-02-17T01:17:31.693747389Z INFO linkerd2_proxy::app::main using controller at Some(Name(NameAddr { name: "linkerd-proxy-api.linkerd.svc.cluster.local", port: 8086 }))
2019-02-17T01:17:31.693784789Z INFO linkerd2_proxy::app::main routing on V4(127.0.0.1:4140)
2019-02-17T01:17:31.693791089Z INFO linkerd2_proxy::app::main proxying on V4(0.0.0.0:4143) to None
2019-02-17T01:17:31.693795189Z INFO linkerd2_proxy::app::main serving Prometheus metrics on V4(0.0.0.0:4191)
2019-02-17T01:17:31.693798889Z INFO linkerd2_proxy::app::main protocol detection disabled for inbound ports {25, 3306}
2019-02-17T01:17:31.693802889Z INFO linkerd2_proxy::app::main protocol detection disabled for outbound ports {25, 3306}
2019-02-17T16:48:44.40973951Z WARN admin={bg=resolver} linkerd2_proxy::control::destination::background::destination_set Destination.Get stream errored for NameAddr { name: "contents.studyo-beta.svc.cluster.local.", port: 5000 }: Grpc(Status { code: Unknown, message: "grpc-status header missing, mapped from HTTP status code 500" })
2019-02-17T16:48:44.427472729Z WARN linkerd-proxy-api.linkerd.svc.cluster.local:8086 linkerd2_proxy::proxy::reconnect connect error to Config { addr: Name(NameAddr { name: "linkerd-proxy-api.linkerd.svc.cluster.local", port: 8086 }), tls_server_identity: None(Disabled), tls_config: None(Disabled) }: Connection refused (os error 111) (address: 10.0.208.33:8086)
2019-02-17T16:48:47.395795919Z WARN admin={bg=resolver} linkerd2_proxy::control::destination::background::destination_set Destination.Get stream errored for NameAddr { name: "generator.studyo-beta.svc.cluster.local.", port: 5000 }: Inner(Upstream(Inner(Inner(Timeout(3s)))))
2019-02-17T16:48:47.395830019Z WARN admin={bg=resolver} linkerd2_proxy::control::destination::background::destination_set Destination.Get stream errored for NameAddr { name: "subscriptions.studyo-beta.svc.cluster.local.", port: 5000 }: Inner(Upstream(Inner(Inner(Timeout(3s)))))
2019-02-17T16:48:47.395837419Z WARN admin={bg=resolver} linkerd2_proxy::control::destination::background::destination_set Destination.Get stream errored for NameAddr { name: "auth.studyo-beta.svc.cluster.local.", port: 5000 }: Inner(Upstream(Inner(Inner(Timeout(3s)))))
2019-02-17T16:48:47.395842819Z WARN admin={bg=resolver} linkerd2_proxy::control::destination::background::destination_set Destination.Get stream errored for NameAddr { name: "schools.studyo-beta.svc.cluster.local.", port: 5000 }: Inner(Upstream(Inner(Inner(Timeout(3s)))))
2019-02-17T16:49:14.419632794Z WARN linkerd2_proxy::app::profiles profile stream failed: Grpc(Status { code: Internal })
2019-02-17T16:49:14.419665894Z WARN linkerd2_proxy::app::profiles profile stream failed: Grpc(Status { code: Internal })
2019-02-17T16:49:14.419672294Z WARN linkerd2_proxy::app::profiles profile stream failed: Grpc(Status { code: Internal })
2019-02-17T16:49:14.419676894Z WARN linkerd2_proxy::app::profiles profile stream failed: Grpc(Status { code: Internal })
2019-02-17T16:49:14.419680894Z WARN linkerd2_proxy::app::profiles profile stream failed: Grpc(Status { code: Internal })
2019-02-17T16:49:14.419684694Z WARN linkerd2_proxy::app::profiles profile stream failed: Grpc(Status { code: Internal })
2019-02-17T18:37:56.270801926Z WARN admin={bg=resolver} linkerd2_proxy::control::destination::background::destination_set Destination.Get stream errored for NameAddr { name: "generator.studyo-beta.svc.cluster.local.", port: 5000 }: Grpc(Status { code: Internal })
2019-02-17T18:37:56.270840026Z WARN linkerd2_proxy::app::profiles profile stream failed: Grpc(Status { code: Internal })
2019-02-17T18:37:56.270846526Z WARN linkerd2_proxy::app::profiles profile stream failed: Grpc(Status { code: Internal })
2019-02-17T18:37:56.270850226Z WARN admin={bg=resolver} linkerd2_proxy::control::destination::background::destination_set Destination.Get stream errored for NameAddr { name: "subscriptions.studyo-beta.svc.cluster.local.", port: 5000 }: Grpc(Status { code: Internal })
2019-02-17T18:37:56.270854726Z WARN admin={bg=resolver} linkerd2_proxy::control::destination::background::destination_set Destination.Get stream errored for NameAddr { name: "auth.studyo-beta.svc.cluster.local.", port: 5000 }: Grpc(Status { code: Internal })
2019-02-17T18:37:56.270882026Z WARN admin={bg=resolver} linkerd2_proxy::control::destination::background::destination_set Destination.Get stream errored for NameAddr { name: "schools.studyo-beta.svc.cluster.local.", port: 5000 }: Grpc(Status { code: Internal })
2019-02-17T18:37:56.271173627Z WARN admin={bg=resolver} linkerd2_proxy::control::destination::background::destination_set Destination.Get stream errored for NameAddr { name: "contents.studyo-beta.svc.cluster.local.", port: 5000 }: Grpc(Status { code: Internal })
2019-02-18T12:44:02.438382369Z WARN linkerd2_proxy::app::profiles profile stream failed: Grpc(Status { code: Internal })
2019-02-18T12:44:04.583336903Z WARN linkerd2_proxy::app::profiles profile stream failed: Grpc(Status { code: Internal })
2019-02-18T12:44:05.794252891Z WARN linkerd2_proxy::app::profiles profile stream failed: Grpc(Status { code: Internal })
2019-02-18T12:44:05.944295775Z WARN linkerd2_proxy::app::profiles profile stream failed: Grpc(Status { code: Internal })
```

Observations:
* None of the destination pods have been restarted recently.
* The control plane has not been restarted, all pods are healthy with a 0 restart count
* Communications started failing a few hours ago, everything was fine this morning and yesterday
* What did change in my environment is that I deployed 2 service profile resources for 2 other services (which aren't even involved in the current failing comms)
* The `proxy-api` logs show a few "Establishing/stopping watch on endpoint xyz"
  * But they also show a bucketload of `failed to parse duration for route` errors, which are related to the routes defined in the recently-introduced service profiles (see above). But it seems like those errors are safe to ignore (See #2276)

**Comment by bourquep** [comment] 2019-02-19 20:34
I had to delete the 2 service profiles, then restart the control plane, in order to bring everything back to a working state.

**Comment by bourquep** [comment] 2019-02-19 20:45
Additional observation: After restarting the failing pod (api-v3), but before deleting the service profiles and restarting the CP, the `linkerd-proxy` logs for the restarted pod spewed an endless bunch of:

`WARN linkerd2_proxy::app::profiles error fetching profile for XYX`

Where `XYZ` is most of my other services defined in my cluster, for which I did not create service profiles.

**Comment by bourquep** [comment] 2019-02-20 13:42
This morning, looking at the `linkerd-proxy` container logs from all my pods, I see that at some point proxies from most pods started spewing these:

```
WARN linkerd2_proxy::app::profiles profile stream failed: Grpc(Status { code: Unknown, message: "grpc-status header missing, mapped from HTTP status code 500" })

WARN linkerd-proxy-api.linkerd.svc.cluster.local:8086 linkerd2_proxy::proxy::reconnect connect error to Config { addr: Name(NameAddr { name: "linkerd-proxy-api.linkerd.svc.cluster.local", port: 8086 }), tls_server_identity: None(Disabled), tls_config: None(Disabled) }: Connection timed out (os error 110) (address: 10.0.208.33:8086) 

WARN admin={bg=resolver} linkerd2_proxy::control::destination::background::destination_set Destination.Get stream errored for NameAddr { name: "rest-api.studyo-prod.svc.cluster.local.", port: 5000 }: Grpc(Status { code: Internal }) 
```

With the last one (destination_set) being by far the most frequent, 10k occurrences in the last 6 hours.

The `proxy-api` logs still show a ton of `failed to parse duration for route` errors, which can be ignored, but nothing else except the usual "establishing watch" info messages.

I realize now that I had forgotten to delete 2 service profile definitions from a test namespace when I restarted the CP (see 2 comments above). I am deleting them now, and confirm that I have no service profiles at all by running `get serviceprofile --all-namespaces`. I am restarting the CP, will follow-up later.

**Comment by grampelberg** [comment] 2019-02-20 16:27
This really sounds like https://github.com/Azure/AKS/issues/790. Have you tried rolling the tunnel instead of restarting the control plane yet?

**Comment by bourquep** [comment] 2019-02-20 16:29
Not in the current scenario, no. I'll give it a shot next time.

**Comment by bourquep** [comment] 2019-02-21 14:02
24 hours later, after deleting all of my service profiles in all namespaces and restarting the CP, the proxy logs have been pretty quiet.

**Comment by gamer22026** [comment] 2019-02-21 19:03
Same issue for me (* stable-2.2.0) Not on Azure/AKS. Same fix (delete all serviceprofiles, restart CP).

**Comment by hawkw** [comment] 2019-03-01 00:17
Hi @bourquep and @gamer22026, we've recently merged a PR (#202) that should improve the error messages for those gRPC errors.  If you're able to upgrade to edge-19.2.5, the improved error messages will hopefully help us to track down where the problem is coming from!

> **Side note**, I was getting this `2019-02-21T18:52:34.29278738Z WARN linkerd2_proxy::app::profiles profile stream failed: Grpc(Status { code: Unknown, message: "grpc-status header missing, mapped from HTTP status code 500" })` on all linkerd-proxy logs, even services that are are not using gRPC.

@gamer22026 Yeah, the proxy uses gRPC internally for talking to the control plane, so seeing gRPC error messages in the logs for services that aren't using gRPC themselves is not _too_ surprising...

**Comment by bourquep** [comment] 2019-03-01 12:49
@hawkw Will upgrade this weekend!

**Comment by jon-walton** [comment] 2019-03-05 03:24
@grampelberg I'm not so sure about Azure/AKS#790 I was seeing this on an AKS-Engine cluster (aks-engine doesn't use the tunnel component).

I'll upgrade to edge now and try to reproduce

**Comment by bourquep** [comment] 2019-03-05 14:10
I've just upgraded to `edge-19.2.5`, will monitor the proxy logs today. Once I confirm that all seems good, I'll redeploy my service profiles and see what happens.

**Comment by hawkw** [comment] 2019-03-05 18:40
@bourquep thanks, Pascal! Please let me know if anything goes wrong!

**Comment by siggy** [comment] 2019-03-18 21:28
@bourquep any update?

**Comment by bourquep** [comment] 2019-03-19 18:05
Sorry, haven't tried re-deploying my service profiles yet.

**Comment by hawkw** [comment] 2019-03-22 23:20
Hi @borquep, if you're able, we'd really like to know if this issue still exists for you on today's edge (`edge-19.3.3`). This is currently a release blocker for `stable-2.3`, but since we haven't been able to reproduce it, we can't verify whether or not this bug has been fixed --- there have certainly been some recent changes to the subsystems that might be _involved_ in this issue.

**Comment by bourquep** [comment] 2019-03-26 13:05
@hawkw Sorry about that, I'll try to test this today!

**Comment by hawkw** [comment] 2019-04-10 23:20
Hi @bourquep, any updates?

**Comment by olix0r** [comment] 2019-04-11 22:56
We've stopped receiving other reports like this since updating the profiles client, so I'm closing this. Please reopen if you see it again, though!

**Closed by olix0r** 2019-04-11 22:56 UTC
Labels: area/profiles, bug, priority/P0
