### ISSUE TITLE
flaky integration test: TestCliTap timeout

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#1227] opened 2018-06-28 21:39 UTC
Integration tests failed in CI: https://travis-ci.org/runconduit/conduit/jobs/397919327

```
--- FAIL: TestCliTap (95.16s)
    --- PASS: TestCliTap/tap_a_deployment (18.07s)
    --- PASS: TestCliTap/tap_a_service_call (3.99s)
    --- FAIL: TestCliTap/tap_a_pod (60.51s)
        tap_test.go:137: cmd [/home/travis/gopath/src/github.com/runconduit/conduit/conduit tap pod/t3-6768bd8c64-q7wdn --namespace conduit-git-9f274526-tap-test --conduit-namespace conduit-git-9f274526] Timed out trying to read 10 lines
```

Succeeded on subsequent run.

**Comment by hawkw** [comment] 2018-06-29 17:59
This seems like it could potentially be a `h2` bug --- would love to hear what @carllerche thinks.

**Comment by carllerche** [comment] 2018-07-03 18:28
Either there is a bug or the assertion is invalid.

Is there a repro for this?

**Comment by klingerf** [comment] 2018-07-03 21:24
@carllerche I unfortunately don't have a great repo yet. It happens occasionally when running the integration tests. If I see it again I can ping you to see what additional info might be helpful.

**Comment by hawkw** [comment] 2018-07-06 21:02
I'm attempting to reproduce this and hopefully get more logs out of the proxy that's hitting the assertion. Hopefully that will let us narrow down what's causing it to be hit.

**Comment by hawkw** [comment] 2018-07-06 23:52
I've been running `TestCliTap` with an unoptimized proxy constantly for over 2 hours in an attempt to repro this, and I haven't seen it yet --- it seems to be very intermittent.

**Comment by klingerf** [comment] 2018-08-03 22:47
I saw this tap test failure again today. It looks like the tap container panicked and restarted while the tap test was running. Here are the logs from the tap container:

```
2018-08-03T22:40:02.129190374Z time="2018-08-03T22:40:02Z" level=info msg="Tapping 1 pods for target: {Namespace:unreleased-tap-test Type:deployment Name:gateway}"
2018-08-03T22:40:02.129240828Z time="2018-08-03T22:40:02Z" level=info msg="Establishing tap on 172.17.0.34:4190"
2018-08-03T22:40:03.071961414Z panic: send on closed channel
2018-08-03T22:40:03.072003801Z 
2018-08-03T22:40:03.072057408Z goroutine 269 [running]:
2018-08-03T22:40:03.072064959Z github.com/linkerd/linkerd2/controller/tap.(*server).tapProxy(0xc4202f2bf0, 0x14841e0, 0xc4206fe720, 0x3f800000, 0xc420890130, 0xc420b7d830, 0xb, 0xc4207034a0)
2018-08-03T22:40:03.072071029Z 	/go/src/github.com/linkerd/linkerd2/controller/tap/server.go:274 +0x3a9
2018-08-03T22:40:03.072077001Z created by github.com/linkerd/linkerd2/controller/tap.(*server).TapByResource
2018-08-03T22:40:03.072082985Z 	/go/src/github.com/linkerd/linkerd2/controller/tap/server.go:90 +0x50b
```

And here are the logs from the linkerd-proxy container in the same time range:

```
2018-08-03T22:40:03.08215208Z ERR! proxy={server=out listen=127.0.0.1:4140 remote=172.17.0.9:47534} linkerd2_proxy::transparency::tcp tcp duplex error: Transport endpoint is not connected (os error 107)
2018-08-03T22:40:03.958568006Z ERR! proxy={server=out listen=127.0.0.1:4140 remote=172.17.0.9:49618} linkerd2_proxy::transparency::tcp tcp duplex error: Transport endpoint is not connected (os error 107)
2018-08-03T22:40:03.958607334Z ERR! proxy={server=out listen=127.0.0.1:4140 remote=172.17.0.9:49608} linkerd2_proxy::transparency::tcp tcp duplex error: Transport endpoint is not connected (os error 107)
2018-08-03T22:40:03.959649138Z ERR! proxy={server=out listen=127.0.0.1:4140 remote=172.17.0.9:49610} linkerd2_proxy::transparency::tcp tcp duplex error: Broken pipe (os error 32)
2018-08-03T22:40:03.975793716Z ERR! proxy={server=out listen=127.0.0.1:4140 remote=172.17.0.9:49612} linkerd2_proxy::transparency::tcp tcp duplex error: Transport endpoint is not connected (os error 107)
```

**Comment by klingerf** [comment] 2018-10-30 23:29
Haven't seen any new occurrences of this test failure in a few months, so I'm going to close it, but we can reopen if it pops back up again.

**Closed by klingerf** 2018-10-30 23:29 UTC
Labels: area/test
