### ISSUE TITLE
proxy fails inbound requests when --ha control plane is degraded

### ISSUE THREAD

**Issue by listenerme** [linkerd/linkerd2#4624] opened 2020-06-18 00:41 UTC
### What is the issue?

Randomly resulted in "503" error on linkerd-proxy associated with application containers

### How can it be reproduced?
Its not everytime, happens during node shutdown or cluster upgrade..evicted pods are created in another node, will have (1/2) in READY status. Same applies for linkerd containers too(whose linkerd-proxy failed with 503 error itself"

linkerd-controller-64cf8696f7-d79tx        1/2     Running   1          26m
linkerd-destination-57847f975b-8sj7v       1/2     Running   0          26m
linkerd-proxy-injector-5689db6474-mzxjg    1/2     Running   1          19m
linkerd-sp-validator-84d86bf697-w5746      1/2     Running   1          26m
linkerd-tap-799498f9f8-kqzcv               1/2     Running   1          26m

### Logs, error output, etc

  Warning  Unhealthy         2m58s                 kubelet, aks-devpool-XXXXXXX-vmss000000  Readiness probe failed: Get http://10.X.X.101:4191/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy         29s (x15 over 2m49s)  kubelet, aks-devpool-XXXXXXX-vmss000000  Readiness probe failed: HTTP probe failed with statuscode: 503

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version:
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS:
- Linkerd version:

**Comment by cpretzer** [comment] 2020-06-18 01:06
hi @listenerme we're going to need quite a bit more information to get to the bottom of this issue.

The first thing that will help is the output from the `linkerd check` command.

Can you tell me more about the environment where you're running Linkerd?
- What version of kubernetes are you using?

From the bit of logs that you shared, it looks like more than just Linkerd is unhealthy. Specifically, the `kubelet` appears to be unhealthy because the readiness probe has failed. Do you have any logs from the kubelet? What is the status of all the pods in the `kube-system` namespace?

You mention that `Its not everytime, happens during node shutdown or cluster upgrade`. What is triggering this shutdown/upgrade?

Have you installed Linkerd with the `--ha` flag? That will ensure that additional replicas of the control plane are running during node maintenance.

Please tell me more about the application containers. What protocols are they using?

I'd also like to take a look at the YAML files that you have to validate their configuration.

One last thing that will help is the output from the Linkerd proxy logs with the 503 errors. Can you use the `kubect logs` command to get that output and put it in a gist if it's too large?

**Comment by listenerme** [comment] 2020-06-18 10:37
AKS environment, K8s version: 1.15.11

a) Disruption can be triggered by the daily shutdown of one node at night
b) Rebooting for security packages or kernel update
c) AKS upgrade
d) Node drain(here in this case, for HA testing)

`linkerd check` will never work unless all pods are scheduled successfully. We cant rely on this as this is HA testing, we cant have all control plane pods online.

Currently its happening during the HA testing... scenario... Where I have 3 node cluster with --ha option(exactly helm values-ha.yaml) and  I have drained two nodes to see linkerd is working fine. Then it turned out to be a "big NO". 


1) Two replicas of linkerd control plane components unschedulable(expected behavior)
2) Other replica should work fine and should serve the linkerd API, but its not working... I was getting 1/2 ready status for all linkerd control plane components with 503. Kubelet of the node where control plane components were online

**Then I turned on more nodes(ie: two nodes are on now)**
3) 503 error vanished from the logs as the control plane components created on other nodes, however first replica linkerd contolplane ready status remains the same(1/2). Though no error, application created too having a ready status of (1/2). 
4) Restarting the control plane is not an option as its a manual activity
5) Created a new pod with namespace annotation on, that too created with 1/2 


$ kubectl get pods
NAME                       READY   STATUS    RESTARTS   AGE
siz-5bbf67fdf-t85rg        1/2     Running   0          9h

**$ kubectl logs siz-5bbf67fdf-t85rg  -c linkerd-proxy**
time="2020-06-18T00:28:52Z" level=info msg="running version stable-2.8.0"
[     0.7478972s]  INFO linkerd2_proxy: Admin interface on 0.0.0.0:4191
[     0.7517472s]  INFO linkerd2_proxy: Inbound interface on 0.0.0.0:4143
[     0.7521072s]  INFO linkerd2_proxy: Outbound interface on 127.0.0.1:4140
[     0.7541072s]  INFO linkerd2_proxy: Tap interface on 0.0.0.0:4190
[     0.7543472s]  INFO linkerd2_proxy: Local identity is default.default.serviceaccount.identity.linkerd.cluster.local
[     0.7546472s]  INFO linkerd2_proxy: Identity verified via linkerd-identity.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.7549872s]  INFO linkerd2_proxy: Destinations resolved via linkerd-dst.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.8140470s]  INFO linkerd2_app_inbound: Serving listen.addr=0.0.0.0:4143

**$ kubectl logs siz-5bbf67fdf-t85rg  -c nginx**
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up

I am just using sample applications right now(like nginx , redis), thats is working fine. Here the issue is with linkerd-proxy. If it fails with 503 or readiness probe fails(current situtation), I am suspecting inbound and outbound connections will be affected, I am yet reached that point of application testing yet

**Comment by cpretzer** [comment] 2020-06-19 05:59
@listenerme Thanks for this detail, it's helpful.

If I'm reading this correctly, you've installed Linkerd in HA mode using helm.

There are three healthy nodes, each running replicas for the Linkerd control plane, all of which are 2/2 status before the nodes are drained.

When two of the nodes are drained and shut down, the healthy replicas on the third node go into a `1/2` state? That is unexpected behavior for sure.

When the control plane pods are in this state, can you send the output of `kubectl get po -n linkerd` from the third node?

I'm working to set up a cluster in AKS to try to reproduce this.

Have you customized `values-ha.yml`? 

Please also send the `helm install` command that is used to install Linkerd.

**Comment by listenerme** [comment] 2020-06-19 18:24
Yes, installed using helm3,

Due to the unavailability of 3rd node, I am using only 2 nodes(3 replicas), assuming that 3rd replica is already down when I start testing, other replicas are working fine. So two of the available replicas are 2/2 before the 2nd node is drained

I haven't customized values-ha.yaml for this setup, but customized some variables with --set command

When  two nodes are down, following is the get pods output. After the second node is back , 1/2 remains the same for all pods mentioned below.

linkerd-controller-64cf8696f7-d79tx        1/2     Running   1          41h
linkerd-destination-57847f975b-8sj7v       1/2     Running   0          41h
linkerd-grafana-75c8d56f96-64kfx           2/2     Running   0          41h
linkerd-prometheus-6d8f85b995-7sxjk        2/2     Running   0          41h
linkerd-proxy-injector-5689db6474-mzxjg    1/2     Running   1          41h
linkerd-sp-validator-84d86bf697-w5746      1/2     Running   1          41h
linkerd-tap-799498f9f8-kqzcv               1/2     Running   1          41h
linkerd-web-c9cb6bdb6-9ss6p                2/2     Running   2          41h

Helm command:

helm3  upgrade --install linkerd2 --namespace linkerd ./stable-2.8.0/linkerd2/values-ha.yaml --set-file global.identityTrustAnchorsPEM=./certs/ca.crt --set identity.issuer.scheme=kubernetes.io/tls --set global.proxy.resources.cpu.request=10m --set global.proxy.resources.cpu.limit=100m --set global.proxy.resources.memory.request=25Mi --set global.proxy.resources.memory.limit=250Mi  --set global.cniEnabled=true --set installNamespace=false ./stable-2.8.0/linkerd2

**Comment by cpretzer** [comment] 2020-06-22 22:00
Thanks @listenerme, this detail is helpful.

So, I'm not really surprised that requesting three replicas when only two nodes are available is resulting in undesired behavior. That being said, we still plan to set up an environment to test this out, that way we can get some definitive answers.

**Comment by listenerme** [comment] 2020-06-23 23:37
Thank you for the reply. High availability should atleast support 1 failure right? If that is the case, linkerd should work with two replicas too, thats my understanding. Not sure whether 1 replica is designed to work alone if request for three replicas(with values-ha.yaml)

**Comment by olix0r** [comment] 2020-06-24 00:58
@listenerme You're correct that Linkerd should continue to operate normally in a degraded state.

Especially, I would expect that pods that have are already running would continue to run normally without issue.

We could see some temporary issues as new pods are scheduled on the existing nodes (especially if control plane components are not healthy).

But it sounds like we have enough information to try to reproduce this ourselves and dig in further. I'm going to update the description so that it's clearer to us as we review issues (many of which can manifest as a 503).

Thanks for the helpful report!

**Comment by zaharidichev** [comment] 2020-06-30 08:33
@listenerme I have tried to replicate the issue on AKS. Here are the steps I took: 


1. Spin up a cluster on Azure (3 nodes)

2. linkerd install --ha | kubectl apply -f 

3. Apply following resources: 

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        linkerd.io/inject: enabled  
    spec:
      containers:
      - name: backend
        image: buoyantio/bb:v0.0.5
        args:
        - terminus
        - "--h1-server-port=8888"
        - "--response-text=hello"
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: default
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 8888
    targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: test
        image: scrapinghub/httpbin:latest
        command:
        - sleep
        - "3600"
```


4. Ssh into the test container and run: while true; do   curl -s -o /dev/null  -w "Status: %{http_code}\n" http://backend-svc:8888; sleep 1; done

6. Drain one of the nodes where linkerd is running and observe that the control plane gets into a degraded state

7. Make sure there are no error statuses

8. Uncordon the node and observe the control plane recovering.

I have not experienced any problems. While this was carried out the application was running and was healthy. One thing I noticed is that during one of my tests the backend service got unscheduled, so I started observing 503 errors. That was kind of expected though - the service was not running after all. 

If you can spot something obvious that I am missing or can put together some steps to reproduce all of that, it will be greatly appreaciated. Not, I have tried that on kind as well.

**Comment by Abrishges** [comment] 2020-07-01 00:02
@zaharidichev In step 5,  it look like you drained the nodes graceful and might not cause errors since Linkerd pods will be drain properly and they will be reschedule to new node.  To simulate a sudden node outage at least which happened to us, we used the following command in AKS
` Stop-AzVmss -ResourceGroupName rgname -VMScaleSetName vmssname -InstanceId id -Force -SkipShutdown -StayProvisioned`

**Comment by cpretzer** [comment] 2020-07-05 21:58
hi @listenerme and @Abrishges would you mind running your tests with the latest [edge](https://github.com/linkerd/linkerd2/releases/tag/edge-20.7.1)? @zaharidichev committed some updates that should address this

**Comment by zaharidichev** [comment] 2020-07-06 05:58
@cpretzer @listenerme @Abrishges I added some commits that would allow linkerd stat and other commands to proceed but this does not fix the initial problem that results in 503 errors... I am still working on that one

**Comment by cpretzer** [comment] 2020-07-06 17:12
Oops! I got excited and spoke too soon. Thanks for clarifying @zaharidichev

**Closed** 2020-10-22 04:28 UTC
Labels: area/ha, wontfix
