### ISSUE TITLE
502: Bad Gateway error due to linkerd-proxy 'Bad certificate' TLS error

### ISSUE THREAD

**Issue by sagilson** [linkerd/linkerd2#5350] opened 2020-12-08 22:53 UTC
### What is the issue?
We have a kubernetes cluster that uses linkerd to encrypt traffic between pods using the linkerd-proxy. We also have a nginx container within our deployment that handles routing traffic. When we deploy our our service on the kubernetes cluster, there are no issues for a seemingly random amount of time (anywhere between 1hr to 1 week). The nginx container is constantly routing our health check pings to our service to make sure it is up and healthy, but will start failing suddenly, as shown in the following gist:
https://gist.github.com/sagilson/c8c8a8c6be460f94707f681ec84a58d4

Checking the logs on the linkerd-proxy containers in each of our pods, we start simultaneously seeing the following error:
https://gist.github.com/sagilson/1b18836ced0d165fcf41c500f9cab096

In order to install linkerd on our cluster, we use helm install. We followed the following guide:
https://linkerd.io/2/tasks/install-helm/
To perform the helm install. My fear is that either the intermediate / root certificate is going stale. However, when I delete the pod containing the nginx container and linkerd-proxy, the issue goes away. However, all other pods still throw the 'Bad Certificate' error, although traffic is still routed from nginx to our service some how.
 
We only started seeing this error when we moved to stable-2.9.0. We need to use this build as it has encryption features we require. We were using stable-2.8.1 before.
### How can it be reproduced?

We do not really know why this error is occurring, so our repro steps have been to stand up a k8s cluster with our service and then wait for it to eventually break. 

### Logs, error output, etc
https://gist.github.com/sagilson/c8c8a8c6be460f94707f681ec84a58d4
https://gist.github.com/sagilson/1b18836ced0d165fcf41c500f9cab096

#### `linkerd check` output

```
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
```

### Environment

- Kubernetes Version: v1.18.6
- Cluster Environment: AKS
- Host OS: Debian-like
- Linkerd version: stable-2.9.0

### Possible solution
We are able to mitigate the issue by deleting the pod containing the nginx container and a linkerd-proxy container. However after a random amount of time, the error comes back.
### Additional context
I am happy to provide additional context as questions come in about this issue.

**Comment by kleimkuhler** [comment] 2020-12-10 19:26
Hey @sagilson! I have a few questions as this could be from any one of multiple things.

1. Do you have an application you care share that reliably reproduces this? I see that the timeframe it occurs is anywhere from 1 hr to 1 week, but thought I'd check!
2. Does `linkerd check --proxy` report everything as okay?
3. If you look at the pod YAML for the Linkerd destination and identity pods, do their trust anchors match?
4. Can you please share the logs from the Linkerd identity and destination pods? It would be helpful if you are able to bump those up to `debug` as well.
5. Lastly, I saw that you maintain tight control over all certificates in your service--are you using cert-manager to do this or anything that may be rotating control plane pod certificates?

If you can answer the above questions and provide any additional information about the particulars of your install, that would be helpful in figuring out what is going on. Thanks!

**Comment by behrtam** [comment] 2020-12-17 13:51
Might be the same as https://github.com/linkerd/linkerd2/issues/5298

**Comment by olix0r** [comment] 2020-12-17 18:13
> Might be the same as #5298

As far as I can tell, there aren't any logs indicating the absolute-form error mentioned in that issue, so I wouldn't assume they're related unless we are seeing that same error message.

Regarding the error message:

```
[253013.089415s]  INFO ThreadId(02) daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=0.0.0.0:0 target.addr=0.0.0.0:0}: linkerd2_app_core::serve: Connection closed error=received fatal alert: BadCertificate
[253013.321265s]  WARN ThreadId(01) dst: rustls::session: Sending fatal alert BadCertificate
[253013.434737s]  WARN ThreadId(01) identity: rustls::session: Sending fatal alert BadCertificate
[253013.590916s] ERROR ThreadId(02) daemon:admin{listen.addr=0.0.0.0:0}:accept{peer.addr=0.0.0.0:0 target.addr=0.0.0.0:0}: rustls::session: TLS alert received: Message {
    typ: Alert,
    version: TLSv1_2,
    payload: Alert(
        AlertMessagePayload {
            level: Fatal,
            description: BadCertificate,
        },
    ),
}
```

This indicates that there's a problem communicating with the _control plane_, but I'm not seeing errors related to dataplane (pod to pod) communication. I'd be curious to see the output of `linkerd metrics` on a pod exhibiting this behavior -- the raw metrics dump should give us a clearer signal on the types of errors you've encountered.

This could potentially be an instance of https://github.com/linkerd/linkerd2/issues/5209, which we've fixed in stable-2.9.1.

I'm a bit miffed about the bad certificate error you're seeing, though; but I think we'd need deeper diagnostic information to get to the bottom of that. Especially, are there any errors logged on the control plane proxies?

**Comment by sagilson** [comment] 2020-12-28 20:03
Thanks for all the help with this. I went through and looked at the linked issue you gave, but upgrading to the edge version to use the new TLS forwarding stack is not an option for us at the moment. I will try and upgrade a cluster to stable-2.9.1 and see if that resolves the issue. Bringing our cluster back to stable-2.8.1 solved the issue, so it is a regression in 2.9.0. Here is  gist containing the output of ```linkerd metrics```: https://gist.github.com/sagilson/2e57e011d8cf2cb2fff9e5fbfe9f5e27

The control plane proxies have the following error:
```
[    10.273763s]  WARN ThreadId(01) inbound:accept{peer.addr= target.addr=}: rustls::session: Sending fatal alert AccessDenied
[    10.273899s]  INFO ThreadId(01) inbound:accept{peer.addr= target.addr=}: linkerd2_app_core::serve: Connection closed error=unexpected error: no server certificate chain resolved
```
 Any thoughts?

**Comment by cpretzer** [comment] 2020-12-29 00:08
@sagilson I looked through the `linkerd metrics` output and I don't see any error totals. I think that the metrics should include responses with specific error codes, but I'm not 100% sure. That might be in the metrics for the service itself.

Regarding the `no server certificate chain resolved` message, that appears to be coming from the `rustls` [library](https://github.com/ctz/rustls/blob/main/rustls/src/server/hs.rs#L754) that the proxy uses.

Based on what I've read here, it sounds like there could be an issue with certificate rotation, but I don't have enough info to support that.

If you can, it would help to get the answers to the questions that @kleimkuhler asked:

> 1. Do you have an application you care share that reliably reproduces this? I see that the timeframe it occurs is anywhere from 1 hr to 1 week, but thought I'd check!
> 2. Does linkerd check --proxy report everything as okay?
> 3. If you look at the pod YAML for the Linkerd destination and identity pods, do their trust anchors match?
> 4. Can you please share the logs from the Linkerd identity and destination pods? It would be helpful if you are able to bump those up to debug as well.
> 5. Lastly, I saw that you maintain tight control over all certificates in your service--are you using cert-manager to do this or anything that may be rotating control plane pod certificates?

**Comment by sagilson** [comment] 2020-12-29 01:33
Yes I can answer those questions. Sorry about the delay on these, and thanks for the help.
1. I cannot share the application that reproduces this unfortunately. I have not been able to determine any rhyme or reason as to why the certificates begin to be denied, causing this error
2. Everything succeeds as normal, except for the data plane proxy metrics are not found in prometheus.  I receive this error on the last step: 
``` data plane proxy metrics are present in Prometheus
    Data plane metrics not found for <namespace>/<microservice pod>-676488b9fb-dg66l, <namespace>/<nginx/traffic routing pod>-65767fcbfc-wf62s, <namespace>/<service frontend pod>-756f4cf677-n9wbq.
    see https://linkerd.io/checks/#l5d-data-plane-prom for hints
```
3. We used  helm to install linkerd on our service, and used this guide to set up the trust anchors provided to helm: https://linkerd.io/2/tasks/generate-certificates/index.html
We used the charts found on the linkerd2 github to perform the helm install, including the relevant destination and identity yamls: https://github.com/linkerd/linkerd2/tree/main/charts/linkerd2
4. Linkerd destination pod logs: https://gist.github.com/sagilson/52c26fd048aade011333fa23ba45d804
Linkerd identity pod logs: https://gist.github.com/sagilson/a9c251cb0f59639cf300602510856fec
Let me know if you need me to bump the logging to debug if these are not sufficient. 
5. Nothing on our end is rotating control plane pod certificates. The certificate made for the helm install step has a year expiration time so that shouldn't be the issue.

Let me know if you've got any other questions!

**Comment by cpretzer** [comment] 2020-12-29 23:59
@sagilson my initial thought is that the chart repo is on the main branch, and you should use the [stable-2.9.1](https://github.com/linkerd/linkerd2/tree/stable-2.9.1/charts/linkerd2) tag, because main is frequently merged with ongoing work.

Better still is to add the stable repo to your helm installation: https://linkerd.io/2/tasks/install-helm/#adding-linkerds-helm-repository

The dataplane metrics piece is interesting, and I'd like to see if you get the same messages when using the stable helm charts.

**Comment by olix0r** [comment] 2021-01-04 18:41
Hmm, these log messages are extremely suspicious:

```
time="2020-12-27T23:49:30Z" level=info msg="certifying default..identity.linkerd.cluster.local until 2020-12-28 23:49:50 +0000 UTC"
time="2020-12-27T23:49:30Z" level=info msg="certifying ..identity.linkerd.cluster.local until 2020-12-28 23:49:50 +0000 UTC"
```

In both of these cases, the namespace is omitted from the identity string and, in the later case, the there is no service account name. I can't explain how this could happen, but this points strongly to a misconfiguration.

Does `linkerd check --proxy` show any warnings when run against this namespace/workload?

**Comment by adleong** [comment] 2021-02-10 21:03
Closing due to inactivity.  Please feel free to re-open if you are able to provide more information.

**Closed by adleong** 2021-02-10 21:03 UTC

**Comment by feiyushi** [comment] 2021-04-15 21:31
reporting back. it was a misconfiguration where trust anchor and intermediate CA shared the same subject name.

**Comment by benny659** [comment] 2021-05-07 00:41
> reporting back. it was a misconfiguration where trust anchor and intermediate CA shared the same subject name.

Hi @feiyushi could you more elaborate what do mean same subnet name ?
