### ISSUE TITLE
AKS v1.22 linkerd-cni fails to start without `privileged: true` due to permission denied error reading /host/etc/cni/net.d/10-azure.conflist

### ISSUE THREAD

**Issue by tspearconquest** [linkerd/linkerd2#8209] opened 2022-04-05 18:58 UTC
### What is the issue?

We upgraded our cluster in Azure to v1.22.6 yesterday and another today, both displayed the same issue.

When linkerd-cni attempts to start up, it receives a permission denied error:

### How can it be reproduced?

Install linkerd-cni and linkerd to a cluster running Kubernetes v1.19. Then upgrade the cluster to v1.20, followed by v1.21, followed by v1.22. Wait for the pods to start coming up on v1.22 and look at the linkerd-cni namespace.

### Logs, error output, etc

```
$ kubectl logs po/linkerd-cni-6fbs9 -n linkerd-cni -p
Wrote linkerd CNI binaries to /host/opt/cni/bin
Using CNI config template from CNI_NETWORK_CONFIG environment variable.
      "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
      "k8s_api_root": "https://<redacted>:__KUBERNETES_SERVICE_PORT__",
CNI config: {
  "name": "linkerd-cni",
  "type": "linkerd-cni",
  "log_level": "info",
  "policy": {
      "type": "k8s",
      "k8s_api_root": "https://<redacted>:443",
      "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
  },
  "kubernetes": {
      "kubeconfig": "/etc/cni/net.d/ZZZ-linkerd-cni-kubeconfig"
  },
  "linkerd": {
    "incoming-proxy-port": 4143,
    "outgoing-proxy-port": 4140,
    "proxy-uid": 2102,
    "ports-to-redirect": [],
    "inbound-ports-to-ignore": ["4191","4190"],
    "simulate": false,
    "use-wait-flag": false
  }
}
jq: error: Could not open file /host/etc/cni/net.d/10-azure.conflist: Permission denied
```

### output of `linkerd check -o short`

```
Linkerd core checks
===================

linkerd-existence
-----------------
× control plane pods are ready
    No running pods for "linkerd-destination"
    see https://linkerd.io/2.11/checks/#l5d-api-control-ready for hints

Status check results are ×

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ linkerd-viz pods are injected
    could not find proxy container for metrics-api-f9ddcc77d-rpb95 pod
    see https://linkerd.io/2.11/checks/#l5d-viz-pods-injection for hints
× viz extension proxies are healthy
    No "linkerd-proxy" containers found in the "linkerd" namespace
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-healthy for hints
```

### Environment

- Kubernetes Version: 1.22.6
- Cluster environment: AKS
- Host OS: Ubuntu 18.04
- Linkerd Version: stable-2.11.2

### Additional context

We obtained a shell on one of the pods and found that the ownership of the file in question is UID and GID 1001, and the permissions are 0600. The CNI seems to be able to create its own file but unable to read or write to the 10-azure.conflist file.

```
$ kubectl exec -it po/linkerd-cni-cv5zv -n linkerd-cni -- /bin/sh
# ls -ld /host
drwxr-xr-x 4 root root 4096 Apr  5 17:47 /host
# ls -ld /host/etc
drwxr-xr-x 3 root root 4096 Apr  5 17:47 /host/etc
# ls -ld /host/etc/cni
drwxr-xr-x 3 root root 4096 Apr  5 17:47 /host/etc/cni
# ls -ld /host/etc/cni/net.d
drwxr-xr-x 2 root root 4096 Apr  5 16:25 /host/etc/cni/net.d
# ls -l /host/etc/cni/net.d/
total 12
-rw------- 1 1001  1001  375 Apr  5 17:59 10-azure.conflist
-rw------- 1 root 65532 4138 Apr  5 17:45 ZZZ-linkerd-cni-kubeconfig
```

We have customized the linkerd installation using kustomize, so below is the partial deployment.yaml with the changes that get incorporated by kustomize. In the below, if we change `allowPrivilegeEscalation` and `privileged` to `true` then linkerd-cni starts up, but otherwise it gets the error above.

```
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: linkerd-cni
  namespace: linkerd-cni
  annotations:
    ignore-check.kube-linter.io/host-network: Linkerd CNI requires access to the host network
    ignore-check.kube-linter.io/run-as-non-root: Linkerd CNI requires root access
spec:
  template:
    metadata:
      labels:
        app: linkerd-cni
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - name: install-cni
        imagePullPolicy: Always
        image: <privately hosted image>
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            cpu: "10m"
            memory: "20Mi"
          requests:
            cpu: "10m"
            memory: "20Mi"
```

**Comment by tspearconquest** [comment] 2022-04-05 19:00
For clarification, this works fine on Kubernetes 1.18 and 1.19. We did not check whether this worked with v1.20 or 1.21 on the way to v1.22.

**Comment by tspearconquest** [comment] 2022-04-05 22:47
I've just edited the cni daemonset on our v1.18 cluster and v1.22 cluster to add a custom entrypoint that simply sleeps, so that I could verify the file permissions before the CNI process starts.

On v1.18, the permissions are set to 644 and ownership is the uid and gid of the pod.
On v1.22, the permissions are set to 600 and ownership is the uid and gid 1001.

**Comment by mateiidavid** [comment] 2022-04-06 13:00
@tspearconquest hey, thanks for raising this. A bit unfortunate that it requires `privileged: true`.  Let's see if I understand this correctly:

* AKS (Azure) CNI creates its conflist and kubeconfig files
* You install `linkerd-cni` but it fails because it does not have permissions to modify the contents (i.e no `+w`)
* Setting `privileged: true` was enough to get it working

I tried to repro with Calico instead of Azure CNI:

```
# Calico without linkerd-cni
$ stat 10-calico.conflist
  File: 10-calico.conflist
  Size: 692             Blocks: 8          IO Block: 4096   regular file
Device: 36h/54d Inode: 5129042     Links: 1
Access: (0664/-rw-rw-r--)  Uid: (    0/    root)   Gid: (    0/    root)

# Note access: ug=rw,o=r
```

```
drwxr-xr-x 2 root root 4.0K Apr  6 12:38 .
drwxr-xr-x 3 root root 4.0K Apr  6 12:38 ..
-rw-r--r-- 1 root root 2.4K Apr  6 12:38 10-calico.conflist
-rw------- 1 root root 2.1K Apr  6 12:38 ZZZ-linkerd-cni-kubeconfig
-rw------- 1 root root 2.1K Apr  6 12:35 calico-kubeconfig
```

I'm running v1.21 on a k3d cluster

Everything worked well and linkerd appended the CNI plugin's config to `10-calico.conflist`. Worth noting, the permissions for the calico conflist are `644` (same as `v1.18`) -- a bit more permissive than `600`. I suspect the issue is the lack of read permissions. In our CNI plugin installer, all of our writes are atomic, which means that in actuality we _don't append to the file_, we create a temporary file with the changed contents and then just `mv` it. If the CNI file would still be `644` or `604`, I _think_ we'd be good.

As far as I understand `privileged` it means the container will re-use the same capabilities that other processes running on the host would have. This sort of elevates the capabilities of the container itself. I just wanted to clarify: _it was enough to set privileged to true for this to work? Didn't have to run as root?_

If this is just a matter of surfacing an option, you can already use `--set privileged=true` (if installing through CLI). We expose the option for the CNI plugin:

https://github.com/linkerd/linkerd2/blob/693625b97b4e6a7cd8167a500e5b729517137567/charts/linkerd2-cni/values.yaml#L37

If we need to change the container to run as root, then I'm also open to it. That should work, although uid=0 on container is uid=0 on host. Under normal circumstances that shouldn't be a problem, but since we're mounting the host fs I'm a bit wary of just running this as root. 

Let me know what you think and we can take it from there.

**Comment by tspearconquest** [comment] 2022-04-06 13:54
Hi Matei,

The CNI container runs as root by default, which we did not change, and we explicitly added `privileged: false` to the `securityContext` in our setup on v1.18 and v1.19. The only change we were required to make to get it working was to change `privileged: false` to `privileged: true`

```
~ ❯ linkerd install-cni --install-namespace=false |grep -i runAsUser
~ ❯ docker run --rm -it --entrypoint "" cr.l5d.io/linkerd/cni-plugin:stable-2.11.1 /bin/sh
# whoami
root
#
```

I did not try to change the UID of the CNI process to run as non-root but still with privileged flag, however I can do this today and let you know the results.

This issue seems to be caused by a change made on Azure between v1.19.13 and v1.22.6, so I'm not sure if Calico on a K3d cluster is going to be able to satisfy the requirements for reproduction.

Since I was unable to read the `10-azure.conflist` file despite being user `root` in the container, that at least confirms that with user `root` and `privileged: false` it does not work anymore, whereas it did work before.

**Comment by admincasper** [comment] 2022-04-06 14:31
We're having a related issue with linkerd-cni, we installed linkerd-cni instead of running the initContainer for linkerd specifically because it required `privileged: true`.

We are running linkerd-cni on Kubernetes 1.22.6 in AKS and we're currently running without `privileged: true`. Linkerd-cni 2.11.1 was installed using the helm chart and not the CLI. 

I'm commenting on this issue because the helm chart uses hostpath volumes with read capabilities which is a security concern and not a best practice. A privileged pod, as far as I know, is even worse as it has ALL capabilities and access to the kernel. Mounting a volume with write capabilities would solve @tspearconquest's issue above, but I'm concerned it will replace his issue with mine.

Is there a possible fix for using read-only hostpath volumes?

**Comment by olix0r** [comment] 2022-04-06 15:01
It might be a good idea to create an issue on https://github.com/Azure/AKS/issues to see if they have any recommendations on how this should be handled

**Comment by mateiidavid** [comment] 2022-04-06 15:09
> The CNI container runs as root by default, which we did not change, and we explicitly added `privileged: false` to the `securityContext` in our setup on v1.18 and v1.19. The only change we were required to make to get it working on v1.22 was to change `privileged: false` to `privileged: true`

Ah, sorry that's on me, I must've assumed for some reason because it's not specified in the securityContext, we don't run as root. Well, so if the only required change was to set `privileged: true`, can you try installing the cni plugin with the privilege value set to true? i.e

```
linkerd install-cni --set "privileged=true" | kubectl apply -f -
```

This should do the trick unless I'm missing something? 😅 

> I did not try to change the UID of the CNI process to run as non-root but still with privileged flag, however I can do this today and let you know the results.

Not sure it would change anything tbh. Truth is the perm changes on Azure's side suck a bit. Running our CNI plugin with the same group ID as theirs would've been a better solution than `privileged=true` imo but the perms for the file will still not allow read access for the group...not sure that'd fix anything. 

> This issue seems to be caused by a change made on Azure between v1.19.13 and v1.22.6, so I'm not sure if Calico on a K3d cluster is going to be able to satisfy the requirements for reproduction.

Yeah, I don't have easy access to an AKS cluster so I can't repro this. I wanted to see how other CNI providers manage file permissions for their CNI configurations. I find it peculiar that Azure CNI is so restrictive; this in essence means they don't allow any chaining? 

> Since I was unable to read the `10-azure.conflist` file despite being user `root` in the container, that at least confirms that with user `root` and `privileged: false` it does not work anymore, whereas it did work before.

Not ideal, but at least you can set privileged=true so it won't block you from going to prod. It might be worth perhaps reaching out to the Azure CNI team, like Oliver mentioned, to see what the intent behind the change was or how you can get around it? I'm not sure what else we can do here to fix this.

@admincasper, hey, thanks for the reply. Will try to go through some of your concerns quickly.

> We're having a related issue with linkerd-cni, we installed linkerd-cni instead of running the initContainer for linkerd specifically because it required privileged: true.

The init container should now run as non-root and non-privileged by default. Current stable version uses a different init container image, recent edges use the new one. You can look through [the partials file](https://github.com/linkerd/linkerd2/blob/main/charts/partials/templates/_proxy-init.tpl#L36).

> We are running linkerd-cni on Kubernetes 1.22.6 in AKS and we're currently running without privileged: true. Linkerd-cni 2.11.1 was installed using the helm chart and not the CLI.

> I'm commenting on this issue because the helm chart uses hostpath volumes with read capabilities which is a security concern and not a best practice. A privileged pod, as far as I know, is even worse as it has ALL capabilities and access to the kernel. Mounting a volume with write capabilities would solve @tspearconquest's issue above, but I'm concerned it will replace his issue with mine.

Well, you don't have to use `privileged=true`. In most cases, it shouldn't be required. It seems for @tspearconquest running the cni agent as privileged does the trick, so my suggestion was to make use of the configurable value. The cni agent should continue to run as unprivileged by default imo, it's one of the observations I made above: _privileged means the container will have the same capabilities as any other process running on the host_. 

As to mounting hostpath volumes with read capabilities, do you have any other idea on how to write to the host's fs without mounting a hostpath volume? AFAIK this is the standard for most CNI plugins that need to bootstrap config. It's weird, and a security concern, but I'm not (personally) aware of any other way to do this.

**Comment by mateiidavid** [comment] 2022-04-06 15:56
Right, that makes sense. It's not ideal to have to run it in privileged mode -- I totally get that --  it's definitely not what I'd recommend _under normal conditions_. Our hands are kind of tied here though since we didn't introduce the change. 

Nonetheless, thanks for raising the issue and awareness. Let's see what the recommended course of action is from the Azure team and take it from there :)

**Comment by tspearconquest** [comment] 2022-04-06 23:03
Thanks. As a side note, it doesn't appear that `linkerd install-cni` supports the `-f` flag, nor the `--set` flag, so I don't seem to have a way to set `privileged: true` during the CNI install without using kustomize.

**Comment by mateiidavid** [comment] 2022-04-14 09:58
@tspearconquest it appears the issue's been fixed (https://github.com/Azure/AKS/issues/2888) and it was a problem on AKS' side. Since CNI files will be created with `644` as a permission now and we can actually read the contents in our script, I'm going to go ahead and close this.

> Thanks. As a side note, it doesn't appear that linkerd install-cni supports the -f flag, nor the --set flag, so I don't seem to have a way to set privileged: true during the CNI install without using kustomize.

Oops, noted. We'll see what we can do there to make the UX a bit nicer. 

Message me if you want this open or if stuff breaks. Thanks a lot for your insight thus far and for your time! :)

**Closed by mateiidavid** 2022-04-14 09:58 UTC
Labels: area/cni
