### ISSUE TITLE
"linkerd check --proxy" takes loooooong time to complete with pods in Init or Pending

### ISSUE THREAD

**Issue by geekmush** [linkerd/linkerd2#3574] opened 2019-10-14 20:39 UTC
### What is the issue?

Running `linkerd check --proxy` when there are pods in `Init or Pending` causes the check to take an inordinate amount of time (long timeouts?)

### How can it be reproduced?

Have a pod in Initializing or Pending status and run a `linkerd check --proxy' ... and when it gets to the last stage of `data plane and cli versions match`, it will show an error for the pod that isn't fully functional yet...which obviously *wouldn't work anyway*.

It also does this for pods in other error conditions (i.e. `CrashLoopBackOff`), but that seems somewhat reasonable (if quite a long default timeout).

### Logs, error output, etc

Nothing more interesting than a standard `linkerd check --proxy` with failing on the first busted pod it checks (I think ... only 1 is referenced).

### Environment

- Kubernetes Version: 1.14.6
- Cluster Environment: AKS
- Host OS: MacOS / AKS's Linux
- Linkerd version: 2.6

### Possible solution

Should linkerd attempt to detect when a pod is not in "Running" status and exempt it from the proxy check (I would think it would fail the check by default, no need to wait on it)?

### Additional context

**Comment by grampelberg** [comment] 2019-10-15 15:45
By default, `check` waits for all the components to be up and ready. This is by design so that folks who are getting started get a chance to see everything come up instead of erroring immediately.

In this instance, it sounds like you'd like to just make sure the proxies that are running are operating correctly? What exactly are you checking for? Does `--wait 1` work?

**Comment by geekmush** [comment] 2019-10-15 16:48
That might work ... I tried that but didn't realize I needed the time
denomination (i.e "1s") ... just figured that out.  I guess I thought it
would default to seconds.  My bad.   Only issue, in a script, I only see
"success" or "failure" ... so, I can't tell if it is working or have a "one
busted pod, but everything else good".

I'd still have to do some "smart things" to figure out if what is errored
is a real error or a broken pod.

So, for example, we have a couple of cases where this breaks the `linkerd
check --proxy`.

1 - Broken/Crashed Pod
  Something is keeping the primary container from running properly (broken
config, missing required component (i.e. database table not setup yet),
busted code, etc). In this case, the linkerd-proxy container is up, but has
no one to slurp data from, so it comes back as "broken" in the check.  I'm
not sure if that's the correct response, but I also don't know how you (or
the proxy) would find out that the container the proxy is supposed to
service is alive and well (do you have access to see the readiness state of
the to-be-proxied container?).

2 - Pending or Initializing Pod
  We have (too frequently) run into a scenario where the pod is pending an
k8s event or resource (i.e. a database pod waiting to get scheduled on a
node that can map enough PVCs to satisfy the pod's requirements).  In this
case, there is no linker-proxy container running yet, but that still causes
a failure report in the `linkerd check --proxy`.  I don't think that the
check should fail for a proxy that is on a pod that hasn't actually gotten
past the Init state ... technically, there's nothing to fail.  Should it be
reported in a non-fail way?  Maybe?  This feels like it should be a larger
discussion.

Perhaps a couple of modifier flags like `--ignore-pending-pods` and
`--ignore-errored-pods` could be added to the proxy version of the check?

Just some thoughts ...

Hope this helps,
Sam

**Comment by geekmush** [comment] 2019-10-15 17:03
Well, note to self ... markdown doesn't work via email, sorry!

Also wanted to add a note.  As we are attempting to implement linkerd in a Helm Operator environment, we will be running the various install/upgrade/check commands against a new or existing environment over and over and they need to run idempotently (or at least fail in a way that we can manage it).  This appears to be a new pattern being more and more widely adopted, so it is something we'd like you to consider.

From that perspective, the pods running in the cluster may very well be in various states of operability.  Our concern with running the `linkerd check` command is to validate that linkerd itself is operating normally and the `Running` pods/proxies are communicating correctly (i.e. validate the data plane functionality).

Right now, this may be an odd case, but I can see it becoming more prevalent, provided this Helm Operator pattern continues.  The theory being that if the parts will work, they will converge.  Linkerd is fairly low in our stack, so we need to validate it is functional in order for the other parts to work the way "we want".

Hope this helps clarify my data point.

Thanks!

**Comment by grampelberg** [comment] 2019-10-15 18:55
It feels like this is more in scope for using the k8s API directly for your use cases than `check` specifically. From your use cases:

- broken/crashed pod - if the pod isn't coming up, it should be marked as failed. While it is possible that the proxy is operating okay, the combination might be what's crashing everything and still need eyes.
- pending/initializing pods - this feels like an error too. If a pod is pending, folks should be notified. It'd be tough to make an assumption as to *why* a pod is pending and look more deeply into it.

Having a proxy pass its readiness check should be used as a validator of health, so you should be able to do all this with selectors and `kubectl` or the k8s api depending on how you want to integrate there. Could you point me in the direction of the helm operator pattern?

**Comment by geekmush** [comment] 2019-10-15 19:54
So, the original idea was somewhere around here:  https://coreos.com/blog/introducing-operators.html

Since they were kind enough to publish a standard SDK (https://github.com/operator-framework/operator-sdk), there is naturally only 1 implementation of an operator ... just kidding, there's a zillion (https://github.com/operator-framework/awesome-operators).

We've decided to run with https://kopf.readthedocs.io/en/latest/ because most of us in our group are more fluent in python than go.

Our implementation of the operator is to build and maintain our high-level application, which is made up of a pile of services (infrastructure stuff) and microservice apps.  The Operator's goal is to get the environment to a stable, consistent operating state.  For a Production environment, that means ALL GREEN, but for a development environment, there's often broken bits as the developers work along.  As they push changes through the build system, the Operator sees the update (through various mechanisms, including the K8s event bus) and re-deploys updated code, etc, etc.

So, stuff has to be able to be run over and over and that means doing various baseline checks each run to determine a stable state up to point X, before going onto the next step.

Each service/app is different the way you determine working status (API call, CLI, just "run it", etc).  This is why we need to find a safe, idempotent manner to test linkerd each time we do another run.

Hopefully, this helps clarify our use case.  Attached is a snapshot of one of our development clusters "right now" ... there's a LOT of red because we broke a database seed script and much of that red are microservices that are waiting for the database to exist (or, more accurately, a k8s secret to exist, otherwise, we would have the container running and spin waiting for the DB resource to show up).  Once the fix gets pushed, the Operator will do another pass from the top and reset the world, trying to get it to converge closer to the desired state of ALL GREEN (or all blue in k9s's case :) ).

As for a pending pod, should the `linkerd check --proxy` fail for a linkerd-proxy container that hasn't actually started?  Assuming *other* proxies have started and are functional...
![showard@FL1-P-WS063 (k9s) 2019-10-15 13-25-47](https://user-images.githubusercontent.com/1620201/66864841-4cb89500-ef53-11e9-8f4f-0174b9a8de75.png)

**Comment by grampelberg** [comment] 2019-10-15 20:16
> As for a pending pod, should the linkerd check --proxy fail for a linkerd-proxy container that hasn't actually started? Assuming other proxies have started and are functional...

If it was scheduled and hasn't started, it should fail. Remember, `Pending` also counts if there's not enough resources on the cluster.

It still feels like the correct solution to this problem is using the readiness checks. You've got some custom logic for your environments that'll require a little bit more thought and code around it.

**Comment by grampelberg** [comment] 2019-10-21 21:26
@geekmush I'm going to close this out for now. It sounds like you're trying to do something special that feels like a better fit for readiness checks. Please open back up if I'm wrong!

**Closed by grampelberg** 2019-10-21 21:26 UTC
