### ISSUE TITLE
Ability to run pre-checks with with docker container runtime

### ISSUE THREAD

**Issue by vikas027** [linkerd/linkerd2#8583] opened 2022-05-30 02:39 UTC
### What problem are you trying to solve?

It seems like there is no way to run pre-checks when using docker container runtime. One, can only check post installation as shown [here](https://linkerd.io/2.11/tasks/troubleshooting/#l5d-proxy-init-run-as-root).

```bash
➜  ~ linkerd check --pre
there are nodes using the docker container runtime and proxy-init container must run as root user.
try installing linkerd via --set proxyInit.runAsRoot=true
```

### How should the problem be solved?

Maybe introduce an optional flag to check runtime

```bash
➜  ~ linkerd check --pre --runtime docker
```

### Any alternatives you've considered?

No

### How would users interact with this feature?

```bash
➜  ~ linkerd check --pre --runtime docker
```

### Would you like to work on this feature?

maybe

**Comment by olix0r** [comment] 2022-05-31 14:45
Rather than add a `--runtime` flag, it seems like `check --pre` should display its normal output. The note about the proxy-init config is valid--you'll need to use that setting when installing--so there should probably be some informational/warning output of a check, but it shouldn't block all other checks from running.

**Comment by vikas027** [comment] 2022-05-31 23:56
Hey @adleong ,

I am seeing a different error in the latest edge release.

```bash
➜  ~ ./linkerd2 version --client
Client version: edge-22.5.3
➜  ~ ./linkerd2 check --pre
Error rendering install manifest: error configuring Kubernetes API clientset: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

➜  ~ linkerd version --client
Client version: stable-2.11.2
➜  ~ linkerd check --pre
there are nodes using the docker container runtime and proxy-init container must run as root user.
try installing linkerd via --set proxyInit.runAsRoot=true
➜  ~ 
```

**Comment by kleimkuhler** [comment] 2022-06-01 16:56
@vikas027 This doesn't seem to be a Linkerd issue. Have you looked at aws/aws-cli#6920? I'm not sure if you're using AWS/EKS, but it seems to be a currently active issue with that error and there are a few workarounds posted in there.

**Comment by pcgeek86** [comment] 2022-06-10 17:54
I'm having this same issue. I deployed a Kubernetes 1.23 Cluster on Linode, and attempted to run `linkerd check --pre`.

Linkerd refuses to do any checks, simply because the cluster is using the Docker container runtime.

```
C:\git> linkerd check --pre
there are nodes using the docker container runtime and proxy-init container must run as root user.
try installing linkerd via --set proxyInit.runAsRoot=true
C:\git> linkerd version
Client version: stable-2.11.2
Server version: unavailable
```

I'm using PowerShell Core on Windows 11 Developer Preview

**Comment by vikas027** [comment] 2022-06-14 03:10
> @vikas027 This doesn't seem to be a Linkerd issue. Have you looked at [aws/aws-cli#6920](https://github.com/aws/aws-cli/issues/6920)? I'm not sure if you're using AWS/EKS, but it seems to be a currently active issue with that error and there are a few workarounds posted in there.

Thanks, @kleimkuhler . The issue was indeed with the version of the AWS APIs. Bumping up the AWS version from v2.4.20 to  v2.7.7 helped as it uses the updated API version `v1beta1`.

**Comment by kleimkuhler** [comment] 2022-06-14 16:47
Thanks for the update @vikas027!

I have confirmed this is an issue though; thanks for the comment @pcgeek86.

Leaving the explanation incase someone wants to pick it up; otherwise we'll get around to this soon.

`linkerd check --pre` ends up calling `renderInstallManifests` [here](https://github.com/linkerd/linkerd2/blob/be2733b2b1df62e5966587ea5545d89e316f8edd/cli/cmd/check.go#L151-L160). So even though the check was removed in #7468, we still end up calling the same path that `linkerd install` does.

The fix for this is going to be making sure that when `renderInstallManifests` is called — and thus `installControlPlane` — we're somehow avoiding the docker container runtime check [here](https://github.com/linkerd/linkerd2/blob/8038aa24d639bb6a1e558e556ac019bfd4346da3/cli/cmd/install.go#L222).

**Closed** 2022-06-22 14:04 UTC
Labels: area/cli, bug
