### ISSUE TITLE
Connect timeout after container restart

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1762] opened 2018-10-12 20:28 UTC
### What is the issue?

After a little while, the grafana container in the control plane crashes. When this happens, k8s tries to restart it. The container comes back up again, grafana successfully listens on port 3000, but the liveness probes never succeed. Connecting to port 3000 externally to the pod, TCP connect occurs but headers are never received and the request never goes through (as far as I can tell).

I've tried creating a simple nginx container, killing the nginx process and seeing. That doesn't appear to replicate this specific problem. I'm not sure what is causing the grafana container to die, but it might be part of the cause here.

### How can it be reproduced?

- Turn TLS on for the control plane
- Add emojivoto to the cluster, turn TLS on
- Scale vote-bot to the 100-150 range
- Load grafana dashboard and wait, it usually takes 5-10m for the initial crash.

### Environment

- Kubernetes Version: 1.10.7
- Cluster Environment: AKS
- Host OS: Ubuntu 16.04
- Linkerd version: stable-2.0.0

**Comment by grampelberg** [comment] 2018-10-12 21:45
Also on AKS + k8s 1.11.3

**Comment by dadjeibaah** [comment] 2018-10-30 22:55
We need to repro this without TLS to see if we run into the same issue.

**Comment by bcorijn** [comment] 2018-11-28 16:05
I seem to have the same issue with my grafana going into a CrashLoopBackOff, also running with TLS at the moment but on an AWS cluster. 
Besides issue https://github.com/linkerd/linkerd2/issues/1747 that you already linked to, this one  also looks related: https://github.com/linkerd/linkerd2/issues/1730

**Comment by grampelberg** [comment] 2018-11-28 16:16
@dadjeibaah I'm reasonably sure it isn't possible to repro without TLS (I really tried).

**Comment by hawkw** [comment] 2018-12-12 19:15
I'm curious to know if this can still be reproduced on stable-2.1?

**Comment by christianhuening** [comment] 2018-12-15 09:05
I just updated to Linkerd stable-2.1 and tried to reproduce the bug. So far it's looking great! I scaled vote-bot to 250 instances and it's running smoothly for 15-20 Minutes now.
![grafik](https://user-images.githubusercontent.com/738953/50041162-993ff500-0050-11e9-8b1d-bc0004bf32b6.png)
![grafik](https://user-images.githubusercontent.com/738953/50041177-c2608580-0050-11e9-8f34-dafb6ff4b38b.png)

Running with the following:
5 Node Cluster
K8s: 1.13.1
Linkerd: 2.1
--tls=optional
Network: kube-router 0.2.3

**Comment by klingerf** [comment] 2018-12-17 22:52
@christianhuening Awesome! Am glad to hear that the grafana pod isn't crashing under the additional load. I agree that seeing the empty authority in the `linkerd stat` output is a bit weird, but otherwise this all looks good to me.

**Comment by seanmonstar** [comment] 2019-01-07 23:23
> So from my point of view the issue is not present atm.

@grampelberg do you agree, and we can just close?

**Comment by grampelberg** [comment] 2019-01-07 23:40
@seanmonstar I believe it is still an issue. Resource requests were added in 2.1 which makes this specific set of replication steps not work any longer (you need to get a container to crash and restart).

**Comment by hawkw** [comment] 2019-01-22 20:34
Thus far, this issue is proving quite difficult to reproduce. Repeatedly `kill -9`ing emojivoto's web pod until it goes into CrashLoopBackOff doesn't seem to be sufficient AFAICT.

**Comment by adleong** [comment] 2019-02-12 22:25
Here's a theory:  is it possible that the grafana process was crashing without resetting its TCP connection?  This could get it into a state where the Linkerd proxy is holding onto a connection that grafana has dropped.  

If so, this should be fixed by the recent addition of TCP keepalive.  @grampelberg have you been able to reproduce this since the keepalive fix?  @olix0r does this sound like a reasonable theory to you?

**Comment by grampelberg** [comment] 2019-02-12 22:52
Huh, that's a good theory. I've not had time to do any reproduction yet. It should be easy to A/B test on AKS though with the reproduction steps.

**Closed** 2019-06-10 00:02 UTC
Labels: area/identity, area/proxy, bug, wontfix
