### ISSUE TITLE
Connection closed error=proxy admin server is HTTP-only

### ISSUE THREAD

**Issue by possani** [linkerd/linkerd2#5672] opened 2021-02-05 09:19 UTC
### What is the issue?
The communication between prometheus and the proxy should be using HTTPS but that is not the case.

### How can it be reproduced?
Upgrade from version **stable-2.9.1** to version **edge-21.1.4**

Initially, it was installed using:
```
linkerd install \
  --identity-trust-anchors-file ca.crt \
  --identity-issuer-certificate-file issuer.crt \
  --identity-issuer-key-file issuer.key \
  | kubectl apply -f -
```
For upgrading I did:
```
linkerdEdge upgrade | tee linkerd/base/linkerd.yaml
linkerdEdge viz install | tee linkerd/base/linkerd-viz.yaml
```
and argo replaced the old YAML files with the new ones.

### Logs, error output, etc

```
INFO ThreadId(02) daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=<prometheus pod ip>:35390 target.addr=<pgbouncer pod ip>:4191}: linkerd_app_core::serve: Connection closed error=proxy admin server is HTTP-only
```

#### `linkerd check` output

I have already rolled it back.

### Environment

- Kubernetes Version: 1.16
- Kustomize Version: v3.8.1 (argo CD)
- Cluster Environment: (AWS)
- Linkerd version: edge-21.1.4

### Possible solution
Maybe the same flags (for identity) should be available for viz

### Additional context
I was using opaque-ports for pgbouncer (5432) and I have rolled it back already

**Comment by adleong** [comment] 2021-02-10 20:12
Thanks @possani!  We'll look into this and let you know if we need any further information.

**Comment by kleimkuhler** [comment] 2021-03-01 20:50
After speaking with @possani off GitHub I'm closing this for now.

The `upgrade` command used did not prune old components, and it's possible that the old Prometheus was still trying to scrape resources. They are not upgrading from stable until 2.10 is released and they'll reach back out on this issue if they run into it again.

**Comment by muenchdo** [comment] 2021-03-15 12:38
Just wanted to mention that I've seen a few other reports of this on Slack:

* https://linkerd.slack.com/archives/C89RTCWJF/p1615804665326100?thread_ts=1615781294.318500&cid=C89RTCWJF
* https://linkerd.slack.com/archives/C89RTCWJF/p1615577738257000
* https://linkerd.slack.com/archives/C89RTCWJF/p1615731581290500?thread_ts=1615713931.279100&cid=C89RTCWJF

**Comment by kleimkuhler** [comment] 2021-03-15 13:52
@muenchdo Thanks I'll reopen and we'll look into this further.

**Comment by kleimkuhler** [comment] 2021-03-30 16:27
@virenrshah and @alekseiplotnikov I've been trying to reproduce this, but have not seen it occur on any app pod's proxy yet. I'm installing linkerd, linkerd-viz, and then injecting an application like [emojivoto](https://github.com/BuoyantIO/emojivoto).

There are a few questions I have. Feel free to answer as many as you can—I would really appreciate it!

1.  Is there anything unique about the pod's that you see this occur on? If you only see it on some and not others, anything come to mind that may set that pod apart from others? It could be helpful to know and try to reproduce.
2. Are the pods already injected and this only occurs after an upgrade?
3. Does it seem to ever resolve?
4. Is it reproducible on the same pods, or does it seem random?
5. Can you provide any additional logs? I'd be curious to see Linkerd's destination pod proxy logs. Also if this is reproducible for either of you, more logs would be helpful from the proxies. If you add `config.linkerd.io/proxy-logs: linkerd=debug,warn` that would be a huge help.

**Comment by virenrshah** [comment] 2021-03-31 12:05
@kleimkuhler I installed linkerd viz again into my already injected cluster and deploy. So far, I have not seen any repeat of the error msgs but will keep an eye out. I will be doing another deploy soon so that might trigger it.

**Comment by virenrshah** [comment] 2021-04-06 00:27
@kleimkuhler So, just a data point. I can't make changes to this cluster right now (even increasing the log level because it's production) but we started getting these errors without any re-deploy of the application/services/pods. You can see it jumping up and there was no change in deploy at that time. 
<img width="1103" alt="Screen Shot 2021-04-05 at 8 23 22 PM" src="https://user-images.githubusercontent.com/9826261/113642223-51906d80-964d-11eb-9889-d0613038ee44.png">

**Comment by tobygale** [comment] 2021-04-06 13:16
We're seeing the same issue and have also found that restarting the Prometheus pod fixes the issue for a seemingly random period of time.

After seeing a commit that references this issue further up the thread that mentions protocol detection, we've found a more stable work-around by adding the `config.linkerd.io/opaque-ports: "4191"` annotation to deployments.

**Comment by olix0r** [comment] 2021-04-08 16:37
After researching this, we're pretty sure that this error message is innocuous. We've updated the admin server so that this situation is handled gracefully by the proxy. This updated proxy is available on recent edge releases and will be included in stable-2.10.1.

**Closed by olix0r** 2021-04-08 16:37 UTC

**Comment by tarvip** [comment] 2021-04-13 12:19
@olix0r this fix in upcoming stable-2.10.1 affected only admin server or proxy in general? The reason why I am asking is that we have some other services also that are having interesting messages after upgrading to stable-2.10.0. For example a service that is using Akka HTTP started logging following error:
```
Illegal request, responding with status '400 Bad Request': Unsupported HTTP method: The HTTP method started with 0x16 rather than any known HTTP method. Perhaps this was an HTTPS request sent to an HTTP endpoint
```

when I restart this service, then it is gone for some time, but then reappears randomly. I suspect that it is related to same issue.

**Comment by kleimkuhler** [comment] 2021-04-13 13:08
@tarvip Do you have any of the app's proxy logs around the time that you see this? It would be helpful to see if it's failing to detect a protocol or something and passing it through to the app container.

**Comment by tarvip** [comment] 2021-04-13 14:20
I investigated one case, I didn't have raw log available anymore, but I was using logs in kibana.
For example when we had this `0x16` in our logs, like 760 messages per second, in the same second there were 76 following messages in proxy-log:
```
{"timestamp":"...","level":"INFO","fields":{"message":"Connection closed","error":"request timed out"},"target":"linkerd_app_core::serve","spans":[{"name": "inbound"},{"client_addr": "10.1.21.79:33178","target_addr": "10.1.4.38:8080","name": "accept"}],"threadId":"ThreadId(1)"}
```

and 8 following messages:
```
{"timestamp":"...","level":"INFO","fields":{"message":"Connection closed","error":"proxy admin server is HTTP-only"},"target":"linkerd_app_core::serve","spans":[{"name": "daemon"},{"listen_addr": "0.0.0.0:4191","name": "admin"},{"client_addr": "10.1.26.203:45330","target_addr": "10.1.4.38:4191","name": "accept"}],"threadId":"ThreadId(2)"}
```

`10.1.21.79` belonged to traefik pod and `10.1.4.38` to linkerd-viz.prometheus.
I checked also traefik pod proxy log, there was silence at that time.

**Comment by olix0r** [comment] 2021-04-13 14:45
@tarvip It would be best to open a new issue for the problem you're seeing.

Any log messages with `"spans":[{"name": "daemon"}` are unrelated to your application problem--and as mentioned in this issue, these are innocuous and have been fixed.

It would also be helpful if you can configure the proxies with the pod annotation `config.linkerd.io/proxy-log-level: linkerd=debug,warn` so that we have more information about the specific requests going through the proxy.

It would be _best_ if you can also include a k8s manifest to configure the relevant components (Traefik, akka, etc) so that we can try to replicate this setup locally.

Thanks!

**Comment by tarvip** [comment] 2021-04-13 16:28
@olix0r thanks, I will open new issue when I have more data available.

**Comment by tarvip** [comment] 2021-04-16 11:15
@olix0r regarding initial issue, I upgraded one of our linkerd from 2.10.0 to 2.10.1, `proxy admin server is HTTP-only` is gone, but now proxy logs are polluted by:
```
{"timestamp":"[   517.977900s]","level":"INFO","fields":{"message":"Connection closed","error":"invalid HTTP method parsed"},"target":"linkerd_app_core::serve","spans":[{"name":"daemon"},{"listen.addr":"0.0.0.0:4191","name":"admin"},{"client.addr":"10.0.5.162:51408","name":"accept"}],"threadId":"ThreadId(2)"}
```

I also enabled the debug log:
```
{"timestamp":"[   517.977546s]","level":"DEBUG","fields":{"message":"Peeked bytes from TCP stream","sz":289},"target":"linkerd_tls::server","spans":[{"name":"daemon"},{"listen.addr":"0.0.0.0:4191","name":"admin"},{"client.addr":"10.0.5.162:51408","name":"accept"}],"threadId":"ThreadId(2)"}
{"timestamp":"[   517.977605s]","level":"DEBUG","fields":{"message":"Identified foreign SNI","sni":"..."},"target":"linkerd_tls::server","spans":[{"name":"daemon"},{"listen.addr":"0.0.0.0:4191","name":"admin"},{"client.addr":"10.0.5.162:51408","name":"accept"}],"threadId":"ThreadId(2)"}
{"timestamp":"[   517.977643s]","level":"DEBUG","fields":{"message":"DetectResult","protocol":"None","elapsed":"7.9µs"},"target":"linkerd_detect","spans":[{"name":"daemon"},{"listen.addr":"0.0.0.0:4191","name":"admin"},{"client.addr":"10.0.5.162:51408","name":"accept"}],"threadId":"ThreadId(2)"}
{"timestamp":"[   517.977663s]","level":"DEBUG","fields":{"message":"Failed to parse HTTP request; handling as HTTP/1"},"target":"linkerd_app::admin","spans":[{"name":"daemon"},{"listen.addr":"0.0.0.0:4191","name":"admin"},{"client.addr":"10.0.5.162:51408","name":"accept"}],"threadId":"ThreadId(2)"}
{"timestamp":"[   517.977687s]","level":"DEBUG","fields":{"message":"Creating HTTP service","version":"Http1"},"target":"linkerd_proxy_http::server","spans":[{"name":"daemon"},{"listen.addr":"0.0.0.0:4191","name":"admin"},{"client.addr":"10.0.5.162:51408","name":"accept"}],"threadId":"ThreadId(2)"}
{"timestamp":"[   517.977717s]","level":"DEBUG","fields":{"message":"Handling as HTTP","version":"Http1"},"target":"linkerd_proxy_http::server","spans":[{"name":"daemon"},{"listen.addr":"0.0.0.0:4191","name":"admin"},{"client.addr":"10.0.5.162:51408","name":"accept"}],"threadId":"ThreadId(2)"}
{"timestamp":"[   517.977831s]","level":"DEBUG","fields":{"message":"The client is shutting down the connection","res":"Err(hyper::Error(Parse(Method)))"},"target":"linkerd_proxy_http::server","spans":[{"name":"daemon"},{"listen.addr":"0.0.0.0:4191","name":"admin"},{"client.addr":"10.0.5.162:51408","name":"accept"}],"threadId":"ThreadId(2)"}
{"timestamp":"[   517.977900s]","level":"INFO","fields":{"message":"Connection closed","error":"invalid HTTP method parsed"},"target":"linkerd_app_core::serve","spans":[{"name":"daemon"},{"listen.addr":"0.0.0.0:4191","name":"admin"},{"client.addr":"10.0.5.162:51408","name":"accept"}],"threadId":"ThreadId(2)"}
```
`10.0.5.162` belongs to `linkerd-viz.prometheus`

I understand it is harmless, but would be nice not to log those info messages.
