### ISSUE TITLE
EKS multicluster gateway has no IP

### ISSUE THREAD

**Issue by danielarcari** [linkerd/linkerd2#8074] opened 2022-03-15 21:22 UTC
### What is the issue?

* We have two AWS EKS clusters, in separate accounts, both have linkerd stable-2.11.1 installed, with multicluster. 
* All checks green (see below). 
* A meshed and exported service in cluster A appears, correctly, as a mirrored service in cluster B.
* I can `exec` into a pod in cluster B and successfully hit the ClusterIP of the mirrored service.
* However, according to the docs, the endpoint IP of both the exported service and the gateway should be the same, but in our case, the gateway has no IP (also see below).
* The logs for the gateway show a continuous stream of `INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=direct connections must be mutually authenticated` messages.

As far as I can tell, this is a vanilla installation of linkerd multicluster in EKS. Although the output below does not show a Gateway IP, the `describe svc linkerd-gateway` output does provide the AWS ELB CNAME, one of whose IPs matches the mirrored service endpoint. `curl`ing _those_ IPs on port 4143 results in "(52) Empty reply from server", or on 4191, a 404.

Does this indicate an improperly setup cluster, and if so, how should our install process be fixed?
If the install is OK, how can we verify that the mirrored service is configured correctly? (Our ultimate goal is to put the ALB ingress controller on top of this service (and others), running the ALB in one cluster and backing services in other clusters).

** kubectl output **
From cluster A, which is running the original service that's mirrored to cluster B:
```
kubectl -n linkerd-multicluster get svc linkerd-gateway -o "custom-columns=GATEWAY_IP:.status.loadBalancer.ingress[*].ip"
GATEWAY_IP
<none>
```

From cluster B:
```
kubectl --context k8b get endpoints test-client-k8s-test-a -o 'custom-columns=ENDPOINT_IP:.subsets[*].addresses[*].ip'
ENDPOINT_IP
52.1.x.x
```

### How can it be reproduced?

Setup two EKS clusters, install linkerd with common trust root as documented, and multicluster as follows (nothing special AFAIK):

```
linkerd --context k8b multicluster install | kubectl --context k8b apply -f -
linkerd multicluster install | kubectl apply -f -

linkerd multicluster link --cluster-name k8s-test-a | kubectl --context k8b apply -f -
linkerd --context k8b multicluster link --cluster-name k8s-test-b | kubectl apply -f -

linkerd multicluster check
linkerd --context k8b multicluster check
```

### Logs, error output, etc

kubectl logs -l app=linkerd-gateway -n linkerd-multicluster -c linkerd-proxy
[ 46369.918932s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=direct connections must be mutually authenticated
...

### output of `linkerd check -o short`

Cluster A:

Linkerd core checks
===================

Status check results are √

Linkerd extensions checks
=========================

Status check results are √

Status check results are √

Cluster B:

Linkerd core checks
===================

Status check results are √

Linkerd extensions checks
=========================

Status check results are √

Status check results are √

### Environment

AWS EKS
linkerd stable-2.11.1

**Comment by adleong** [comment] 2022-04-12 17:20
Hi @danielarcari!

It sounds like since you can successfully send requests to mirror services, everything here is working as intended and the only point of concern is the error message in the logs.  Is that correct?

The `direct connections must be mutually authenticated` message indicates that something attempted to connect to your cluster without proper mTLS.  Note that this isn't necessarily traffic from you other cluster and may be unmeshed traffic from some other source.  On its own, I don't think this message indicates any problem.

**Comment by olix0r** [comment] 2022-04-19 16:53
I'm going to close this for now, but please let us know if you're hitting issues other than these log messages.

**Closed by olix0r** 2022-04-19 16:53 UTC
Labels: bug
