### ISSUE TITLE
gRPC clients fail with proxy max-concurrence exhausted errors after upgrading to 2.9.1

### ISSUE THREAD

**Issue by n-oden** [linkerd/linkerd2#5541] opened 2021-01-14 16:34 UTC
### What is the issue?

After moving from linkerd edge-20.7.5 to stable-2.9.1, we see a large number of connections being blocked due to proxy max-concurrency errors.  This seems to center around (but not be entirely limited to) connections coming over a google internal LoadBalancer service.

### How can it be reproduced?

This happens consistently when we attempt to upgrade to 2.9.1. :(

### Logs, error output, etc

See [this thread on the linkerd slack](https://linkerd.slack.com/archives/C89RTCWJF/p1608587218114900)

### Environment

- Kubernetes Version: 1.16.15-gke.4300
- Cluster Environment: GKE
- Host OS: GKE CoS
- Linkerd version: stable-2.9.1

**Comment by olix0r** [comment] 2021-01-14 17:13
Can you share any details about the gRPC APIs in question? We haven't been able to reproduce this issue with our (admittedly simple) test gRPC applications.

**Comment by n-oden** [comment] 2021-01-14 18:55
@olix0r fair question; I've recently made some improvements to our grpc debugging tooling and am going to try to set up a time soon to re-attempt the upgrade and hopefully be able to get some better info out of it.

**Comment by cpretzer** [comment] 2021-01-14 22:09
Thiis may be related to #5183

**Comment by olix0r** [comment] 2021-01-15 01:14
As mentioned in the other issue:

> While debugging this today, we noticed something surprising: this error message is completely misleading. The underlying error doesn't actually indicate that the service is at capacity (so we've been trying debug a very different situation). Instead, this error signals, simply, that the proxy is in _failfast_. A service may enter failfast whenever it is unable to process requests for some amount of time---outbound=3s, inbound=1s. A load balancer, for instance, may have no endpoints; or, when no balancer is present, an individual endpoint may be down or otherwise not processing requests. The failfast mechanism is primarily intended to prevent the proxy from buffering requests indefinitely. If the service has been stuck in an unavailable state, we start serving error response immediately, rather than waiting a full timeout before the request fails.
>
> Recently (since 2.9.x), we've updated the proxy to include more descriptive failfast error messages, to indicate which layer of the proxy is in failfast. I've opened a PR to replace "max concurrency exhausted" with this more descriptive error message (https://github.com/linkerd/linkerd2-proxy/pull/847); and we'll revisit the data we have in light of this revelation.
>
> This is a high priority for us to address before stable-2.10.

I'm now less concerned about the details of the gRPC API... Instead, the output of `linkerd metrics` on a pod failing with these errors would probably be informative. Now that we have a clearer lead on this, we'll be adding diagnostics to the upcoming edge release(s) so that we can get a clearer plan of attack.

**Comment by n-oden** [comment] 2021-01-15 16:01
@olix0r interesting!  That definitely tracks with what we've been seeing -- one of the absolutely mystifying aspects of it was the fact that I could not even begin to imagine how we would have overrun a 100k-slot connection pool!

Given the current state of play, I think it makes sense for us to wait for an edge release that has https://github.com/linkerd/linkerd2-proxy/pull/847 merged into it (hopefully the next one?) and try again once that's in place.

**Comment by olix0r** [comment] 2021-01-15 23:28
We've merged linkerd/linkerd2-proxy#847 and linkerd/linkerd2-proxy#848 to main to help improve failfast diagnostics. I've built and pushed a container image for the proxy that includes these changes. It can be used with control planes from 2.9.x or recent edge releases.

```
spec:
  template:
    metadata:
      annotations:
        config.linkerd.io/proxy-image: ghcr.io/olix0r/l2-proxy
        config.linkerd.io/proxy-version: main.79c95af8
```

**Comment by n-oden** [comment] 2021-01-19 14:18
@olix0r that docker tag does not seem to exist?

```
$ docker pull ghcr.io/olix0r/l2-proxy
Using default tag: latest
Error response from daemon: name unknown
```

Also: can I apply those annotations at the namespace level or do they need to be made part of the spec for all deployments/statefulsets?

**Comment by olix0r** [comment] 2021-01-19 15:42
@n-oden Sorry about that. I've done some more debugging over the weekend and I have a branch that would be good for you to test:

**Comment by olix0r** [comment] 2021-01-25 23:06
We continue to work on diagnosing and reproducing this issue. We've made some changes to the inbound stack that may better highlight what's going on. I'd recommend testing with the following workload annotations:

```
config.linkerd.io/proxy-image: ghcr.io/olix0r/l2-proxy
config.linkerd.io/proxy-version: main.b8c2aa71
config.linkerd.io/proxy-log-level: linkerd_stack::switch_ready=debug,linkerd_reconnect=debug,linkerd_transport::connect=debug,linkerd=info,warn
```

**Comment by n-oden** [comment] 2021-01-29 20:09
@olix0r I attempted to roll `edge-21.1.4` out to our test environment today.  The instant symptom was that our internal IAM service was no longer able to talk to our pgbouncer service; the linkerd proxy log from one of the iam pods is attached.
[linker-proxy.log.gz](https://github.com/linkerd/linkerd2/files/5896082/linker-proxy.log.gz)

**Comment by n-oden** [comment] 2021-01-31 20:44
After a bit more fiddling around... I may have discovered something interesting. 

For reasons that can only be described as "historical silliness", our pgbouncer pods themselves listen on `6432/tcp`.  We run a pgbouncer _service_ that listens on `5432/tcp` (the standard postgres port) and round-robins connections to 6432 on the pods.

If I add the following annotation to the pgbouncer deployment template spec.. everything works!

```
        config.linkerd.io/skip-outbound-ports: "5432,6432"
        config.linkerd.io/skip-inbound-ports: "5432,6432"
        config.linkerd.io/proxy-log-level: linkerd_stack::switch_ready=debug,linkerd_reconnect=debug,linkerd_transport::connect=debug,linkerd=info,warn
```

Does the proxy special-case handling of 5432/tcp because we know that's commonly postgres?

I can now toggle the bad behavior on and off by removing or adding back `6432/tcp` to the pgbouncer skip-inbound/outbound-ports annotation.  When the port is not listed, the linkerd-proxy log is an endless spew of:

```
[    17.985802s]  INFO ThreadId(01) inbound:accept{peer.addr=10.20.3.115:38640 target.addr=10.20.6.145:6432}: linkerd_app_core::serve: Connection closed error=Protocol detection timeout after: 100B after 10.001611899s
```

**Comment by n-oden** [comment] 2021-01-31 21:02
Actually, a bit of further experimentation suggests that the problem isn't the port, it's protocol detection for postgres generally: other services that talk to pg (directly or via pgbouncer) show similar issues if we don't manually exempt the port.

```
[   214.958508s]  INFO ThreadId(01) outbound:accept{peer.addr=10.20.3.80:37344 target.addr=10.24.12.55:5432}: linkerd_app_core::serve: Connection closed error=Protocol detection timeout after: 110B after 10.001708338s
[   393.970684s]  INFO ThreadId(01) outbound:accept{peer.addr=10.20.3.80:42816 target.addr=10.24.12.55:5432}: linkerd_app_core::serve: Connection closed error=Protocol detection timeout after: 110B after 10.001121727s
[   707.999478s]  INFO ThreadId(01) outbound:accept{peer.addr=10.20.3.80:49800 target.addr=10.24.12.55:5432}: linkerd_app_core::serve: Connection closed error=Protocol detection timeout after: 110B after 10.000818737s
```

**Comment by adleong** [comment] 2021-02-03 00:42
Hi @n-oden!  In the edges since stable-2.9.x we've made changes to the way that protocol detection works.  If a client opens a connection but does not send enough information in order for Linkerd to detect the protocol within 10 seconds, it will fail the connection.  It seems that this is probably what is happening with your postgres client.

Thankfully, in recent edges you can mark certain ports as "opaque" which will tell the Linkerd proxy to skip protocol detection altogether and to treat the connection as an opaque byte stream.  Instructions can be found in the release notes: https://github.com/linkerd/linkerd2/releases/tag/edge-21.1.1

**Comment by adleong** [comment] 2021-02-10 21:12
As of [edge-21.2.1](https://github.com/linkerd/linkerd2/releases/tag/edge-21.2.1) the proxy behavior has changed back so that it no longer fails connections when they time out protocol detection.  @n-oden I recommend trying the latest edge to see how that works for you.

**Comment by adleong** [comment] 2021-02-17 20:03
@n-oden please feel free to re-open this issue if the latest edge release does not fix this.

**Closed by adleong** 2021-02-17 20:03 UTC

**Comment by joewilliams** [comment] 2021-02-25 19:27
I am running into similar max-concurrency errors after upgrading from 2.8.1 to 2.9.x.

```
[    62.711286s]  WARN ThreadId(01) outbound:accept{peer.addr=10.36.14.162:48562 target.addr=10.36.31.100:8080}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
```

We've tried ignoring ports to no avail.

```
config.linkerd.io/skip-inbound-ports: 8443,8080,25,443,587,3306,11211,5432
```

**Comment by joewilliams** [comment] 2021-02-25 21:38
Another data point in addition to the above. We use gloo as an ingress controller and if upgrade everything in our cluster to 2.9.3 but then set gloo proxy pods (like below) to use 2.8.1 everything works as expected. So I am wondering if this is due to some interaction between gloo and linkerd.

```
config.linkerd.io/proxy-version: stable-2.8.1
```

**Comment by joewilliams** [comment] 2021-02-25 23:14
Iterating through each version of the proxy it seems like 2.10.2 works fine but [2.10.3](https://github.com/linkerd/linkerd2/blob/e89dcca83f7e88b4776507c20afbff1e1f1d2176/CHANGES.md#edge-20103) we start seeing the errors.

**Comment by kleimkuhler** [comment] 2021-02-26 17:31
@joewilliams Are you able to to test more recent edges that exercise more current behavior of the proxy? I'd be curious if you still see this with `edge-21.2.3`.

You'll probably need to do more than setting the proxy version annotation; you may need to do an install/upgrade using that version since a lot of components have changed.

**Comment by joewilliams** [comment] 2021-02-26 17:54
@kleimkuhler I gave just changing the proxy version (I can't upgrade the cluster at the moment) a try and get similar but different error messages. The grpc client now says:
```
ERROR:
  Code: Unavailable
  Message: HTTP Server service in fail-fast
```

linkerd-proxy logs:
```
[    53.360779s]  WARN ThreadId(01) outbound:accept{client.addr=10.36.31.175:43900 target.addr=10.36.30.70:8080}: linkerd_timeout::failfast: HTTP Server entering failfast after 3s
[    53.360878s]  WARN ThreadId(01) outbound:accept{client.addr=10.36.31.175:43900 target.addr=10.36.30.70:8080}: linkerd_app_core::errors: Failed to proxy request: HTTP Server service in fail-fast
[    53.633194s] DEBUG ThreadId(01) outbound:accept{client.addr=10.36.31.175:43900 target.addr=10.36.30.70:8080}: linkerd_reconnect::service: Failed to connect error=received corrupt message
[    53.633246s] DEBUG ThreadId(01) outbound:accept{client.addr=10.36.31.175:43900 target.addr=10.36.30.70:8080}: linkerd_reconnect::service: Recovering
[    54.135428s] DEBUG ThreadId(01) outbound:accept{client.addr=10.36.31.175:43900 target.addr=10.36.30.70:8080}: linkerd_reconnect::service: Failed to connect error=received corrupt message
[    54.135470s] DEBUG ThreadId(01) outbound:accept{client.addr=10.36.31.175:43900 target.addr=10.36.30.70:8080}: linkerd_reconnect::service: Recovering
[    54.637969s] DEBUG ThreadId(01) outbound:accept{client.addr=10.36.31.175:43900 target.addr=10.36.30.70:8080}: linkerd_reconnect::service: Failed to connect error=received corrupt message
```

**Comment by kleimkuhler** [comment] 2021-02-26 18:08
@joewilliams Yea so unfortunately I think using the newer proxies is going to required upgrading the control plane as well.

The edge that we are releasing today should be a release candidate for `stable-2.10.0`. I'm not sure if we'll be spending more time on older proxy versions until we confirm this exists in current versions. I can update you when the stable is released and maybe try it then?

**Comment by joewilliams** [comment] 2021-02-26 18:23
@kleimkuhler thanks, since we have things working by running linkerd 2.9.3 but with 2.8.1 proxy on these pods I'll likely wait until 2.10 is out to try again. In terms of debugging the issue, rather than upgrading, can you think of some reason why linkerd would think the service is in fail-fast? That seems to be the common error here. I mentioned in the linkerd slack that my hunch is that something unknown is causing the fail-fast error, and the symptom originally was that requests weren't getting processed causing the client to see `proxy max-concurrency exhausted`. With the new proxy that still seems to be true but the `proxy max-concurrency exhausted` error message is now `HTTP Server service in fail-fast` which is more appropriate considering what we see in the linkerd-proxy logs, as well as the fact that in newer versions of the proxy the max in flight request limits have been increased from 10k to 100k, so it's far harder to trigger the concurrency error if a backend is in fail-fast. At the moment I don't see any reason why the service is in fail-fast and looking at [diffs](https://github.com/linkerd/linkerd2-proxy/compare/release/v2.102.0...release/v2.103.0) I haven't found anything outside of the max in flight request limit, but a lot has changed since 2.8.1 😅. Anyway, I think if we can figure out why it's in fail-fast and fix that this problem will be resolved.

**Comment by kleimkuhler** [comment] 2021-03-25 17:02
@joewilliams sorry that I did not get back to you on this. Around these releases, fail-fast errors were occurring for any one of several reasons and it was tough to get an idea about what exactly the issue was without more verbose logging.

`stable-2.10.0` has since been released which will fix your issue, so I'm hoping you will be okay upgrading to that.
