### ISSUE TITLE
proxy: with tls=optional, tcp_open_connections grows unbounded

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#1361] opened 2018-07-24 06:35 UTC
With `tls=optional`, the controller container seems to leak inbound connections:

![image](https://user-images.githubusercontent.com/240738/43120069-c5091486-8ecd-11e8-89a7-ca1a1f59d769.png)

Such a leak is not observed when TLS is not enabled:

![image](https://user-images.githubusercontent.com/240738/43119945-491398ce-8ecd-11e8-93c3-978afb9aaba9.png)

I cannot corroborate that this is an actual leak by comparing tcp_open_total / tcp_close_total, which makes me suspect this could be a metrics recording error?

**Comment by hawkw** [comment] 2018-07-24 17:17
I'd also be interested to see if there's an upward trend in `process_open_fds` as well.

**Comment by hawkw** [comment] 2018-07-24 18:09
I took a closer look at the stats, and based on what I saw, it's seeming more likely that this _is_ a leak (and not a metrics issue). Consider the following:

Here's a chart of the `tcp_open_connections` metric _and_ the difference between the `tcp_open_total` and `tcp_close_total` for the controller proxy's inbound router:
![screen shot 2018-07-24 at 11 03 00 am](https://user-images.githubusercontent.com/2796466/43157372-b39975f6-8f31-11e8-9494-21a9109490ed.png)
The two orange lines are the `{peer="src", tls="true"}` connections.

Here's the graph of open file descriptors:
![screen shot 2018-07-24 at 11 04 14 am](https://user-images.githubusercontent.com/2796466/43157424-db806412-8f31-11e8-843b-168f3cc8f863.png)
The yellow line is the controller proxy.

And here's the controller proxy's heatmap of connection durations:
![screen shot 2018-07-24 at 11 03 21 am](https://user-images.githubusercontent.com/2796466/43157441-eaa02f2c-8f31-11e8-8ee1-0619b2ea6ad0.png)

The upward trend in all these graphs implies that proxy may be leaking connections.

**Comment by hawkw** [comment] 2018-07-24 20:48
I have a strong suspicion this is due to improperly-written resources in `tokio_rustls`, which yield upon seeing a `WouldBlock` but fail to inform the reactor so they can be notified again. In at least some cases, nothing else ever notifies the task again, so it never finishes. The leaked tasks retain ownership of the TCP connections, so they are never closed.

I'm doing some testing to make sure the `tokio_rustls` bug is what's causing this issue.

**Comment by olix0r** [comment] 2018-07-24 21:10
I should note that we later realized that I wasn't on a recent master, so it's possible that this bug was fixed by the connection management changes in hyper.

**Comment by olix0r** [comment] 2018-07-25 00:29
I've also confirmed that I can reproduce this on v18.7.2

**Comment by hawkw** [comment] 2018-07-30 23:58
Okay, I can now reproduce this locally. It appears to occur only with connections that are over TLS, where the server peer sends the `Transfer-Encoding: chunked` amd `Connection: keep-alive` headers. When the client disconnects, it seems like the TCP connection to the client can fail to be shut down.

**Comment by briansmith** [comment] 2018-07-31 00:17
> Okay, I can now reproduce this locally. It appears to occur only with connections that are over TLS, where the server peer sends the `Transfer-Encoding: chunked` amd `Connection: keep-alive` headers. When the client disconnects, it seems like the TCP connection to the client can fail to be shut down.

Is it possible that the HTTP layer is trying to `shutdown()` the connection in this scenerio. If so, I'd examine the shutdown implementation in transport/tls.

/cc @seanmonstar

**Comment by hawkw** [comment] 2018-07-31 00:26
@briansmith I've been looking at the trace logs, and when a connection is leaked, it appears that `shutdown` is never called.

**Comment by grampelberg** [comment] 2018-12-03 22:51
Over to @hawkw for really specific replication steps.

**Comment by hawkw** [comment] 2018-12-05 19:19
I have some theories about this --- will continue digging.

**Comment by hawkw** [comment] 2018-12-11 22:41
Closing this issue, as with the current stable release (2.1) there's no longer a connection leak with TLS enabled. See also https://github.com/linkerd/linkerd2/issues/1950#issuecomment-445046012 etc.

**Closed by hawkw** 2018-12-11 22:41 UTC
Labels: area/proxy, area/tls, bug
