### ISSUE TITLE
Linkerd 2.10: No retry after timeout

### ISSUE THREAD

**Issue by JoergM** [linkerd/linkerd2#5963] opened 2021-03-28 10:03 UTC
### What is the issue?

When configuring a timeout and isRetryable at the same Route there will be no retry after a timeout. 

### How can it be reproduced?

Setup the booksapp demo as described in https://linkerd.io/2.10/tasks/books/. Do also setup the service profiles including the examples for retries and timeouts. 

Then `kubectl -n booksapp edit sp/books.booksapp.svc.cluster.local`

Change the settings for the GET route:

```
spec:
  routes:
  - condition:
      method: GET
      pathRegex: /books\.json
    isRetryable: true #ADD THIS
    name: GET /books.json
    timeout: 5ms # ADD THIS
```

Now watch the routes:

`watch linkerd viz -n booksapp routes deploy/webapp --to svc/books -o wide` 

You will see that the books-route will still fail in EFFECTIVE_SUCCESS even if there should be retries that fix this.

```
GET /books.json             books              62.11%          1.6rps          100.00%       1.0rps      4ms           7ms          10ms
```
Depending on your runtime environment you might change the timeout value to something different to see timeout effects. You can also try to see a difference between isRetryable enabled and not. You will not see any.

I have also tested this in a private application where I could trace the call received on server side. When there was a request that took too long then there was definitely not a second request that would have resulted from a retry.

### Logs, error output, etc

see above

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √

Linkerd extensions checks
=========================

linkerd-jaeger
--------------
√ linkerd-jaeger extension Namespace exists
√ collector and jaeger service account exists
√ collector config map exists
√ jaeger extension pods are injected
√ jaeger extension pods are running

Status check results are √

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ prometheus is installed and configured correctly
√ can initialize the client
√ viz extension self-check

Status check results are √

```

### Environment

- Kubernetes Version: 1.18
- Cluster Environment: GKE
- Host OS: Container Optimized by GCP
- Linkerd version: 2.10

**Comment by adleong** [comment] 2021-03-29 20:32
Hi @JoergM!  This is the intended behavior.  The timeout applies to the request in its totality, including retries.  This behavior and the motivation behind it is described here: https://linkerd.io/2.10/features/retries-and-timeouts/

**Comment by JoergM** [comment] 2021-03-30 16:30
@adleong Thanks for the answer I have actually read the linked documentation several times before, but only after your answer I read it as an overall timeout. It is stated very indirectly. Would it make sense to state this fact in a more direct way in the documentation? Maybe I am not the only one who doesn't get it. 

The comment in the service profile template also doesn't mention retries: 
```
# A route can define a request timeout.  Any requests to this route that
# exceed the timeout will be canceled.  If unspecified, the default timeout
# is '10s' (ten seconds).
```
If you are interested I can create PRs with suggested changes.

Also would a feature request to implement retries after timeout with additional timeouts per try have any chance of success? 

The pattern of retrying a request after it timed out is a pretty common one. And as I understand it now this is something the application has to take care of. This feels inconsistent as for other errors the service mesh handles retries on its own.

**Comment by adleong** [comment] 2021-03-30 18:50
We'd absolutely welcome a docs PR to help make this more explicit.

As for adding retries after the timeout, we're open to discussion.  The most important questions to address would be: exactly what problem are you trying to solve, and can that problem be solved with existing tools?

**Comment by JoergM** [comment] 2021-03-31 08:29
Ok. I will create the PRs and a feature request. It will probably take some days.

**Comment by olix0r** [comment] 2021-04-01 17:16
I'm closing this issue for now, but please let us know if you run into any more problems!

**Closed by olix0r** 2021-04-01 17:16 UTC
