### ISSUE TITLE
Traffic mirroring / shadowing

### ISSUE THREAD

**Issue by michalschott** [linkerd/linkerd2#11027] opened 2023-06-16 13:04 UTC
### What problem are you trying to solve?

I have a use case, where I need to send the same HTTP request to two upstreams - this is essentially traffic mirroring / shadowing.

### How should the problem be solved?

https://istio.io/latest/docs/tasks/traffic-management/mirroring/

I'll leave technical implementation to you ;)

### Any alternatives you've considered?

custom rev-proxy which intercepts request and sends it to destinations

### Would you like to work on this feature?

no

**Comment by adleong** [comment] 2023-06-20 22:54
Thanks for filing this, @michalschott; I think this is probably a duplicate of https://github.com/linkerd/linkerd2/issues/4385

As you can see, traffic shadowing has been something we've been interested in doing for a long time, but it's never risen to the top of our priority list.  I don't think it's something we'll add in the timeframe of the next release or two, but our work to adopt the Gateway API for configuring client policy does set us up very nicely for adding this kind of functionality in the future.

**Closed** 2023-06-21 08:10 UTC
Labels: enhancement
