### ISSUE TITLE
Panic when running `linkerd install --ignore-cluster` on latest edge

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#8374] opened 2022-04-29 19:48 UTC
### What is the issue?

I have a cluster running the previous edge (22.35) and the CLI that was released with the latest edge (22.4.1). When I run `linkerd install --ignore-cluster`, it panics with "invalid memory address or nil pointer dereference".

I've also tested it on a cluster running the current edge, and it still panics.

### How can it be reproduced?

Install the latest linked edge on your cluster, then run `linkerd install --ignore-cluster`

### Logs, error output, etc

```
$ linkerd install --ignore-cluster                                                                    
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x25f703d]

goroutine 1 [running]:
github.com/linkerd/linkerd2/cli/cmd.install({0x2df4918, 0xc0001b2008}, 0x0, {0x2db6040, 0xc0001ac008}, 0xc000773d78, {0xc000379600, 0xc0001c3f00, 0xc000773d50}, 0x0, ...)
	/linkerd-build/cli/cmd/install.go:160 +0x7d
github.com/linkerd/linkerd2/cli/cmd.newCmdInstall.func1(0xc00012d680, {0xc00007f370, 0x1, 0x1})
	/linkerd-build/cli/cmd/install.go:131 +0x2e8
github.com/spf13/cobra.(*Command).execute(0xc00012d680, {0xc00007f360, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x3f15f00)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/linkerd-build/cli/main.go:37 +0x279
```

### output of `linkerd check -o short`

```
$ linkerd check -o short
Status check results are √
```

### Environment

```
$ linkerd version --short
edge-22.4.1
edge-22.4.1
$ kubectl version --short
Client Version: v1.22.5
Server Version: v1.22.6+k3s1
```

**Comment by alpeb** [comment] 2022-04-29 19:54
Dupe of #8364 :-P

**Closed by alpeb** 2022-04-29 19:54 UTC
Labels: bug
