### ISSUE TITLE
linkerd-control-plane pods fail with linkerd-cni and proxy.nativeSidecar enabled

### ISSUE THREAD

**Issue by krzysztof-mitus** [linkerd/linkerd2#12391] opened 2024-04-04 09:19 UTC
### What is the issue?

Helm chart linkerd-control-plane install fails when having cniEnabled=true and proxy.nativeSidecar=true.
Both linkerd-destination and linkerd-proxy-injector fail on linkerd-network-validator container in CrashLoopBackOff state with the following log:

```
2024-04-04T08:59:17.257953Z  INFO linkerd_network_validator: Listening for connections on 0.0.0.0:4140
2024-04-04T08:59:17.257986Z DEBUG linkerd_network_validator: token="PqBwBvtO5lWbgVvHjaZ0MQQTqqZwjmkfQPtxoK4iysvQ5KG0zyDpEWQtpoZXfLU\n"
2024-04-04T08:59:17.257993Z  INFO linkerd_network_validator: Connecting to 1.1.1.1:20001
2024-04-04T08:59:27.259562Z ERROR linkerd_network_validator: Failed to validate networking configuration. Please ensure iptables rules are rewriting traffic as expected. timeout=10s
```

### How can it be reproduced?

1. On EKS 1.29 install helm charts:

- linkerd-crds 2024.3.5
- linkerd2-cni 2024.3.5
- linkerd-control-plane 2024.3.5

2. linkerd-control-plane helm values:

- cniEnabled: true
- proxy.nativeSidecar: true

### Logs, error output, etc

see above

### output of `linkerd check -o short`

× control plane pods are ready

### Environment

- EKS 1.29
- Bottlerocket OS 1.19.3 (aws-k8s-1.29)

### Possible solution

Issue probably caused by the code:
https://github.com/linkerd/linkerd2-proxy-init/blob/main/cni-plugin/main.go#L196

See [slack](https://linkerd.slack.com/archives/C89RTCWJF/p1711721675731259)

### Additional context

Control plane pods are running when proxy.nativeSidecar: false. Enabling the feature causes pods failure.

### Would you like to work on fixing this bug?

None

**Comment by mateiidavid** [comment] 2024-04-04 13:14
@krzysztof-mitus thanks for raising this! So, if I understand correctly, the problem is that when you use `nativeSidecar` you still get the init container when you shouldn't, since it's supposed to be disabled through `cniEnabled`?

**Comment by alpeb** [comment] 2024-04-04 17:34
I've pushed a fix to linkerd/linkerd2-proxy-init#362.
@krzysztof-mitus pending a linkerd-cni release, you can give this a try with the image I published `ghcr.io/alpeb/cni-plugin:v1.4.1` that contains that fix.

**Comment by msuszko-vertex** [comment] 2024-04-05 12:17
I can confirm https://github.com/linkerd/linkerd2-proxy-init/pull/362 does help. Linkerd 2024.4.1 with `proxy.nativeSidecar: true` and `cniEnabled: true` runs `linkerd-network-validator` initContainer successfully.

**Comment by krzysztof-mitus** [comment] 2024-04-05 12:22
thanks for quick resolution and test

**Closed** 2024-04-10 23:17 UTC
Labels: bug
