### ISSUE TITLE
Getting started demo does not work

### ISSUE THREAD

**Issue by asad-awadia** [linkerd/linkerd2#1924] opened 2018-12-04 22:37 UTC
### What is the issue?

Following the getting started demo steps doesn't work as expected on docker for mac edge kubernetes

### How can it be reproduced?

Follow the steps as is from here `https://linkerd.io/2/getting-started/`

### Logs, error output, etc
```
$ kubectl -n linkerd logs -f prometheus-66fb47b7d6-q6phq prometheus

level=error ts=2018-12-04T21:31:53.943962383Z caller=main.go:234 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:306: Failed to list *v1.Pod: Get https://10.96.0.1:443/api/v1/namespaces/linkerd/pods?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused"

```

```
$ kubectl -n linkerd logs -f controller-6b4d8db598-qxpcb public-api
time="2018-12-04T21:59:29Z" level=error msg="Query(max(process_start_time_seconds{}) by (pod, namespace)) failed with: Get http://prometheus.linkerd.svc.cluster.local:9090/api/v1/query?query=max%28process_start_time_seconds%7B%7D%29+by+%28pod%2C+namespace%29: dial tcp 127.0.0.1:9090: connect: connection refused"
time="2018-12-04T22:32:31Z" level=error msg="Query(max(process_start_time_seconds{}) by (pod, namespace)) failed with: Get http://prometheus.linkerd.svc.cluster.local:9090/api/v1/query?query=max%28process_start_time_seconds%7B%7D%29+by+%28pod%2C+namespace%29: dial tcp 127.0.0.1:9090: connect: connection refused"
```

#### `linkerd check` output

```text
kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[ok]
kubernetes-api: is running the minimum Kubernetes API version..............[ok]
linkerd-api: control plane namespace exists................................[ok]
linkerd-api: control plane pods are ready..................................[ok]
linkerd-api: can initialize the client.....................................[ok]
linkerd-api: can query the control plane API...............................[ok]
linkerd-api[kubernetes]: control plane can talk to Kubernetes..............[ok]
linkerd-api[prometheus]: control plane can talk to Prometheus..............[FAIL] -- Error calling Prometheus from the control plane: Get http://prometheus.linkerd.svc.cluster.local:9090/api/v1/query?query=max%!p(MISSING)rocess_start_time_seconds%!B(MISSING)%!D(MISSING)%!+(MISSING)by+%!p(MISSING)od%!C(MISSING)+namespace%!:(MISSING) dial tcp 127.0.0.1:9090: connect: connection refused

Status check results are [FAIL]
```

### Environment

- Kubernetes Version:
```
➜  ~ kubectl version --short
Client Version: v1.10.3
Server Version: v1.10.3
```

- Cluster Environment: (GKE, AKS, kops, ...)
Docker for mac edge

- Host OS: Mac OS X - High Sierra 10.13.4

- Linkerd version:
```
➜  ~ linkerd version
Client version: stable-2.0.0
Server version: stable-2.0.0
```

### Possible solution
¯\_(ツ)_/¯

### Additional context

Looks like Linkerd is having trouble accessing the Kubernetes HTTP API and accessing Prometheus either because Prometheus pods aren't set up right or the DNS entry is messed - most likely the former

 I have tried with a fresh install of docker edge and I get the same thing each time

**Comment by grampelberg** [comment] 2018-12-04 22:50
@asad-awadia any more details? I just tested on a fresh `2.0.0.0-mac82 (29268)` (k8s v1.10.3) and everything worked.

There are some connection refused lines, but those are expected as the sidecar proxy starts up.

**Comment by asad-awadia** [comment] 2018-12-04 22:54
@grampelberg any other commands you want me to run and paste the output? I don't know what else might be relevant

**Comment by asad-awadia** [comment] 2018-12-05 16:23
@grampelberg  I am installing it with the steps listed on the getting started page

```
11384  curl -sL https://run.linkerd.io/install | sh\n
11385  export PATH=$PATH:$HOME/.linkerd2/bin\n
11386  linkerd version\n
11387  linkerd check --pre\n
11388  linkerd install | kubectl apply -f -\n
11389  linkerd check\n
```

[Output of kubectl get ...](https://gist.github.com/asad-awadia/2351c0869c669a4519eb0e1b0829817b)

**Comment by grampelberg** [comment] 2018-12-05 16:39
That all looks right to me....

What does check look like after you've waited for awhile? Can you run a pod in the linkerd namespace and hit the API server (kubectl would be great)?

**Comment by asad-awadia** [comment] 2018-12-05 18:04
>What does check look like after you've waited for awhile?

```
➜  ~ linkerd check
kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[ok]
kubernetes-api: is running the minimum Kubernetes API version..............[ok]
linkerd-api: control plane namespace exists................................[ok]
linkerd-api: control plane pods are ready..................................[ok]
linkerd-api: can initialize the client.....................................[ok]
linkerd-api: can query the control plane API...............................[ok]
linkerd-api[kubernetes]: control plane can talk to Kubernetes..............[ok]
linkerd-api[prometheus]: control plane can talk to Prometheus..............[FAIL] -- Error calling Prometheus from the control plane: Get http://prometheus.linkerd.svc.cluster.local:9090/api/v1/query?query=max%!p(MISSING)rocess_start_time_seconds%!B(MISSING)%!D(MISSING)%!+(MISSING)by+%!p(MISSING)od%!C(MISSING)+namespace%!:(MISSING) dial tcp 127.0.0.1:9090: connect: connection refused

Status check results are [FAIL]
```

>Can you run a pod in the linkerd namespace 

Yes 

>and hit the API server (kubectl would be great)?

Assuming I understand what you are saying correctly - No I cannot

```
/usr/src/app # KUBE_TOKEN=$(</var/run/secrets/kubernetes.io/serviceaccount/token)
/usr/src/app # curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" \
>       https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/linkerd/pods/$HOSTNAME

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "pods \"hello-kubernetes-548c65944-d8l5n\" is forbidden: User \"system:anonymous\" cannot get pods in the namespace \"linkerd\"",
  "reason": "Forbidden",
  "details": {
    "name": "hello-kubernetes-548c65944-d8l5n",
    "kind": "pods"
  },
  "code": 403
```

**Comment by asad-awadia** [comment] 2018-12-07 16:58
Yes - the pods restart but linkerd check gives the same error


```
linkerd-api[prometheus]: control plane can talk to Prometheus..............[FAIL] -- Error calling 
Prometheus from the control plane: Get http://prometheus.linkerd.svc.cluster.local:9090/api/v1/query?
query=max%!p(MISSING)rocess_start_time_seconds%!B(MISSING)%!D(MISSING)%!+
(MISSING)by+%!p(MISSING)od%!C(MISSING)+namespace%!:(MISSING) dial tcp 127.0.0.1:9090: 
connect: connection refused
```

**Comment by klingerf** [comment] 2018-12-17 22:32
@asad-awadia We released [Linkerd stable 2.1](https://github.com/linkerd/linkerd2/releases/tag/stable-2.1.0) last week. Would you mind trying that out to see if it fixes the issue you were seeing with 2.0 in your environment?

**Comment by AnujKS** [comment] 2019-01-12 11:42
Still happening in version 2.1

**Comment by renner-osi** [comment] 2019-01-14 15:33
@AnujKS i had same issue and root cause in my case was the cluster name was not the default. Resolved by first putting linkerd install > into a filename such as ```linkerd install > l5d-manifest.yml```  then sed replacing all cases of cluster.local with my actual cluster name. `sed 's/cluster.local/mycluster.io/' `

**Comment by pms1969** [comment] 2019-01-29 11:08
I've just found my way here and am experiencing the same problem.

trying edge-19.1.3 I get the following output from `linkerd check`
```
$ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ can query the control plane API
√ [kubernetes] control plane can talk to Kubernetes
× [prometheus] control plane can talk to Prometheus
    Error calling Prometheus from the control plane: Get http://linkerd-prometheus.linkerd.svc.cluster.local:9090/api/v1/query?query=max%!p(MISSING)rocess_start_time_seconds%!B(MISSING)%!D(MISSING)%!+(MISSING)by+%!p(MISSING)od%!C(MISSING)+namespace%!:(MISSING) dial tcp: lookup linkerd-prometheus.linkerd.svc.cluster.local on 10.3.0.10:53: no such host

Status check results are ×
```

[linkerd.log](https://github.com/linkerd/linkerd2/files/2807351/linkerd.log)

That's using `linkerd install --ha --image-pull-policy=Always --tls=optional --proxy-auto-inject | kubectl apply -f -` to install, but I've tried with a vanilla install and get the same results.

**Comment by grampelberg** [comment] 2019-01-29 16:37
@pms1969 can you curl that endpoint from inside a container running in `linkerd-controller`?

**Comment by pms1969** [comment] 2019-01-30 04:09
@grampelberg this is what I get:
```
$ k -n linkerd exec linkerd-controller-987b67747-n64nx public-api -- curl http://linkerd-prometheus.linkerd.svc.cluster.local:9090                   
Defaulting container name to public-api.                                                                                                             
Use 'kubectl describe pod/linkerd-controller-987b67747-n64nx -n linkerd' to see all of the containers in this pod.                                   
time="2019-01-30T04:06:46Z" level=info msg="running version edge-19.1.3"                                                                             
time="2019-01-30T04:06:46Z" level=info msg="waiting for caches to sync"                                                                              
time="2019-01-30T04:06:46Z" level=info msg="caches synced"                                                                                           
time="2019-01-30T04:06:46Z" level=info msg="starting admin server on :9995"                                                                          
time="2019-01-30T04:06:46Z" level=info msg="starting HTTP server on :8085"                                                                           
time="2019-01-30T04:06:46Z" level=fatal msg="listen tcp :9995: bind: address already in use"                                                         
command terminated with exit code 1           
```

**Comment by pms1969** [comment] 2019-01-30 04:32
ok.  by `sed`ing the install output to change `cluster.local` to my cluster suffix, and then piping it into kubectl, it now works as expected.

```
$ linkerd check                                                                                                                                     
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ can query the control plane API
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus

linkerd-service-profile
-----------------------
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

**Comment by grampelberg** [comment] 2019-01-30 16:50
That explains it, please see #1720 and #1741. I'm going to close this out for now. Please open up a separate issue if you're still having troubles!

**Closed by grampelberg** 2019-01-30 16:50 UTC
Labels: bug, needs/more
