### ISSUE TITLE
linkerd viz dashboard (cannot find Kubernetes canonical name from friendly name [trafficsplit])

### ISSUE THREAD

**Issue by eddie-huhu** [linkerd/linkerd2#9969] opened 2022-12-08 04:19 UTC
### What is the issue?

500 An error has occurred.
cannot find Kubernetes canonical name from friendly name [trafficsplit]
https://linkerd.hex.guru/api/tps-reports?resource_type=trafficsplit&namespace=default&tcp_stats=true&window=1m

### How can it be reproduced?

![image](https://user-images.githubusercontent.com/65880317/206384646-3b474c66-7e48-42c5-b0f9-7af8879be52d.png)

### Logs, error output, etc

500 An error has occurred.
cannot find Kubernetes canonical name from friendly name [trafficsplit]
https://linkerd.hex.guru/api/tps-reports?resource_type=trafficsplit&namespace=default&tcp_stats=true&window=1m

### output of `linkerd check -o short`

linkerd-identity
----------------
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2022-12-08T04:51:43Z
    see https://linkerd.io/2.12/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints

linkerd-webhooks-and-apisvc-tls
-------------------------------
‼ proxy-injector cert is valid for at least 60 days
    certificate will expire on 2022-12-09T01:36:39Z
    see https://linkerd.io/2.12/checks/#l5d-proxy-injector-webhook-cert-not-expiring-soon for hints
‼ sp-validator cert is valid for at least 60 days
    certificate will expire on 2022-12-09T01:36:39Z
    see https://linkerd.io/2.12/checks/#l5d-sp-validator-webhook-cert-not-expiring-soon for hints
‼ policy-validator cert is valid for at least 60 days
    certificate will expire on 2022-12-09T01:36:39Z
    see https://linkerd.io/2.12/checks/#l5d-policy-validator-webhook-cert-not-expiring-soon for hints

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.12.1 but the latest stable version is 2.12.2
    see https://linkerd.io/2.12/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane and cli versions match
    control plane running stable-2.12.2 but cli running stable-2.12.1
    see https://linkerd.io/2.12/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies and cli versions match
    linkerd-destination-7f95496b94-266x7 running stable-2.12.2 but cli running stable-2.12.1
    see https://linkerd.io/2.12/checks/#l5d-cp-proxy-cli-version for hints

linkerd-ha-checks
-----------------
‼ pod injection disabled on kube-system
    kube-system namespace needs to have the label config.linkerd.io/admission-webhooks: disabled if injector webhook failure policy is Fail
    see https://linkerd.io/2.12/checks/#l5d-injection-disabled for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ tap API server cert is valid for at least 60 days
    certificate will expire on 2022-12-09T01:36:39Z
    see https://linkerd.io/2.12/checks/#l5d-tap-cert-not-expiring-soon for hints
‼ viz extension proxies and cli versions match
    grafana-54c8c4c4bc-szvpz running stable-2.12.2 but cli running stable-2.12.1
    see https://linkerd.io/2.12/checks/#l5d-viz-proxy-cli-version for hints
‼ prometheus is installed and configured correctly
    missing ClusterRoles: linkerd-linkerd-viz-prometheus
    see https://linkerd.io/2.12/checks/#l5d-viz-prometheus for hints

Status check results are √

### Environment

GKE
kubernetes version:1.22.15-gke.100
linkerd version : linkerd 2.12.2 (stable)

### Would you like to work on fixing this bug?

yes

**Comment by adleong** [comment] 2022-12-08 17:39
Closing as duplicate of https://github.com/linkerd/linkerd2/issues/9554

**Closed by adleong** 2022-12-08 17:39 UTC
Labels: area/web, priority/P1, bug, needs/design
