### ISSUE TITLE
Mirror service endpoint updates seem inconsistent

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#4549] opened 2020-06-03 22:03 UTC
### What is the issue?

I've been struggling to get my gateway healthy. While it was unhealthy, I had a successfully mirrored service `podinfo-east` in the source cluster without any endpoints. After making the gateway healthy (as validated by watching the service-mirror logs), no endpoints showed up on `podinfo-east`. Deleting and recreating the annotations on the target cluster's `podinfo` fixed the issue.

On the other side of things, after I'd seen `podinfo-east` working, I deleted the probe port in the target cluster's gateway. This caused the gateway to go unhealthy (as observed by watching the service-mirror logs) but did not remove the endpoints from `podinfo-east`.

**Comment by grampelberg** [comment] 2020-06-03 22:05
Note: removing the annotations from `podinfo` in the target cluster *does* remove the mirrored service from the source cluster.

**Comment by zaharidichev** [comment] 2020-06-04 08:44
What was the initial state. If it was unhealthy because it did not have an IP address yet, then yes it is realted to the race condition

**Comment by cpretzer** [comment] 2020-06-08 20:27
I ran some tests on `edge-20.6.2` and am still seeing the endpoints when the target gateway is unhealthy.

Starting with a healthy multicluster setup using podinfo, I ran these tests:

- Removed the `mc-probe` port from the linkerd-gateway service in the target cluster
-- The `podinfo-east` endpoint was not removed from the source cluster and `linkerd check --multicluster` reported the gateway as healthy. `linkerd mc gateways` also reported a healthy target gateway

- deleted the annotations from the `podinfo` service in the target cluster
-- The `podinfo-east` endpoint was removed from the source cluster

- added the annotations to the `podinfo` service in the target cluster
-- the `podinfo-east` endpoint was added to the source cluster

- changed the `mc-probe` port in the `linkerd-gateway` service on the target cluster to `4182`
-- the source service mirror marked the target gateway as unhealthy
-- the `linkerd check --multicluster` output showed the gateway as unhealthy
-- the `podinfo-east` endpoint was not removed from the source cluster

- after reverting the port to `4181` the `linkerd-gateway-east` service in the source cluster had a port of `4182`. Attempts to update the `linkerd-gateway` service in the target cluster did not update the port of the `linkerd-gateway-east` service in the source cluster
-- Deleting the `linkerd-gateway-east` service from the source cluster, then adding a benign label to the `linkerd-gateway` service in the target cluster, forced the service to be recreated with the correct port

After these tests, the endpoint management appears to not work and the service management for the probes shows similar behavior of not being updated properly.

**Comment by cpretzer** [comment] 2020-06-08 21:24
> after reverting the port to 4181 the linkerd-gateway-east service in the source cluster had a port of 4182. Attempts to update the linkerd-gateway service in the target cluster did not update the port of the linkerd-gateway-east service in the source cluster
-- Deleting the linkerd-gateway-east service from the source cluster, then adding a benign label to the linkerd-gateway service in the target cluster, forced the service to be recreated with the correct port

Ran another test for longer and this behavior isn't happening now. Per @grampelberg I may not have waited long enough for the gateway to be marked as healthy

**Comment by cpretzer** [comment] 2020-06-08 22:49
I ran some more tests and can confirm that the endpoints are *not* removed when the gateway is marked as unhealthy. Is this the expected behavior?

**Comment by cpretzer** [comment] 2020-06-08 23:08
Okay, so based on [this logic](https://github.com/linkerd/linkerd2/blob/master/controller/cmd/service-mirror/probe_worker.go#L102), it looks like there is no change to the configuration when the gateway goes in and out of the healthy state.

The events to create endpoints are generated when the service to be mirrored is [updated](https://github.com/linkerd/linkerd2/blob/master/controller/cmd/service-mirror/cluster_watcher.go#L812).

So, I think everything is working as designed and we can close this.

**Closed** 2020-06-17 00:19 UTC
Labels: area/multicluster, priority/P0
