### ISSUE TITLE
Linkerd2 viz dashboard not working on microsoft edge (chromium)

### ISSUE THREAD

**Issue by kirinnee** [linkerd/linkerd2#5753] opened 2021-02-16 14:40 UTC
## Bug Report
Linkerd2 viz dashboard not working on Microsoft edge chromium 

### What is the issue?
CSS Crashes

### How can it be reproduced?
On width larger than `992px` on Microsoft edge chromium with dashboard deployed.

### Logs, error output, etc
Browser console error:
```
main.4c9e27fff3e3bb634814.js:24407 TypeError: Failed to execute 'px' on 'CSS': The provided double value is non-finite.
    at rt (main.4c9e27fff3e3bb634814.js:2723)
    at Array.onProcessStyle (main.4c9e27fff3e3bb634814.js:2723)
    at e.t.onProcessStyle (main.4c9e27fff3e3bb634814.js:1)
    at e.t.onProcessRule (main.4c9e27fff3e3bb634814.js:1)
    at Array.forEach (<anonymous>)
    at e.t.process (main.4c9e27fff3e3bb634814.js:1)
    at new e (main.4c9e27fff3e3bb634814.js:1)
    at e.t.createStyleSheet (main.4c9e27fff3e3bb634814.js:1)
    at vn (main.4c9e27fff3e3bb634814.js:2723)
    at main.4c9e27fff3e3bb634814.js:2723
```
```
main.4c9e27fff3e3bb634814.js:2723 Uncaught TypeError: Failed to execute 'px' on 'CSS': The provided double value is non-finite.
    at rt (main.4c9e27fff3e3bb634814.js:2723)
    at Array.onProcessStyle (main.4c9e27fff3e3bb634814.js:2723)
    at e.t.onProcessStyle (main.4c9e27fff3e3bb634814.js:1)
    at e.t.onProcessRule (main.4c9e27fff3e3bb634814.js:1)
    at Array.forEach (<anonymous>)
    at e.t.process (main.4c9e27fff3e3bb634814.js:1)
    at new e (main.4c9e27fff3e3bb634814.js:1)
    at e.t.createStyleSheet (main.4c9e27fff3e3bb634814.js:1)
    at vn (main.4c9e27fff3e3bb634814.js:2723)
    at main.4c9e27fff3e3bb634814.js:2723
```

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2021-03-11T05:08:12Z
    see https://linkerd.io/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 21.2.1 but the latest edge version is 21.2.2
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 21.2.1 but the latest edge version is 21.2.2
    see https://linkerd.io/checks/#l5d-version-control for hints
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.20
- Cluster Environment: k3s
- Host OS: ubuntu 20.04 (AWS)
- Linkerd version: edge-21.2.1

### Possible solution
rescale to below 992px screen width

### Additional context
Screen Width: 1920 x 1080
Edge version: Version 88.0.705.68 (Official build) (64-bit)

**Comment by kellycampbell** [comment] 2021-02-16 17:34
Duplicate of #5612

**Comment by kleimkuhler** [comment] 2021-02-16 22:09
Yep this is a duplicate so I'll close this since we are tracking there.

**Closed by kleimkuhler** 2021-02-16 22:09 UTC
