### ISSUE TITLE
APIService swagger specs

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#4209] opened 2020-03-27 22:10 UTC
### What is the issue?

It appears that some k8s clients assume APIServices expose swagger specs. If they don't get the spec, crashes happen. See:

- https://github.com/godaddy/kubernetes-external-secrets/issues/278
- #4116 

### How can it be reproduced?

- Install Linkerd and then add external secrets.
- Start GKE cluster with calico.

### Possible solution

Have the `tap` and `smi-metrics` APIServices return swagger profiles.

**Comment by siggy** [comment] 2020-03-27 22:15
It might be as simple as adding something like:
```go
router.GET("/swagger.json", handleSwagger)
```
to:
https://github.com/linkerd/linkerd2/blob/3088f404cec1c33349acfc07e6dc8aad8e0d179f/controller/tap/handlers.go#L78-L87

**Comment by dad264** [comment] 2020-04-01 12:50
This issue has caused trouble for us as we are users of [KES](https://github.com/godaddy/kubernetes-external-secrets/). Luckily, it's just in our QA environment right now. Would your recommendation be to roll back to https://github.com/linkerd/linkerd2/releases/tag/stable-2.6.1 so we can get back up and running?

**Comment by grampelberg** [comment] 2020-04-01 16:26
@dad264 the work around is to just install Linkerd after KES.

**Comment by dad264** [comment] 2020-04-01 16:28
If KES restarts, I don't believe it will start up again.

**Comment by dad264** [comment] 2020-04-01 19:16
Worked around it [like this](https://github.com/godaddy/kubernetes-external-secrets/issues/278#issuecomment-607440992)

**Comment by kleimkuhler** [comment] 2020-04-11 00:13
So I do not think this an issue about the routes that the tap API service exposes.

Between 2.6.1 and 2.7, the Linkerd tap endpoints started showing up in the response from `openapi/v2`:

```
curl localhost:port/openapi/v2 | jq .
..
    "/apis/tap.linkerd.io": {
      "get": {
            ..
        }
      }
    },
    "/apis/tap.linkerd.io/v1alpha1": {
      "get": {
            ..
        }
      }
    },
..
```

These returned endpoints do not have an `operationID` field which is not required.

This is an issue because as one of comments mentions in godaddy/kubernetes-external-secrets#278, a dependency *expects* an `operationID` to be present ([code](https://github.com/silasbw/swagger-fluent/blob/master/lib/loader.js#L223)).

To fix this, Linkerd can add an `operationID` field to tap's `/openapi/v2` response. I've confirmed this works in d314212e980c029dd577d9f43e376a33539d3ce5.

We can add this field so it does not cause downstream errors, but I think this should ultimately be fixed in [swagger-fluent](https://github.com/silasbw/swagger-fluent/) which KES depends on.

**Comment by cpretzer** [comment] 2020-04-11 22:14
Awesome find @kleimkuhler. I missed the `operationID` field. Reviewing your PR now.

**Comment by kleimkuhler** [comment] 2020-04-20 18:05
This title of this issue is a little different than what was changed in #4245, but the issues described are closed by that change. I do not think the tap service needs a `/swagger` endpoint.

**Closed by kleimkuhler** 2020-04-20 18:05 UTC
Labels: area/controller, bug, priority/P0
