### ISSUE TITLE
Check doesn't pass Prometheus

### ISSUE THREAD

**Issue by okian** [linkerd/linkerd2#2282] opened 2019-02-14 01:14 UTC
### What is the issue?
I'm trying to install linkerd in bare-metal kubernetes cluster but  seems like there is a problem with Prometheus. in ```linkerd check``` log! it seems like it's looking for ```cluster.local``` but the cluster name is ```cyb.local```. i'm not sure if that's the problem or not. prior to this i had installed Prometheus in another namespace so i tried to edit ```linkerd-prometheus```  service and change its type to ```ExternalName``` and direct it to my current healthy instance of prometheus  but it didn't change anything.
### How can it be reproduced?
I just ran 
linkerd check --pre 
in my first attempt  
linkerd install |kubectl apply -f - 
second time (after deleting linkerd namespace)
linkerd install  --proxy-auto-inject |kubectl apply -f - 

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ can query the control plane API
√ [kubernetes] control plane can talk to Kubernetes
× [prometheus] control plane can talk to Prometheus
    Error calling Prometheus from the control plane: Get http://linkerd-prometheus.linkerd.svc.cluster.local:9090/api/v1/query?query=max%!p(MISSING)rocess_start_time_seconds%!B(MISSING)%!D(MISSING)%!+(MISSING)by+%!p(MISSING)od%!C(MISSING)+namespace%!:(MISSING) dial tcp: lookup linkerd-prometheus.linkerd.svc.cluster.local on 10.233.0.3:53: no such host
    see https://linkerd.io/checks/#l5d-api-control-api for hints

```text
your output here ...
```

### Environment

- Kubernetes Version: 
Client Version: v1.11.2
Server Version: v1.12.2
- Cluster Environment: (GKE, AKS, kops, ...)
Bare-metal
- Host OS:
Ubuntu 16.04
- Linkerd version:
Client version: stable-2.2.0
Server version: stable-2.2.0

**Comment by klingerf** [comment] 2019-02-14 02:15
@okian Thanks for reporting this. The issue is that linkerd doesn't currently allow configuration of the cluster base domain, as described in #1720. Some users have reported that hand-editing the linkerd install YAML to replace "cluster.local" with "cyb.local" globally would fix your issue, but #1720 tracks adding actual support for alternate base domains. Am going to close this issue in favor of that one.

**Closed by klingerf** 2019-02-14 02:15 UTC
