### ISSUE TITLE
TCP connection hangs indefinitely

### ISSUE THREAD

**Issue by Rishka** [linkerd/linkerd2#1505] opened 2018-08-22 18:15 UTC
Was testing out https://github.com/contribsys/faktory in my cluster when linkerd2 was deployed to the namespace

Before linkerd2, it worked correctly

After, the ruby client would not connect and hangs indefinitely. 

Both faktory and the ruby app were in pods with linkerd proxies. Tried it with both `--tls=optional` and `--tls=false`

Also, can connect to the web port for faktory, only the tcp connection is failing

**Comment by seanmonstar** [comment] 2018-08-22 18:30
Is "faktory" using a server-speak-first? As in, when a connection is made, the client connection doesn't send anything, and instead waits for the server to respond in some way? If that's the case, then these connections would be hanging at the protocol detection step...

**Comment by wmorgan** [comment] 2018-08-22 19:18
@seanmonstar you could be right. https://github.com/contribsys/faktory/blob/master/server/server.go#L193

**Comment by hawkw** [comment] 2018-08-22 22:02
@Rishka 
> will linkerd not detect the protocol even if both ends are using linkerd?

Yeah, that's correct. The linkerd proxy that accepts the connection from the client waits to detect the protocol before it opens its own client connection to the destination proxy, because the protocol detected can influence how the request is ultimately routed. When the protocol is server-speaks-first, the destination linkerd proxy never receives the request at all.

**Comment by wmorgan** [comment] 2018-08-23 00:54
> is that a "workaround" or is it just skipping the proxy altogether(I assume the later)?

That's correct, this skips the proxies. The other workaround, I believe, is to TLS the connection--from what I understand, the proxy attempts no protocol detection in this case (because it can't).

**Comment by seanmonstar** [comment] 2018-08-23 01:01
Huh, interesting. I just looked around in the inject command, and ya, it seems to make those ports completely skipped by the proxy. That shouldn't be *required*, since there is actually an option to allow the connections to flow through the proxy, just skipping protocol detection, but still giving you transport level metrics.

That was actually what I originally suggested be used in these cases, and unless there's problems with that, I'd lean towards this being a "docs" bug, that server-speak-first protocols section should instead instruct you how to simply disable protocol detection instead of skipping the proxy entirely.

**Comment by wmorgan** [comment] 2018-08-23 01:02
@seanmonstar oh I had no idea that was there! What is the option to skip protocol detection?

**Comment by klingerf** [comment] 2018-08-23 01:03
#1285 describes adding support for disabling protocol detection on inject. We haven't done that yet though, so the only option at this point is to skip the proxy altogether (or hand edit the inject yaml).

**Comment by Rishka** [comment] 2018-08-23 13:40
Unfortunately, disabling protocol detection does not seem to work. Added 
```
        - name: LINKERD2_PROXY_OUTBOUND_PORTS_DISABLE_PROTOCOL_DETECTION
          value: "7419"
```
to the "client", and 
```
        - name: LINKERD2_PROXY_INBOUND_PORTS_DISABLE_PROTOCOL_DETECTION
          value: "7419"
```
to the "server" and it went back to the original behavior

**Comment by grampelberg** [comment] 2018-12-03 22:11
Duplicate of #1285.

**Closed by grampelberg** 2018-12-03 22:11 UTC
Labels: area/proxy, bug, needs/more, priority/P2
