### ISSUE TITLE
Argo Rollouts compatibility issues

### ISSUE THREAD

**Issue by aarosil** [linkerd/linkerd2#5413] opened 2020-12-19 00:41 UTC
Issue Type:

- [ ] Bug report
- [X] Feature request

**Background**
Argo Rollouts replaces the native `Deployment` object with it's own object and takes over creation of replicasets ([docs](https://argoproj.github.io/argo-rollouts/migrating/) ). This seems to break the conventions of the linkerd dashboard, which assumes all things deployed are part of a deployment. I now see an IP address which used to be a link to a `Deployment` page. Also, it seems some information is missing (requests no longer appear under `Inbound` section)

**What happened**:
Losing information/utility of linkerd dashboard when migrating from `Deployment` to Argo `Rollout` CRD

**What you expected to happen**:
N/A

**How to reproduce it (as minimally and precisely as possible)**:
Install Argo Rollouts and deploy some apps with a `Rollout` instead of the native `Deployment` object
View how the linkerd dashboard is much less useful since pods are not grouped into a single Resource anymore

**Anything else we need to know?**:
I'm evaluating linkerd in a test cluster, in order to develop solution to use Argo Rollouts for progressive delivery of my apps

**Environment**:
- linkerd2 vanilla `--ha` install
- GKE w/ kubernetes 1.17

**Dashboard screenshots**
Deployment:
<img width="1366" alt="with deployment" src="https://user-images.githubusercontent.com/5607841/102675652-1413dd00-414f-11eb-934d-19e8d78c51a3.png">

Rollout:
<img width="1365" alt="with rollout" src="https://user-images.githubusercontent.com/5607841/102675709-3c034080-414f-11eb-80a8-61929f54ec9b.png">
Instead of the deploy name, we see Pod IP. Also, resource is missing under "Inbound" section

**Comment by adleong** [comment] 2020-12-21 20:10
Is this a duplicate of https://github.com/linkerd/linkerd2/issues/5189?

**Comment by aarosil** [comment] 2021-01-04 21:18
> Is this a duplicate of #5189?

It's closely related. I think this issue should be closed, as long as there is already a feature request logged for https://github.com/linkerd/linkerd2/issues/5189#issuecomment-735907382 (to populate the dashboard resource types based off observed metrics from the reworked metrics labels)

**Comment by cpretzer** [comment] 2021-01-04 21:58
thanks for the note @aarosil

**Closed by cpretzer** 2021-01-04 21:58 UTC
