### ISSUE TITLE
java.io.EOFException: SSL peer shut down incorrectly

### ISSUE THREAD

**Issue by phxql** [linkerd/linkerd2#4126] opened 2020-03-02 13:19 UTC
### What is the issue?

After deploying linkerd2 in our cluster, `java.io.EOFException: SSL peer shut down incorrectly` show up.

### How can it be reproduced?

Unsure, happens randomly.

### Logs, error output, etc

Output from the Java application:

```
Caused by: feign.RetryableException: Remote host terminated the handshake executing GET [redacted]
	at feign.FeignException.errorExecuting(FeignException.java:213)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:115)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:80)
	at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler.java:109)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	... 27 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at sun.security.ssl.SSLSocketImpl.handleEOF(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at feign.Client$Default.convertResponse(Client.java:82)
	at feign.Client$Default.execute(Client.java:78)
	at org.springframework.cloud.sleuth.instrument.web.client.feign.TracingFeignClient.execute(TracingFeignClient.java:100)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:110)
	... 32 common frames omitted
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
	at sun.security.ssl.SSLTransport.decode(Unknown Source)
	... 45 common frames omitted
```

At the same time i see this in the logs:

```
linkerd-proxy 2020-02-28T14:28:31.821200718Z [   355.372461220s DEBUG outbound:accept{peer.addr=10.1.131.169:56612}: linkerd2_app_core::accept_error: Connection failed error=request timed out
```

#### `linkerd check` output

```text
─$ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-cni-plugin
------------------
√ cni plugin ConfigMap exists
√ cni plugin PodSecurityPolicy exists
√ cni plugin ClusterRole exists
√ cni plugin ClusterRoleBinding exists
√ cni plugin Role exists
√ cni plugin RoleBinding exists
√ cni plugin ServiceAccount exists
√ cni plugin DaemonSet exists
√ cni plugin pod is running on all nodes

linkerd-identity
----------------
√ certificate config is valid
√ trust roots are using supported crypto algorithm
√ trust roots are within their validity period
√ trust roots are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust root

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-14T18:02:25Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cluster Environment: selfhosted
- Host OS: Coreos
- Linkerd version:
```
Client version: stable-2.7.0
Server version: stable-2.7.0
```

### Additional information

I suspect the issue pops up when the remote backend times out. Then linkerd somehow kills the connection in a way that the java SSL implementation throws an exception.

**Comment by grampelberg** [comment] 2020-03-04 17:56
This sounds pretty normal. Is there something being impacted specifically?

**Comment by phxql** [comment] 2020-03-09 07:34
Hi, I don't agree that `java.io.EOFException: SSL peer shut down incorrectly` sounds pretty normal.

The impact is the non-ability to speak with the backend system. Doesn't happen all the time, but does happen occasionally.

This issue only pops up when proxying the traffic through linkerd. When excluding the service from linkerd, the connection to the backend works. I have a workaround with excluding the outbound port 443.

**Comment by grampelberg** [comment] 2020-03-09 16:05
Ahha, that's what I was looking for! You're not really getting anything out of proxying 443, so that's a solid workaround. We've got a bug to look into though!

**Comment by grampelberg** [comment] 2020-03-09 20:56
The next step for us would be getting a really narrow repro. It'd be perfect if you could provide some k8s yaml that results in this exact behavior.

**Comment by phxql** [comment] 2020-03-10 08:21
I'll try to do that, but can't promise anything. The backend system is part of a proprietary system.

**Comment by mmiller1** [comment] 2020-04-29 15:02
I ran into a similar issue prompting me to open https://github.com/linkerd/linkerd2/issues/4308 (which now may be a duplicate of this one). I included very rudimentary reproduction steps that I was able to demonstrate the problem with intermittently.

**Closed** 2020-08-16 07:08 UTC
Labels: bug, needs/repro, wontfix
