### ISSUE TITLE
When service label selector is changed under traffic , linkerd prevents outbound traffic

### ISSUE THREAD

**Issue by gokcesurenkok** [linkerd/linkerd2#5405] opened 2020-12-17 19:21 UTC
### What is the issue?
we have blue/green deployment strategy in our services. After we deploy the new release and switch the service by changing the selector of  k8s service, we are having downtime since none of the outbound traffic cannot be sent through linkerd. It continues for a minute, then it recovers. 

### How can it be reproduced?
It seems to be happening with the services having heavy traffic, you can follow the step I described above. And we tried the same scenario with no injection of linkerd , that problem did not happen.
### Logs, error output, etc
[   173.555662s]  WARN ThreadId(01) outbound:accept{peer.addr=10.233.106.74:60610 target.addr=10.233.9.220:1903}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast

there are bunches of "Failed to proxy request: Service in fail-fast" when it happens
(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
```

### Environment

- Kubernetes Version: v1.16.7
- Cluster Environment: (GKE, AKS, kops, ...) bare metal
- Host OS: centos 7
- Linkerd version:
Client version: stable-2.9.1
Server version: stable-2.9.1

**Comment by adleong** [comment] 2020-12-17 23:43
Thanks @gokcesurenkok.  I'm going to try to reproduce this.

**Comment by adleong** [comment] 2020-12-23 18:30
So I tried to reproduce this at low traffic volume and didn't see the issue.  Specifically, when I edited the service label selector, I saw traffic shift smoothly without errors or fail-fast log messages.  However, I did notice that when we edit the service selector like this, the destination controller sends two updates to the proxy: first a `remove` of the old addresses followed by an `add` of the new addresses.  This means that the proxy's load balancer will be very briefly empty.  At high enough traffic volumes, it is conceivable that a request could come through during this brief period of time where the load balancer is empty.

@olix0r Would this scenario trigger a fail-fast in the proxy?  Would the proxy then reject requests for a period of time even if the load balancer becomes non-empty?

The solution may be as simple as changing the order of updates that the destination controller sends so that it sends the `add` before the `remove`.

**Comment by gokcesurenkok** [comment] 2020-12-31 06:10
@adleong @olix0r hello guys, is there any update on this issue? we are having difficulty every time we switch service selectors when we release something on production. 
It would be nice to try the solution of @adleong in the next release.

**Comment by olix0r** [comment] 2020-12-31 16:33
@adleong The failfast timeout is something like 3 seconds, so I would be pretty surprised if it took that long to process consecutive discovery updates.

@gokcesurenkok We don't even have a way to reproduce this issue yet, so we can't really start working on a fix. What @adleong suggests is just a shot in the dark, but we can't just make changes on a hunch---I'm not convinced that this solution would help you. Can you share debug logs from a proxy with this behavior (i.e. by setting the annotation `config.linkerd.io/proxy-log-leve: debug`)? If this is causing problems for you, you might consider changing your blue/green strategy to avoid relabeling? Can you use `TrafficSplit` to change weights between multiple services instead?

**Comment by hadican** [comment] 2021-01-20 19:20
Hi @gokcesurenkok, we are experiencing the same issue. We are running a deployment with lightweight 400+ pods on GKE 1.16, and all are calling a deployment with powerful 6 pods. After a while, say 8-10mins later, we are getting below errors: (hundreds of them)
```
[ 763.599271s] WARN ThreadId(01) inbound:accept{peer.addr=10.37.184.4:42850 target.addr=10.39.171.4:50053}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
[ 763.599321s] WARN ThreadId(01) inbound:accept{peer.addr=10.36.11.3:47188 target.addr=10.39.171.4:50053}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
[ 763.599341s] WARN ThreadId(01) inbound:accept{peer.addr=10.39.52.3:58804 target.addr=10.39.171.4:50053}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
[ 763.599356s] WARN ThreadId(01) inbound:accept{peer.addr=10.36.42.4:35406 target.addr=10.39.171.4:50053}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
[ 763.599369s] WARN ThreadId(01) inbound:accept{peer.addr=10.36.65.4:34996 target.addr=10.39.171.4:50053}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
[ 763.599421s] WARN ThreadId(01) inbound:accept{peer.addr=10.39.135.4:54506 target.addr=10.39.171.4:50053}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
```

**Comment by kforsthoevel** [comment] 2021-01-21 18:03
@olix0r We ran into a similar problem today. We started 200+ pods in a very short time frame (~1min). Outbound traffic stopped for the whole cluster with the same fail-fast error messages. During debugging we found a lot of errors in the `destination` log:

```
level=error msg="Failed to get node topology for node ip-172-X-X-X.eu-west-1.compute.internal: context canceled" addr=":8086" component=endpoint-translator remote="127.0.0.1:47822" service="my-service.default.svc.cluster.local:80"
```

and

```
level=error msg="Failed to send address update: rpc error: code = Internal desc = transport: transport: the stream is done or WriteHeader was already called" addr=":8086" component=endpoint-translator remote="127.0.0.1:47822" service="my-servicedefault.svc.cluster.local:80"
```

<img width="997" alt="Screenshot 2021-01-21 at 19 01 52" src="https://user-images.githubusercontent.com/2952012/105392169-3354cd00-5c1b-11eb-9df8-c87c7fa44f46.png">

Each of the 200+ pods make TCP requests against 6 dependent services during startup.

Here are the memory and CPU stats for the `destination` pods during the outage.

<img width="1170" alt="Screenshot 2021-01-21 at 18 57 28" src="https://user-images.githubusercontent.com/2952012/105391605-8f6b2180-5c1a-11eb-9c8c-8b18a7d6cc92.png">

After about 5 minutes everything was fine again and the outbound traffic was ok. 

Let me know if you need further info.

**Comment by olix0r** [comment] 2021-01-21 20:29
@kforsthoevel thanks. this is interesting. Are there errors in the destination controller's _proxy_ logs at that time?

**Comment by kforsthoevel** [comment] 2021-01-22 10:26
@olix0r There are four types of log messages from `linkerd-proxy`. But 139 log lines.

a)

```json
{
  "timestamp": "[242094.812456s]",
  "level": "INFO",
  "fields": {
    "message": "Connection closed",
    "error": "connection error: Transport endpoint is not connected (os error 107)"
  },
  "target": "linkerd2_app_core::serve",
  "span": {
    "peer.addr": "100.96.255.12:50692",
    "target.addr": "100.96.16.137:8086",
    "name": "accept"
  },
  "spans": [
    {
      "name": "inbound"
    },
    {
      "peer.addr": "100.96.255.12:50692",
      "target.addr": "100.96.16.137:8086",
      "name": "accept"
    }
  ],
  "threadId": "ThreadId(1)"
}
```

b)

```json
{
  "timestamp": "[242026.532422s]",
  "level": "INFO",
  "fields": {
    "message": "Connection closed",
    "error": "Timed out while reading client stream prefix"
  },
  "target": "linkerd2_app_core::serve",
  "span": {
    "peer.addr": "100.97.24.9:47186",
    "target.addr": "100.96.8.38:8086",
    "name": "accept"
  },
  "spans": [
    {
      "name": "inbound"
    },
    {
      "peer.addr": "100.97.24.9:47186",
      "target.addr": "100.96.8.38:8086",
      "name": "accept"
    }
  ],
  "threadId": "ThreadId(1)"
}
```

c)

```json
{
  "timestamp": "[242007.664132s]",
  "level": "INFO",
  "fields": {
    "message": "Connection closed",
    "error": "TLS detection timeout"
  },
  "target": "linkerd2_app_core::serve",
  "span": {
    "peer.addr": "100.96.239.9:46686",
    "target.addr": "100.96.8.38:8086",
    "name": "accept"
  },
  "spans": [
    {
      "name": "inbound"
    },
    {
      "peer.addr": "100.96.239.9:46686",
      "target.addr": "100.96.8.38:8086",
      "name": "accept"
    }
  ],
  "threadId": "ThreadId(1)"
}
```

d)

```json
{
  "timestamp": "[241404.015655s]",
  "level": "INFO",
  "fields": {
    "message": "Connection closed",
    "error": "connection error: Broken pipe (os error 32)"
  },
  "target": "linkerd2_app_core::serve",
  "span": {
    "peer.addr": "100.96.8.119:58412",
    "target.addr": "100.96.8.38:4191",
    "name": "accept"
  },
  "spans": [
    {
      "name": "daemon"
    },
    {
      "listen.addr": "0.0.0.0:4191",
      "name": "admin"
    },
    {
      "peer.addr": "100.96.8.119:58412",
      "target.addr": "100.96.8.38:4191",
      "name": "accept"
    }
  ],
  "threadId": "ThreadId(2)"
}
```

Let me know if you need further info.

**Comment by adleong** [comment] 2021-01-26 19:44
Hi @hadican and @kforsthoevel!  Thanks for these reports.  Could you each please open a new issue for these reports with as much information as possible about the steps you took to trigger the issue or the events that lead up to the issue.  This particular issue describes a very specific scenario involving updating the label selector of an existing service and I think we may be confusing things by lumping them in together.  Thanks!

**Comment by adleong** [comment] 2021-01-28 19:26
@kforsthoevel thanks for filing #5629.  just to keep this clear, I'm going to delete your comment on this issue and we can continue the conversation on #5629.

**Comment by kleimkuhler** [comment] 2021-02-15 17:40
Because this is destination service related, it may be worth keeping an eye on #5722 which is merged and should be in the edge this week.

We separated these issues out originally, but since there have been no updates on this it will be good to test and rule things out.

**Comment by adleong** [comment] 2021-02-19 23:25
Edge-21.2.3 which includes #5722 has been released.  @gokcesurenkok please let me know if you are able to try out this edge release and see if it resolves this problem.

**Comment by gokcesurenkok** [comment] 2021-03-01 08:15
hi @adleong, sorry for the late reply, I have been told that the failures are significantly reduced after edge-21.2.3.Thanks

**Comment by adleong** [comment] 2021-03-13 01:54
@gokcesurenkok great to hear!  Thanks for confirming.

**Closed by adleong** 2021-03-13 01:54 UTC
