### ISSUE TITLE
proxy: high cpu on shutdown

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#1231] opened 2018-06-29 17:40 UTC
Observing high CPU on the proxy when a pod is shutdown.

Prometheus query (found on the `Conduit Health` dashboard):
```
sum(irate(process_cpu_seconds_total{conduit_io_control_plane_ns="$namespace", job="conduit-proxy"}[20s])) by (namespace, pod)
```

Pod is shutdown via:
```bash
kubectl -n $LIFECYCLE_NS delete po $POD
```

Reproduced with 1 minute and 5 minute pod lifecycles:

## 1 minute restart

![screen shot 2018-06-29 at 10 08 51 am](https://user-images.githubusercontent.com/236915/42105277-99cc3818-7b84-11e8-97cb-77e855bf72c2.png)
![screen shot 2018-06-29 at 10 09 33 am](https://user-images.githubusercontent.com/236915/42105278-99e4377e-7b84-11e8-9914-9546b352514b.png)

## 5 minute restart

![screen shot 2018-06-29 at 10 37 33 am](https://user-images.githubusercontent.com/236915/42106328-89c233e2-7b88-11e8-99fd-46e85fafbc1b.png)

![screen shot 2018-06-29 at 10 37 49 am](https://user-images.githubusercontent.com/236915/42106332-8c33c690-7b88-11e8-9e77-86f1fcf53035.png)

## Steps to reproduce

With the conduit-lifecycle example:
```
$ conduit install -v git-15718de2 --conduit-namespace conduit-lifecycle | kubectl apply -f -
$ bin/deploy 5
$ bin/scale 5 5
```

**Comment by siggy** [comment] 2018-07-05 23:05
Possibly related, introduction of injected proxy increases emojivoto shutdown time from 48s to 66s. This is reproduced running K8s on Docker for Mac.

### Without proxy

```bash
$ time (kubectl delete ns emojivoto && while kubectl get ns emojivoto > /dev/null 2>&1; do :; done)
namespace "emojivoto" deleted

real	0m48.061s
user	0m43.140s
sys	0m10.586s

$ time (kubectl delete ns emojivoto && while kubectl get ns emojivoto > /dev/null 2>&1; do :; done)
namespace "emojivoto" deleted

real	0m48.062s
user	0m43.743s
sys	0m10.647s
```

### With proxy

```bash 
$ time (kubectl delete ns emojivoto && while kubectl get ns emojivoto > /dev/null 2>&1; do :; done)
namespace "emojivoto" deleted

real	1m7.172s
user	0m58.100s
sys	0m14.264s

$ time (kubectl delete ns emojivoto && while kubectl get ns emojivoto > /dev/null 2>&1; do :; done)
namespace "emojivoto" deleted

real	1m6.190s
user	0m59.144s
sys	0m14.847s
```

**Comment by grampelberg** [comment] 2018-07-11 20:52
@siggy should we have a separate issue for container shutdown or do you think they're the same core issue?

**Comment by seanmonstar** [comment] 2018-07-11 21:04
Is it possible to tell if without the proxy requests get interrupted? On receiving a shutdown signal, the proxy does this:

- For HTTP/1, starts closing connections after any current request is completed.
- For HTTP/2, starts a graceful `GOAWAY`, which allows any started requests to complete first.
- For TCP, just hopes the connections close some day ;_;

**Comment by seanmonstar** [comment] 2018-07-12 22:23
Just landed some changes that fixed some very suspicious code, such that in some circumstances, the admin thread could busy loop until the main thread finally terminated. Not sure how to test that it fixes this, though.

**Comment by hawkw** [comment] 2018-07-30 21:34
I just ran a quick lifecycle test, and it appears that this is _not_ fixed in v18.7.1:
![screen shot 2018-07-30 at 2 32 23 pm](https://user-images.githubusercontent.com/2796466/43424875-9b90fc6c-9405-11e8-889d-739998653a62.png)

**Comment by klingerf** [comment] 2018-07-30 21:37
@hawkw Heads up that the latest release is v18.7.2. I'm pretty sure v18.7.1 does not include the changes that @seanmonstar mentioned.

**Comment by hawkw** [comment] 2018-07-30 21:47
Sorry, I meant to say v18.7.2.

However, I _don't_ think that test was run against the right version, as I realised linkerd-lifecycle farms out to the `linkerd` binary, and mine wasn't built recently, so I think that although my control plane was installed with v18.7.2, my `inject` command was injecting a much earlier version (`git-e5cce1ab`), which did not include @seanmonstar's changes. Nevermind!

I believe @siggy also recently ran tests and confirmed that this issue was fixed?

**Comment by hawkw** [comment] 2018-07-30 22:06
Continuing to see similar spikes on proxy version `git-9bb4ecb0`, with the CLI built from a pull of the most recent master:
<img width="1150" alt="screen shot 2018-07-30 at 3 03 49 pm" src="https://user-images.githubusercontent.com/2796466/43426302-1b943dee-940a-11e8-9834-23278db8c3fc.png">

**Comment by seanmonstar** [comment] 2018-07-30 22:17
What exactly am I look at with the graphs? It looks like there's a dramatic change, from 2 minutes down to 1 second... though I don't know what it actually means.

**Comment by seanmonstar** [comment] 2018-07-31 00:59
Alright then, found another busy loop related to shutdown: https://github.com/carllerche/h2/pull/296

**Comment by hawkw** [comment] 2018-07-31 19:00
linkerd/linkerd2-proxy#33 updates the proxy to depend on a version of `h2` that includes @seanmonstar's changes in carllerche/h2#296. I'm going to rerun the tests to see if that change fixes this issue.

**Comment by hawkw** [comment] 2018-08-06 20:48
Since the CPU usage spikes are of much lower magnitude than they were originally, the current behaviour is acceptable.

**Closed by hawkw** 2018-08-06 20:48 UTC
Labels: area/production, area/proxy, priority/P2
