### ISSUE TITLE
Requests which are canceled due to service profile governance are not retried

### ISSUE THREAD

**Issue by pwlodek** [linkerd/linkerd2#3743] opened 2019-11-20 15:25 UTC
### What is the issue?
Requests which are timed out by the service profile timeout parameter are not subject to retry.

I would like timeouts which are governed by service profile to be treated as failures, and I would like them to be retried.

### How can it be reproduced?

Create a simple Linkerd service profile, and set a timeout on any route to be a small value, say 500ms. Now if you call this endpoint from a meshed pod, and when it happens that the call takes more than 500ms to complete, the pod will see 504 gateway timeout. No retries are happening.

### Logs, error output, etc

No logs. This is simply not happening.

### Environment

- Kubernetes Version: 1.14.3
- Cluster Environment: Any (tested on AKS and Docker Desktop)
- Host OS: Windows
- Linkerd version: 2.6

### Possible solution

No

### Additional context

Imagine you have a service endpoint /database/products. When you do GET /database/products you will receive a list of products from a database. Sometimes this call takes 50ms to complete, sometimes it takes 3sec to complete. I would like to be able to tell linkerd hey, if this request takes longer than X, cancel it AND do a retry (according to a retry budget). This situation would be analogues to a situation where this endpoint returns 500, in which case linkerd (if configured) will do a retry according to the budget.

Why is this important? Say I configured above route to timeout after 500ms. I have a meshed pod which does GET /database/products. Say the first request takes more than 500ms, in which case the request is canceled. But linkerd will do a retry, so the request is retried and lets say it will take 100ms this time. So what happened is first requestd timed out after 500ms but it was retried and the second time it took 100ms to complete. So from the calling pod point of view the request took ~600ms to complete. If linkerd didint interfere it would take 3 sec to complete. That is what should happen.

At this point, the fact that Linkerd cancels the request after X and returns 504 gateway timeout is pretty much useless.

**Comment by pwlodek** [comment] 2019-11-20 15:36
One possible approach would be to include a new parameter on service profile: retryTimeout (name is deceptive a little bit). Here is the idea.

proposed service profile parameters;

timeout: 2000ms
retryTimeout: 500ms
isRetryable: true

with the above configuration we retain current functionality of a request being canceled. So if the request (or a sum of request + retries) is more than 2000ms, cancel it and return 504 gateway timeout to the caller. But if retry timeout is specified (and needs to be smaller than timeout) then this instructs linkerd to timeout the call after retryTimeout value (500ms in the sample), AND retry the call, wait 500ms, retry, etc, up to the max timeout which is 2000ms.

I hope the above idea makes sense.

**Comment by grampelberg** [comment] 2019-11-22 17:06
@adleong any insights?

**Comment by adleong** [comment] 2019-12-03 00:18
Hey @pwlodek!  Yes, having a "per-try" timeout does make sense but what we've found is that configuring and properly tuning the per-try timeout is very sensitive and brittle.  Choosing the right value is critical because if you tune the timeout too low, you'll end up with a lot of retries or even errors and if you tune it too high, it won't provide any value.  To make matters worse, the correct value will change over time as the performance characteristics of your application change.  

A more robust approach would be to use latency percentiles instead of a fixed timeout.  For example, as done in https://github.com/tower-rs/tower/blob/master/tower-hedge/src/lib.rs

I'm going to close this issue since the timeout is working as intended.  But if you're interested in helping add something like hedge requests into Linkerd, please jump into the #contributors channel in slack and we can form a plan of action.

**Closed by adleong** 2019-12-03 00:18 UTC

**Comment by pwlodek** [comment] 2019-12-03 08:41
Hi @adleong! Thanks for the information. So I understand that current implementation of timeouts is pretty much "fail fast". It does not bring any magic the way retries do? While I see huge benefits of doing retries via service mesh, I can hardly see custom values for timeouts. Correct me if I'm wrong.
