### ISSUE TITLE
Proxy injector not attaching when cluster is scaled up

### ISSUE THREAD

**Issue by mayank-ag-dev** [linkerd/linkerd2#11623] opened 2023-11-16 09:41 UTC
### What is the issue?

I have successfully installed Linkerd v2.14 on Google Kubernetes Engine (GKE) v1.27. However, every time I resize the node pool from zero, I need to manually restart the application pod to attach the Linkerd container. I am looking for a way to automatically attach the Linkerd container to all the application pods when the node pool is resized, without having to perform manual restarts. I want to know if there is a way to automatically attach the Linkerd container to all the application pods when the node pool is resized without having to perform manual restarts.

### How can it be reproduced?

By installing l5d and resize the node pool of GKE cluster

### Logs, error output, etc

Logs for application as there is no logs for linkerd
{"level":"info","ts":"2023-11-16T08:57:46.944Z","caller":"podinfo/main.go:140","msg":"Starting podinfo","version":"5.0.3","revision":"","port":"9898"}

### output of `linkerd check -o short`

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.14.0 but the latest stable version is 2.14.3
    see https://linkerd.io/2.14/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.14.0 but the latest stable version is 2.14.3
    see https://linkerd.io/2.14/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-d995f46dc-dktbm (stable-2.14.0)
	* linkerd-identity-86c6f76f6c-l2mzl (stable-2.14.0)
	* linkerd-proxy-injector-6fc56bcd48-dzfvw (stable-2.14.0)
    see https://linkerd.io/2.14/checks/#l5d-cp-proxy-version for hints

### Environment

GKE v1.27
Linkerd stable-2.14.0

### Would you like to work on fixing this bug?

None

**Comment by kflynn** [comment] 2023-11-16 17:11
"Scale up the cluster" meaning "adding Nodes", correct? Just wanting to make sure we're looking at the right thing here...

**Comment by mayank-ag-dev** [comment] 2023-11-17 02:06
> "Scale up the cluster" meaning "adding Nodes", correct? Just wanting to make sure we're looking at the right thing here...

**Comment by mayank-ag-dev** [comment] 2023-11-17 02:14
Sure, @kflynn so at night we resize our GKE node pool to zero, and every morning we resize the node pool again from zero to n once we resize we need to manually restart the all application pod to attach the Linkerd container.

**Comment by alpeb** [comment] 2023-11-23 14:37
The problem could be that the injector cannot start soon enough before your app workloads. Try setting linkerd's [webhookFailurePolicy](https://github.com/linkerd/linkerd2/blob/stable-2.14.5/charts/linkerd-control-plane/values.yaml#L291) to `Fail`, so that the scheduler retries pod creation until the injector becomes ready.

**Comment by mayank-ag-dev** [comment] 2023-11-24 07:28
I attempted to set the **webhookFailurePolicy: Fail** in linkerd but I'm having no success.

**Comment by alpeb** [comment] 2023-11-24 14:43
Are you perhaps running the linkerd CNI plugin?

**Comment by mayank-ag-dev** [comment] 2023-11-24 17:07
No, cniEnabled is set to false in my configuration

**Comment by kflynn** [comment] 2023-11-30 19:27
@mayank-ag-dev, I think the next step here is probably to uninstall Linkerd and reinstall it in HA mode, as described in https://linkerd.io/2.14/features/ha/ -- that'll set the `webhookFailurePolicy` and also make sure that we have multiple replicas for the control plane, antiaffinity, etc., so that everything should work smoothly. Let's give that a shot.

**Comment by kflynn** [comment] 2023-12-18 21:21
@mayank-ag-dev Any joy on HA mode? 🙂

**Comment by kflynn** [comment] 2024-01-04 15:43
@mayank-ag-dev Happy new year! Still looking for HA-mode results, if you've gotten to try that? 🙂

**Comment by kflynn** [comment] 2024-02-08 23:15
@mayank-ag-dev OK, I've reproduced this and can verify that installing Linkerd in HA mode solves the problem. I'm going to go ahead and close this – if HA mode doesn't work for you, somehow, let us know!

----

For the curious, I actually reproduced it with `k3d` because that let me see the details of what was happening. Scripting for bash or zsh follows:

```bash
create_cluster () {
    k3d cluster create ffs \
        --agents 3 \
        --servers 1 \
        -p 80:80@loadbalancer -p 443:443@loadbalancer \
        --k3s-arg --disable=local-storage,traefik@server:0

    kubectl taint nodes k3d-ffs-server-0 node-role.kubernetes.io/master=:NoSchedule
}

install_linkerd () {
    if [ \( "$1" != "" \) -a \( "$1" != "--ha" \) ]; then
        echo "Usage: install_linkerd [--ha]" >&2
    else
        linkerd install --crds | kubectl apply -f -
        linkerd install $1 | kubectl apply -f -
        linkerd check
    fi
}

install_faces () {
    kubectl create ns faces
    kubectl annotate ns faces linkerd.io/inject=enabled    

    helm install -n faces \
        --version 0.8.0 faces oci://registry-1.docker.io/dwflynn/faces-chart
}

delete_cluster () {
    k3d cluster delete ffs
}

check_pods () {
    kubectl get pods -n linkerd -o wide
    kubectl get pods -n faces -o wide
}

watch_pods () {
    watch 'sh -c "kubectl get pods -n linkerd -o wide; kubectl get pods -n faces -o wide"'
}

drop_nodes () {
    nodes=$(
        kubectl get node \
          | grep -v control-plane | grep -v NAME \
          | awk ' { print $1 }'
    )
    echo $nodes | xargs kubectl delete node
    echo $nodes | xargs k3d node delete
}

add_nodes () {
    k3d node create new0 --cluster ffs --role agent    
    k3d node create new1 --cluster ffs --role agent    
    k3d node create new2 --cluster ffs --role agent    
}
```

Paste the functions above, then run this sequence to see the problem:

```bash
create_cluster
install_linkerd
install_faces
watch_pods
```

Wait until all the pods are running (all the Faces pods should show two containers). Then

```bash
drop_nodes
watch_pods
```

Wait for the pods to go to `Pending` state. This will take a bit. Finally

```bash
add_nodes
watch_pods
```

and you'll see that when the Faces pods come back, they'll have only one container. This is because Faces starts _much_ faster than Linkerd, so the proxy injector isn't running, so nothing good happens when Faces comes back up.

Now repeat with Linkerd in HA mode:

```bash
delete_cluster
create_cluster
install_linkerd --ha
install_faces
watch_pods
```

Same thing, wait for all pods to be running (you'll note there there are a lot more Linkerd pods running, and that they're scattered evenly across the three `agent` nodes). Then

```bash
drop_nodes
watch_pods
```

Wait for Pending (or missing -- in my setup, the Faces pods are often gone entirely), then

```bash
add_nodes
watch_pods
```

and _this_ time you'll see all the Linkerd pods start running before any of the Faces pods start -- and the Faces pods will have two containers again, like they should.

This is because one of the things that Linkerd's HA mode does is to force pod startup to wait for the proxy injector to be running, which is exactly what you want here.

**Closed by kflynn** 2024-02-08 23:15 UTC
Labels: bug
