### ISSUE TITLE
latest smi spec versions not supported, locked to v1alpha1

### ISSUE THREAD

**Issue by vyta** [linkerd/linkerd2#5550] opened 2021-01-15 17:53 UTC
### What is the issue?
SMI spec version is locked to v1alpha1, meaning latest versions do not work

### How can it be reproduced?
Create resources with newer versions of smi spec on cluster with linkerd

### Logs, error output, etc

```sh
... : no matches for kind "TrafficTarget" in version "access.smi-spec.io/v1alpha2"
... : no matches for kind "HTTPRouteGroup" in version "specs.smi-spec.io/v1alpha3"
```

#### `linkerd check` output

```sh
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

pre-kubernetes-setup
--------------------
√ control plane namespace does not already exist
√ can create non-namespaced resources
√ can create ServiceAccounts
√ can create Services
√ can create Deployments
√ can create CronJobs
√ can create ConfigMaps
√ can create Secrets
√ can read Secrets
√ can read extension-apiserver-authentication configmap
√ no clock skew detected

pre-kubernetes-capability
-------------------------
√ has NET_ADMIN capability
√ has NET_RAW capability

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

Status check results are √
```

### Environment

- Kubernetes Version: v1.18.10
- Cluster Environment: AKS
- Host OS: 
- Linkerd version: stable-2.9.2

**Comment by adleong** [comment] 2021-01-15 18:23
Duplicate of https://github.com/linkerd/linkerd2/issues/3962

**Closed by adleong** 2021-01-15 18:23 UTC
