### ISSUE TITLE
Warnings about CRD version `v1beta1`

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4989] opened 2020-09-21 15:53 UTC
### What is the issue?

Installing Linkerd on k8s version `1.19.0` emits some warnings about the usage of the depreciated version of `CustomResourceDefiniton` resource like
```
warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/serviceprofiles.linkerd.io created
customresourcedefinition.apiextensions.k8s.io/trafficsplits.split.smi-spec.io created
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-prometheus created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-prometheus created
serviceaccount/linkerd-prometheus created
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-proxy-injector created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-proxy-injector created
serviceaccount/linkerd-proxy-injector created
secret/linkerd-proxy-injector-tls created
Warning: admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
mutatingwebhookconfiguration.admissionregistration.k8s.io/linkerd-proxy-injector-webhook-config created
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-sp-validator created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-sp-validator created
serviceaccount/linkerd-sp-validator created
secret/linkerd-sp-validator-tls created
Warning: admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration

```

Updating the `apiVersion` field to the supported version should probably fix this.

**Comment by Pothulapati** [comment] 2020-09-22 10:50
Okay, Did some reading on this.

This occurs in `1.19` because of the [new warnings feature](https://kubernetes.io/blog/2020/09/03/warnings/), which warns users when depreciated APIs are used. `apiextensions.k8s.io/v1beta1` is currently depreciated and will be removed in 1.22, and we have to move our CRD's to `apiextensions.k8s.io/v1` by then as per https://github.com/kubernetes/kubernetes/issues/82022

Moving to `apiextensions.k8s.io/v1` not only means that we would be bumping our Min k8s version to `1.16` but also nrrf update our CRDs based on the new fields (some fields moved around with more required configuration options). Obviously, We cannot take this right away as `1.16` is pretty new, and we would probably do this closer to 1.122. 

Until then, This can act as a place-holder for depreciated API related warnings.

_The same explanation applies also for `admissionregistration.k8s.io` which were also added in `1.16`_

**Comment by olix0r** [comment] 2021-01-14 18:09
Dupe of #5484

**Closed by olix0r** 2021-01-14 18:09 UTC
Labels: area/controller, priority/P0
