### ISSUE TITLE
Several pages on the dashboard are blank

### ISSUE THREAD

**Issue by PriyankPa** [linkerd/linkerd2#9528] opened 2022-09-30 05:58 UTC
### What is the issue?

- The **Tap, Top and Route** pages show up blank. There is some javascript error in the browser console.
- The **Traffic Split** Page is blank as well. The error there seems to be some server side check failing.

![image](https://user-images.githubusercontent.com/3187668/193196107-16622912-1269-4f48-a7fe-4863c93e4df0.png)

![image](https://user-images.githubusercontent.com/3187668/193196932-ea7bb8de-308f-43d2-bf67-ec98db73fc87.png)

Just FYI, the dashboard is not exposed to public internet. SSL cert is obtained using DNS challenge of Lets Encrypt.

### How can it be reproduced?

Install Linkerd 2.12.1 (stable) following instructions from Linkerd's Getting Started guide.

In my case, since it is accessed via a non localhost address. I have removed the `-enforced-host` argument from container args in `deployment/web` as detailed in this document https://linkerd.io/2.12/tasks/exposing-dashboard/#dns-rebinding-protection

### Logs, error output, etc

- Javascript Error on Tap, Top and Routes page:
```
main.0a28ea5b8c240bc91550.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'search')
    at main.0a28ea5b8c240bc91550.js:2:789749
    at n (main.0a28ea5b8c240bc91550.js:2:791104)
    at Ko (main.0a28ea5b8c240bc91550.js:2:245022)
    at xs (main.0a28ea5b8c240bc91550.js:2:290927)
    at pl (main.0a28ea5b8c240bc91550.js:2:283703)
    at dl (main.0a28ea5b8c240bc91550.js:2:283628)
    at rl (main.0a28ea5b8c240bc91550.js:2:280658)
    at Qs (main.0a28ea5b8c240bc91550.js:2:277426)
    at zl (main.0a28ea5b8c240bc91550.js:2:298641)
    at main.0a28ea5b8c240bc91550.js:2:299850
```

- Error on Traffic Splits page:
The failing request exported via Chrome's Copy as curl (bash)
```
curl 'https://linkerd.******/api/tps-reports?resource_type=trafficsplit&namespace=default&tcp_stats=true&window=1m' \
  -H 'authority: linkerd.*****' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cache-control: no-cache' \
  -H 'cookie: _ga=GA1.2.13464***.16642****; _gid=GA1.2.149632****.16644****' \
  -H 'pragma: no-cache' \
  -H 'referer: https://linkerd.******/namespaces/default/trafficsplits' \
  -H 'sec-ch-ua: "Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36' \
  --compressed
```
```
{
    "error": "cannot find Kubernetes canonical name from friendly name [trafficsplit]"
}
```

### output of `linkerd check -o short`

```
> linkerd check -o short
Status check results are √
```

### Environment
- Linkerd 2.12.1 (stable).
- Kubernetes Version
```> kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.6
Kustomize Version: v4.5.4
Server Version: v1.23.6+k3s1
```
- Kubernetes Distro: k3s
- Host OS: Centos
```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

```
$ uname -r
3.10.0-957.1.3.el7.x86_64
```

### Additional context

The screenshots above are taken from the dashboard running on the cluster but I have verified that the same issue occurs when running dashboard locally (using `linkerd viz dashboard` command). In-fact problems with local dashboard are what led me to run it in the cluster.

Tried using both Chrome and Firefox

**Comment by oncipriani** [comment] 2022-09-30 17:30
Same issue here. Linkerd 2.12.1 (stable) installed using Helm Chart.

**Comment by jeremychase** [comment] 2022-10-03 20:03
This is a duplicate of #9306

**Closed by jeremychase** 2022-10-03 20:03 UTC
Labels: area/web, bug
