### ISSUE TITLE
Issue with proxying a gRPC service

### ISSUE THREAD

**Issue by Monnoroch** [linkerd/linkerd2#2111] opened 2019-01-18 09:08 UTC
### What is the issue?

When adding linkerd proxy to a gRPC service, linkerd proxy fails all requests.

### How can it be reproduced?

I use moby/buildkit as an example of a gRPC service. I deployed it in k8s like so:
```
namespace: build
name: buildkit

...

image: moby/buildkit:v0.3.3@sha256:7eaccec7a90a43546b0fa870e55c860014fc3bbdd55c3697f59e7c812c246c06
args:
  - --addr
  - tcp://0.0.0.0:80
livenessProbe:
  exec:
    command:
      - buildctl
      - --addr
      - tcp://0.0.0.0:80
      - debug
      - workers
``` 

and the linkerd proxy and proxy init using `linkerd inject` on my buildkit manifest. Liveness probe is working just fine, which means the server can connect to itself via localhost. Then I try to build any image with this server from another pod:
```
buildctl \
  --addr tcp://buildkit.build:80 \
  build \
  '--progress=plain' \
  '--frontend=dockerfile.v0' \
  --local 'context=.' \
  --local 'dockerfile=my-dir' \
  --frontend-opt 'filename=my-image.dockerfile'
  --frontend-opt 'platform=linux/amd64'
```

This is working just fine when buildkit is deployed without the data proxy, however it doesn't work with it.

Client logs:
```
2019/01/18 08:53:01 http2: server: error reading preface from client localhost: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR
error: failed to receive status: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR
```

Linkerd data proxy debug log (started it with `LINKERD2_PROXY_LOG=debug,linkerd2_proxy=debug`):
```
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} linkerd2_proxy::app::inbound::orig_proto_downgrade downgrading requests; source=Source { remote: V4(10.244.9.210:43272), local: V4(10.244.9.209:4143), orig_dst: Some(V4(10.244.9.209:80)), tls_status: None(Disabled), _p: () }
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} hyper::proto::h1::io read 33 bytes
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} hyper::proto::h1::conn parse error (invalid HTTP version specified) with 33 bytes
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} hyper::proto::h1::dispatch read_head error: invalid HTTP version specified (Http2)
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} hyper::server::conn error polling connection protocol: invalid HTTP version specified (Http2)
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::codec::framed_write send; frame=Settings { flags: SettingsFlags(0), header_table_size: None, enable_push: None, max_concurrent_streams: None, initial_window_size: None, max_frame_size: None, max_header_list_size: None }
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::codec::framed_read received; frame=Settings { flags: SettingsFlags(0), header_table_size: None, enable_push: None, max_concurrent_streams: None, initial_window_size: None, max_frame_size: None, max_header_list_size: None }
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::codec::framed_write send; frame=Settings { flags: SettingsFlags(1), header_table_size: None, enable_push: None, max_concurrent_streams: None, initial_window_size: None, max_frame_size: None, max_header_list_size: None }
DBUG tokio_reactor loop process - 1 events, 0.000s
DBUG tokio_reactor loop process - 0 events, 0.000s
DBUG tokio_reactor loop process - 1 events, 0.000s
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::codec::framed_read received; frame=Headers { stream_id: StreamId(1), stream_dep: None, flags: HeadersFlag { end_stream: false, end_headers: true, padded: false, priority: false } }
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::server malformed headers: malformed authority
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::codec::framed_read received; frame=Data { stream_id: StreamId(1), flags: DataFlags { end_stream: true } }
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::codec::framed_read received; frame=Headers { stream_id: StreamId(3), stream_dep: None, flags: HeadersFlag { end_stream: false, end_headers: true, padded: false, priority: false } }
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::server malformed headers: malformed authority
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::codec::framed_read received; frame=Data { stream_id: StreamId(3), flags: DataFlags { end_stream: true } }
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::codec::framed_read received; frame=Headers { stream_id: StreamId(5), stream_dep: None, flags: HeadersFlag { end_stream: false, end_headers: true, padded: false, priority: false } }
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::server malformed headers: malformed authority
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::codec::framed_read received; frame=Settings { flags: SettingsFlags(1), header_table_size: None, enable_push: None, max_concurrent_streams: None, initial_window_size: None, max_frame_size: None, max_header_list_size: None }
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::proto::settings received remote settings ack
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::codec::framed_read received; frame=Data { stream_id: StreamId(5) }
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::codec::framed_write send; frame=Reset { stream_id: StreamId(1), error_code: PROTOCOL_ERROR }
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::codec::framed_write send; frame=Reset { stream_id: StreamId(3), error_code: PROTOCOL_ERROR }
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.9.210:43272} h2::codec::framed_write send; frame=Reset { stream_id: StreamId(5), error_code: PROTOCOL_ERROR }
```

I'm also seeing these errors:
```
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.1.0:38208} hyper::proto::h1::conn parse error (invalid HTTP version specified) with 724 bytes
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.1.0:38208} hyper::proto::h1::dispatch read_head error: invalid HTTP version specified (Http2)
DBUG proxy={server=in listen=0.0.0.0:4143 remote=10.244.1.0:38208} hyper::server::conn error polling connection protocol: invalid HTTP version specified (Http2)
```

The actual server is not being called at all.

#### `linkerd check` output

```text
$ linkerd check
kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[ok]
kubernetes-api: is running the minimum Kubernetes API version..............[ok]
linkerd-api: control plane namespace exists................................[ok]
linkerd-api: control plane pods are ready..................................[ok]
linkerd-api: can initialize the client.....................................[ok]
linkerd-api: can query the control plane API...............................[ok]
linkerd-api[kubernetes]: control plane can talk to Kubernetes..............[ok]
linkerd-api[prometheus]: control plane can talk to Prometheus..............[ok]
linkerd-api: no invalid service profiles...................................[ok]
linkerd-version: can determine the latest version..........................[ok]
linkerd-version: cli is up-to-date.........................................[ok]
linkerd-version: control plane is up-to-date...............................[ok]

Status check results are [ok]
```

### Environment

Bare-metal cluster,

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ uname -a
Linux mars 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ linkerd version
Client version: stable-2.1.0
Server version: stable-2.1.0
```

### Additional context

Proxying HTTP servers works just fine in the same cluster.

[Here](https://github.com/moby/buildkit/blob/master/client/client.go#L25) is how buildkit creates a gRPC client. My suspicion is that linkerd proxy doesn't work with `grpc.WithInsecure()` connections (judging by `h2::server malformed headers: malformed authority`), which IMO is a bug.

I know that proxying gRPC services does work for many people though, so I might have done something wrong to break it. Would appreciate any guidance on how to solve my problem.

**Comment by grampelberg** [comment] 2019-01-18 18:21
With a spec that replicates it:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkit
  labels:
    app: buildkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkit
  template:
    metadata:
      labels:
        app: buildkit
    spec:
      containers:
      - name: buildkit
        image: moby/buildkit:v0.3.3
        args:
          - --addr
          - tcp://0.0.0.0:80
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          exec:
            command:
              - buildctl
              - --addr
              - tcp://0.0.0.0:80
              - debug
              - workers

---

apiVersion: v1
kind: Service
metadata:
  name: buildkit
spec:
  selector:
    app: buildkit
  ports:
  - name: http
    port: 80
    targetPort: 80
```

And a simpler `buildctl` command:

```bash
buildctl --addr tcp://buildkit.default:80 du
```

**Comment by grampelberg** [comment] 2019-01-23 01:39
Thanks to @hawkw, it looks like buildkit does not use a RFC compliant `:authority`. In my example, it looks like:

```
:authority: tcp://buildkit.default:80
```

The proxy fails because it is unable to decode the request. Playing around with `buildctl` a little bit, it doesn't appear to support setting `addr` to be something that *is* RFC compliant. Wondering if anyone has a good work around.

Coming out of this, there should be some issues around making the debugging for when a failure like this occurs easier.

**Comment by hawkw** [comment] 2019-01-23 01:52
For reference: [a valid authority does not contain a scheme](https://tools.ietf.org/html/rfc3986#section-3.2)

**Comment by hawkw** [comment] 2019-01-23 18:40
@grampelberg I opened https://github.com/linkerd/linkerd2/issues/2133 for more informative log messages when rejecting invalid pseudo-headers.

**Comment by grampelberg** [comment] 2019-01-23 20:55
I'm going to close this out for now. @Monnoroch please reopen if I'm missing something.

**Closed by grampelberg** 2019-01-23 20:55 UTC
Labels: area/proxy

**Comment by Monnoroch** [comment] 2019-01-23 20:59
@grampelberg you said that buildkit doesn't use the correct protocol. However, they do use the official grpc-go library that is not too outdated. I find it hard to believe that it's less correct than the rust-based implementation in this package.

**Comment by olix0r** [comment] 2019-01-23 21:53
@Monnoroch We're still trying to nail down the exact interaction that's causing this, but `tshark` makes it clear that--one way or another--buildkit is sending requests that [violate the RFC](https://httpwg.org/specs/rfc7540.html#rfc.section.8.1.2.3):
```
        Header: :authority: tcp://buildkit-19-1-2.default:80
            Name Length: 10
            Name: :authority
            Value Length: 32
            Value: tcp://buildkit-19-1-2.default:80
            Representation: Literal Header Field with Incremental Indexing - Indexed Name
            Index: 1
```

This is looks like it's caused by a subtle interaction between buildkit's utility code, grpc's resolver api, and dialers... hopefully we can pin it down to something more specific.

**Comment by Monnoroch** [comment] 2019-01-23 22:03
@olix0r thanks! Perhaps we should open a bug in their repo and see if they have any thoughts on this issue?

**Comment by olix0r** [comment] 2019-01-23 22:16
@Monnoroch I agree that's probably a good next step. It sounds potentially related to the specialized logic referenced in this issue https://github.com/moby/buildkit/issues/251

**Comment by grampelberg** [comment] 2019-01-23 23:31
Okay, here are some more details.

1. buildkit creates their [own dialer](https://github.com/moby/buildkit/blob/master/client/client_unix.go#L13).
1. This dialer uses `net.DialTimeout` and naively splits on `://`.
1. Because [DialTimeout](https://golang.org/pkg/net/#DialTimeout) is being used, the address ends up needing to be something like `tcp://`.
1. grpc-go uses a slightly different [naming scheme](https://github.com/grpc/grpc/blob/master/doc/naming.md). 
1. When grpc-go cannot parse the scheme (`scheme://authority/endpoint` or `dns://buildkit.default:80`), it defaults to [using target](https://github.com/grpc/grpc-go/blob/master/resolver_conn_wrapper.go#L56).
1. This ends up setting `:authority` to `Endpoint` as a [default](https://github.com/grpc/grpc-go/blob/master/clientconn.go#L261).

So, there are a couple options on the buildkit side:

- Use the default grpc-go dialer instead of a custom one.
- Use [`WithAuthority`](https://github.com/grpc/grpc-go/blob/master/dialoptions.go#L415) to set to the second half of the split string.
