### ISSUE TITLE
`linkerd metrics` panics if port-forward fails

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#3978] opened 2020-01-27 18:41 UTC
```
Error running port-forward: error upgrading connection: unable to upgrade connection: pod not found ("PODNAME_PODNS")panic: close of closed channel

goroutine 24 [running]:
github.com/linkerd/linkerd2/pkg/k8s.(*PortForward).Stop(0xc000347860)
	/linkerd-build/pkg/k8s/portforward.go:207 +0x2f
github.com/linkerd/linkerd2/cli/cmd.getMetrics(0xc000411540, 0x0, 0x0, 0x0, 0x0, 0xc00072bce0, 0x17, 0xc00072bd00, 0x12, 0xc0005357d0, ...)
	/linkerd-build/cli/cmd/metrics.go:173 +0x437
github.com/linkerd/linkerd2/cli/cmd.newCmdMetrics.func1.1(0xc000411540, 0xc000772720, 0x0, 0x0, 0x0, 0x0, 0xc00072bce0, 0x17, 0xc00072bd00, 0x12, ...)
	/linkerd-build/cli/cmd/metrics.go:109 +0x71
created by github.com/linkerd/linkerd2/cli/cmd.newCmdMetrics.func1
```

should be handled gracefully

**Comment by mayankshah1607** [comment] 2020-01-28 09:17
@grampelberg @olix0r I'd like to work on this one if that's okay :smile:

**Comment by grampelberg** [comment] 2020-01-28 17:23
@mayankshah1607 go for it!

**Comment by mayankshah1607** [comment] 2020-02-01 12:25
@olix0r @grampelberg any suggestions on how I can reproduce this bug?

**Comment by ihcsim** [comment] 2020-02-02 22:08
@mayankshah1607 I think you can fake this error with this change:
```
diff --git a/pkg/k8s/portforward.go b/pkg/k8s/portforward.go
index 8f5e79f6..1dace80d 100644
--- a/pkg/k8s/portforward.go
+++ b/pkg/k8s/portforward.go
@@ -143,6 +143,7 @@ func newPortForward(
 // run creates and runs the port-forward connection.
 // When the connection is established it blocks until Stop() is called.
 func (pf *PortForward) run() error {
+	return fmt.Errorf("a fake port-foward error")
 	transport, upgrader, err := spdy.RoundTripperFor(pf.config)
 	if err != nil {
 		return err
```

I am reasonably sure it's because we are missing a `return` statement in this block of code in `cli/cmd/metrics.go`:
```
	if err = portforward.Init(); err != nil {
		fmt.Fprintf(os.Stderr, "Error running port-forward: %s", err)
	}
```
Without a `return`, the CLI will continue to execute the subsequent code causing the `http.Get()` to fail. Also, I suspect the port-foward needs to check if the `stopCh` is nil before calling `close()` on it in its `Stop()` method.

**Comment by mayankshah1607** [comment] 2020-02-03 17:52
@ihcsim thanks for the suggestions! I was able to reproduce this bug. However, returning from that block of code and/or checking if `stopCh` is `nil` before calling `close()` didn't work as it would never be `nil` apparently. 
I looked into ways to check if a channel is closed before actually closing it (and without reading from it directly); but they did not seem to be very safe. 
The best solution seems like recovering from the panic caused by `close()`. I have opened a PR. Would be great if you could give it a review :) - https://github.com/linkerd/linkerd2/pull/4007

**Comment by ihcsim** [comment] 2020-02-03 18:30
> recovering from the panic caused by close().

That feels like covering up the real problem though. There are only 2 reasons why closing a channel will cause a panic; closing a nil channel, or closing an already closed channel. Can you check if the default `case` in this `select` statement (in `pkg/k8s/portforward.go`) conflict with the `defer portforward.Stop()` in the CLI?

```		select {
		case <-pf.GetStop():
			// stopCh was closed, do nothing
		default:
			// pf.run() returned for some other reason, close stopCh
			pf.Stop()
		}
```
Will it work if the preceding `if` conditional just `return` after sending an error to the `failure` channel? i.e. 
```
		if err := pf.run(); err != nil {
			failure <- err
                        return
		}
```

**Comment by mayankshah1607** [comment] 2020-02-04 07:50
@ihcsim you are right. The routine in `Init()` goes to the default case which causes the channel to close. `defer portforward.Stop()` in `cli/cmd/metrics.go` conflicts with the above, causes a closed channel to close; hence the panic. Returning from the routine when if `pf.run()` throws an error seems to have fixed it. Mind taking a look now? https://github.com/linkerd/linkerd2/pull/4007

**Closed** 2020-02-20 05:44 UTC
Labels: area/cli, good first issue, help wanted
